### ISSUE TITLE
Propozycja dodania 2 eventów

### ISSUE THREAD

**Issue by McKoxu** [FunnyGuilds/FunnyGuilds#1000]
Jako iż jestem "developerem" pewnego dodatku do FG, przydały by mi się 2 eventy
1. Wywoływany podczas wejścia na teren jakiejś gildii, najlepiej z pobraniem tego kto wykonał event i na teren jakiej gildii ktoś wszedł
2. Wywoływany podczas opuszczenia terenu jakiejś gildii, z pobraniem tego samego co 1 event ;v 

Wiem że nikt nie używa tego "API" FunnyGuilds oprócz mnie no ale cóż ;v

**Comment by Kamilkime** [comment]
Zawsze w sumie możesz sam dopisać to do FG i dać pull request 🤔

**Comment by insertt** [comment]
Dodano w 8936a92.
