### ISSUE TITLE
phpmyadmin 

### ISSUE THREAD

**Issue by Natusiek** [FunnyGuilds/FunnyGuilds#1002]
Gdzie mogę zedytować żeby mniej konektów było na phpmyadmin 
https://gyazo.com/e824c8bfaad8ddb326304c801ba2bc26

**Comment by Kamilkime** [comment]
W configu

**Comment by Natusiek** [comment]
No gdzie ?
mysql: 
  hostname: asdasdsad
  port: 3306
  database: asdas
  user: asd
  password: asdasd
  connectionTimeout: 3000
  usersTableName: users
  guildsTableName: guilds
  regionsTableName: regions

**Comment by Kamilkime** [comment]
A twoje FG jest w jakiej wersji? Pokaż screena z użycia `/funnyguilds version`

**Comment by Natusiek** [comment]
4.3.0 Tribute

**Comment by Kamilkime** [comment]
A mamy już 4.4.1, więc go użyj :/
https://ci.insertt.pl/job/FunnyGuilds/31/

**Comment by insertt** [comment]
Opcja została dodana po release 4.3.0: https://github.com/FunnyGuilds/FunnyGuilds/commit/2520e41, a więc zaktualizuj plugin.

**Comment by Natusiek** [comment]
User user = User.get(player.getName()); Gdzie jest user w 4.4.1 ?

**Comment by Kamilkime** [comment]
Teraz nie jest w `net.dzikoysk.funnyguilds.basic` tylko `net.dzikoysk.funnyguilds.basic.user` - wystarczy na nowo zaimportować
