### ISSUE TITLE
Nabijanie rankingu

### ISSUE THREAD

**Issue by Drizz1** [FunnyGuilds/FunnyGuilds#1006]
Witam, proponuję zmianę działania rank-farming.
Obecnie:
Atakujący zabija gracza nr. 1 i nie może zabić go ponownie przez określony czas w cfg, ale..
Atakujący zabija gracza nr. 2 i może znowu zabić gracza nr. 1
Można w ten sposób nabijać ranking, wystarczą 2 ofiary.
Proponuję:
- Po zabiciu ofiary można ponownie dostać za nią ranking po określonym czasie w cfg i zabcie kolejnego gracza nie usuwa czasu gracza pierwszego.

Pozdrawiam

**Comment by insertt** [comment]
@Drizz1 wprowadziliśmy zmiany w rejestrowaniu danych dot. nabijania rankingu, jeżeli mógłbyś to przetestuj [najnowszy build deweloperski](https://ci.insertt.pl/job/FunnyGuilds/) i daj znać, czy teraz jest ok.

**Comment by Drizz1** [comment]
Wygląda na to, że zostało to naprawione. Przetestuję to na większej ilości graczy i dam znać, proszę o nie zamykanie tematu. Gorzej jest z https://github.com/FunnyGuilds/FunnyGuilds/issues/1003 <-- wymaga testów, bo raz działa raz nie.

**Comment by Drizz1** [comment]
Naprawione, do zamknięcia.
