### ISSUE TITLE
funnyguilds niewiem jak zrobic komende ze spacja

### ISSUE THREAD

**Issue by yoczus** [FunnyGuilds/FunnyGuilds#1007]
Chcialbym zrobic ze komenda ktora sie edytuje na samym dole configu jest z spacja np zamiast /zaloz to /g zaloz ale jak robie z spacja czyli /g zaloz to wywala blad i nie moge zadnej komendy wpisac wiem ze na starszych wersjach fg to dzialalo ale jak zrobic to teraz?

**Comment by LimePolish** [comment]
guild: 
    name: "g"
    aliases: 
    - "gildie"
    - "gildia"
    enabled: true
i mozesz ustawic /g zaloz itp.
