### ISSUE TITLE
Możliwość wyłączenia prefixów w nickach nad głową

### ISSUE THREAD

**Issue by oski646** [FunnyGuilds/FunnyGuilds#1010]
Witam otóż mam prośbę o możliwość w configu **wyłączenia** dodawania prefixów gildyjnych każdemu graczowi (mówię tutaj o prefixie "teamu" scoreboardowego, tego nicku nad głową), ponieważ chciałbym napisać własne dodając różne suffixy czy trochę modyfikując wygląd tego, a w aktualnym momencie nie jest to możliwe dlatego że jak zmienię suffix jednego teamu (gildii) to wszystkie osoby z tego teamu będą go miały. Liczę na szybkie rozpatrzenie mojej propozycji 😄

**Comment by insertt** [comment]
Na jakiej zasadzie miałoby to działać?

**Comment by oski646** [comment]
Jeśli ja ustawię w configu że prefixy są wyłączone to FG nie dodaje teamów do scoreboardu gracza, a robię to ja ustawiając własne teamy. Bo zależy mi żeby zrobić coś takiego jak **[TAG] nickgracza VIP**, unikalnie dla każdego gracza. Jeśli są jakieś pytania wyjaśnię głębiej o co mi chodzi 😄
