### ISSUE TITLE
Znikanie prefixów w nametagu

### ISSUE THREAD

**Issue by Drizz1** [FunnyGuilds/FunnyGuilds#1017]
Zdarza się to bardzo często, 2 linijka w nametagu z punktami działa zawsze.
Problem jest z 1 linijką, gdzie jest tag gildii.

**Comment by insertt** [comment]
Czy błąd da się zreprodukować wyłącznie z FunnyGuilds na serwerze? Jaka wersja serwera?

**Comment by Drizz1** [comment]
dokładna przyczyna nie jest znana, są jednak zależności gdy ktoś się teleportuje to czasem zniknie a czasem nie. 1.8.8 błąd raczej, gdy jest większa ilość osób na serwerze.

**Comment by Drizz1** [comment]
Gdy nametag zniknie trzeba relognąć, aby ponownie się pojawił.

**Comment by Drizz1** [comment]
Chyba mam przyczynę, przy większej ilości graczy przy wejściu na serwer nie wczytują się nametagi.

**Comment by insertt** [comment]
Czy coś się zmieniło w najnowszym nightly? (https://github.com/FunnyGuilds/FunnyGuilds/commit/c347298739cd56d20f02519f1c36fd7d4c135bb7)
