### ISSUE TITLE
Użycie obecnie bezużytecznej zmiennej

### ISSUE THREAD

**Issue by Kamilkime** [FunnyGuilds/FunnyGuilds#1019]
Zmienna `prefixEnemies` jest obecnie z jakiegoś powodu niepobierana z cfg, ale użyta głębiej w kodzie (https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/element/IndividualPrefix.java#L87)

https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java#L853-L854

**Comment by insertt** [comment]
Zmienna to pozostałość starej funkcjonalności, która została usunięta lecz kod pozostał, który przydałoby się usunąć.

**Comment by Kamilkime** [comment]
Która została usunięta? Przecież te tagi są nadal w użyciu

**Comment by insertt** [comment]
Sama funkcjonalność wypowiedzenia wojny innej gildii nie jest już dostępna, zaś kod odpowiedzialny za inny kolor tagów itd. pozostał.
