### ISSUE TITLE
Problem podczas tworzenia gildii

### ISSUE THREAD

**Issue by oski646** [FunnyGuilds/FunnyGuilds#1025]
Witam jest problem gdy ktokolwiek tworzy gildie. Sytuacja wygląda następująco:
- Gracz wpisuje komendę do założenia gildii (tepa go pod ziemią, tworzy wokół obsidian ale bez serca)
- 20 sekund nic się nie dzieje
- Nagle wyrzuca wszystkich bez powodu z serwera
- Przez 10 sekund nie da się wejść na serwer bo piszę, że ten gracz jest już na serwerze
- Gildia się tworzy w bazie danych (tworzy się serce)
- Wszyscy znowu mogą wejść na serwer
Tak wygląda krok po kroku co się dzieje podczas tworzenia gildii. Do momentu stworzenia 20-25 gildii wszystko było OK, nagle zaczęło coś się takiego dziać.
**W konsoli nie ma żadnych błędów**

**Comment by insertt** [comment]
Czy ten bug da się zreprodukować za każdym razem?

**Comment by oski646** [comment]
Tak ten błąd pojawia się za każdym razem co zmusiło mnie do wyłączenia tej komendy na serwerze na czas naprawy tego błędu. Jeśli potrzeba mogę zaprosić na serwer i pokazać dokładnie jak wygląda ten błąd.

**Comment by oski646** [comment]
Chciałbym tylko zaznaczyć, że korzystam z opcji zapisywania MySQL. Liczę również na szybkie rozwiązanie problemu.

**Comment by oski646** [comment]
Problem dalej się pojawia, laguje serwer przy tworzeniu gildii, prosiłbym o kontakt i zobaczenia tego na własne oczy, ponieważ uniemożliwia to grę graczom na serwerze.
Discord: OSKI#0213

**Comment by insertt** [comment]
Czy ten problem występuje gdy na serwerze jest tylko FunnyGuilds?

**Comment by oski646** [comment]
Tak

**Comment by insertt** [comment]
Korzystasz z bazy zewnętrznej czy z uruchomionej na tym samym serwerze?

**Comment by oski646** [comment]
Z bazy danych postawionej na titanaxe więc nie jestem w stanie powiedzieć czy zewnętrzna czy uruchomiona na tym samym serwerze.

**Comment by insertt** [comment]
Czy problem występuje, gdy zostanie uruchomiona komenda `/fg save-all` ?

**Comment by oski646** [comment]
Tak

**Comment by insertt** [comment]
Najnowszy build deweloperski powinien mieć naprawiony ten problem: https://ci.insertt.pl/job/FunnyGuilds/71/

**Comment by oski646** [comment]
Wszystko na ten moment działa poprawnie.
