### ISSUE TITLE
No Value Messages - Brak zmian na serwerze

### ISSUE THREAD

**Issue by XeVeDo** [FunnyGuilds/FunnyGuilds#1030]
,,No Value Messages,, Sekcja w pliku konfiguracyjnym w ogólnie nie działa nie można zmienić ustawień gdy jakaś opcja zostanie zmodyfikowana plugin i tak korzysta z wartości domyślnych

**Comment by XeVeDo** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/43013921/57180902-aa699100-6e8d-11e9-8dad-b72207dcc40a.png)
![Screenshot_16](https://user-images.githubusercontent.com/43013921/57180904-ad648180-6e8d-11e9-806e-a9404eb72090.png)

Niezależnie czy zostawimy wartość bez niczego, czy użyjemy 'a' lub "a" plugin odmawia współpracy w tym aspekcie

**Comment by Kamilkime** [comment]
Podeślij cały swój plik messages.yml

**Comment by XeVeDo** [comment]
[github.zip](https://github.com/FunnyGuilds/FunnyGuilds/files/3144891/github.zip)

**Comment by insertt** [comment]
Niereprodukowalny błąd.
