### ISSUE TITLE
Wsparcie dla Holograms

### ISSUE THREAD

**Issue by eryk172** [FunnyGuilds/FunnyGuilds#1038]
Witam,
proponuje dodac wsparcie dla https://www.spigotmc.org/resources/holograms.4924/

Pozdr.

**Comment by dzikoysk** [comment]
@eryk172 na czym miałoby polegać dokładnie to wsparcie?

**Comment by dzikoysk** [comment]
Brak odp.

**Comment by Foogyyy** [comment]
Chodzilo o to aby pojawial sie hologram informacyjny na jajkiem

**Comment by dzikoysk** [comment]
@Foogyyy z jakim komunikatem?

**Comment by McKoxu** [comment]
Plugin Holograms z  tego co widzę ma wsparcie dla pluginu Holograms-Placeholders który prawdopodobnie ładuje placeholdery do tego głównego pluginu, Ten plugin (Holograms-Placeholders) wymaga pluginu PlaceholderAPI do którego funnyguilds ma wsparcie, więc warto sprawdzić czy zdziała :v
