### ISSUE TITLE
System podboju gildii oparty o beacona

### ISSUE THREAD

**Issue by Alexwords** [FunnyGuilds/FunnyGuilds#1063]
Witam, 
Czy jest możliwość dodania pewnego systemu  beacona? Cały proces byłby bardzo prosty. Beacona możesz stawiać tylko na cuboidzie, swojej (przynależnej) gildii. Po postawieniu tego beacona przez x czasu nie możesz go zniszczyć / przestawić na terenie swojej gildii. Może to zrobić gildia przeciwna (zarówno w czasie x jak i po) i klocek który wypada na ziemie po zniszczeniu beacona za pomocą tnt nie może być przez nie zniszczony. 
Pozdrawiam,

**Comment by dzikoysk** [comment]
@Alexwords ten system miałby być niezależny od obecnego systemu podbijania gildii, czyli jakaś poboczna funkcja, czy miałby to być alternatywny sposób właśnie tego podbijania?

**Comment by Foogyyy** [comment]
wydaje mi się ze to jest pomysł z craftcore :/ ponieważ takie beacony na tym właśnie serwerze maja miejsce działają one w ten sposób że lider po postawieniu beacona może zebrać go raz na 72 godziny. Natomiast przeciwnicy którzy taką gildię atakują po wbiciu do beacona mogą go zdobyć poprzez skopanie go kilofem 500 razy po czym otrzymują go do ekwipunku (oczywiście osoby te muszą posiadać gildię).

**Comment by dzikoysk** [comment]
Czyli to alternatywny system podboju gildii.

**Comment by Alexwords** [comment]
ale dało by rade

śr., 3 lip 2019 o 15:27 Dzikoysk <notifications@github.com> napisał(a):

**Comment by Kamilkime** [comment]
Ale... Czemu to zamykasz, niech sobie leży i czeka :/

**Comment by dzikoysk** [comment]
#2221
