### ISSUE TITLE
Dodanie logblock - rejestracja poczynań graczy

### ISSUE THREAD

**Issue by margonn** [FunnyGuilds/FunnyGuilds#1068]
witam
czy byś mógł dodać do funnyguilds logblock  to jest rejestracja poczynań graczy i tylko właściciel i zastępca może tego logblock używać a żeby to zadziałało trzeba mieć złoty kilof.

A to się bardzo przyda

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/issues/610
