### ISSUE TITLE
Dodanie opisu gildii i możliwości ustawienia pvp między sojuszniczymi gildiami

### ISSUE THREAD

**Issue by margonn** [FunnyGuilds/FunnyGuilds#1069]
Dodanie takich komend do pluginu funnyguilds:

/członek [nick] - degraduje zastępcę gildii.
/dg - wysyła wiadomości do gildii.
/ds [wiadomości] - wysyła wiadomość do sojuszy.
/friendlyfire - możliwość bicia członków gildii.
/friendlyfireally [tag] - możliwość bicia sojuszników.
/lider [nick] - przekazuje lidera gildii.
/opis [tekst] - ustawia opis gildii.
/sojusz [tag] - oferuje sojusz innej gildii.
/uprawnienia - informacje o systemie uprawnień w gildii.
/uprawnienia [nick] - uprawnienia członków gildii.
/zerwij [tag] - zrywa sojusz z gildią.

**Comment by dzikoysk** [comment]
Większość komend jest już w dostępnych. Z tych które można rozważyć, to:
```
/friendlyfireally [tag] - możliwość bicia sojuszników.
/opis [tekst] - ustawia opis gildii.
```

Co do tego:

```
/uprawnienia - informacje o systemie uprawnień w gildii.
/uprawnienia [nick] - uprawnienia członków gildii.
```

To FG nie posiada systemu uprawnień, więc na ten moment też nie mają sensu.

**Comment by dzikoysk** [comment]
#651
