### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Foogyyy** [FunnyGuilds/FunnyGuilds#1072]
Witam.
Mam problem z pluginem citizen i mam pytanie czy mógłbym prosić o instrukcje zwiazane z tym pluginem i połączeniem go z funnyguilds.

Z góry dzięki.

**Comment by insertt** [comment]
Z czym dokładniej masz problem?

**Comment by Foogyyy** [comment]
Ogółnie nie wiem na jakiej zasadzie to działa

**Comment by Foogyyy** [comment]
chdzi mi aby zrobic takie miejsce gdzie stoi top 3 graczy
w postaci npc cy tak sie da?

**Comment by Foogyyy** [comment]
jeżeli nie da sie tak zrobic do zaliczcie to do propozycji

**Comment by dzikoysk** [comment]
FunnyGuilds nie łączy się z pluginem Citizens, więc niestety nie zrobisz top 3 opartego na rankingu graczy z FG. Możesz to dodać jako propozycję w osobnym issue.
