### ISSUE TITLE
Dodanie konfiguracji prefixów i możliwość wiekszej konfiguracji suffixów w nametagach

### ISSUE THREAD

**Issue by SeRyJnY** [FunnyGuilds/FunnyGuilds#1077]
Dodanie ustawiania suffixów w nametagu: np wyświetlanie zmiennej {POS}, (Chyba, że to jest i ja tego po prostu tego nie widzę :)  Także można zrobić zmienną np.{GROUP), która dawała by prefix z permissionsex, luckperms :P

**Comment by insertt** [comment]
Moim zdaniem ta opcja nie powinna być implementowana w pluginie na gildie, ale poczekajmy na opinie innych.
/cc @dzikoysk @Kamilkime

**Comment by dzikoysk** [comment]
Można dodać api dla dodatków, żeby mogły tam sobie coś dodać + ew. jakieś podstawowe zmienię związane z fg 🤔

**Comment by SeRyJnY** [comment]
@dzikoysk API by było spoko

**Comment by P3ridot** [comment]
Możemy użyć aktualnie np. NametagEdit i placeholdera `%rel_funnyguilds_prefix%`. Ale możemy dodać taką funkcjonalność do pluginu oraz pozwolić na ustawianie większej ilości rzeczy prefixu i m.in. dodać też tam wsparcie PlaceholderAPI

**Comment by P3ridot** [comment]
Dodane suffixów i wsparcie PAPI (więc można sobie już tam ustawiać co tylko się wymarzy)
