### ISSUE TITLE
Panel gildyjny

### ISSUE THREAD

**Issue by shorv** [FunnyGuilds/FunnyGuilds#1100]
Propozycje, aby dodać panel gildyjny, tj. panel lidera. Na przykład pod komendą /panel możecie zmienić czy gracz w gildii może stawiać skrzynki czy też, lub cokolwiek innego, np. Czy może włączać pvp, czy może wylewać lave itd.

Kolejna propozycja to aby dało się usunąć główki z tabu. Nie zmienić, tylko usunąć.

**Comment by torobolin** [comment]
nie jestem pewien ale chyba jest juz mozliwosc usuniecia glowek z tablisty. Ja zrobilem to poprostu zmieniajac w server.properties online-mode: false albo w panelu hostingu bedziesz mial tryb premium czy cos i daj to na false

**Comment by P3ridot** [comment]
Nie jestesmy w stanie usunac główek z taba ponieważ minecraft na to nie pozwala, wiec zostaje sam panel

**Comment by DevangerTM** [comment]
-  ### **Serce Gildii** - Czyli taki panel zarządzania gildią "Panel Lidera" w której znajdowały by się różne usprawnienia. W nim znajdowały by się wszystkie opcje poniżej z możliwością edytowania.

> ![Opera Zrzut ekranu_2022-07-08_033145_www youtube com](https://user-images.githubusercontent.com/41342020/177898634-501f8a3a-d243-48e0-bbd4-ea8346bef7a6.png)

**Comment by P3ridot** [comment]
Z #2058 

 - ### **Dodatkowe opcje** - Te opcje już są pod komendami ale jak by była możliwość już robienia tego gui Serca Gildii / Panelu Gildii to tam też można by było można dodać. Tak samo z pvp on/off lub ulepszaniem regionu gildii.

> ![Opera Zrzut ekranu_2022-07-08_031133_www youtube com](https://user-images.githubusercontent.com/41342020/177902724-92c251c4-e28a-4c60-b6c7-b40c740dbaf9.png)
> ![Opera Zrzut ekranu_2022-07-08_031115_www youtube com](https://user-images.githubusercontent.com/41342020/177902730-17c39f5c-b774-4dbf-a29a-0af80a344379.png)

**Comment by dzikoysk** [comment]
* https://github.com/FunnyGuilds/FunnyGuilds/issues/2226
