### ISSUE TITLE
FunnyGuilds nie zamyka połączeń z bazą danych.

### ISSUE THREAD

**Issue by WojciechXi** [FunnyGuilds/FunnyGuilds#1101]
Otóż posiadam najnowszą wersję pluginu(na ten moment 4.5.1 pod 1.14, java 8), problem polega na tym, że każdy reload serwera rezerwuje kolejne połączenia w bazie danych, a nie zamyka starych(stare idą w stan uśpienia i zapychają):

![obraz](https://user-images.githubusercontent.com/32740834/63229619-c3ab0900-c202-11e9-811c-b393e84c3a90.png)
![obraz](https://user-images.githubusercontent.com/32740834/63229631-d6bdd900-c202-11e9-98b7-0476ffb690d4.png)
![obraz](https://user-images.githubusercontent.com/32740834/63229636-e2110480-c202-11e9-91c2-1753fc554d79.png)

Każdy reload rezerwuje kolejne 5 slotów połączeń(na ostatnim skrinie jest piętnaście z FunnyGuild i jedno z mojego, więc jednego nie uwzględniajcie).

Proponuję zamknąć połączenia na funkcji onDisable - u mnie to działa :)

**Comment by insertt** [comment]
Generalnie FunnyGuilds oficjalnie nie wspiera reloadów, dlatego zalecamy restartować serwer w celu uniknięcia takich problemów.
