### ISSUE TITLE
Problem z połączeniem z bazą danych

### ISSUE THREAD

**Issue by jamoreq** [FunnyGuilds/FunnyGuilds#1102]
https://pastebin.com/J3ZVEBkS

**Comment by Kamilkime** [comment]
Upewnij się, że w configu FG, w sekcji od bazy danych, masz `useSSL` ustawione na `false`

**Comment by jamoreq** [comment]
No mam ustawione true, ale łączność z baza danych testowałem i tez są errory.Chyba ze mam zmienic na false i ich wogole nie będzie.

**Comment by Kamilkime** [comment]
No... to przecież napisałem - żebyś się upewnił że w configu masz tam `false`, wtedy nie będzie błędu :/

**Comment by jamoreq** [comment]
pliki mysql tez sie nie generują w phpmyadmin

**Comment by jamoreq** [comment]
dobra, sprawdzę.

**Comment by jamoreq** [comment]
Do zamknięcia.
