### ISSUE TITLE
Sejf/Skarbiec gildyjny

### ISSUE THREAD

**Issue by margonn** [FunnyGuilds/FunnyGuilds#1103]
Witam

Mam taką propozycję do dodania a więc dodanie do pluginu sejfu gildyjnego który pod daniu uprawnień przez właściciela członkom gildii mają wtedy do niego dostęp i mogą wtedy wrzucać tam itemy i każdy może je wyciągać z gildii a żeby otworzyć sejf gildii piszemy komendę /sejf i otwiera się okienko gui gdzie w lewym górnym rogu pisze sejf gildii.

**Comment by DevangerTM** [comment]
- ### **Składki gildii** - Polega na stworzeniu składki gildii na wybrany przez założyciela gildii przedmiot i dzięki temu założyciel może zorganizować zrzutkę i wie kto się złożył. Dzięki temu będzie mógł kogoś awansować w hierarchii swojego teamu. Znajdowały by się tam opcje stworzenia składki, wybrania przedmiotu i ilości, a także usunięcia składek. 
 -  #1669 
>  
> ![Opera Zrzut ekranu_2022-07-08_030610_www youtube com](https://user-images.githubusercontent.com/41342020/177898953-d54dd505-c688-45dc-b8d1-acc1873024be.png) ![Opera Zrzut ekranu_2022-07-08_030500_www youtube com](https://user-images.githubusercontent.com/41342020/177898956-db7c506c-9203-422d-9787-039550314bbf.png)
> ![Opera Zrzut ekranu_2022-07-08_030441_www youtube com](https://user-images.githubusercontent.com/41342020/177898958-012be659-9ec3-4fe8-a361-5a946b511314.png)
> ![Opera Zrzut ekranu_2022-07-08_030415_www youtube com](https://user-images.githubusercontent.com/41342020/177898959-f259aebc-c79b-4ab5-97dc-779289f8dc5c.png)![Opera Zrzut ekranu_2022-07-08_030356_www youtube com](https://user-images.githubusercontent.com/41342020/177898962-7ffd88d2-6573-4b2d-aef4-c5a0235feffa.png)
> ![Opera Zrzut ekranu_2022-07-08_030330_www youtube com](https://user-images.githubusercontent.com/41342020/177898963-437ceb7a-93f9-4aaa-8885-d43ba8b0e99b.png)

**Comment by dzikoysk** [comment]
* https://github.com/FunnyGuilds/FunnyGuilds/issues/2226
