### ISSUE TITLE
Error przy zakładaniu gildii  (paperspigot 1.14.4) najnowsza wersja pluginu

### ISSUE THREAD

**Issue by Hippiskus** [FunnyGuilds/FunnyGuilds#1106]
Witam. mam problem z pluginem funnyguilds. który polega na tym że przy zakładaniu gildii na konsoli pojawia się mnóstwo błędów pomimo tego że plugin działa.
Załączam log błędu i config pluginu. server stoi na (paperspigot 1.14.4) a wersja pluginu to 4.5.1
https://pastebin.com/F7dyj3c5 - log
https://pastebin.com/j9WZgytQ - config
Proszę o szybką pomoc!

**Comment by dzikoysk** [comment]
Problem leży po stronie serwera bazy danych - FG nie może sie z nią połączyć. Upewnij się że ip/host/port są dobre oraz czy serwer db w ogóle odpowiada. Ewentualnie zmień bazę.
