### ISSUE TITLE
Można wyjmować przedmioty z gui

### ISSUE THREAD

**Issue by Hippiskus** [FunnyGuilds/FunnyGuilds#1110]
No problem jest prosty, po otwarciu gui /przedmioty, można wyciągać z niego itemy!
-Config: https://pastebin.com/XFFhKjrE
-Na konsoli nie ma żadnego Errora

**Comment by insertt** [comment]
Wrzuć logi z serwera.

**Comment by szymczakjarek** [comment]
Witam. Posiadam ten sam problem. W konsoli nie ma żadnej informacji czy błędu, tak jakby wszystko działało poprawnie, jednak z GUI da się wyciągnąć wszystkie przedmioty. Ta sama wersja pluginu, mc 1.13.2. Próbowałem znaleźć jakieś rozwiązanie przeszukując internet, jednak nie spotkałem się z podobnym problemem.

**Comment by Kamilkime** [comment]
Niech ktoś z was podeśle logi (latest.log) z serwera

**Comment by Hippiskus** [comment]
Log podsyłam w postaci pliku do pobrania (plik jest dość duży i pastebin nie pozwala)
https://www.sendspace.com/file/orp56p

**Comment by insertt** [comment]
To nie są pełne logi serwera.
