### ISSUE TITLE
Błąd ze slotami w inventory API

### ISSUE THREAD

**Issue by Nejmik242** [FunnyGuilds/FunnyGuilds#1111]
Witam,
Napisałem sobie swój plugin na api gui z funnyguilds. 
Błąd polegał na tym, że jeśli mam jakiś przedmiot (np. w slocie 10) z przypisanym eventem (np. wyświetlanie wiadomości graczowi) i jeśli gracz kliknie w swoim ekwipunku na 10 slot (czyli ten: https://imgur.com/a/aK6rEIW) to wtedy wykonuje się action tak jak by kliknął na 10 slot w stworzonym gui.
Naprawa błędu to zamiana w GuiActionHandler e.getSlot() na e.getRawSlot()

**Comment by Kamilkime** [comment]
Możesz stworzyć Pull Request z poprawką - chętnie takowy przyjmiemy

**Comment by Nejmik242** [comment]
Oks
