### ISSUE TITLE
{TAG} w nazwie

### ISSUE THREAD

**Issue by CHOMIKgp** [FunnyGuilds/FunnyGuilds#1114]
Witam:
1. na wersji 1.14.4 nie widać tagów gildi w nicku!
2. Aby mozna bylo zmienic pozycjie tagu gildii (Przed lub Za nickiem)

Nie chodzi o tag na chacie a tym nad graczem!

**Comment by insertt** [comment]
Wrzuć pełny log serwera gdy błąd zostanie zreprodukowany.
