### ISSUE TITLE
TNT

### ISSUE THREAD

**Issue by Szymon22431** [FunnyGuilds/FunnyGuilds#1117]
Witam!
1. Mam taką propozycję aby dodać taką opcję aby wszystkie bloki miały 50% szans wybuchu.
- np. będzie lista których bloków nie wybuchną 
- np. będzie lista żeby zmienić % szans wybuchu.
2. Zmienne topki na TAB
- Żeby była zmienna na TAB
np. Topka punktów, topka zgonów, topka zabójstw.
3. Asysty:
- 2 opcje
- 1. Opcja aby włączyć 1 asystę (1 Gracz tylko ma asystę)
- 2. Opcja ile graczy ma dostać asystę.

To wszystko.
Dziękuje!

**Comment by Szymon22431** [comment]
Ale mi chodzi o wybuchy itemów na terenie gildii

config:
# Jakie materialy i z jaka szansa maja byc niszczone po wybuchu
# <material>: <szansa (w %)
explode-materials: 
  water: 50.0
  lava: 50.0

I chodzi mi o to żeby było coś w stylu że można ustawić że wszystkie bloki mają 50% że nie musisz wpisywać wszystkie bloki do configu bo to jednak troszkę długo zajmie :/.

**Comment by dzikoysk** [comment]
#1135
