### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

### ISSUE THREAD

**Issue by jamoreq** [FunnyGuilds/FunnyGuilds#1125]
https://pastebin.com/Q8Kt44kb

**Comment by jamoreq** [comment]
https://pastebin.com/G1xEHDp3

**Comment by XANT3R** [comment]
Dodaję swoje potwierdzenie błędu : https://pastebin.com/8kxcRS6f

Oraz Config: https://pastebin.com/bCfWs3sD

Dodam, że nie mam w ogóle ustawionego MySQL a FLAT.

**Comment by insertt** [comment]
Błąd został naprawiony w [najnowszym nightly](https://ci.insertt.dev/job/FunnyGuilds/job/master/). (0e95eb2cf581f078facfd6c2547a52acdcf083b9)
