### ISSUE TITLE
Bug z TNT poza terenem gildii

### ISSUE THREAD

**Issue by FejmiQ** [FunnyGuilds/FunnyGuilds#1130]
Jest mały błąd gdyż od wersji 4.5.1 tnt nie niszczy nic za terenem gildii ale niszczy poszczególne przedmioty jakie jak:
1. ender chest
2. anvil
3. enchantment table

I właśnie chodzi mi o to aby to się nie niszczyło za terenem gildii też tak jak inne przedmioty

Błąd 2/Propozycja
Gdy gildia ma ochrone tnt nie dziala na jej terenie gildii tnt, a gdy sie wyłaczy ochrone w config.yml to gildie można podbić  odrazu.

PROPOZYCJA:
Propozycja jest taka aby tnt które np wylatuje z amutomatycznej armaty i takich innych armat leciało prosto aby te tnt strzelało normalnie jak np na serwerze Dragon-Survival.EU

Jeśli znajdę jakieś małe błędy lub będę miał propozycje oczywiście je zgłoszę na github

**Comment by dzikoysk** [comment]
@FejmiQ w sumie to nie do końca bug, po prostu wszystkim odpowiadało to, aby poza terenem gildii też działała ta ochrona. Można dodać opcję w configu od ograniczenia ochrony tnt do terenu gildii.

**Comment by FejmiQ** [comment]
Ale za za terenem gildi np jak jest opcja włączona aby nie niszczylo sie
nic za terenem gildi, to te rzeczy co doda sie w configu aby tnt niszczylo
to i tak za terenem rozwala

pt., 1 lis 2019, 00:04 użytkownik Dzikoysk <notifications@github.com>
napisał:

**Comment by dzikoysk** [comment]
@FejmiQ co masz ustawione w configu pod `explode-should-affect-only-guild`

**Comment by FejmiQ** [comment]
W configu mam ustawione co tnt ma niszczyc i gdy mam opcje aby tnt
niszczylo tylko na terenie gildi to i tak rzeczy co są w tym i tak się
niszczą za terenem

pt., 1 lis 2019, 00:22 użytkownik Dzikoysk <notifications@github.com>
napisał:

**Comment by insertt** [comment]
Najnowsze nightly dostępne [tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/) powinno mieć naprawiony opisany problem.

**Comment by FejmiQ** [comment]
Jeszcze jest jedna rzecz do poprawy czyli wybuch tnt. Gdy tnt jest w
wodzie/lavie nie niszczy nic, gdy jest obok wody/lavy dopiero niszczy jakąś
część tej wody/lavy i bloków, a gdy jest to w wodzie bądź w lavie nie
dzieje sie nic tylko wybucha

pt., 1 lis 2019, 00:34 użytkownik insertt <notifications@github.com>
napisał:

**Comment by insertt** [comment]
Czy błąd wymieniony w issue został naprawiony w najnowszym nightly?

**Comment by FejmiQ** [comment]
Nowa wersja do pobrania tak?

pt., 1 lis 2019, 00:38 użytkownik insertt <notifications@github.com>
napisał:

**Comment by insertt** [comment]
Tak, nightly.
