### ISSUE TITLE
Asysty za zabójstwo nie działają.

### ISSUE THREAD

**Issue by Tofik000** [FunnyGuilds/FunnyGuilds#1132]
Po prostu nie działają. Nie posiadam pluginu WorldGuard.

**Comment by insertt** [comment]
Czy w najnowszej wersji błąd dalej występuje?

**Comment by Tofik000** [comment]
Mam inną wersje i działa, również 4.4.2 ale od 1.8 do 1.13

W dniu wt., 7.01.2020 o 15:42 insertt <notifications@github.com> napisał(a):
