### ISSUE TITLE
Nie odejmuje życia gildi gdy gracz chcę ją podbić

### ISSUE THREAD

**Issue by Wybranowsky** [FunnyGuilds/FunnyGuilds#1133]
Gracz z innej gildii próbuje podpić inną gildie bez ochrony, uderza w ender crytala i wywala błąd w konsoli, nie odejmuje życia tej gildi ale dodaje ochrone gildi ktora jest ustawiona w configu pluginu na 12h po podbiciu.

Wersja mc: 1.14.4
Wersja FG: 4.5.1 Tribute
Pluginy: `Plugins (30): LuckPerms, WorldEdit, LoginSecurity, PVPControl, CobbleX, KukuStone, PlaceholderAPI, UltimateTimber, ElektronTnT, ProtocolLib, LotusPierozki, ElektronHelpPlus, SkinsRestorer, karolekDrop, BoyFarmer, Vault, FastLogin, Essentials, HeadDatabase, HolographicDisplays, DiscordSRV, EssentialsChat, ElektronGuilds, SuperVanish, EssentialsSpawn, WorldGuard, JupiterCore, BetterRTP, WorldGuardExtraFlags, GoldenCrates`

Log z uruchaminia serwera: https://pastebin.com/5Y2tz8Ge
Log błędu po próbie podbicia gildii przez gracza z innej gildi:
`28.10 12:10:37 [Server] pool-11-thread-1/WARN java.lang.IllegalStateException: GuildLivesChangeEvent cannot be triggered asynchronously from another thread.
28.10 12:10:37 [Server] pool-11-thread-1/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at net.dzikoysk.funnyguilds.event.SimpleEventHandler.handle(SimpleEventHandler.java:8)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at net.dzikoysk.funnyguilds.system.war.WarSystem.attack(WarSystem.java:53)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at net.dzikoysk.funnyguilds.system.war.WarListener.call(WarListener.java:77)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:58)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at net.dzikoysk.funnyguilds.concurrency.requests.WarUseRequest.execute(WarUseRequest.java:19)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
28.10 12:10:37 [Server] pool-11-thread-1/WARN at java.lang.Thread.run(Thread.java:748)`

**Comment by jamoreq** [comment]
Spróbuj użyć wydania nightly

**Comment by Wybranowsky** [comment]
@jamoreq też miałeś ten błąd?

**Comment by jamoreq** [comment]
nie, a używacie wersji stabilnej czy master (nightly) ?

**Comment by Wybranowsky** [comment]
stabilna 4.5.1 Tribute

**Comment by dzikoysk** [comment]
![obraz](https://user-images.githubusercontent.com/4235722/67680173-00c21300-f98b-11e9-9c8d-a53fd0ed211a.png)

Użyj nightly, tam już sporo poprawek @insertt zrobił względem ostatniego release

**Comment by Wybranowsky** [comment]
ok na najnowszej Nightly działa 🥇
