### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by FejmiQ** [FunnyGuilds/FunnyGuilds#1136]
Witam!
Chcialbym zglosic propozycje.

Propozycja 1.
Chodzi o tnt, czyli aby tnt lecialo ladnie i prosto np jak na serwerze Dragon-Survival.Eu albo CraftCore.pl
Teraz gdy jest takie tnt jak teraz to nie mozna ladnie i prosto przebic gildi.
Propozycja 2.
Panel gildi oraz uprawnienia
Chodzi tutaj o to aby pod np komenda /panel albo /zarzadzaj i mozliwosc zmiany komendy na taka jaka chce.
W tym chodziloby o to ze np jak ktos wpisze te komende to wyswietla mu sie gui ze wszystkimi czlonkami jego gildi i moze wybrac dowolnego gracza i otwiera mu sie nowe gui i tam ma jakie moze nadac mu uprawnienia.
Przyklad uprawnien
Dostep do sejfu
Niszczenie kamienia na terenie gildi
niszczenie obsydianu
stawianie blokow
otwieranie skrzynek
Propozycja 3
Zmiania id glowek na TAB'ie na id takie jakie kazdy chce
Propozycja 4.
komenda /sejf
czyli ze tam mozna przechowywac itemy i kazdy gracz z gildi moze sejf otworzyc jesli ma do niego uprawnienia
Propozycja 5.
Dodanie komend
/g zaloz
/g itemy
/g usun
/g potwierdz
/g zapros
itp

**Comment by SeRyJnY** [comment]
1.  W paper spigocie jest o ile pamiętam taka opcja :)

**Comment by kacperduras** [comment]
#963, #895, a reszta jest w konfiguracji.
