### ISSUE TITLE
Problem z konfiguracja TAB!

### ISSUE THREAD

**Issue by neviq1** [FunnyGuilds/FunnyGuilds#1141]
Występuje taki problem z TAB LISTA.

https://zapodaj.net/5b35c33a6d0b8.png.html

Config: 
player-list: 
  1: "&8&l&m---------------"
  2: " &8&l✘ &c&lSTATYSTYKI &8&l✘"
  3: "&8&l&m---------------"
  4: ""
  5: "&8» &7Nick: &6{PLAYER}"
  6: "&8» &7Zabojstwa: &6{KILLS}"
  7: "&8» &7Smierci: &6{DEATHS}"
  8: "&8» &7Punkty: &6{POINTS}"
  9: "&8» &7Pozycja: &6{POSITION}"
  10: "&8» &7KDR: &6{KDR}"
  11: ""
  12: "  &8&l✘ &c&lGILDIA &8&l✘"
  13: ""
  14: "&8» &7Tag: &6{G-TAG}"
  15: "&8» &7Punkty: &6{G-POINTS}"
  16: "&8» &7Zabojstwa: &6{G-KILLS}"
  17: "&8» &7Smierci: &6{G-DEATHS}"
  18: "&8» &7Online: &6{G-MEMBERS-ONLINE}"
  19: "&8» &7Pozycja: &6{G-POSITION}"
  20: ""
  21: "&8&l&m---------------"
  22: " &8&l✘ &c&lRANKING PVP &8&l✘"
  23: "&8&l&m---------------"
  24: ""
  25: "&71. &6{PTOP-1}"
  26: "&72. &6{PTOP-2}"
  27: "&73. &6{PTOP-3}"
  28: "&74. &7{PTOP-4}"
  29: "&75. &7{PTOP-5}"
  30: "&76. &7{PTOP-6}"
  31: "&77. &7{PTOP-7}"
  32: "&78. &7{PTOP-8}"
  33: "&79. &7{PTOP-9}"
  34: "&710. &7{PTOP-10}"
  35: "&711. &7{PTOP-11}"
  36: "&712. &7{PTOP-12}"
  37: "&713. &7{PTOP-13}"
  38: "&714. &7{PTOP-14}"
  39: "&715. &7{PTOP-15}"
  40: ""
  41: "&8&l&m---------------"
  42: " &8&l✘ &c&lTOP GILDIE &8&l✘"
  43: "&8&l&m---------------"
  44: ""
  45: "&71. &6{GTOP-1}"
  46: "&72. &6{GTOP-2}"
  47: "&73. &6{GTOP-3}"
  48: "&74. &7{GTOP-4}"
  49: "&75. &7{GTOP-5}"
  50: "&76. &7{GTOP-6}"
  51: "&77. &7{GTOP-7}"
  52: "&78. &7{GTOP-8}"
  53: "&79. &7{GTOP-9}"
  54: "&710. &7{GTOP-10}"
  55: "&711. &7{GTOP-11}"
  56: "&712. &7{GTOP-12}"
  57: "&713. &7{GTOP-13}"
  58: "&714. &7{GTOP-14}"
  59: "&715. &7{GTOP-15}"
  60: ""
  61: "&8&l&m---------------"
  62: " &8&l✘ &c&lINFORMACJE &8&l✘"
  63: "&8&l&m---------------"
  64: ""
  65: "&8» &7TPS: &6{TPS}"
  66: "&8» &7Ping: &a{PING}"
  67: "&8» &7Godzina: &6{HOUR} {MINUTE} {SECOND}"
  68: "&8» &7Dzien: &6{DAY_OF_WEEK}"
  69: " &f● &6/pomoc"
  70: " &f● &6/oferty"
  71: " &f● &6/warp"
  72: " &f● &6/zadania"
  73: " &f● &6/yt"
  74: " &f● &6/zglos"
  75: " &f● &6/helpop"
  76: ""
  77: "&8&l&m----------------"
  78: "   &c&lRekrutacja:"
  79: "        &a&lON"
  80: "&8&l&m----------------"

**Comment by neviq1** [comment]
zrobione. 
tylko teraz z tym problem https://megawrzuta.pl/download/21cc7ad3051f0ea182eec9fe3926fe1d.html

**Comment by rrye** [comment]
Jest to zawarte w konfiguracji pluginu.
https://github.com/FunnyGuilds/FunnyGuilds/blob/bf37962d69e6275631b01df75542f7a18552c137/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java#L994-L1002

Można zmienić te komunikaty w `player-list-header` oraz `player-list-footer`.
