### ISSUE TITLE
Problem z tabem

### ISSUE THREAD

**Issue by YellowDeath** [FunnyGuilds/FunnyGuilds#1144]
Duzo nie trzeba pisac, problem jest taki, ze w lewym gornym rogu pisza nicki graczy online na sewerze, co mozna z tym zrobic?
![2019-11-29_13 54 04](https://user-images.githubusercontent.com/58341797/69884934-0f2d8280-12db-11ea-83f8-83d804bd1872.png)

**Comment by dzikoysk** [comment]
Ale miałeś wrzucić problemy związane z nową wersją, nie starą :0
