### ISSUE TITLE
Problem z tabem (WYŚWIETLANIE GILDI)

### ISSUE THREAD

**Issue by Toms0n** [FunnyGuilds/FunnyGuilds#1147]
Cześć, mam problem otóz zmienna {G-TOP} nie działa i nie wyświetla gildi.

Wersja pluginu: 4.5.2
Silnik: PaperSpigot 1.8.8

Config:
https://pastebin.com/vA8BLWC2

Zrzut ekranu: 
![2019-12-07_20 22 34](https://user-images.githubusercontent.com/56000046/70379673-b63f9900-192f-11ea-93b4-ad13c35a9940.png)

**Comment by insertt** [comment]
Podeślij pełne logi serwera.

**Comment by Toms0n** [comment]
Logi? w konsoli żaden błąd nie występuje.

**Comment by Dejmi1337** [comment]
Po prostu w konfiguracji masz ustawione żeby zaliczało gildie od iluś tam członków o ile dobrze pamiętam ;)

**Comment by insertt** [comment]
Problem rozwiązany.
