### ISSUE TITLE
Zmienne topki

### ISSUE THREAD

**Issue by T0fficzeG** [FunnyGuilds/FunnyGuilds#1148]
Co trzeba aby zrobic aby uzyskac zmienne topki zabojstw punktow smierci?

**Comment by rrye** [comment]
Potrzebujesz do tego pluginu PlaceholderAPI.
https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-2/#funnyguilds

**Comment by T0fficzeG** [comment]
okej dzieki ale co potem ? ;v

**Comment by P3ridot** [comment]
Gdzie chcesz używać tych zmiennych?

**Comment by T0fficzeG** [comment]
tablista funnyguilds

**Comment by T0fficzeG** [comment]
do zmiany topek np rankingu zabojstw

**Comment by rrye** [comment]
Wystarczy czytać komentarze w konfiguracji. Nad sekcją z tablistą są wypisane zmienne.

**Comment by T0fficzeG** [comment]
mi chodzilo ze w tabeli np topka zabojstw zmienia sie na topka punktow i potem jeszcze w topka zginiec . Nie wiem jak to zrobić ;d

**Comment by P3ridot** [comment]
Bo w samym funnyguildzie nie da się tego zrobić :/

**Comment by xEc000** [comment]
Możesz uzyć pluginu BungeeTabListPlus dzięki któremu ustawisz różne wartości dla danej tabeli. Działa to na zasadzie odświeżania tablist'y. Na przykład tabela z numerem 1 posiada wartość zmiennej G-TOP1 i po odpowiednim czasie jest ona odswiezana na wartość zmiennej P-TOP1 z ustalonym czasem odświeżania w configu. Niestety do tego musisz posiadać serwer Bungeecord na którym będzie opierała się tablist'a. Wiem że jest możliwość zrobienia animowanej tablisty na spigocie lecz nie pamiętam pluginu.
