### ISSUE TITLE
Zablokowanie zabijania zwierząt i villagerów na terenie gildii

### ISSUE THREAD

**Issue by CHOMIKgp** [FunnyGuilds/FunnyGuilds#1156]
Aby gracze  którzy nie należna do gildii nie mogli zabijać zwierząt/potworów na tak owym terenie.

**Comment by Blox61** [comment]
No pomysł dobry tylko chciałbym wspomnieć że potwory również zadają obrażenia i to by było takie dziwne jak ty nie możesz zabić szkieleta a ten nawala w ciebie strzałami XD

**Comment by CHOMIKgp** [comment]
To nie licząc potworów tylko zwierzęta

**Comment by dzikoysk** [comment]
Opcja dostępna w najnowszym nightly poprzez włączenie `animals-protection` w configu.
