### ISSUE TITLE
Blad po zimportowaniu do intellij

### ISSUE THREAD

**Issue by yoczus** [FunnyGuilds/FunnyGuilds#1161]
pobralem z githuba najnowsza wersje funnyguilds source code zimportowalem a po zrobieniu w mavenie 'clean install' mam taki blad

logi:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building FunnyGuilds 4.6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.bstats.org/content/repositories/releases/be/maximvdw/MVdWUpdater/1.6.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata be.maximvdw:MVdWUpdater:1.6.0-SNAPSHOT/maven-metadata.xml from/to bstats-repo (http://repo.bstats.org/content/repositories/releases/): Failed to transfer file: http://repo.bstats.org/content/repositories/releases/be/maximvdw/MVdWUpdater/1.6.0-SNAPSHOT/maven-metadata.xml. Return code is: 521 , ReasonPhrase:Origin Down.
[WARNING] Failure to transfer be.maximvdw:MVdWUpdater:1.6.0-SNAPSHOT/maven-metadata.xml from http://repo.bstats.org/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of bstats-repo has elapsed or updates are forced. Original error: Could not transfer metadata be.maximvdw:MVdWUpdater:1.6.0-SNAPSHOT/maven-metadata.xml from/to bstats-repo (http://repo.bstats.org/content/repositories/releases/): Failed to transfer file: http://repo.bstats.org/content/repositories/releases/be/maximvdw/MVdWUpdater/1.6.0-SNAPSHOT/maven-metadata.xml. Return code is: 521 , ReasonPhrase:Origin Down.
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ funnyguilds ---
[INFO] 
[INFO] --- git-commit-id-plugin:3.0.1:revision (default) @ funnyguilds ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.271 s
[INFO] Finished at: 2019-12-30T21:58:24+01:00
[INFO] Final Memory: 14M/202M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:3.0.1:revision (default) on project funnyguilds: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by insertt** [comment]
Sklonuj repozytorium za pomocą gita.
