### ISSUE TITLE
ERROR StatusLogger Log4j2

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1163]
Podczas wyłączania serwera występuje taki błąd:
`[08:03:23] [Server thread/WARN]: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`
Dla pewności wykonałem ten testy tylko z 1 pluginem na serwerze i z 0 pluginów też.
[latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/4012102/latest.log)
[latest - b.log](https://github.com/FunnyGuilds/FunnyGuilds/files/4012103/latest.-.b.log)

Dodatkowo powiem że mam najnowszą nightly a wyświetla się że jest nowa nowsza wersja.

**Comment by insertt** [comment]
Aktualnie ten błąd można zignorować gdyż nie powoduje nic poważnego.

**Comment by radek203** [comment]
> Aktualnie ten błąd można zignorować gdyż nie powoduje nic poważnego.

Kiedy zmieniłem zapis na MYSQL błąd występuje też podczas uruchamiania serwera.
```
[18:01:08 INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.6.0-SNAPSHOT Tribute-8f03703
[18:01:08 WARN]: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```

**Comment by rrye** [comment]
Dzieje się tak, ponieważ zapis danych nie ma nic wspólnego z tym błędem. 
To nie jest nic groźnego, plugin i tak będzie działał poprawnie.

**Comment by radek203** [comment]
> Dzieje się tak, ponieważ zapis danych nie ma nic wspólnego z tym błędem.
> To nie jest nic groźnego, plugin i tak będzie działał poprawnie.

Okej, i tak mimo że dostałem też wcześniej odpowiedź, że nic groźnego, to wszystko co jakiś błąd wywala, wole zgłosić. Mam uczulenie na wszelkiego rodzaju błędy :D.
Można liczyć na naprawianie tego?

**Comment by insertt** [comment]
Czy błąd występuje w najnowszej wersji?

**Comment by radek203** [comment]
Tak

**Comment by insertt** [comment]
Wrzuć pełny log serwera.

**Comment by radek203** [comment]
[latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/4143178/latest.log)

W tej chwili nie korzystam z MySQL więc występuje to tylko podczas wyłączania serwera.
Wcześniej jak testowałem to przy uruchamianiu było jak się MySQL używa, więc podejrzewam że gdybym uruchomił zapis mysql to też przy uruchamianiu by było.
