### ISSUE TITLE
Wyłączenie tagów?

### ISSUE THREAD

**Issue by Verdun1337** [FunnyGuilds/FunnyGuilds#1167]
Czy jest opcja aby wyłączyć całkowicie tagi gildii?

**Comment by insertt** [comment]
W jakim celu?

**Comment by Verdun1337** [comment]
W takim celu aby zrobić własne tagi + dodatki własne

**Comment by insertt** [comment]
Wyświetlanie tagów na czacie oraz nad głową można wyłączyć odpowiednio w konfiguracji pluginu na chat oraz w konfiguracji samego FunnyGuilds.

**Comment by Verdun1337** [comment]
chodzi mi jedynie nad głowa, lecz ustawienie w configu prefixu na "" nie pomaga

**Comment by Verdun1337** [comment]
gdy wyłączam dummy i ustawiam własne swoim pluginem wszystko działa, lecz nad głowa się buguje :/

**Comment by insertt** [comment]
Opisz dokładniej problem "bugowania się nad głową" (i btw. alternatywą może być po prostu własny fork FunnyGuilds).

**Comment by Verdun1337** [comment]
eh gdy ustawiam tag, byle co to nadaje się tylko jednemu graczowi, gdy zrobi się gildia itp, to usuwam wszystkim, ale chyba sam dodam source funnyguilds i sam tam pozmieniam tylko zbytnio mi się nie chce co update nadpisywać tego :/

**Comment by Verdun1337** [comment]
chodzi że nadaje, ogl bez fg nadaje tak jak chce ale gdy włączę fg wszystko się sypie, znaczy błędów nie ma ale ustawia jednemu graczowi. Obecnie to chyba nadpiszę to ale jak można to w nowych wydaniach możecie dodać opcje true false jak w dummy :)

**Comment by insertt** [comment]
To brzmi na problem po stronie Twojego pluginu, możesz napisać do nas na naszym [Discordzie](https://discord.gg/CYvyq3u) i może będziemy w stanie Ci pomóc.

**Comment by Verdun1337** [comment]
oky

**Comment by TheMolkaPL** [comment]
> tylko zbytnio mi się nie chce co update nadpisywać tego

Możesz sobie zrobić patch takiej zmiany i potem ją tylko aplikować. Patch robisz uzywając [git format-patch](https://git-scm.com/docs/git-format-patch), a aplikujesz [git am](https://git-scm.com/docs/git-am). W tym momencie całe CraftBukkity i jego potomkowie tak powstają.

Innym rozwiązaniem może być zrobienie sobie brancha i używanie [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) na nowych wersjach.
