### ISSUE TITLE
dodatek na panel gildyjny

### ISSUE THREAD

**Issue by T0fficzeG** [FunnyGuilds/FunnyGuilds#1168]
Witam! Posiada ktoś z was plugin (dodatek) na panel gildyjny np fGuildsAddon?

**Comment by rrye** [comment]
Taki pomysł już padł [tutaj](https://github.com/FunnyGuilds/FunnyGuilds/issues/1100) i najwidoczniej nikomu się nie śpieszy, aby go zrealizować.
Lepiej chyba zapytać użytkowników, np. na discordzie FunnyGuilds, bo tutaj przychodzą zazwyczaj z problemami.

**Comment by insertt** [comment]
#1100
