### ISSUE TITLE
Nie działają asysty

### ISSUE THREAD

**Issue by heraqu** [FunnyGuilds/FunnyGuilds#1170]
Siemka, w configu mam włączone asysty a one nie działają :) Ktoś wie jak to ogarnąć?

**Comment by insertt** [comment]
Z jakiej wersji korzystasz?

**Comment by heraqu** [comment]
4.5.2

**Comment by insertt** [comment]
Zaktualizuj do najnowszego nightly i sprawdź konfigurację.
