### ISSUE TITLE
Nie działa wiadomość o asystach

### ISSUE THREAD

**Issue by heraqu** [FunnyGuilds/FunnyGuilds#1172]
Siemka, nie działa ta wiadomość, https://i.imgur.com/vnmJfWO.png 
lecz gdy dopisze zmienną {ASSISTS} do rankDeathMessage to wyświetla osoby asystujące

**Comment by insertt** [comment]
Pole `rankAssistMessage` określa format, który zostanie zamieniony w miejscu zmiennej `{ASSISTS}` (o ile asysty są włączone w konfiguracji) w wiadomościach dotyczących zabójstw gracza. https://github.com/FunnyGuilds/FunnyGuilds/blob/09f2317b9697cd4108330037e998b45c0c748074/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java#L261-L263
