### ISSUE TITLE
Tagi nad nickami w innym pluginie

### ISSUE THREAD

**Issue by Dejmi1337** [FunnyGuilds/FunnyGuilds#1173]
Witam. Chciałbym zapytać czy jest jakaś możliwość korzystania z waszego systemu tagów nad nickami graczy gdyż tagi z innego pluginu nie działają gdy na serwerze są funnyguildsy. Wersja serwera to 1.14.4

**Comment by insertt** [comment]
Wystarczy wyłączyć tagi w konfiguracji FunnyGuilds (`guild-tag-enabled`) i użyć osobnego pluginu na tagi nad głową, który wspiera np. PlaceholderAPI i skorzystać z naszych placeholderów (`%funnyguilds_g-tag%`, `%funnyguilds_g-name%` itd.)
