### ISSUE TITLE
Tablista - błędy

### ISSUE THREAD

**Issue by tajemniktv** [FunnyGuilds/FunnyGuilds#1177]
# Tablista - error
Cześć, podczas wchodzenia na serwer i kliknięcia TABu, wywala błąd. Przez chwilę pokazuje się zwykła lista graczy, na której mam przekreślone te kreseczki symbolizujące jakość połączenia. Po relogu wywala ten błąd i po chwili tablista się pokazuje.
Wersja FG: 4.6.0-SNAPSHOT Tribute-f68875e
Silnik: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) 
Implementing API version 1.8.8-R0.1-SNAPSHOT
Log z błędu: https://hasteb.in/aqazupuy.shell
Config: https://hasteb.in/tiwibaqu.yaml

**Comment by insertt** [comment]
Błąd został naprawiony w [najnowszym nightly](https://ci.insertt.dev/job/FunnyGuilds/job/master/).
