### ISSUE TITLE
Błąd - New flags cannot be registered at this time

### ISSUE THREAD

**Issue by tajemniktv** [FunnyGuilds/FunnyGuilds#1178]
Podczas włączania serwera: https://hasteb.in/koqeqofi.makefile
Podczas użycia komendy /g: https://hasteb.in/epuqixol.bash
Podczas próby uruchomienia pluginu przez PluginManager: https://hasteb.in/xamaqavo.shell

Po usunięciu pluginu ServerListMOTD wszystko wraca do normy

Wersja FG: Najnowsze Nightly (na dzień 21.01)
Silnik: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8)
Implementing API version 1.8.8-R0.1-SNAPSHOT

**Comment by tajemniktv** [comment]
Po usunięciu pluginu ServerListMOTD wszystko wraca do normy

**Comment by insertt** [comment]
Wrzuć pełny log serwera z tym błędem.

**Comment by tajemniktv** [comment]
Wydaje mi się że ma to coś związanego z bStats, który próbuje pobrać aktualną liczbę graczy a przy pluginie ServerListMOTD automatycznie włączyły się FakeSloty. Po wywaleniu SLMOTD było okej, natomiast kolejny plugin, który edytuje motd i sloty - znowu się wywala plugin. 

Dobra, odkryłem źródło problemu - FunnyGuilds wysypał się dwa razy przez FunnySkAddon-Extended. Teraz FunnyGuilds działa aczkolwiek FunnySkAddon-Extended już nie. Z tego co wiem ten dodatek do skryptu nie jest Waszego autorstwa, right?

Nie mam już po co wstawiać loga z konsoli, ale wrzucam loga z erroru funnyskaddon
https://hasteb.in/xofoxufe.swift

**Comment by insertt** [comment]
FunnySKAddon to plugin nie naszego autorstwa, także musisz napisać do autora tego pluginu w tej sprawie.
