### ISSUE TITLE
Po przeładowaniu PlaceholderAPI zmienne nie działają.

### ISSUE THREAD

**Issue by PolskiStevek** [FunnyGuilds/FunnyGuilds#1180]
Po przeładowaniu pluginu PlaceholderAPI komendą /papi reload (lub plugmanem), zmienne z FunnyGuilds przestają się "podmieniać" we wszystkich pluginach. Restart serwera naprawia ten problem.

Screen przed przeładowaniem PlaceholderAPI:
![Przechwytywanie](https://user-images.githubusercontent.com/29680081/72928309-034cc280-3d58-11ea-8b3a-8666104c8057.PNG)
Screen po przeładowaniu PlaceholderAPI:
![2](https://user-images.githubusercontent.com/29680081/72928335-152e6580-3d58-11ea-9525-ccd778ab940f.PNG)

Log: https://pastebin.com/FnGkA2sv
Wersja serwera: PaperSpigot 1.8.8
Wersja FG: Najnowsza Nightly (4.6.0 Build 7​4 - 22 sty 2020, 10:12)
Edit: Wszystkie inne pluginy posiadające swoje placeholdery, działają poprawnie po użyciu /papi reload, wyjątkiem jest FG.

**Comment by rrye** [comment]
Zatem nie reloaduj serwera.

**Comment by PolskiStevek** [comment]
> Zatem nie reloaduj serwera.

Nie reload serwera, tylko komenda /papi reload, dzięki której można zainstalować dodatki z chmury PlaceholderAPI.

**Comment by insertt** [comment]
Błąd został naprawiony w [najnowszym nightly](https://ci.insertt.dev/job/FunnyGuilds/job/master/).
