### ISSUE TITLE
Duplikaty gildii na tabliście

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1183]
Ogólnie mam opcje że top gildii dopiero od 2 osób w gildii i się tab buguje gdy jest gildia która ma jedną osobę i powinna być top 1

![2020-01-24_18 57 02](https://user-images.githubusercontent.com/57212337/73100819-a59eae80-3eee-11ea-829b-30a4dbe058b9.png)
![2020-01-24_21 05 50](https://user-images.githubusercontent.com/57212337/73100820-a6374500-3eee-11ea-879b-22d7f734ccdb.png)
![2020-01-24_21 08 01](https://user-images.githubusercontent.com/57212337/73100821-a6374500-3eee-11ea-8c89-9e829b24a830.png)

Spigot: 1.12.2
[FunnyGuilds] Loading FunnyGuilds v4.6.0-SNAPSHOT Tribute-4e87f4d
[ProtocolLib] Enabling ProtocolLib v4.5.1-SNAPSHOT-b445

  64: "&7» &e&l1. &f{GTOP-1}"
  65: "&7» &e&l2. &f{GTOP-2}"

**Comment by TheMolkaPL** [comment]
Fajna nazwa serwera xD

**Comment by insertt** [comment]
Podeślij pełną konfigurację pluginu

**Comment by radek203** [comment]
> Podeślij pełną konfigurację pluginu

Można jakoś pv discord czy coś?

**Comment by TheMolkaPL** [comment]
Nawet skkf jest w administracji XD lmao
