### ISSUE TITLE
Nowy błąd podczas uruchamiania serwera, niedziałająca opcja w configu

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1191]
`[12:07:22 WARN]: Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added`

Odnośnie pewnej opcji w configu:
```
# Czy gracze z uprawnieniem 'funnyguilds.ranking.exempt' powinni byc uwzglednieni przy wyznaczaniu pozycji gracza w rankingu
skip-privileged-players-in-rank-positions: true
```
Próbowałem to ustawiać na true i false ale żadna opcja tak jakby nie działała dalej gracz z permisją znajdował się nad graczami bez permisji

[FunnyGuilds] Loading FunnyGuilds v4.6.0-SNAPSHOT Tribute-b159b4b
Spigot: 1.12.2

**Comment by radek203** [comment]
@insertt Jeszcze tutaj jest problem według mnie z tym jak osoba która ma się nie liczyć do rankingu a założy gildię, mam ustawione że przynajmniej 2 osoby muszą być w gildii żeby się liczyła do rankingu, a żeby tak zrobić że 2 osoby która liczą się normalnie do rankingu?
![2020-02-01_14 14 15](https://user-images.githubusercontent.com/57212337/73592773-0ab16000-44fe-11ea-8c12-a404f2b5348e.png)
![2020-02-01_14 14 23](https://user-images.githubusercontent.com/57212337/73592774-0ab16000-44fe-11ea-9c6c-d956c433e3eb.png)

**Comment by insertt** [comment]
Stwórz nowy issue z propozycją.
