### ISSUE TITLE
Nowy błąd podczas uruchamiania serwera.

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1193]
[15:29:13 WARN]: Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added

Błąd jeżeli się nie mylę, zaczął wyskakiwać od tej wersji:
https://ci.insertt.dev/job/FunnyGuilds/job/master/81/

Moja obecna wersja: [FunnyGuilds] Loading FunnyGuilds v4.6.0-SNAPSHOT Tribute-39b485c
Spigot: 1.12.2

**Comment by insertt** [comment]
To nie błąd tylko ostrzeżenie, do tego niezwiązane z funkcjonalnością samego pluginu.

**Comment by radek203** [comment]
No dobra, ale jednak się wyświetla czyli jest przez coś spowodowany.

**Comment by insertt** [comment]
To wynik konsensusu między zmniejszeniem wielkości pluginu oraz dodania nowej zależności (+ braku wsparcia pewnej funkcji w pluginie Mavena). Ostrzeżenie nie wpływa w żaden sposób na działanie pluginu, także można go zignorować.
