### ISSUE TITLE
Propozycja dodania czasu kiedy TNT jest włączone/wyłączone

### ISSUE THREAD

**Issue by Blox61** [FunnyGuilds/FunnyGuilds#1196]
Witam. przychodzę z propozycją dodania funkcji automatycznego włączania oraz wyłączania TNT w określonym czasie. W configu byłoby:
1. Godzina od której TNT ma być włączone
2. Godzina od której TNT ma być wyłączone
3. Włączenie/wyłączenie funkcji

**Comment by insertt** [comment]
Jest to już zaimplementowane w pluginie pod opcjami w konfiguracji: `guild-tnt-protection-enabled`, `guild-tnt-protection-start-time`, `guild-tnt-protection-end-time`.
