### ISSUE TITLE
Lava/Woda Tylko na terenie Gildii

### ISSUE THREAD

**Issue by CHOMIKgp** [FunnyGuilds/FunnyGuilds#1199]
Aby dodac tak samo jak z tnt ze lava/woda wylewa sie tylko na terenie gildii.

**Comment by jasuogra** [comment]
Były lepsze propozycje zasługujące na zrobienie, ta jak najbardziej jest taka indywidualna by zrobić ją za pomocą api ¯\_(ツ)_/¯
