### ISSUE TITLE
Komenda na regeneracje terenu gildii

### ISSUE THREAD

**Issue by maxwhitepl** [FunnyGuilds/FunnyGuilds#1208]
Możliwość dodania opcji regeneracji gildii po ciężkim ataku np **tnt** 

**Właściciel gildii musiałby użyć komendy** "_/g regeneracja_" która by przywracała dany teren z przed ataku i _automatycznie naprawi bloki_ które zostały wysadzone tnt.

Opcja była by możliwa do wyłączenia w configu pluginu jeżeli ktoś nie chciałby aby taka opcja była

**Comment by Blox61** [comment]
Ale to chyba na tym polega żeby samemu naprawiać szkody, a nie korzystać z ułatwienia ;P

**Comment by Zabujca997** [comment]
No tak ale można dodać taką opcje nie które serwery korzystają z tego

**Comment by Bart0l** [comment]
Proponuje aby dodać taka możliwość ale żeby działa ma zasadzie takiej:
Gdy wpiszemy /regeneracja to zabierze nam z ekwipunku X itemow/$$$ które będą do ustalenia w configu i dopiero wtedy zacznie sie regeneracja terenu gildii z przed najazdu wrogiej gildii.

**Comment by Zabujca997** [comment]
Dokładnie tak

**Comment by xpiREC** [comment]
Fajnie byłoby najpierw wprowadzić https://github.com/FunnyGuilds/FunnyGuilds/issues/610 żeby mieć dane, które przyspieszyłyby wprowadzenie tej opcji, tutaj kwestia implementacji — taką widzę logikę.

**Comment by Zabujca997** [comment]
> 

Wystarczyło by możliwość współpracy z pluginem **CoreProtect** lub **LogBlockiem**. Regeneracja mogła by zapisać dane w **MySQL** lub pliku bazy terenu.
