### ISSUE TITLE
Opcja zmiany miejsca wyświetlania wiadomości

### ISSUE THREAD

**Issue by CHOMIKgp** [FunnyGuilds/FunnyGuilds#1209]
Aby ten komunikat co wyswietla sie na title dało sie ustawic na actionbar, i wgl ze np jak ktos kogos zabije to nie pisze na czacie tylko na actonbar, ale to wiesz tak ze mozesz zmienic.

**Comment by P3ridot** [comment]
Rozwiniete w #2059

**Comment by P3ridot** [comment]
Opcja dostępna w najnowszym Nightly
