### ISSUE TITLE
Zmienna {WG-REGION}

### ISSUE THREAD

**Issue by heraqu** [FunnyGuilds/FunnyGuilds#1210]
Siemka, 
zmienna {WG-REGION} powinna pokazywać region na którym się jest. Jest region zrobiony a zmienna się nie aktualizuje. W czym może być problem?
![image](https://user-images.githubusercontent.com/46068203/75099489-8022c480-55c2-11ea-886c-6bc881db04d4.png)

**Comment by insertt** [comment]
Czy na serwerze jest załadowany plugin WorldGuard?

**Comment by heraqu** [comment]
Tak jest

**Comment by insertt** [comment]
Wrzuć pełen log serwera.

**Comment by heraqu** [comment]
W logach nic nie ma, lecz problem nagle sam się naprawił po jakiś 10h nie robienia nic przy FG XDD
ani WG
