### ISSUE TITLE
Dwa te same nicki w bazie a różne UUID

### ISSUE THREAD

**Issue by dj1sklero** [FunnyGuilds/FunnyGuilds#1213]
Witam!
Mam problem z wprowadzenie pluginu, ponieważ na testach wychodzi że co jakiś czas kilka osób mają dodatkowy wpis w bazie z innym UUID. Kasowanie wpisów w bazie nie pomaga bo jakimś czasie znów dodaje kolejne. Problem w tym że nowy wpis dostaje 1000 pkt. na start i brak gildii jeśli posiadał.

**Comment by insertt** [comment]
Z jakiej wersji pluginu korzystasz?

**Comment by dj1sklero** [comment]
4.6.0-SNAPSHOT, ale w wcześniejszych wersjach miałem to samo.

**Comment by insertt** [comment]
I na najnowszej wersji dalej pojawiają się duplikaty z róznym uuid?

**Comment by dj1sklero** [comment]
Dokładnie, mogę podesłać jakieś logi lub wycinek z bazy

**Comment by insertt** [comment]
Chwilę czasu temu mieliśmy kilka poprawek, które powinny wyeliminować ten problem, dlatego pytam o to czy dalej się pojawiają na najnowszej wersji (w tym najnowszym nightly).

**Comment by dj1sklero** [comment]
No ja pobierałem ostatnią możliwą wersje z relase, jeśli jest jakaś beta czy coś podobnego, to mogę sprawdzić bo serwer jest jeszcze przed wydaniem.

**Comment by insertt** [comment]
https://ci.insertt.dev/job/FunnyGuilds/job/master/

**Comment by radek203** [comment]
Miałem ten sam problem używając pluginu FastLogin. Nie działa on poprawnie dlatego u mnie się to bugowało.
