### ISSUE TITLE
Problem z wykryciem enchantu!

### ISSUE THREAD

**Issue by therazerpll** [FunnyGuilds/FunnyGuilds#1225]
Problem leży w tym, iż stworzyłem swój unikalny przedmiot z "hide enchant" w skript tj. give glowing 1 of diamond named "twójitem" with lore "opis" to player. Wiem, że enchant ukryty w skript to arrow_infinite 69 natomiast po  wpisaniu tego enchantu do configu FG nie wykrywa go tylko w /przedmioty dodawany jest item z pokazanym enchantem! Czy jest jakaś opcja, żeby przedmioty wymagane do założenia gildii były również w jakiś sposób dodawane jako "hide enchant"? Proszę o sprawną odpowiedź.

**Comment by insertt** [comment]
Aktualnie nie bardzo jest "przewidziana" taka możliwość (w sensie ukrycie enchantów za pomocą nałożenia wyżej wymienionego), gdyż Funnyguilds wykorzystuje standardowy sposób nakładania enchantów na przedmiot - jednakże istnieje możliwość ukrycia tychże enchantów, tylko aktualnie nie jest to wspierane w naszym pluginie.

**Comment by therazerpll** [comment]
Kurde :/ bardzo mi na tym zależy :/ nie dacie tego zrobić w przyszłej aktualizacji?

**Comment by therazerpll** [comment]
lub jeszcze inaczej jeśli chciałbym sam to dodać to w jakiej klasie musiałbym to mniej więcej zmienić?
