### ISSUE TITLE
Nieprawidłowe pojawianie się serca gildii

### ISSUE THREAD

**Issue by Ziom1bart** [FunnyGuilds/FunnyGuilds#1228]
Witam!
Chciałbym zgłosić błąd związany z nieprawidłowym pojawianiem się serca gildii.
Więc tak, na moim serwerze używam plugina multiverse i mam na nim 2 światy.
1 z lobby(world)
2 z Survivalem (Survival)
Jeżeli chcę utworzyć gildię w świecie Survival nie pojawia ona tam, tylko na świecie z lobby.

**Comment by dzikoysk** [comment]
#1269
