### ISSUE TITLE
Ranking ELO

### ISSUE THREAD

**Issue by heraqu** [FunnyGuilds/FunnyGuilds#1233]
Witam, czy ranking ELO nie powinien działać na zasadzie... dostajesz 100 a zabiera Ci np. 30? Bawiłem się w configu, różne metody tego rankingu stosowałem i za każdym razem +50 -50... jest na to jakieś rozwiązanie?

**Comment by therazerpll** [comment]
Podpinam się :)!

**Comment by heraqu** [comment]
@dzikoysk wiesz coś na ten temat?

**Comment by dzikoysk** [comment]
Niestety nie wiem nic na ten temat
