### ISSUE TITLE
Zalanie projektu leczniczą abstrakcją

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#1239]
#### **Nastała nowa era, a my ludzie północy opuszczamy naszych jaskiniowych przyjaciół! :0**

![Bez nazwy](https://user-images.githubusercontent.com/4235722/78725619-43bbe580-7930-11ea-88fe-71f85e332e56.png)

Konserwatywne przekonania części grupy nie mogą decydować o naszej świetlanej przyszłości. Nie porzucimy 30 lat rozwoju technologii plemion dookoła na rzecz fałszywych wartości podrzucanych nam przez żerujących na nas jednostkach.

Aby wyzwolić się spod religijnych okowów niedopuszczających do siebie postępu, przemyliśmy się w naparze z leczniczej abstrakcji, która zmyła nam klapki z oczu. Rzeczy, które po tym nam się ukazały są nadal ciężkie do zrozumienia przez wcześniejsze ograniczenia umysłowe. Otóz:
* Matka natura to abstrakcja, która buduje życie
* Nieabstrakcyjne byty jak susły, to wyjątki od większości, a nie standardy. *(Tu matka natura wyraźnie pokazała w objawieniu, że nie wolno susłów i szatańskich pytonów wciskać gdzie popadnie, to nie jest wasza pierwsza dziewczyna, trzymajcie swojego węża na wodzy!)*
* Świat nie kończy się na jednej jaskinii i nie musimy w niej wszystkiego trzymać, czas wyjść ze strefy komfortu i złych przyzwyczajeń
* Abstrakcja buduje nasz świat szybciej z uwagi na niesamowitą drzemiącą w niej moc, niestety jest jednocześnie zagrożeniem w rękach nieumiejętnych ograniczonych jednostek siejących chaos za jej pośrednictwem

Jesteśmy świadomi, że część naszych pobratymców nie nadąża za resztą i nie ma nic w tym złego. Nie chcemy jednak, żeby zapchani pierdołami o susłach dalej próbowali nas na siłę nimi zainteresować. Dlatego odchodzimy w pokoju!

<div align="center">
        <img src="https://i.imgur.com/49sGsr0.gif">
</div>

Pierwszymi postanowieniami naszej grupy, jest zalanie starych, ograniczonych i źle wykonanych narzędzi, następującymi potężnymi abstrakcyjnymi mieszankami:

* Odciążający nas FunnyCommands, który poniesie nas siłą abstrakcji tam, gdzie rozwiązania ludzi prostych zawiodły
* Bardzo gęsty i mocny ORM leczący wszystkie rany, aby nic nigdy już z niego nie wyciekło - nazwany roboczo PandaORM
* Proste i czytelne księgi abstrakcji trzymające naukową wiedzę i potwierdzone fakty, wolne od cherry pickingu ludzi wierzących, zwane przez bardów Donfigsami

kekw

**Comment by rrye** [comment]
kekw

**Comment by KrekBuk** [comment]
Sprzeciw.
Ormy sa bardzo czesto slaba, cieknaca abstrakcja.
