### ISSUE TITLE
Error w konsoli 

### ISSUE THREAD

**Issue by Koziol434343** [FunnyGuilds/FunnyGuilds#1241]
Bład cały czas występuje i troche irytuje, konsola jest zaśmiecona. :)

Błąd: 
![blad](https://user-images.githubusercontent.com/63369904/78824011-f302c600-79dd-11ea-9744-143158576bb4.png)
w configu nic nie zmienialem ale:  https://pastebin.com/5mapgqrA

**Comment by insertt** [comment]
Zaktualizuj plugin do najnowszego nightly.

**Comment by Koziol434343** [comment]
> Zaktualizuj plugin do najnowszego nightly.

a gdzie to jest? Bo szukam i nie wiem gdzie znalezc ;/

**Comment by insertt** [comment]
[Tutaj](https://ci.insertt.dev/job/FunnyGuilds/).
