### ISSUE TITLE
Tagi gildii - brak koloru na nicku

### ISSUE THREAD

**Issue by Issante** [FunnyGuilds/FunnyGuilds#1249]
Utworzyłem następujący tag dla:
prefix-other: "&8[&c{TAG}&8]&c "

Podczas gdy tag jest czerwony (a kwadratowy nawias ciemnoszary), to nick pozostaje biały.

**Comment by insertt** [comment]
Ta opcja w konfiguracji aktualnie działa tylko dla prefixów i nie ma wpływu na display name gracza.
