### ISSUE TITLE
Jak zrobić zmianę sekcji w ITEM GUI

### ISSUE THREAD

**Issue by Procix94** [FunnyGuilds/FunnyGuilds#1251]
Mam takie pytanie, jak mogę zrobić by pisać Linijkę niżej, dokładniej tak jak na obrazku niżej:

Obraz: https://i.imgur.com/2TSdzbZ.png

**Comment by BimberDziadka** [comment]
Przed linkiem dodaj &n

**Comment by BimberDziadka** [comment]
> Mam takie pytanie, jak mogę zrobić by pisać Linijkę niżej, dokładniej tak jak na obrazku niżej:
> 
> Obraz: https://i.imgur.com/2TSdzbZ.png

Tam gdzie chcesz, żeby zaczynała się nowa linia dodaj &n, powinno zadziałać.
