### ISSUE TITLE
Błąd topek gildii przy bungeetablist plus

### ISSUE THREAD

**Issue by DudeKK-sa** [FunnyGuilds/FunnyGuilds#1255]
Witam, mam błąd topek gidii pod plugin bungeetablistplus, myślę iż jest to głównie błąd funnyguilds ponieważ pod komendą /top jest tak samo podsyłam ssy
![nr1](https://user-images.githubusercontent.com/64638172/80798879-b58cf500-8ba5-11ea-8f1d-98b10f44b1a6.png)
![nr2](https://user-images.githubusercontent.com/64638172/80798888-b887e580-8ba5-11ea-8e2a-71dc3c0fade6.png)
![nr3](https://user-images.githubusercontent.com/64638172/80798895-bcb40300-8ba5-11ea-87d8-e40b95d27d56.png)

**Comment by insertt** [comment]
Wersja pluginu?

**Comment by DudeKK-sa** [comment]
4.6.0 problem najprawdopodobniej był w schemacie na gildie, odinstalowalem poprzedni schemat wgrałem nowy i wszystko działa. Nwm czemu ale gdy wgl nie miałem pliku ze schematem w folderze fg oraz worldedita, gildie i tak wgrywały się z tym schematem xd

**Comment by insertt** [comment]
Warto również zaktualizować plugin do najnowszej wersji, bo podobny błąd został naprawiony między 4.6.0 a 4.7.0
