### ISSUE TITLE
Dodanie wsparcia dla nametagedit

### ISSUE THREAD

**Issue by DudeKK-sa** [FunnyGuilds/FunnyGuilds#1256]
Witam, proponuje dodanie wsparcia dla pluginu NameTagEdit :) Czyli że gdy dodajemy suffix lub prefix gildie przed nickiem nie będą się bugowały, byłaby to naprawde dobra opcja 👍 
![xd123](https://user-images.githubusercontent.com/64638172/80800450-c63f6a00-8ba9-11ea-8cc5-e4413d985423.png)

**Comment by SeRyJnY** [comment]
Spoko opcja, dawałem już tę propozycję w 2019 roku ale do teraz nie dodano :(

**Comment by insertt** [comment]
Bo sama funkcjonalność nie jest prosta do zaimplementowania w taki sposób, by nie kolidowała z innymi pluginami.

**Comment by P3ridot** [comment]
#1698 właściwie pozwala na to, wystarczy użyc placeholdera `%rel_funnyguilds_prefix%`
