### ISSUE TITLE
Dodanie komendy dla administracji do zmiany tagu gildii

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#1259]
Istnieje komenda _/ga nazwa_ która pozwala zmienić nazwę gildii. Proponuje dodać komendę _/ga tag_ która pozwalałaby również zmienić tag gildii.

**Comment by dzikoysk** [comment]
`/ga tag [tag] [nowy tag]`

**Comment by P3ridot** [comment]
Tak sobie patrzę na tego commita ale czy tutaj https://github.com/FunnyGuilds/FunnyGuilds/commit/467d30f5afa5ae87819a9e87cb859fd83a1c2170#diff-26500ba2f1640d6a9db7662d335c061bR30 nie powinna być użyta ta metoda tagExists zamiast nameExists?

**Comment by dzikoysk** [comment]
Magia `ctrl c` `ctrl v`, za chwilę wrzucę fixa xD
