### ISSUE TITLE
Błąd z "rank-farming-consideration-timeout"

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1260]
Więc tak jak w temacie mam taki błąd, że jeżeli gracz zabije jakiegoś gracza i ten zabity przez niego gracz zginie drugi raz nawet 30 minut później ale np. skacząc z wysokości To gracz 1 który wcześniej go zabił dostanie punkty. Mimo prawidłowych ustawień w configu
```
# Czy ostatni gracz, ktory zaatakowal gracza, ktory zginal ma byc uznawany jako zabojca
rank-farming-last-attacker-as-killer: true
# Przez ile sekund gracz, ktory zaatakowal gracza, ktory zginal ma byc uznawany jako zabojca
rank-farming-consideration-timeout: 18
```
[FunnyGuilds] Loading FunnyGuilds v4.7.0 Tribute-871d0e4
Działało to tak samo na 1.15.2 jak i na 1.12.2 i 1.8.8 (Na tych testowałem)

**Comment by insertt** [comment]
Naprawione w najnowszym nightly.
