### ISSUE TITLE
Dodanie linijek do header/footer TAB

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1262]
Proponuje dodanie możliwości dodania kilku linijek do headera oraz footera na TABie
Coś typu:
player-list-header: "LINIJKA1\nLINIJKA2\nLINIJKA3"
Żeby dało się oddzielić linijki \n
Próbowałem tego używać tak samo jak \0 ale nie działa to, więc twierdze że nie ma takiej funkcji, a jakby coś takiego dodać to TAB będzie wyglądał bardziej estetycznie i przejrzyściej.

**Comment by insertt** [comment]
Taka opcja jest już dostępna w pluginie w postaci wsparcia `\n` jako nowej linii w sekcjach `player-list-header` oraz `player-list-footer`.
