### ISSUE TITLE
Dodanie: Możliwości włączenia/wyłączenia pvp między sojuszem - komenda dla graczy

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1263]
Proponuje dodanie możliwości włączenia jak i wyłączenia przez założycieli gildii jak i zastępców (ewentualnie adminów) pvp między gildiami z którym są w sojuszu.
Według mnie komenda mogłaby wyglądać w ten sposób: /pvp <TAG>
jak zwykłe /pvp się wpisze dalej zmienia pvp w gildii gracza.

**Comment by insertt** [comment]
Taka opcja jest już dostępna w pluginie: `/pvp`, `damage-ally` w konfiguracji.
