### ISSUE TITLE
Wsparcie działania pluginu per-world

### ISSUE THREAD

**Issue by zone-a-1** [FunnyGuilds/FunnyGuilds#1269]
To znaczy ogólnie plugin działa świetnie z BungeeCord jak i bez tylko chodzi mi o to że moja strona hostingowa nie pozwala na używanie BungeeCord (i ogólnie nie chcę jak na razie go używać), a na serwerze mam też inne tryby. I na innych trybach dalej jest tablist, komendy itd. z pluginu. I moje pytanie brzmi: Czy moglibyście dodać do configu miejsce gdzie można by było dać listę światów na których plugin byłby kompletnie wyłączony?

**Comment by insertt** [comment]
Aktualnie niestety nie ma planów na dodanie wsparcia działania pluginu per-world, ponieważ wymagałoby to dość dużej przebudowy działania samego pluginu, a końcowo i tak niewiele osób korzystałoby z takiej opcji.

**Comment by dawidsk12345** [comment]
Ok, warto było spytać, jak coś może sam coś pokombinuję z kodem

**Comment by insertt** [comment]
Może warto zastanowić się nad zmianą hostingu i użyciem BungeeCorda.

**Comment by dawidsk12345** [comment]
Na razie jest to mały serwer i nie mam zbytnio kasy na używanie BungeeCorda ale zastanowię się. Dzięki za szybką odpowiedź

**Comment by P3ridot** [comment]
Dużo pracy a jak już kiedyś wspomniano to prawie nikt by tego nie używał
