### ISSUE TITLE
Wyświetlanie wiadomości międzygildyjnych w logach serwera

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1273]
Kiedy gracze wysyłają coś na czacie gildijnym/sojuszniczym/globalnym gildii to nie wyświetla się to w konsoli. Według mnie powinno się wyświetlać albo powinna być opcja na włączenie tego.

**Comment by dzikoysk** [comment]
Za pomocą opcji `log-guild-chat` można teraz włączyć logowanie chatu gildyjnego.
