### ISSUE TITLE
Błąd przy łączeniu sie z MySQL

### ISSUE THREAD

**Issue by Bart0l** [FunnyGuilds/FunnyGuilds#1275]
Wszystko w linku: 
https://hastebin.com/icimaneyej.md

**Comment by insertt** [comment]
To nie jest problem wynikający z winy FunnyGuilds, gdyż błąd wskazuje na to, że nie udało się połączyć ze wskazaną bazą danych.

**Comment by Bart0l** [comment]
Można uzyskać jakąś pomoc przy podłączeniu pluginu? pokazać co źle robie?

**Comment by insertt** [comment]
Wrzuć sekcję konfiguracji dot. bazy danych.

**Comment by Bart0l** [comment]
data-interval: 1
# Typ zapisu danych
# FLAT - Lokalne pliki
# MYSQL - baza danych
data-model: MYSQL
# Dane wymagane do polaczenia z baza
# UWAGA: connectionTimeout jest w milisekundach!
# Sekcja poolSize odpowiada za liczbe zarezerwowanych polaczen, domyslna wartosc 5 powinna wystarczyc
# Aby umozliwic FG automatyczne zarzadzanie liczba polaczen - ustaw poolSize na -1
# Sekcje usersTableName, guildsTableName i regionsTableName to nazwy tabel z danymi FG w bazie danych
# Najlepiej zmieniac te nazwy tylko wtedy, gdy jest naprawde taka potrzeba (np. wystepuje konflikt z innym pluginem)
# Aby zmienic nazwy tabel, gdy masz juz w bazie jakies dane z FG:
# 1. Wylacz serwer
# 2. Zmien dane w configu FG
# 3. Zmien nazwy tabel w bazie uzywajac np. phpMyAdmin
mysql: 
  hostname: "mysql.craftserve.pl"
  port: 3306
  database: "csrv_721929"
  user: "csrv_721929"
  password: "xxxxxx"
  poolSize: -1
  connectionTimeout: 30000
  useSSL: true
  usersTableName: "users"
  guildsTableName: "guilds"
  regionsTableName: "regions"

**Comment by insertt** [comment]
Czyli to prawdopodobnie problem z bazą danych, z której korzystasz.
