### ISSUE TITLE
Błąd przy wklejaniu Schematic

### ISSUE THREAD

**Issue by Bart0l** [FunnyGuilds/FunnyGuilds#1283]
Hej, Chce zrobić własny schematic przy wklejaniu gildii i gdy wklejam i zapisuje wyświetla się przy tworzeniu gildii komnikat: An internal error occured while attempting to perform this command.
Log pluginu: https://pastebin.com/QC9gisma
config: https://pastebin.com/YkML8Rim
wyglad srodka gildii: ![XOXO](https://user-images.githubusercontent.com/50382769/82652963-cb2e9100-9c1e-11ea-9403-cf63bf1074f8.png)

**Comment by insertt** [comment]
Plugin aktualnie nie wspiera WorldEdita/WorldGuarda 7.0+: #1218

**Comment by Bart0l** [comment]
Czy w najbliższym czasie zostanie dodane wsparcie dla wersji WE/WG 7.0+?

**Comment by insertt** [comment]
Aktualnie trwają prace nad wsparciem, ale wymaga to większej przebudowy struktury pluginu, dlatego jeżeli wsparcie będzie gotowe to pojawi się release.
