### ISSUE TITLE
Bug - widoczny tag nad graczem który ma niewidzialność

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1285]
Gdy gracz ma efekty niewidzialności, dalej widać jego nick, punkty, gildię nad głową.

FunnyGuilds version 4.7.0 Tribute-98147ce
PaperSpigot: 1.8.8

![2020-05-24_10 52 20](https://user-images.githubusercontent.com/57212337/82749908-bed83e80-9dac-11ea-9f16-0bf90d4988ab.png)

**Comment by insertt** [comment]
Bug nie jest spowodowany działaniem pluginu tylko używaniem wersji 1.8, na której występuje błąd z niepoprawną obsługu stanu flag drużyn oraz stanem gracza.
