### ISSUE TITLE
Błąd w konsoli.

### ISSUE THREAD

**Issue by Bart0l** [FunnyGuilds/FunnyGuilds#1286]
Tak jak w temacie:
https://pastebin.com/EtBRbJwL

**Comment by insertt** [comment]
Błąd wynika prawdopodobnie z uszkodzenia pluginu, spróbuj pobrać ponownie i wgrać na serwer.

**Comment by Bart0l** [comment]
Wgrałem wersję release od nowa czysty jar i występuje ten sam błąd
Spigot-1.15.2
