### ISSUE TITLE
Zmienione wiadomości o śmierci gracza.

### ISSUE THREAD

**Issue by Bart0l** [FunnyGuilds/FunnyGuilds#1287]
Zastanawiałem się czego może brakować w tym pluginie, i od dawna brakuje według mnie "custom śmierci"
Już tłumaczę:
Chciałbym aby w pluginie pojawiła się opcja zmiany standardowej wiadomości o śmierci gracza np z X burned to death czy coś 
Przykład:
death-in-lava: {USERNAME} utonął w lavie! (-{-}) 
death-from-high: {USERNAME} spadł z wysokości (-{-})
I tak dalej.. fajnie było by zobaczyć taką opcje w FG :)

**Comment by Rollczi** [comment]
Ten pomysł nie jest powiązany z FunnyGuilds...

Za to są już jakieś pluginy nawet z efektami dodatkowymi, a nawet integracją discord:
https://www.spigotmc.org/resources/deathmessages.3789/
https://www.spigotmc.org/resources/deathwarden.73535/
