### ISSUE TITLE
Skarbiec gildyjny

### ISSUE THREAD

**Issue by Blox61** [FunnyGuilds/FunnyGuilds#1297]
Witam. Piszę z propozycją dodania skarbca gildii otwierającego się pod komendą /skarbiec.
Miałoby to za zadanie przetrzymywać itemy gildii, które każdy członek może je w nim umieścić. Każda gildia posiadałaby swój skarbiec. Można go otwierać w każdym miejscu, nie tylko w gildii

**Comment by arturekdev** [comment]
Może dodatkowo system ulepszania skarbców? :D

**Comment by Blox61** [comment]
> Może dodatkowo system ulepszania skarbców? :D

Dokładnie. Powiększanie skarbca przykładowo

**Comment by grabeq123** [comment]
Najlepiej abye ten skarbiec mogl byc otwierany tylko w sercu gildi np ze podchodzisz do serca klikasz i on ci sie odpala.

**Comment by P3ridot** [comment]
Opcja weryfikacji włożonych i wykętych przedmiotów oraz system pozwalający na ustawienie składek (#1669)

**Comment by P3ridot** [comment]
Duplicate #1103
