### ISSUE TITLE
Brak rankingu dla zaatakowanego kiedy atakujący sam zginie.

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1304]
Kiedy atakujący zaatakuje kogoś i ta osoba go nie uderzy, to mimo tego że atakujący zginie np. przez upadek to zaatakowany przez niego gracz nie dostanie punktów, mimo że zmieścił się w czasie ustawionym w configu.

https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
59-64, tam jest tylko określone jeżeli jest ostatni atakujący a nie też zaatakowany co według mnie powinno być.

**Comment by insertt** [comment]
Moim zdaniem system rankingu w aktualnej formie działa dobrze, gdyż nie widzę powodu dlaczego gracz, który nie przyczynił się do śmierci danego gracza powinien dostać punkty za śmierć tego gracza - i takie rozumowanie też można zaobserwować w wielu grach online, gdzie zaatakowanie danego gracza a następnie śmierć bez kontrybucji zaatakowanego gracza powoduje jedynie naliczenie samobójstwa lub zabójstwa przez innego gracza.

**Comment by radek203** [comment]
Moim zdaniem powinna być taka opcja w configu żeby takie coś włączyć ponieważ są takie sytuacje że gracz np. może specjalnie denerwować innych graczy np. strzelając do nich z łuku i uciekając po drodze specjalnie wskakując do dziury żeby siebie zabić żeby tylko ten co go goni nie dostał punktów. A jest to tylko jeden przykład, a takich sytuacji jest wiele więcej.
