### ISSUE TITLE
Błąd podczas pobierania statusu wersji nightly

### ISSUE THREAD

**Issue by Qotrek** [FunnyGuilds/FunnyGuilds#1307]
Witam, po uruchomieniu serwera wywala błąd, niestety nie znalazłem rozwiązania dlatego piszę tutaj. 
Korzystam z oficjalnej i aktualnie najnowszej wersji Pluginu FunnyGuilds.
Poniżej wklejam lastes.log, dodam iż błąd pojawia się bez ingerowania z config.
[latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/4877516/latest.log)

**Comment by insertt** [comment]
Spróbuj zaktualizować do najnowszego nightly dostępnego [tutaj](https://ci.insertt.dev/job/FunnyGuilds).

**Comment by Qotrek** [comment]
Dzięki bardzo za pomoc.

**Comment by Qotrek** [comment]
Niestety nadal nie działa :/

**Comment by insertt** [comment]
To nie jest najnowsza wersja nightly pluginu, a przynajmniej tak wynika z podesłanych przez Ciebie logów: ``` org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.4.3 Tribute-f23a2cc```

**Comment by Qotrek** [comment]
> To nie jest najnowsza wersja nightly pluginu, a przynajmniej tak wynika z podesłanych przez Ciebie logów: ` org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.4.3 Tribute-f23a2cc`

![image](https://user-images.githubusercontent.com/49820993/86906720-3de2c580-c114-11ea-9a38-67e727ea686d.png)
Czy to jest najnowsza wersja?

**Comment by dzikoysk** [comment]
Tak, ta https://ci.insertt.dev/job/FunnyGuilds/job/master/

**Comment by Qotrek** [comment]
Po wrzuceniu tej wersji na serwer i usunięciu folderu `FunnyGuilds`
Wyskakują takowe błędy [latest.log](https://pastebin.com/7ssTbznA)

**Comment by insertt** [comment]
Pobierz najnowszą wersje nightly dostępną [tutaj](https://ci.insertt.dev/job/FunnyGuilds), a także tymczasowo wyłącz opcję w konfiguracji pod kluczem `update-nightly-info`.

**Comment by Qotrek** [comment]
> Pobierz najnowszą wersje nightly dostępną [tutaj](https://ci.insertt.dev/job/FunnyGuilds), a także tymczasowo wyłącz opcję w konfiguracji pod kluczem `update-nightly-info`.

Pobrałem ją, zmieniłem `update-nightly-info` na false, pozostał tylko jeden błąd [lates.log](https://pastebin.com/8KZvXP8C)

**Comment by insertt** [comment]
Czy mógłbyś spróbować wersji dostępnej [tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/148/) i dać znać, czy teraz wszystko jest ok?

**Comment by Qotrek** [comment]
> Czy mógłbyś spróbować wersji dostępnej [tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/148/) i dać znać, czy teraz wszystko jest ok?

Przy wyłączonym `update-nightly-info` wszystko działa, nie ma błędów, czy włączyć i spróbować ponowanie?

**Comment by insertt** [comment]
> > Czy mógłbyś spróbować wersji dostępnej [tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/148/) i dać znać, czy teraz wszystko jest ok?
> 
> Przy wyłączonym `update-nightly-info` wszystko działa, nie ma błędów, czy włączyć i spróbować ponowanie?

Tak, po zmianie fdb9a63 nightly updater powinien działać poprawnie.

**Comment by Qotrek** [comment]
Występuje taki błąd: [log](https://pastebin.com/tBm0VbgE)

**Comment by Qotrek** [comment]
Przy wchodzeniu  gracza na serwer pojawia się taki bład [log](https://pastebin.com/ZkFkqULt)

**Comment by dzikoysk** [comment]
Czy mógłbyś odpalić serwer z samym FG bez innych pluginów i zobaczyć, czy błąd dalej występuje? :)

**Comment by Qotrek** [comment]
> Czy mógłbyś odpalić serwer z samym FG bez innych pluginów i zobaczyć czy błąd dalej występuje? :)

Po uruchomieniu pluginu na localhoscie nie występuje żadnen błąd [logi](https://pastebin.com/DePSzzhB)
Czy hosting lub jakiś plugin może blokować połączenie?

**Comment by dzikoysk** [comment]
Trafiłeś na konflikt, któryś z Twoich pluginów używa biblioteki `com.fasterxml.jackson.core` w starszej wersji i gryzą się między sobą. Nie możemy relokować tej biblioteki, więc prawdopodobnie niedługo zaimplementujemy tą funkcję w inny sposób. Na ten moment po prostu wyłącz ten updater i będziesz miał problem z głowy.

**Comment by Qotrek** [comment]
> Trafiłeś na konflikt, któryś z Twoich pluginów używa biblioteki `com.fasterxml.jackson.core` w starszej wersji i gryzą się między sobą. Nie możemy relokować tej biblioteki, więc prawdopodobnie niedługo zaimplementujemy tą funkcję w inny sposób. Na ten moment po prostu wyłącz ten updater i będziesz miał problem z głowy.

Okej, dziękuje za odpowiedzi i pozdrawiam.
