### ISSUE TITLE
Placeholder z informacją o tag gildii resetuje się

### ISSUE THREAD

**Issue by kozunek** [FunnyGuilds/FunnyGuilds#1338]
Witam mam problem z placeholder odpowiedzialnym za tag i nazwę gildii ponieważ gdy gracz wychodzi z serwera jest on resetowany. Istnieje możliwość by tag był zapamiętany nawet gdy gracza nie ma na serwerze?

**Comment by dzikoysk** [comment]
Czy na najnowszej wersji problem dalej się pojawia?

**Comment by kozunek** [comment]
Błąd dalej występuje nawet po zaktualizowaniu go do najnowszej wersji

**Comment by dzikoysk** [comment]
Czy błąd występuje na serwerze bez innych pluginów?

**Comment by kozunek** [comment]
Tak w najnowszej wersji wszystko gra juz tylko teraz mam problem bo ustawiam
 explode-materials: 
  '*': 20.0
to owszem na obsydian to dziala ale na inne bloki juz nie
