### ISSUE TITLE
Placeholderapi - scoreboard

### ISSUE THREAD

**Issue by mdkjd** [FunnyGuilds/FunnyGuilds#1340]
Wersja - aktualna
Wersja silnika - 1.16.2 spigot
Problem - po dodaniu pluginu PlaceholderAPI (najnowszej oraz starszej wersji pluginu ) znika napis z liczbą punktów danego gracza tak zwany scoreboard. Czy jest możliwosć dodania wsprcia placeholderapi dla scoreboardu?

**Comment by dzikoysk** [comment]
Możesz spróbować użyć opcji `use-shared-scoreboard` używając najnowszych wersji FG.
