### ISSUE TITLE
problem z sercem gildii na wersji 4.7.0

### ISSUE THREAD

**Issue by PanPioter** [FunnyGuilds/FunnyGuilds#1342]
plugin nie ma configu po zainstalowaniu
https://drive.google.com/file/d/1rcw5zdpJe_12i4oHLA1j7DNqGI0RgsM_/view
a jak dodaje to nic sie nie dzieje
bardzo prosze o pomoc

**Comment by insertt** [comment]
Wrzuć pełen log serwera na np. [Pastebin](https://pastebin.com/) oraz dokładnie z jakiej wersji serwera oraz FunnyGuilds korzystasz.
