### ISSUE TITLE
Długi czas wklejania powietrza ze schematica

### ISSUE THREAD

**Issue by konmedy** [FunnyGuilds/FunnyGuilds#1344]
Wersja FunnyGuilds: 4.7.0 Stable
Silnik serwera: PaperSpigot 1.8.8
Problem: Gdy serwer używa FastAsyncWorldEdit, wklejenie powietrza ze schematica bazy zajmuje minutę. Czas ten jest skrócony do mniej niż sekundy gdy serwer używa zwykłego WorldEdita.

**Comment by oscarPLL** [comment]
To w jaki sposób to jest wina fg? XD

**Comment by CDFN** [comment]
Możliwe, że FG źle używa api (w co bardzo wątpię), ale nadal - możliwość jest. Skoro coś nie działa na poziomie FG to warto to zgłosić, bo może problem nie do końca leży w pluginie który jest zależnością. A tak na marginesie - wątpię, że cokolwiek z tym zdziałasz - https://howoldisminecraft188.today/

**Comment by insertt** [comment]
Korzystamy ze standardowego API WorldEdita i jeżeli wklejanie na standardowym WorldEdicie działa dobrze, to należy szukać problemu w FAWE.
