### ISSUE TITLE
blad z /sethome

### ISSUE THREAD

**Issue by KamilM3004** [FunnyGuilds/FunnyGuilds#1345]
Jesli ktos ustawi /sethome i na tym terenie ktos stworzy gildie osoba co ustawila home nadal moze sie tepac w to miejsce

**Comment by insertt** [comment]
To nie jest problem, który da się rozwiązać po stronie FunnyGuilds, lecz po stronie pluginu oferującego komendę `/sethome` (np. nasłuchując na event od założenia gildii).
