### ISSUE TITLE
Wolne tereny w gui

### ISSUE THREAD

**Issue by Keymilek** [FunnyGuilds/FunnyGuilds#1349]
# Propozycja
Chciałbym zaproponować dodanie kilku rzeczy, które mogło by się przydać do pluginu.

Propozycje:
* ~~Dodanie limitu sojuszu między gildiami~~
* ~~Dodanie komenda /pvpsojusz~~
* Dodanie komendy /wolnemiejsce (Wyświetla wolne tereny na założenie gildii w GUI pokazuje jak daleko mamy i kordynaty tego miejsca)
*  Wsparcie dla hookowania się pluginów na incognito do FG
~~Incognito dla graczy działające właśnie w funnyguilds (Ułatwi to rozgrywke graczom oraz administracji) Gracze mogą ukryć nick, ranking, gildie a admin z opowiednią permisiją widzi wszystko.~~

Pozdrawiam.

**Comment by insertt** [comment]
Komenda /pvpsojusz jest aktualnie zaimplementowana pod komendą `/pvp <tag zaprzyjaźnionej gildii>`

**Comment by insertt** [comment]
Limit sojuszów między gildiami jest dostępny w konfiguracji pluginu.

**Comment by P3ridot** [comment]
Tryb incognito to zbyt skomplikowany system wybiegajacy daleko poza FG. Moglibyśmy jedynie w przyszłości dodać wsparcie hookowania sie do FG, aby takowy tryb incognito wspierać zewnętrznym pluginem
