### ISSUE TITLE
chaty gildyjne i deluxechat

### ISSUE THREAD

**Issue by inuczi** [FunnyGuilds/FunnyGuilds#1352]
Chcialem zglosic blad zwiazany z kompatybilnoscia funnyguilds i deluxechat. W momencie gdy wylaczam deluxe chat chaty gildyjne dzialaja bezproblemu natomiast gdy deluxechat dziala wiadomosc po wykrzykniku wysyla sie jednoczesnie na chacie globalnym jak i na chat gildyjny. Pracuje na sieci serwerow minecraft wiec rezygnacja z deluxechata jest praktycznie niemozliwa, a po przegladnieciu dokumentacji deluxechatu bardzo dokladnie nie znalazlem nic co mogloby naprawic ten blad wiec zwracam sie do was tutaj. Dodatkowo screen z bledu wraz z deluxechatem na wersji 1.16.0 i funnyguilds na wersji 4.7.0
![123460555_1294205384270663_4243058637393738781_n](https://user-images.githubusercontent.com/74372795/98973018-80c60700-2513-11eb-9a6a-b44d64575612.png)

**Comment by insertt** [comment]
Niestety z powodu tego, że DeluxeChat jest pluginem, który obsługuje chat międzyserwerowy, a co za tym idzie działa najprawdopodobniej na poziomie samego proxy, przez co FunnyGuilds nie jest najprawdopodobniej (gdyż plugin jest płatny, więc nie jesteśmy pewni) w stanie jakkolwiek naprawić ten problem.
