### ISSUE TITLE
Problem z TNT

### ISSUE THREAD

**Issue by kozunek** [FunnyGuilds/FunnyGuilds#1353]
W najnowszej wersji Nightly (#179) Nie działa ochrona gildii przed tnt w danych godzinach oraz funkcja "Jakie materialy i z jaka szansa maja byc niszczone po wybuchu" działa tylko na obsidian wodę lawe etc. ale nie działa na podstawowe bloki takie jak stone dirt.

**Comment by insertt** [comment]
Co dokładniej nie działa w funkcji `Jakie materialy i z jaka szansa maja byc niszczone po wybuchu`?

**Comment by kozunek** [comment]
Dodałem np. stone albo dirt by miały szansę na wybuch 20% ale nieważne jaki % jest ustawiony to i tak zwykle bloki wybuchają normalnie funkcja działa tylko na bloki które nie wybuchają takie jak obsydian woda lawa

**Comment by kozunek** [comment]
Ale temat do zamknięcia po pobraniu najnowszego update #180 już wszystko działa prawidłowo
