### ISSUE TITLE
Zmiana działania komendy /ucieczka

### ISSUE THREAD

**Issue by Gracv** [FunnyGuilds/FunnyGuilds#1354]
Siema, moim zdaniem lepiej by było gdyby ucieczka działała dla wszystkich i teleportowała po prostu na spawna, nie każdy na serwerze jest w gildii a uciec z gildii nie może. Ewentualnie dodać do configu opcję włączenia tej alternatywnej ucieczki.

**Comment by dzikoysk** [comment]
Włącz opcję `escape-spawn` z najnowszego nightly i daj znać, czy działa poprawnie :)

**Comment by Gracv** [comment]
Działa
