### ISSUE TITLE
Kolor nicku

### ISSUE THREAD

**Issue by arki77** [FunnyGuilds/FunnyGuilds#1355]
Siemka, 
Jak na SS widać gracz nad głową posiada [TAG] i swój nick, moja propozycja jest taka aby wraz z tagiem zmieniał się również kolor nicku gracza 👍 

![unknown (3)](https://user-images.githubusercontent.com/67235274/99313098-459f3d00-285f-11eb-84c0-318c97c82bd9.png)

**Comment by Rollczi** [comment]
Ta funkcja jest już w FunnyGuilds.
Np. w config:
```prefix-other: "&7[&4{TAG}&7] &c"```

![image](https://user-images.githubusercontent.com/49173834/104005634-bbf85580-51a5-11eb-9c68-42f530cee22e.png)
