### ISSUE TITLE
Punkty antylogoutu.

### ISSUE THREAD

**Issue by szymekXplay** [FunnyGuilds/FunnyGuilds#1358]
Cześć, mam dość poważny problem. Otóż chodzi o punkty i antylogout
Otóż, przykładowo serwer ma antylogout usatwiony na 30 sekund, lecz gildie funnyguilds odejmują punkty tylko 5 sekund od uderzenia.
I prośba o to aby dodać do configu jakiś czas logout dawania punktów czy coś. Jest to dość problematyczne, bo gracz wylogowuje się po ~6 sekundach i zabija go antylogout lecz nie odejmuje punktów.

**Comment by dzikoysk** [comment]
Czy testujesz to przy takich ustawieniach?

```
rank-farming-protect: true
rank-farming-last-attacker-as-killer: true
rank-farming-consideration-timeout: 30
```

**Comment by szymekXplay** [comment]
Tak mam ustawione i nadal to samo.

**Comment by Haczyn** [comment]
@dzikoysk  ten sam problem

**Comment by dzikoysk** [comment]
Czy używacie najnowszego buildu FG z nightly?
