### ISSUE TITLE
Asysty za bicia na terenie NON PVP WorldGuard

### ISSUE THREAD

**Issue by 0VERR** [FunnyGuilds/FunnyGuilds#1359]
Witam, gdy Gracz bije innych na terenie NON PVP, a potem ktoś tego Gracza zabije, to osoba, która uderzała go na terenie NON PVP dostaje asystę.

**Comment by crejk** [comment]
Witam, czy próbowałeś skorzystać z opcji w konfiguracji 'assistsRegionsIgnored'?

**Comment by 0VERR** [comment]
Witam, nie próbowałem ale spróbowałem dzięki działa
