### ISSUE TITLE
Bugowanie 

### ISSUE THREAD

**Issue by BakuQ** [FunnyGuilds/FunnyGuilds#1360]
Witam przychodzę z propozycją aby wprowadzić możliwość robienia Waters skilli na terenie gilii oraz jakoś zrobić aby AntyCheat nie gryzł się z bugowaniem klocków bo gdy jest włączony survivalfly w anty cheaty to gdy się buguje to wybija do góry i bugowanie nie jest płynne

**Comment by insertt** [comment]
Kompatybilność z anticheatami to niestety nie jest prosta sprawa i raczej w najbliższej przyszłości nie planujemy niczego takiego, dlatego też polecałbym albo wyłączyć check na survivalfly albo bugowanie klocków.
