### ISSUE TITLE
Problem z połączeniem do bazy danych.

### ISSUE THREAD

**Issue by PinkBalaclavaa** [FunnyGuilds/FunnyGuilds#1361]
**LOGI** https://hastebin.com/ajocofejuw.css

Dodam że połącznie z baza jest itp. Sprawdzałem na innych bazach danych nie na localhoscie i dalej to samo.
Please help 

najnowsza wersja funnyguilds
mysql 8.0 na ubuntu 20.04

**Comment by dzikoysk** [comment]
Błąd nie dotyczy FG, a ustawień bazy danych na które nie mamy wpływu. Wyłącz SSL i spróbuj połączyć się z bazą.
