### ISSUE TITLE
Nie wiem jak ustawić wymagane przedmioty na założenie gildii

### ISSUE THREAD

**Issue by XenderLord** [FunnyGuilds/FunnyGuilds#1367]
na razie mam w config.yml cos takiego:

items: 
- "<16 diamond_block>"
- "<16 bookshelf>"
- "<32 tnt>"
- "<16 ender_pearl>"

ale to nie działa bo w grze wyświetla mi się cos takiego:
![2020-12-12_21 28 40](https://user-images.githubusercontent.com/46809371/101994229-198da500-3cc1-11eb-8fd7-05726abe2cfb.png)

(pewnie duzo rzeczy zrobiłem nie tak, powinienem dać więcej info, przesłać screena za pomaca linka i w ogule, jak cos to ja to jeszcze moge podać/zmienić sorry)

**Comment by XenderLord** [comment]
dobra 1 problem rozwiazalem, trzeba bylo napisac to tak:

items: 
- "16 diamond_block"
- "16 bookshelf"
- "32 tnt"
- "16 ender_pearl"

ale drugi problem taki ze dalej wyświetla tak dziwnie:
![2020-12-13_00 46 15](https://user-images.githubusercontent.com/46809371/101999384-c32e5f80-3cdc-11eb-9093-38448eb1a3ed.png)

jak to naprawic?

**Comment by dzikoysk** [comment]
Wrzuć config oraz logi z serwera
