### ISSUE TITLE
Nadpisanie opcji z PaperSpigot 1.12.2 (kolizje graczy)

### ISSUE THREAD

**Issue by Rollczi** [FunnyGuilds/FunnyGuilds#1369]
Przez FunnyGuilds 
**enable-player-collisions: false** w paper.yml
przestaje działać.

(Gracze mogą wypchać innych graczy po za spawn)

**Comment by pintoso** [comment]
apparently the same thing happens to me in 1.16.x
later i will test without the plugin to see if it is caused by funnyguilds, but Im experiencing the same problem... collision remains active even if disabled in `spigot.yml`...
>>> _sorry if this is not the issue, I used google translator to understand your problem_

**Comment by Rollczi** [comment]
Plugins with tablist and teams can overwrite collisions. (That's how I understood it)
I've already checked it and certainly FunnyGuilds is overwriting the collision.
Interesting reports on this topic:
[https://github.com/PaperMC/Paper/issues/2517](url)
[https://github.com/PaperMC/Paper/issues/376](url)

It would be nice to make an option in FunnyGuilds with collisions.
