### ISSUE TITLE
Guild members can break blocks while under attack

### ISSUE THREAD

**Issue by pintoso** [FunnyGuilds/FunnyGuilds#1372]
when a guild is under attack, guild members cannot place blocks, this works well and is fine.

**But** they can still BREAK blocks, this is a serious problem... if the guild is under attack, guild members can take the most valuable things and save in an ender's chest, etc ...
please add an option for guild members not to be able to break blocks while the guild is under attack

**Comment by dzikoysk** [comment]
Download the latest nightly. Added:

* `region-explode-block-breaking` - should lock breaking
* `region-explode-block-interactions` - should lock interactions with blocks listed in `blocked-interact` property

Could you confirm if it works as expected?

**Comment by pintoso** [comment]
### Sorry for the delay, it worked perfectly for me!

__
I have a suggestion that I think is related to that:

an option to block the funnel from receiving or moving items if the guild is under attack

why? when the guild is under attack they can still activate some redstone system with dispenser/dropper, etc. to drop items from the chest or shulker box, so they bypass the interaction block.

ways to fix this:

1. IF guild is under attack > IF hopper is in region > Check IF item is from chest or shulker box > cancel move item event

2. ... > check IF Destination is dispenser or dropper > cancel move item event

4. IF guild is under attack > IF hopper is in region > cancel all move item event


> anyway all ways should work well
and are only applied while the guild is under attack, so even if it temporarily stops something from working, after the war everything naturally goes back to normal

>> references:
https://www.spigotmc.org/threads/listen-for-hopper-moving-item-into-another-hopper.245425/
https://www.spigotmc.org/threads/disable-hoppers-moving-items-into-furnaces.420056/
