### ISSUE TITLE
Pomoc z TAG'iem

### ISSUE THREAD

**Issue by MrAdrianek** [FunnyGuilds/FunnyGuilds#1376]
Witam,
Pytanie dotyczące czy dało, by radę zrobić gildie bez ''TAG'u'', ponieważ chciałbym zrobić serwer z dwoma drużynami np: niebieska i czerwona?
Jeśli tak to możesz pomóc jak to zrobić, bo szukam szukam i nie mogę znaleźć jak to ustawić, a nie chce usuwać czegoś nie potrzebnie 

Dziękuje z góry 
Szczęśliwego Nowego Roku 2021

**Comment by Rollczi** [comment]
Nie da się zrobić gildii bez tagu.

**Comment by dzikoysk** [comment]
Ze wszystkich wiadomości możesz usunąć wyświetlanie tagu gildii, więc to raczej nie powinien być problem, żeby je względnie ukryć :)

**Comment by MrAdrianek** [comment]
W messages to usunąć?

**Comment by dzikoysk** [comment]
Musisz przejrzeć oba configi i dostosować to pod swoje potrzeby. W messages.yml ustawiasz wyświetlane wiadomości, w config.yml różne opcje odpowiadające za takie rzeczy, jak wyświetlanie tagów gildii przy nicku.
