### ISSUE TITLE
Zmiana nicku użytkowników premium nich śmiging

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#1382]
![image](https://user-images.githubusercontent.com/4235722/103931886-4e0a4a80-5121-11eb-91ed-706c6d9c461b.png)
![image](https://user-images.githubusercontent.com/4235722/103932118-a5a8b600-5121-11eb-9dd7-98bd5540e0cd.png)

**Comment by crejk** [comment]
Prawdopodobnie w tym [miejscu](https://github.com/FunnyGuilds/FunnyGuilds/blob/a49f5703cb95489a0917bf7ad2ddb9c23ff37328/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java#L41) trzeba usunąć użytkownika z `BY_NAME_USER_COLLECTION` i dodać używając już nowego nicku jako klucza.
