### ISSUE TITLE
Problem z cuboidem

### ISSUE THREAD

**Issue by MrAdrianek** [FunnyGuilds/FunnyGuilds#1391]
Witam, 
Czemu inni gracze spoza gildii mogą niszczyć klocki itp? Czy da się to ustawić? 
Pozdrawiam

**Comment by CDFN** [comment]
Jaką wartość masz w configu przy kluczu `regions-enabled`?

**Comment by MacioSzekTV** [comment]
A masz zainstalowany plugin WorldGuard?

**Comment by MrAdrianek** [comment]
Dobra ogarnięte, dzięki za pomoc

**Comment by dzikoysk** [comment]
Co powodowało błąd w Twoim przypadku? :)
