### ISSUE TITLE
PVP ON/OFF

### ISSUE THREAD

**Issue by MrAdrianek** [FunnyGuilds/FunnyGuilds#1393]
Witam,
Jak włączyc pvp gildyjne?

**Comment by dzikoysk** [comment]
Lider gildii może włączać/wyłączać pvp komendą `/pvp`

**Comment by MrAdrianek** [comment]
A co jeżeli na serwerze jest combatlog i w tym pluginie za pomocą ./pvp wyłącza się lub włącza globalnie pvp?

**Comment by dzikoysk** [comment]
Domyślnie dostępny jest również alias w postaci `/ustawpvp`. Dodatkowo nazwy wszystkich komend i ich aliasy możesz ustawiać w konfiguracji.

**Comment by MrAdrianek** [comment]
Dziękuje za pomoc
