### ISSUE TITLE
Api do pluginu.

### ISSUE THREAD

**Issue by Franqex** [FunnyGuilds/FunnyGuilds#1396]
Piszę plugin i chciałbym sprawdzić czy blok został postawiony na terenie gildi gracza. Wersja to 1.8.8.

**Comment by dzikoysk** [comment]
Użyj klasy metody `RegionUtils.getAt(location)`. Jeżeli zwróci jakiś region, to blok jest na terenie jakiejś gildii, w innym przypadku zwróci null.

**Comment by Franqex** [comment]
Dzięki, działa.
