### ISSUE TITLE
Hologramy z najlepszymi graczami i gildiami

### ISSUE THREAD

**Issue by Keymilek** [FunnyGuilds/FunnyGuilds#1400]
- Możliwość włączenia pvp między sojuszami
- Panel gildyjny z uprawnieniami
- Hologramy z najlepszymi graczami i gildiami

**Comment by dzikoysk** [comment]
Odnośnie punktu 1, to pvp między sojuszami można ustawiać za pomocą `/pvp [tag]` :)

**Comment by arturekdev** [comment]
@Keymilek  Używając pluginów [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/), [HolographicExtension](https://www.spigotmc.org/resources/holographicextension.18461/) oraz [HolographicDisplays](https://dev.bukkit.org/projects/holographic-displays) możesz otrzymać taki efekty. Stwórz hologram z linijką np. {medium} %funnyguilds_gtop-1%, otrzymasz wtedy na hologramie top 1 gildie. 

Zmienne dotyczące rankingu w FunnyGuilds:
%funnyguilds_gtop-x%
%funnyguilds_ptop-x%
