### ISSUE TITLE
Integracja między sojuszami oraz system wojen

### ISSUE THREAD

**Issue by Kamo452** [FunnyGuilds/FunnyGuilds#1401]
Witam! Dostarczam pomysły od graczy na moim serwerze. Używamy wtyczki FunnyGuilds. Poniższe propozycje posiadają poparcie liczące powyżej dwudziestu graczy i osobiście sądzę, że są całkiem w porządku.
1. Zwiększenie integracji z sojusznikami - możliwość budowania/otwierania skrzynek przez sojuszników na terenie własnej gildii, która może zostać wyłączona/włączona przez twórców przy użyciu komendy /integracja [TAG SOJUSZNIKA].
2. Komenda /sojusz pvp pozwalająca na włączenie/wyłączenie możliwości walki z sojusznikami.
3. Komenda /wojna [TAG] pozwalająca na dodanie danej gildii do listy, z którą trwa konflikt. Pod komendą /konflikty [TAG] ukazałaby się lista, z jakimi gildiami jest prowadzona wojna (bardziej pełniłaby rolę informacyjną), natomiast komenda /rozejm [TAG] pozwalałaby na rozwiązanie wojny z daną gildią.
Pozdrawiam

**Comment by dzikoysk** [comment]
Odnośnie punktu 2, to pvp między sojuszami można ustawiać za pomocą `/pvp [tag]` :)

**Comment by Kamo452** [comment]
Nie widziałem, dziękuję
