### ISSUE TITLE
Bug z tnt

### ISSUE THREAD

**Issue by Gracv** [FunnyGuilds/FunnyGuilds#1410]
TNT postawione obok gildii niszczy bloki chociaż nie powinno. 
https://streamable.com/gqvnuo

Wersja mc: 1.16.4
Wersja FG: 4.8.1

**Comment by dzikoysk** [comment]
Dzięki za zgłoszenie :)

Oczekiwanym rezultatem byłoby zniszczenie bloków tylko po stronie bez gildii czy zablokowanie niszczenia bloków przez cały wybuch, jeżeli przynajmniej jeden z dotkniętych wybuchem bloków należy do terenu jakiejś gildii?

**Comment by Gracv** [comment]
> Oczekiwanym rezultatem byłoby zniszczenie bloków tylko po stronie bez gildii czy zablokowanie niszczenia bloków przez cały wybuch, jeżeli przynajmniej jeden z dotkniętych wybuchem bloków należy do terenu jakiejś gildii?

Tnt nie miało zniszczyć nic, na filmie widać że pierwsze TNT nie zniszczyło bloków poza terenem gildii, (Jest to wyłączone w configu) ale za to zniszczyło na terenie gildii chociaż nie powinno (nie powinno - udowadnia to drugie postawione już na terenie TNT)

**Comment by Gracv** [comment]
Drugie tnt nie wybuchło bo jest ochrona godzinowa.
