### ISSUE TITLE
Problem ze zmiennymi fg (BungeetabListPlus)

### ISSUE THREAD

**Issue by kowadl0** [FunnyGuilds/FunnyGuilds#1412]
Czasami po wejsciu na serwer nie laduja sie zmienne z funnyguilds na bungeetablistplus, mam placeholderapi. Czasami  po wejsciu sie pokazuja a czasami nie

**Comment by dzikoysk** [comment]
FG rejestruje placeholdery w BTLP przy starcie serwera i nie odpowiada za logikę związaną z ich ustawianiem na tabliście, więc problem wynika z konfiguracji/błedu w tamtym pluginie.
