### ISSUE TITLE
Zła godzina, efekt bossbar

### ISSUE THREAD

**Issue by Issante** [FunnyGuilds/FunnyGuilds#1413]
Witam,
czy można zmienić jakoś manualnie godzinę lub zmienić strefę czasową? W tabliście jest przestawiony czas o godzinę. Możliwe, że tak samo będzie z ochroną przed TNT. Jak jest np. 16:00, to na Tabie pokazuje 15:00.

Czy da się jakoś usunąć wszystkie efekty po wejściu/wyjściu z terenu gildii?
Próbowałem:
notification-boss-bar-flags: []
notification-boss-bar-flags:
Ale nie da się usunąć, zawsze pozostaje mgła

Jak zrobiłem:
notification-boss-bar-flags: [DARKEN_SKY]
To było darken_sky+create_fog.

Wersja jaką używam to 1.16.4 + FG 4.9.0

**Comment by Issante** [comment]
O ja głupiutki. Jeżeli chodzi o strefę czasową, to miałem ustawioną źle na całym VPS. Musiałem po prostu tam zmienić i już wszystko jest ok :D

**Comment by dzikoysk** [comment]
Z tego co widzę, to mgła jest domyślną opcją w configu:

![image](https://user-images.githubusercontent.com/4235722/105560924-9f1b6080-5d15-11eb-9c27-2b128ec43370.png)

Po jej usunięciu (`notification-boss-bar-flags: []`) i zrestartowaniu serwera nie powinieneś jej widzieć 🤔

**Comment by Issante** [comment]
Faktycznie. nie wiem co źle robiłem, możliwe, że źle kwadratowe nawiasy wstawiłem, ale już działa, dzięki
