### ISSUE TITLE
Wsparcie odpalania kolejnego TNT przy kontrolowanych eksplozjach 

### ISSUE THREAD

**Issue by xGrabekxpl** [FunnyGuilds/FunnyGuilds#1414]
Witam, kiedy opcja w konfiguracji (
![image](https://user-images.githubusercontent.com/77733959/105180283-a9c5d200-5b2a-11eb-809b-15291d1c8c39.png) jest włączona, tnt po wybuchu nie odpala następnego tnt, tak jak to jest w przpadku, gdy tnt jest włączone wszędzie.

**Comment by dzikoysk** [comment]
Na ten moment nie ma takiej opcji, dlatego oznaczam to jako propzycję :)
