### ISSUE TITLE
[LuckPerms] Support

### ISSUE THREAD

**Issue by damianzdw** [FunnyGuilds/FunnyGuilds#1423]
Tak jak w temacie, gdy wgralem fg prefixy, pod TABem i te nad postacia, z luckpermsow sie zbugowaly, nie widac zadnych.

**Comment by arturekdev** [comment]
Z jakiego pluginu na TAB korzystasz?

**Comment by P3ridot** [comment]
Nie umiem tego zreprodukować bo u mnie wszystko działa
