### ISSUE TITLE
blad z region-commands

### ISSUE THREAD

**Issue by inuczi** [FunnyGuilds/FunnyGuilds#1427]
na wersji 4.8.1 Tribute-7a6b881 wystepuje problem z blokowaniem komend na regionie gildii, wpisane w configu dalej pozwalaja uzywac ich w grze

**Comment by dzikoysk** [comment]
Wykonują się wszystkie komendy z różnych pluginów, czy tylko komendy z jakiś konkretnych?

**Comment by inuczi** [comment]
z kazdych pluginow

**Comment by dzikoysk** [comment]
Komendy bez ograniczeń może wykonywać op/osoba z uprawnieniem `funnyguilds.admin`. Upewnij się, że testujesz tą funkcję jako standardowy użytkownik.
