### ISSUE TITLE
Mozliwość wyłączenia PvP.

### ISSUE THREAD

**Issue by Majkon** [FunnyGuilds/FunnyGuilds#1445]
Witam,
Prosiłbym o dodanie możliwości wyłączenia PvP od razu po stworzeniu gildii. Mianowicie chciałbym żeby po utworzeniu gildii można było wyłączyć PvP na terenie całej gildii tak, aby nikt nie mógł się na niej bić  (np. poprzez komendę lub config.yml)
Pozdrawiam.

**Comment by dzikoysk** [comment]
Lider gildii ma możliwość zmiany pvp między osobami z gildii oraz między sojuszami za pomocą komendy /pvp

**Comment by Majkon** [comment]
Tego pluginu używam tylko do rankingu oraz stworzenia jako tako gildi, ale zamysł mojego serwera jest taki, że te gildie to tak na prawdę działki i w niektórych pluginach są flagi i tam mogę sobie ustawić czy na terenie "działki" mogę wyłączyć całkowicie PvP czy też nie. Po wyłączeniu PvP "wrogowie" i tak mogą bić - tych spokojnie grających sobie graczy którzy grają tylko dla stworzenia działki i jej rozbudowy i to właśnie ich mam zamiar uchronić przed PvP. Oczywiście nie chcę ingerować w flagę __global__ gdyż poza terenem gildii pvp normalnie istnieje.

**Comment by dzikoysk** [comment]
Propozycja rozwiązana w postaci małego pluginu/skryptu (z FunnySkAddon).
