### ISSUE TITLE
Api gildie

### ISSUE THREAD

**Issue by Franqex** [FunnyGuilds/FunnyGuilds#1448]
Witam! Potrzebuje api do eventu gdy gildia zostanie zalozona i wyciagniecia z niej gracza ktory ja zalozyl.

**Comment by crejk** [comment]
Mozesz użyć tego eventu:
[GuildPreCreateEvent](https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/event/guild/GuildPreCreateEvent.java)
Założyciela wyciągniesz metodą `getDoer()`

**Comment by Franqex** [comment]
Nie wyszukuje mi takiego eventu jedynie GuildCreateEvent, jednak nie działa on tak jak bym chciał.

**Comment by crejk** [comment]
Zaktualizuj plugin do najnowszej wersji.
