### ISSUE TITLE
Zaimplementowanie hologramów nad sercem

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1462]
Dodajcie nad sercem gildii  hologramy które np pokazuja ile gildia ma serc? i tag Gildi. Fajnie byloby rowniez zobaczyc mozliwosc zmiany Serca Gildii w postaci np jakiejś główki która sie kreci z efektami.

**Comment by Jakubk15** [comment]
Pomysł bardzo mi się podoba, jestem za.

**Comment by P3ridot** [comment]
Can ktoś explain why to jest Feature & Enhancement at ten sam time?

**Comment by Kamilkime** [comment]
Dodanie hologramu wtedy było nowe (feature), zmiana serca byłaby ulepszeniem obecnego systemu (enhancement)

**Comment by P3ridot** [comment]
Same wsparcie hologramów zostało dodane, dodatkowe opcje customizacji serca zostały opisane w #1783
