### ISSUE TITLE
Dodanie mozliwosci automatycznego naprawienia gildi np komenda /napraw

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1464]
Chodzi mi o to ze jezeli jakas gildia zostanie zatakowana i rozwalona to wlasciciel gildi przy uzyciu np komendy /napraw naprawi swoja gildie. Wlasciciel bedzie musial np wplacic do skarbca gildi 120 blokow zlota aby proces naprawiania zostal rozpoczety. Gdy gracz wplacic surowce i zatwierdzi naprawianie gildi to bloki zostana automatycznie stawiane i gildia wroci do swojego pierwotnego wygladu tak jak wygladala przez atakiem na nia. Ta funkcja aby byla tylko i wylacznie odblokowana gdy TnT jest wylaczone. Chodzi tu aby gracze mogli naprawiac gildie w godzinach gdy tnt nie działa aby nie oszukiwac. Wazna sprawa jest tez to ze naprawianie gildi ma polegac tylko na stawianiu blokow a nie np ze jak byla skrzynka z itemami to skrzynka z itemami ktora dana gildia miala powrocila.

**Comment by Rollczi** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/issues/1208

**Comment by Rollczi** [comment]
Skarbca nie ma w fg ale został już tutaj opisany https://github.com/FunnyGuilds/FunnyGuilds/issues/1297

**Comment by grabeq123** [comment]
No to aby gracz poprostu trzymal jakas dana ilosc itemow ustalonych bez tego skarbca
