### ISSUE TITLE
Dodanie funkcji "rozkładu" terenu po usunięciu Gildii

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1465]
Gdy gildia juz wygasnie To fajnie byloby dodac opcje dikejowania bazy. Cala gildia bedzie sie niszczyc blok po bloku przez np okres 3 h po czym juz nic po niej nie zostanie a teren gildii na ktorym byla bedzie wygladal tak jakby nigdy nic tam nie bylo tylko normalny biom

**Comment by grabeq123** [comment]
Pisze ten komentarz aby reaktywować mój dosyć ciekawy pomysł ze względu iż mija już 8 miesięcy i może ktoś coś takiego by dodał :D

**Comment by P3ridot** [comment]
Aktualnie nie jest to priorytetowa rzecz. Myślę, że dalej można sie go spodziewać ale kiedy to już nie wiadmo.

**Comment by grabeq123** [comment]
Okej, rozumiem byle żeby ten pomysł nie przeszedł do histortii a jego realizacja nie była 6 miesieczna czy 1 roczna bo mineło juz kawałek czasu od napisania tego postu

**Comment by dzikoysk** [comment]
Pomysł fajny, ale na razie nie ma szans na wejście w życie. Linkuję jako luźną propozycję z 6.x, gdzie najwcześniej w ogóle byłaby szansa o tym myśleć: 

* https://github.com/FunnyGuilds/FunnyGuilds/issues/2226
