### ISSUE TITLE
Schowek PvP

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1470]
Dzięki temu pluginowi poprawi sie uczciwość podczas PvP Gildyjnych jak i ogólnych. Schowek ma za zadanie ustawic jakis limit koxow ,refili, perelek na calyn serwerze. Jego zastosowanie jest taki ze gdy gracz ma np 32 refy a na serwie jest ustawiony limit 12 to pozostale 20 refów zostaje odlozone do schowka gdzie gracz bedzie mogł wyplacic je w kazdej chwili lecz gdy uderzy jakiegos gracza lub zje koxa czy refa to nadmiar tych przedmiotów zostanie odlozony do schowka. Plugin najlepiej zrobic w gui gdzie np najechanbiem na refila pokaze sie aktualny stan ile gracz posiada refili w schowku i jaki jest limit na serwerze + gdy kliknie np wyplac wszystko to schowek wyplaci mu wszystkie koxy. Wazna rzecza jest to aby schowek mogl wyplacac wszystko ale tylko wtedy gdy gracz z nikim nie walczy lub nie je koxa  bo gdy zje koxa lub bedzie sie z kims klepac to automatycznie zostanie mu ten nadmiar zabrany. Mysle ze sam dodatek jest w miare prosty i nie jest trudny a poprawicie gre  dzieki temu wielu osoba dlatego licze na was chlopaki :D. W przyszlosci mozecie dodac do tej wtyczki Topke ze np Top 10 ludzi ktorzy maja najwiecej refow , koxow i perel w schowko fajna sprawa tak jak np top 10  zjedzonych czy uzytych koxow ,refow i perelek. Dzieki temu PvP nabierze inny i lepszy poziom zabawy.

**Comment by P3ridot** [comment]
"Nie róbmy z FunnyGuilds pluginu na wszystko." ~ insertt

**Comment by grabeq123** [comment]
Mowie tu tylko o dodatku do FG zreszta same FG to Wojny gildi czyli ich glównym celem jest PvP z innymi graczami z przeciwnej gildi a ten dodatek ma za zadanie poprawic jakosc tego PvP

**Comment by CDFN** [comment]
Ale nie każdy gamemode polega na ograniczaniu graczy, podpinam się pod opinię Peridota.

**Comment by grabeq123** [comment]
Ale to ma byc dodatek ktorego nie musisz instalowac jak nie chcesz wiem ze  kazdy woli uczciwe pvp gdzie kazdy ma rowne szanse niz jakby liczylo sie ile kto ma koxow bo to jest bez sensu i odechciewa sie walczyc wtedy.

**Comment by CDFN** [comment]
Nie rozumiem co napisałeś w pierwszym zdaniu. Nadal uważam, że schowek nie powinien być integralną częścią FG (Funny **GUILDS**). A ten drugi argument z cheatowaniem - nie wiem dlaczego w ogóle pojawił się w dyskusji o schowku na przedmioty. Istnieje wiele pluginów, które oferują funkcjonalność schowka i osobiście nie widzę potrzeby dodawania tzw. bloatu do FG.

**Comment by grabeq123** [comment]
Nie ma pluginu na schowek który  jest co jakis czas aktualizowany  i sa dodawane jakies fajne nowe opcje. Chodzi mi o to ze plugin ten ma porpawic tylko tryb pvp na serwerach i wydaje mi sie ze przydalby sie bardzo w fg a gracze ktorzy by go nie chcieli nie musieli by go pobierac.

**Comment by CDFN** [comment]
https://github.com/Kamilkime/KSafe - jak napiszesz coś w Issues to myślę, że autor może dodać
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
wtorek, 2 marca 2021 10:47, grabeq123 <notifications@github.com> napisał(a):

**Comment by Rollczi** [comment]
FunnyGuilds to nie jest Core na cały serwer gildii, tylko jest częścią serwera. FunnyGuilds powinno odpowiadać za **system Gildii** i wszystko z nim związane. Schowek jest częścią **systemu PvP** który zmienia logikę walki, więc ten pomysł prawdopodobnie zostanie odrzucony. No ale jeszcze zobaczymy co zrobi zarząd ~~centralny~~.

**Comment by grabeq123** [comment]
Okej licze jednak ze stworza taki dodatek.

**Comment by Aethusx** [comment]
Xd

**Comment by Morelcia** [comment]
> FunnyGuilds to nie jest Core na cały serwer gildii, tylko jest częścią serwera. FunnyGuilds powinno odpowiadać za **system Gildii** i wszystko z nim związane. Schowek jest częścią **systemu PvP** który zmienia logikę walki, więc ten pomysł prawdopodobnie zostanie odrzucony. No ale jeszcze zobaczymy co zrobi zarząd ~centralny~.

Masz rację, @Rollczi. To by była redundantna redundancja.

**Comment by Kamilkime** [comment]
> https://github.com/Kamilkime/KSafe - jak napiszesz coś w Issues to myślę, że autor może dodać

O, wpadłem przypadkiem a tu mój plugin. No i to prawda - jak by ktoś zaproponował jak dokładnie ma to działać z FG to mogę dodać jakiś hook

**Comment by polskistevek** [comment]
huj

**Comment by P3ridot** [comment]
Funkcjonalność znacząco odbiega poza plugin gildyjny. Są już pluginy na schowek i myślę, że jeśli potrzebują wsparcia dla FG to wystawione API FG im wystarczy. Wyżej został wspomniany np. plugin https://github.com/Kamilkime-Plugins/KSafe
