### ISSUE TITLE
[SuperVanish] integracja z TabList & Dodanie opcji akceptacji /wojny

### ISSUE THREAD

**Issue by Trewur** [FunnyGuilds/FunnyGuilds#1480]
Dodanie opcji akceptacji /wojny między gildiami.
W tablist dodać opcje połączenia z np. supervanish, żeby admini na /v nie byli ukazywani w rankingu czy żeby byli pokazywani jako offline.

**Comment by Rollczi** [comment]
Co do propozycji `Dodanie opcji akceptacji /wojny między gildiami.`, wydaje mi się to bezsensu. Wojny się wypowiada innym czy tego chcą, czy nie. To, że ktoś nie akceptuje wojny, nie oznacza, że jej nie będzie. ¯\\\_(ツ)_/¯
