### ISSUE TITLE
Możliwość określenia osobnych zestawów przedmiotów potrzebnych na gildie przypisanych do danego uprawnienia

### ISSUE THREAD

**Issue by Nexus123123** [FunnyGuilds/FunnyGuilds#1489]
Utworzenia dodatkowych permisji, aby inne rangi (np. vip++, elita, sponsor czy cokolwiek innego) (oprócz Gracza i Vipa) używały mniejszej ilości przedmiotów do tworzenia gildii, ponieważ plugin ma tylko wbudowane trzy permisje (player, admin, default).

**Comment by P3ridot** [comment]
Duplicate #963
