### ISSUE TITLE
Po restarcie powiększenie cuboidów się resetuje.

### ISSUE THREAD

**Issue by Gracv** [FunnyGuilds/FunnyGuilds#1490]
Tak jak w nazwie tematu. 
Baza mysql
Config: 
https://paste.gg/p/anonymous/fd9d347ad87e453a94136704446a549e

Wersja pluginu: 4.9.3 z commitem "Get the regionOther message out of the util class (#1474)"

0 błędów w konsoli

**Comment by Gracv** [comment]
W mysql wszystkie gildie mają size 30, tak jakby tylko to się nie aktualizowało.

**Comment by dzikoysk** [comment]
Na pierwszy rzut ok wszystko wygląda ok. 
* Problem występuje w każdej gildii na serwerze? 
* Czy w momencie powiększenia gildii w trakcie działania wszystko działa poprawnie?

**Comment by Gracv** [comment]
> Problem występuje w każdej gildii na serwerze cały czas, czy to była jednorazowa sytuacja?

Cały czas.

> Czy w momencie powiększenia gildii w trakcie działania serwera do momentu restartu wszystko działa poprawnie?

Tak. Dopiero po restarcie "powiększenia" się resetują do domyślnej wartości.

**Comment by dzikoysk** [comment]
Oki, to teraz kwestia ustalenia czy to się dzieje w trakcie zapisu czy odczytu. Powiększ gildię, zatrzymaj serwer i powiedz czy w bazie jest poprawna wartość. Jeżeli jest poprawna, to uruchom serwer i powiedz czy wtedy dopiero zresetowało.

**Comment by Rollczi** [comment]
@Gracv błąd został już naprawiony w nowej wersji Nightly.
