### ISSUE TITLE
Problem związany z powiększaniem regionów gildii.

### ISSUE THREAD

**Issue by Rollczi** [FunnyGuilds/FunnyGuilds#1505]
Regiony resetują się do wartości domyślnych po restarcie.
Tak jak zostało to opisane w tym issue: https://github.com/FunnyGuilds/FunnyGuilds/issues/1490
Mogę to sprawdzić ale będzie to mogło trochę potrwać.

**Comment by PinkLolicorn** [comment]
你最好检查FunnyBox

**Comment by insertt** [comment]
Naprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/5aa766490f874d3e749c68f2063914cf46d1efe0.
