### ISSUE TITLE
Kolor relacji wojny między gildiami nie wyświetla się na TabList

### ISSUE THREAD

**Issue by Hexany** [FunnyGuilds/FunnyGuilds#1508]
Nad nickiem wyświetla się kolor z relacji wojny między gildiami, natomiast na TabList się już nie wyświetla.
![obraz_2021-04-14_123452](https://user-images.githubusercontent.com/82510004/114697128-cf273e00-9d1d-11eb-9aff-b179c8f29c40.png)
![obraz_2021-04-14_123952](https://user-images.githubusercontent.com/82510004/114697683-82903280-9d1e-11eb-82c0-3b09533b5ce9.png)

**Comment by Rollczi** [comment]
chyba chodzi o jeden kolor (`temat: Kolor o wrogości gildii nie wyświetla się na tabie`) który został dodany z /wojna

**Comment by Hexany** [comment]
> chyba chodzi o jeden kolor (`temat: Kolor o wrogości gildii nie wyświetla się na tabie`) który został dodany z /wojna

Chodzi tylko w wypadku wojen, w sojuszach działa wszystko prawidłowo
