### ISSUE TITLE
Kalifornication (aka Rewrite to Kotlin)

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#1510]
Move to Kotlin.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/YlUKcNNmywk/0.jpg)](https://www.youtube.com/watch?v=YlUKcNNmywk)

**Comment by CDFN** [comment]
????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by PinkLolicorn** [comment]
不不不

**Comment by dzikoysk** [comment]
pozdro poćwicz

**Comment by Rollczi** [comment]
![531226595952820224](https://user-images.githubusercontent.com/49173834/114934960-9912b880-9e08-11eb-8dc3-59832a6e4df7.png)

**Comment by PinkLolicorn** [comment]
![kotlin](https://user-images.githubusercontent.com/44551064/114935189-2a028780-9e3b-11eb-95d5-041c18f77e30.png)

**Comment by dzikoysk** [comment]
Dobra komu by się chciało

**Comment by P3ridot** [comment]
Nasze defaultowe moduły będą w kotlinie, jak ktoś będzie chciał napisać własne to będzie miał API w javie i essa 🤪

**Comment by dzikoysk** [comment]
Done
