### ISSUE TITLE
Problem z fg

### ISSUE THREAD

**Issue by TaczkaAww** [FunnyGuilds/FunnyGuilds#1511]
paper spigot 1.8.8 (na spigot 1.8.8 to samo)
najnowsza wersja FG

[09:28:10 WARN]: [FunnyGuilds] Cannot register EntityPlaceEvent listener on this version of server

**Comment by CDFN** [comment]
To tylko ostrzeżenie, że Twoja wersja serwera nie wspiera tego eventu. Niektóre funkcje mogą być niedostępne. Jeżeli chcesz zlikwidować ten komunikat to zaktualizuj serwer do najnowszej wersji.

**Comment by TaczkaAww** [comment]
w tym problem ze nie chyba nowszej wersji spigota 1.8.8, nawet /zaloz nie dziala

**Comment by TaczkaAww** [comment]
Dobra, /zaloz już dziala był to problem z mojej strony, jakie funkcje mogą nie działac bez tego eventu>

**Comment by PinkLolicorn** [comment]
Będzie można stawiać armor standy, łodzie i wagoniki na terenach nieswoich gildii.

**Comment by TaczkaAww** [comment]
okej, dzięki

**Comment by CDFN** [comment]
> w tym problem ze nie ma chyba nowszej wersji spigota 1.8.8, nawet /zaloz nie dziala

Bo 1.8.8 to legacy wersja i nie będzie otrzymywała już wsparcia od Mojangu. Zaktualizuj serwer do 1.16.x jeżeli chcesz używać feature, które korzystają ze wspomnianego eventu.

>jakie funkcje będą nie działac bez tego eventu?

Blokowanie kładzenia następujących rzeczy na terenie innych gildii: armor stands, boats, minecarts, and end crystals
