### ISSUE TITLE
Możliwość wyłączenia teleportacji na teren czyjejś gildii

### ISSUE THREAD

**Issue by EnzzoKrvl** [FunnyGuilds/FunnyGuilds#1512]
Witam, czy jest możliwość zablokowania /home gdy został on wcześniej ustawiony na terenie wrogiej gildii ?

**Comment by insertt** [comment]
Niestety nie bardzo jest taka możliwość, ale jest możliwość zablokowania komend na wrogich terenach gildii, więc można zablokować możliwość użycia komendy ustawiającej home.

**Comment by EnzzoKrvl** [comment]
No tak, tylko że to nie ma sensu niestety bo gdy ktoś jest w gildii i ustawi sobie /sethome 
To po opuszczeniu jej może nadal się tepać na /home

**Comment by barpec12** [comment]
Teoretycznie dałoby się to zrobić. Można by dodać opcję zablokowania możliwości jakiejkolwiek teleportacji na teren gildii osób, które nie są jej członkami. Wtedy też /tpa dla gości by nie działało.

**Comment by dzikoysk** [comment]
Można, ale to już bardziej propozycja na dodanie nowej funkcji, niż bug. Generalnie plugin tutaj działa poprawnie
