### ISSUE TITLE
Bug na kopiowanie

### ISSUE THREAD

**Issue by razor257** [FunnyGuilds/FunnyGuilds#1550]
FunnyGuilds v4.9.3 Tribute-a570825

Bug na kopiowanie

https://youtu.be/ffbChLXy60U

**Comment by Rollczi** [comment]
Podaj całą konfigurację FunnyGuilds. (usuń dane bazy jeśli używasz)
Oraz dokładną wersję silnika serwer (komenda /ver)

**Comment by razor257** [comment]
Myślałem, przez chwilę że to problem z skryptem blokującym stawianie beacona - bo próbowałem skopiować tylko to. Ale przed chwilą sprawdziłem; da się też inne bloki.

Config: https://pastebin.com/tSez7rah


![image](https://user-images.githubusercontent.com/45005010/119046704-4efb9480-b9bd-11eb-9d0d-7f69281b66b8.png)

![image](https://user-images.githubusercontent.com/45005010/119046840-74889e00-b9bd-11eb-8599-299039ba69bb.png)

**Comment by PinkLolicorn** [comment]
Czy mógłbyś przygotować minimalną wersję plików serwera (kopię) z taką konfiguracją FunnyGuilds gdzie występuje ten błąd? Jak najmniej wtyczek, puste pliki, tak abyś mógł to udostępnić tutaj.

**Comment by PinkLolicorn** [comment]
Nie będzie to jednak potrzebne. Używasz funkcji bugged-blocks, która jak sama nazwa wskazuje wprowadza "bugi". W tym przypadku prawdopodobnym skutkiem ubocznym jest kopiowanie. Twoja konfiguracja nie ma żadnych wykluczeń, co i tak sprowadza na ciebie masę innych problemów. 

Ta funkcja została wprowadzona jakiś czas temu na życzenie jakiegoś z użytkowników, była usprawniana, jednakże docelowo nie ma praktycznie możliwości wyeliminować wszystkich jej problemów.

Tak właściwie jej używanie najlepiej ograniczać do serwerów dla znajomych, szczególnie w takiej konfiguracji lub całkowicie jej nie używać. Zastanawiający jest też czas w postaci 1 ticka, który masz ustawiony, może być on dodatkowym źródłem problemów.
