### ISSUE TITLE
Bug na stawianie wagoników z tnt w dowolnym miejscu na cubie

### ISSUE THREAD

**Issue by razor257** [FunnyGuilds/FunnyGuilds#1551]
**FunnyGuilds v4.9.3 Tribute-a570825

Bug na stawianie wagoników z tnt w dowolnym miejscu na cubie, w tym również tuż obok jajka

https://youtu.be/Od5KDuhiWBg

**Comment by Rollczi** [comment]
Masz włączoną prawdopodobnie funkcję "zbugowanych klocków" przez co klocki zostają na 1 tick (50ms) i można faktycznie coś na nich położyć.
Wystarczy tylko zablokować tory w confingu w tym miejscu dodając je do listy:
![image](https://user-images.githubusercontent.com/49173834/119047851-bc5bf500-b9be-11eb-9e7b-e5e723b42252.png)
