### ISSUE TITLE
Niewidoczne serce gildii

### ISSUE THREAD

**Issue by Celeb69** [FunnyGuilds/FunnyGuilds#1552]
Po aktualizacji do najnowszej wersji pluginu mam taki problem, że serce gildii jest niewidoczne. Zarówno dla mnie jako dla administratora jak i dla nowych graczy. Sposób na rozwiązanie tego to ponowne wejście na serwer, lecz ciężko wmówić graczom, że jak są możliwie blisko serca to powinni się relognąć. Plus serce jest widoczne przy zakładaniu gildii i do czasu kiedy ktokolwiek przy nim jest, jak się je opuści na chwile to znika.

Serce jest klasyczne czyli kryształ endu

**Comment by P3ridot** [comment]
Naprawione czy do zamknięcia?

**Comment by Rollczi** [comment]
Mój PR był związany z tym tematem, ale nie naprawiał tego.
Chodziło o to że był puszczany task, i w środku niego był check. Został wyprowadzony przed taska co lepiej wygląda i też pewnie jest minimalnie wydajniejsze.
Więc do naprawienia ten issue.

**Comment by P3ridot** [comment]
Serce jest zakładam, że wysyłane pakietami taki?

**Comment by P3ridot** [comment]
Mógłby ktoś zreprodukować problem i dokładnie opisać co jest potrzebne do jego reprodukcji? Razem z wersją serwera, FunnyGuilds, listą pluginów itd. Mile widziany byłby filmik

**Comment by P3ridot** [comment]
To w końcu ten błąd występuje czy nie...

**Comment by Rollczi** [comment]
Tak i jest on od prawie zawsze

**Comment by Rollczi** [comment]
Bład występował na kmc jak się dedało w pobliżu serca to wtedy znikało, i trzeba było relognąć. (teleport nie działał)

Pewnie to nie jedyny bug z tym sercem.

**Comment by P3ridot** [comment]
Zostawie to turaj na później https://discord.com/channels/254623242914889729/278157499851341825/929101653326581800

**Comment by P3ridot** [comment]
Na najnowszym Nightly błąd nie powinien już występować
