### ISSUE TITLE
Możliwość zmiany skina główek na tabliście

### ISSUE THREAD

**Issue by Jakubk15** [FunnyGuilds/FunnyGuilds#1562]
Fajnie by było, gdyby można było zmienić główki na tabie na coś innego niż Stivy i Alexy.

**Comment by Rollczi** [comment]
FunnyGuilds wspiera placeholdery w [BungeeTabListPlus](https://www.spigotmc.org/resources/bungeetablistplus.313/), więc bez problemu można zrobić tablista z custom główkami oraz zmiennymi od FunnyGuilds.

Przykałdowa tablista z użyciem tego pluginu:
![image](https://user-images.githubusercontent.com/49173834/119728677-0b4cd300-be74-11eb-8344-969357c8fdf8.png)

**Comment by Jakubk15** [comment]
Można zamknąć issue.
