### ISSUE TITLE
Security system 

### ISSUE THREAD

**Issue by kowadl0** [FunnyGuilds/FunnyGuilds#1595]
Podsyłam ss

![Screenshot_20210720-042933_Log Viewer](https://user-images.githubusercontent.com/77697241/126253702-2062f654-9c46-43af-aef3-69f1f534eb1d.jpg)

**Comment by insertt** [comment]
Naprawione w najnowszym nightly.

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/commit/2f8772add2d7950201cf35a35d07ac8f821b358d
