### ISSUE TITLE
Brak nazwy gildii pod komendą /top

### ISSUE THREAD

**Issue by Qu3rr** [FunnyGuilds/FunnyGuilds#1600]
Cześć mam problem z wyświetlaniem nazwy/tagu gildii pod komendą /top wyświetla się tylko i wyłącznie ilość punktów ale bez nazwy oraz tagu
![Screenshot_5](https://user-images.githubusercontent.com/49995772/128387977-323160c2-6b2c-4a3e-883c-e55975182628.png)

**Comment by dzikoysk** [comment]
Pokaż jak masz ustawione `topList` w `messages.yml`

**Comment by Qu3rr** [comment]
> Pokaż jak masz ustawione `topList` w `messages.yml`

topList:
- '&8◄&8&l▬▬▬▬▬▬▬▬▬▬▬▬▬▬&8► &c&lTOP 10 &8◄&8&l▬▬▬▬▬▬▬▬▬▬▬▬▬▬&8►'
- '&8» &f1&8. &c{GTOP-1}'
- '&8» &f2&8. &c{GTOP-2}'
- '&8» &f3&8. &c{GTOP-3}'
- '&8» &f4&8. &c{GTOP-4}'
- '&8» &f5&8. &c{GTOP-5}'
- '&8» &f6&8. &c{GTOP-6}'
- '&8» &f7&8. &c{GTOP-7}'
- '&8» &f8&8. &c{GTOP-8}'
- '&8» &f9&8. &c{GTOP-9}'
- '&8» &f10&8. &c{GTOP-10}'
- '&8◄&8&l▬▬▬▬▬▬▬▬▬▬▬▬▬▬&8► &c&lTOP 10 &8◄&8&l▬▬▬▬▬▬▬▬▬▬▬▬▬▬&8►'

**Comment by dzikoysk** [comment]
Oki, to podrzuć jeszcze config w takim razie.

**Comment by Qu3rr** [comment]
> Oki, to podrzuć jeszcze config w takim razie.

https://code.skript.pl/HweTOve6

**Comment by dzikoysk** [comment]
Pousuwałeś tagi gildii z formatowania tagów:

```
# Wyglad tagu osob w gildii
prefix-our: '&a'
# Wyglad tagu gildii sojuszniczej
prefix-allies: '&e'
# Wyglad tagu wrogiej gildii
prefix-enemies: ''
# Wyglad tagu gildii neutralnej. Widziany rowniez przez graczy bez gildii
prefix-other: ''
```

W każdym powinno być `{TAG}` po kolorkach.
