### ISSUE TITLE
Problem z uruchomieniem przy zmianie guild-tnt-protection-end-time

### ISSUE THREAD

**Issue by Anyboody** [FunnyGuilds/FunnyGuilds#1602]
Przesyłam config oraz logi

[config.yml.txt](https://github.com/FunnyGuilds/FunnyGuilds/files/6955397/config.yml.txt)
[2021-08-09-51.log](https://github.com/FunnyGuilds/FunnyGuilds/files/6955398/2021-08-09-51.log)

Problem następuje, gdy wartość przekracza godzinę 09:00, to jest przy 09:59 włącza się wszystko poprawnie, lecz przy godzinie 10:00 i wyżej jest następujący problem

**Comment by Rollczi** [comment]
Włóż 16:00 w '
`'16:00'`
Powinno działać poprawnie.
