### ISSUE TITLE
Kompatybilność z CombatLogX

### ISSUE THREAD

**Issue by MoloBoso** [FunnyGuilds/FunnyGuilds#1607]
Witam!
Przychodzę z pomysłem aby dodać kompatybilność z CombatLogiem. Polegałaby ona na dodaniu w config.yml opcji sprawdzania w jaki sposób został zabity gracz.

Po co?
Plugin CombatLogX oferuje antylogout + blokadę wejścia na spawn , lecz przy wylogowaniu się podczas pvp (z pluginem FunnyGuilds) gracz , który się wylogował nie jest zabijany oraz ranking nie zostaje odjęty. Opcja przydała by się bardzo gdyż większość serwerów używa owego pluginu na AntyLogout , a zawsze dodanie takiej opcji podniosło by reputację FunnyGuilds'a + większość osób nie musiałoby pobierać "autorskich pluginów na antylogout" , które są wirusami lub backdoorami.

Pozdrawiam i myślę żę opcja ta zostanie dodana :)

**Comment by dzikoysk** [comment]
Generalnie FunnyGuilds powinno działać z pluginem CombatLogX:

* https://github.com/FunnyGuilds/FunnyGuilds/issues/1051

Być może to zależy od konfiguracji tego w jaki sposób CombatLogX zabija graczy? 🤔 Pewnie @Rollczi wie coś więcej na ten temat.

**Comment by MoloBoso** [comment]
Dzięki i zobaczę jeszcze raz config pluginu CombatLogX :)

**Comment by Rollczi** [comment]
Wystarczy ustawić CombatLogX tak, aby zabijał gracza po wylogowaniu się. Ja osobiście używałem tego pluginu i wszystko działało z FunnyGuilds.
