### ISSUE TITLE
Dodanie scoreboard

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1614]
Dodanie do funnyguilds scoreboard który będzie pokazywał różne ciekawe informacje połączone z Gildiami

**Comment by Kamilkime** [comment]
A nie lepiej użyć jakiegoś pluginu od tego (np. FeatherBoard lub AnimatedScoreboard) i po prostu użyć na nim placeholderów, które FG dodaje do PlaceholderAPI?

**Comment by P3ridot** [comment]
> A nie lepiej użyć jakiegoś pluginu od tego (np. FeatherBoard lub AnimatedScoreboard) i po prostu użyć na nim placeholderów, które FG dodaje do PlaceholderAPI?

Gościu ale z FG trzeba zrobić plugin od wszystkiego???

**Comment by CodeKid0** [comment]
> > A nie lepiej użyć jakiegoś pluginu od tego (np. FeatherBoard lub AnimatedScoreboard) i po prostu użyć na nim placeholderów, które FG dodaje do PlaceholderAPI?
> 
> Gościu ale z FG trzeba zrobić plugin od wszystkiego???

Nie.

**Comment by P3ridot** [comment]
Jest tyle świetnych pluginów na Scoreboardy. FunnyGuilds wystawia tyle placeholderów przez PAPI i zawsze można dodać kolejne.
