### ISSUE TITLE
Dodanie Pandy jako języka skryptowego

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#1615]
:)

**Comment by bopke** [comment]
yes we need this immediately pls implement nao

**Comment by dzikoysk** [comment]
lol can't wait

**Comment by bopke** [comment]
lmao :grin:

**Comment by Rollczi** [comment]
Czekam heh

**Comment by P3ridot** [comment]
When

**Comment by bopke** [comment]
when 🐒

**Comment by dzikoysk** [comment]
soon tm

**Comment by nwseUwU** [comment]
![image](https://user-images.githubusercontent.com/93941726/183134266-f3770e1a-00c9-4cba-8d51-01f8adbc3dd0.png)

**Comment by PinkLolicorn** [comment]
Typowe skrypty nie mają sensu jako integralna część gildii, szczególnie biorąc pod uwagę, ile osób jest w stanie z tego skorzystać. Pomijając już nawet kwestie tego, że bez dobrego API tym bardziej nie ma to sensu — takie rzeczy to robota dla zewnętrznej wtyczki jak np. https://github.com/OkaeriPoland/okaeri-poly

**Comment by dzikoysk** [comment]
https://user-images.githubusercontent.com/4235722/183215665-2162b760-0f95-4af2-8d4b-3a83e1a884d4.mp4

**Comment by P3ridot** [comment]
tbh do we really need that?

**Comment by CDFN** [comment]
Ma arvan, et seda pole vaja

**Comment by P3ridot** [comment]
Sorry, maybe in future but currently we have more important things to do 😔🙏
