### ISSUE TITLE
Funny Guilds nie reaguje na logout (CombatLogX)

### ISSUE THREAD

**Issue by MoloBoso** [FunnyGuilds/FunnyGuilds#1628]
Witam!

Przychodzę (znów) z błędem , gdyż przy wylogowaniu jak jestem w antylogout to nic się nie dzieje. Prosiłbym o jak najszybszą pomoc!

Error: 
![image](https://user-images.githubusercontent.com/87397688/134785974-c2e58cc5-5173-40d2-81d6-57dbfb40a0f3.png)

Wersje:
Funny Guilds 4.9.7
CombatLogX (Najnowsza jak na chwile dodania błędu)

**Comment by insertt** [comment]
Z podanego erroru nie wynika, żeby to był problem FunnyGuilds, a sam error nie jest kompletny - wrzuć pełną wersje.

**Comment by MoloBoso** [comment]
Problem naprawiony , wystarczyło zaaktualizować CombatLogX + w funnyguilds ustawić by nabijanie rankingu było na te same IP
