### ISSUE TITLE
Skarbiec gildyjny - z systemem składek

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1669]
Dodanie Skarbca Gildi gdzie Administracja Gildi bedzie mogla ustawiac Składki Gildyjne  np 64 obsa i kazdy ma na to np 24h zeby wplacic + dodanie opcji takiej zbey administracja mogla zobaczyc kto wplacil a kto nie wplacil w tym menu.

~~Stworzenie GUI w ktorym beda najwazniejsze rzeczy gildyjne (menu gidli) typu (permisje gildi czlonków) gdzie beda pokazane głowni czlonków gildi i np Owner moze awansowac kogos na moda gildi czy adma + owner moze edytowac kazdego gracza i nadac mu poszczegolna permisje np jakis gracz dostal permisje kikania graczy z gildi (chodzi o to ze po nadaniu rangi np ModGildi mozna nadac mu poszczegolne permisje).~~

**Comment by PinkLolicorn** [comment]
Mam wrażenie, że to nie pierwszy i nie ostatni issue dotyczący podobnych rzeczy. Temat jest ciężki jak i samo implementowanie GUI to dużo zabawy, nowe wiadomości i wiele więcej problemów. Generalnie jak ci zależy, to możesz zawsze komuś zapłacić, żeby zrobił PR do FunnyGuilds (tak, w ten sposób się da) i jeśli ten ktoś zrobi kod dobrej jakości, to będziesz miał feature włączony do wtyczki i utrzymywany już dalej przez inne osoby. Tylko musisz brać pod uwagę, że to nadal nie daje ci gwarancji konkretnych rzeczy i jest tylko po twojej stronie. Niemniej — znacznie lepsze niż własna wtyczka, jeśli nie możesz jej sam utrzymywać, np. aktualizować przy zmianach w FunnyGuilds.

**Comment by dzikoysk** [comment]
Plus też fakt, że FG nieprzyjemnie znosi zmiany i dopiero ostatnio pojawiają się możliwości implementacji nowych rzeczy bez powiększania istniejących problemów - stąd wiele nierozwiązanych od miesięcy/lat issues i przez długi czas brak rąk chętnych do pracy. Pierwotnie zajmujące się pluginem osoby po prostu obecnie zajmują się już innymi rzeczami, stąd dosyć powolne tempo zmian.

**Comment by grabeq123** [comment]
Okej ale czemu nie mozna stowrzyc tegiego gui (menu) czy tez skarbca to nie jest jakas funkcja że tak powiem zbędna. Skarbieć ma poprostu uproscić Ownerowi sprawdzanie kto wplaca cos a kto nie wplaca i dzieki temu sama Gildia dalej może sie utrzymać. Tak samo z permisjami ma to na celu ownerowi pomoc w administracji gildyjnej ktora dostanie pozniej jakies konkretne polecenia od ownera co musza wykonywac czy jaka funckje pelnia w danej Gildi?

**Comment by grabeq123** [comment]
To znaczy ze nie ma szans aby takie cos powstało z waszej strony w FunnyGuilds?

**Comment by P3ridot** [comment]
Nie, nie stwierdzilśmy tego - jest szansa że te feature'y zostaną dodane do FG ale nie wiadomo dokładnie kiedy.

**Comment by dzikoysk** [comment]
> 
> 
> Okej ale czemu nie mozna stowrzyc tegiego gui (menu) czy tez skarbca to nie jest jakas funkcja że tak powiem zbędna. Skarbieć ma poprostu uproscić Ownerowi sprawdzanie kto wplaca cos a kto nie wplaca i dzieki temu sama Gildia dalej może sie utrzymać. Tak samo z permisjami ma to na celu ownerowi pomoc w administracji gildyjnej ktora dostanie pozniej jakies konkretne polecenia od ownera co musza wykonywac czy jaka funckje pelnia w danej Gildi?

Takie rzeczy łatwo opisać jako feature request, ale z poziomu kodu to jest sporo rzeczy do dodania w bardzo wielu miejscach. Kod FG generalnie był i mimo paru zmian dalej jest stosunkowo złej jakości, co znacząco utrudnia dodawanie jeszcze takich rzeczy.

> 
> 
> To znaczy ze nie ma szans aby takie cos powstało z waszej strony w FunnyGuilds?

Jest szansa, tylko prawdopodobnie zajmie to jeszcze trochę czasu. Obecnie @Rollczi i @P3ridot skupiają się na przepisywaniu wielu różnych rzeczy pod naszym okiem na Discordzie, aby umożliwić wprowadzanie właśnie takich zmian w przyszłości.

**Comment by P3ridot** [comment]
Żeby cie pocieszyć jesteśmy coraz bliżej przepisania głównej części pluginu co pozwoli na łatwoejsze dodawanie nowych ficzerów

**Comment by grabeq123** [comment]
No to dobra wiadomość oby tak dalej @P3ridot i @Rollczi  :D

**Comment by P3ridot** [comment]
Ogólnie co do panelu to #1100 więc zostawiam skarbiec (na niego propozycja była ale w innej formie)
