### ISSUE TITLE
Prośba o dodanie placeholdera pozwalającego na ustawienie taga gildii

### ISSUE THREAD

**Issue by homerek111** [FunnyGuilds/FunnyGuilds#1698]
Prośba o dodanie placeholdera pozwalającego na ustawienie taga gildii, który zmienia kolory w zależności od relacji gildyjnych (tak jak dzieje się to ze zwykłymi tagami gildyjnymi bez używania placeholderów) Umożliwiłoby to korzystanie z innego pluginu odpowiedzialnego za tagi, z zachowaniem kolorów relacji gildyjnych. Obecnie placeholder %funnyguilds_g-tag% nie zmienia koloru.

**Comment by P3ridot** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#relational-placeholders

Ja to tu tylko zostawię 😳
