### ISSUE TITLE
Error PlaceholdersAPI hook

### ISSUE THREAD

**Issue by Rollczi** [FunnyGuilds/FunnyGuilds#1700]
![funnyguilds.png](https://user-images.githubusercontent.com/49173834/140612765-b1fab382-a0ee-41df-bbe2-bb80d2382067.png)

**Comment by P3ridot** [comment]
Czy błąd da się zreprodukować na najnkwszym Nightly i PlaceholderAPI (2.11.0)? Oraz co jest wymagane, żeby dało sie go zreprodukować?
