### ISSUE TITLE
Chat - Kanały gildyjne

### ISSUE THREAD

**Issue by Aides123** [FunnyGuilds/FunnyGuilds#1715]
Hej!
Mam problem z ustawieniem kanałów gildyjnych. Do testów użyłem - CMI oraz EssentialsX/EssentialsxChat.
Przy obydwóch pluginach ten sam efekt - 2x !wiadomość.
Co należy zrobić żeby tego się pozbyć?

![image](https://user-images.githubusercontent.com/23367220/143714909-d800e471-b8a2-4677-b1c7-41fb3485b25a.png

**Comment by Kamilkime** [comment]
Musisz coś więcej o tym napisać - bo po screenie i tym krótkim opisie nie bardzo wiadomo o co biega

**Comment by Aides123** [comment]
> Musisz coś więcej o tym napisać - bo po screenie i tym krótkim opisie nie bardzo wiadomo o co biega

Wiadomość pierwsza powinna być blokowana na chacie publicznym czyli to "!treść", a zamiast niej powinna pojawiać się tylko wiadomość na kanale gildyjnym. 

Pytanie brzmi, co robię zle że nie blokuje tej pierwszej wiadomości na publicznym?

**Comment by Aides123** [comment]
Podesłać konfiguracje czegoś?
Jeśli chodzi o serwer to:
Wersja Airplane #13
Najnowsza wersja FG
a tu pluginy 
![image](https://user-images.githubusercontent.com/23367220/143719666-f6fa5cd6-d1c8-4590-b876-206226ae1c4f.png)

**Comment by Rollczi** [comment]
normalnie jest anulowany event
też nie widać zbytnio zmian w ostatnim czasie
https://github.com/FunnyGuilds/FunnyGuilds/blob/master/plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerChat.java#L106

coś musi ponownie wywoływać event albo obsługiwać go w dodatkowy sposób

włącz samo funnyguilds bez pluginów, i zobacz czy wiadomości nadal się duplikują

**Comment by Aides123** [comment]
Okej problem zlokalizowany w CMI.
Konkretnie chodzi o opcje "  ClickHoverMessages: true" <- Nie wiem jaki to miało związek ale po wyłączeniu jej jest git.

Do zamknięcia :3
