### ISSUE TITLE
Opcja Bugged blocks

### ISSUE THREAD

**Issue by Aides123** [FunnyGuilds/FunnyGuilds#1716]
Hej!
Korzystam z opcji bugged blocks.
Kilku graczy odkryło sposób na kopiowanie przedmiotów, a samo odtworzenie tego jest proste.
Gracz X stawia bloki, a gracz Y szybko je skopuje. 
Praktycznie za każdym razem uda się skopiować bloki/shulkery.
Dokładniej błąd tyczy tego "bugged-blocks-return: true" <Jeśli opcja jest na false to już nie da się skopiować bo wykopany blok wypada na ziemie, a do gracza nie wraca blok.
Dałoby rade dodać blokade na kopanie postawionych bloków?

Moja konfiguracja:
https://pastebin.com/AFSTE89z

**Comment by Rollczi** [comment]
Wiemy o tym że bloki się kopiują
Duplicate #1550
