### ISSUE TITLE
Ochrona TNT - Nowa opcja.

### ISSUE THREAD

**Issue by Aides123** [FunnyGuilds/FunnyGuilds#1722]
Hej!
Proponuje rozwinąć ochronę przed TNT o jedną funkcje.
Jeśli gildia posiada tarczę ochroną (Początkowa tarcza dla nowych gildii) to automatycznie nie mogą wysadzać bloków na terenie innej gildii. Dopiero po upływie tarczy mogą wysadzać bloki innej gildii.

Nawiązanie do opcji:
Czy gildia podczas okresu ochronnego ma posiadac ochrone przeciw TNT
war-tnt-protection: true

**Comment by Rollczi** [comment]
Nie da się sprawdzić w optymalny sposób, kto odpalił tnt.
Ta funkcja nie jest możliwa do zrealizowania w praktyce.

**Comment by P3ridot** [comment]
By trzeba trackować każdego kto postawił tnt, odpalił - za obliczeń aby zrobić to sensownie. Może wystarczy po prostu zablokować kładzenie tnt przez ludzi z ochroną + odpalanie ogólnie tnt i taki feature moglby jeszcze realnie zostać dodany

**Comment by P3ridot** [comment]
Za dużo roboty, można ogarnąć w zewnętrznym pluginie
