### ISSUE TITLE
Stopień gracza w name tagu

### ISSUE THREAD

**Issue by jarek123442** [FunnyGuilds/FunnyGuilds#1726]
Witam, przychodzę z propozycją dodania stopnia gracza w gildii na name tagu, tak jak to jest zrealizowane na chacie
np. lider ma przy tagu gildii na nad głową dwie gwiazdki, a zastępca 1.

**Comment by DevangerTM** [comment]
###  Dodatkowo gdy przydzielimy Lidera, vLidera lub Mistrza to przy ich nickach wyświetli się jakiś symbol, który wybierzemy w configu. 
 

> ![Opera Zrzut ekranu_2022-07-08_042427_www facebook com](https://user-images.githubusercontent.com/41342020/177904348-8b6782b0-4071-4706-bacd-8e6044043e6d.png)
> ![Opera Zrzut ekranu_2022-07-08_042444_www facebook com](https://user-images.githubusercontent.com/41342020/177904351-39887b7d-90d5-4657-9473-9ac066cc4ebc.png)

**Comment by P3ridot** [comment]
Z nowym systemem wystarczy dodać taki placeholder w kodzie, na razie można to zrobić przez PlaceholderAPI z użyciem placeholdera `%funnyguilds_guild-position%`
