### ISSUE TITLE
Aktualizacja pluginu do 1.18.1

### ISSUE THREAD

**Issue by Blox61** [FunnyGuilds/FunnyGuilds#1750]
Witam. Jak wygląda wasze stanowisko jeżeli chodzi o aktualizację pluginu do wpierania nowszych wersji serwera? Planowane czy temat definitywnie zamknięty?

**Comment by dzikoysk** [comment]
Wersja z nightly posiada ekseprymentalne wsparcie 1.18: 

* https://ci.insertt.dev/job/FunnyGuilds/job/master/

Parę osób testowało i jest podobno git.
