### ISSUE TITLE
Błąd w konsoli

### ISSUE THREAD

**Issue by Blox61** [FunnyGuilds/FunnyGuilds#1758]
Witam. Napotkałem problem z pluginem. Podczas ładowania pluginu pojawił się następujący błąd: 
`[00:28:51] [Server thread/WARN]: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`

Wersja pluginu: FunnyGuilds v4.9.7 Tribute-1730267
Wersja serwera i silnik: paper-1.8.8-444

Więcej logów:
https://pastebin.com/GxznHEJt

**Comment by dzikoysk** [comment]
Użyj wersji 4.10.0 z nightly, bo 4.9.7 jest już przestarzałe :)
