### ISSUE TITLE
Dodanie ochroniarza

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1772]
Przychodze z dosyć ciekawą propozycja dodania ochroniarza czyli jakiegos moba (do ustawienia w configu ) np: Iron Golema ktory bedzie mial nad glowa Pasek hp i z boku  ilehp zostalo/maxhp. Gdy jakis gracz ktory nie jest w gildi (wrog lub jakis przypadkowy gracz ktory zostal wlasnie wyrzucony z gildi sprobuje zatakowac (uderzyc) serce gildi wywola wtedy ochroniarza). Ochroniarz nagle sie pojawi i zacznie bic nieznanych graczy ktorzy nie naleza do danej gildi. Oczywiscie ochroniarza bedzie mozna zabic ale bedzie to dosyc trudne.Po skonczonej bitwie gdy ochroniarz wygra  bedzie czekal az jego caly pasek hp sie zregeneruje i wtedy bedzie mogl znow wejsc do serca gildi. Opcja lvl ochroniarza za np jakies itemy tez bylaby fajna np 10 diaxow to 1 lvl, 30 diaxow i 20 zlota to 2 zl ....  i to bedzie dawac mu wiecej np zycia + zadawanych obrazen. Innymi slowy dopoki ktos nie zabije ochroniarza nie bedzie mogl skrzywdzic serca gildi.

**Comment by kacorvixon1337** [comment]
to nie dragon

**Comment by grabeq123** [comment]
I co z tego ze to nie jest dragon ? Mozna cos takiego dodac przecież

**Comment by Rollczi** [comment]
Dodatkowo wsparcie pandy która będzie bronić serca FunnyGuilds ❤️

**Comment by dzikoysk** [comment]
> 

Ale op pomysł

**Comment by Verdun1337** [comment]
https://i.imgur.com/XGB4wHe.png :") napisz sobie sam

**Comment by Inder00** [comment]
Me and the bois are actually working on that. Stay patient

**Comment by oskarPLL** [comment]
> https://i.imgur.com/XGB4wHe.png dopisane pod funnyguilds

No toxicity please

**Comment by P3ridot** [comment]
> > Dodatkowo wsparcie pandy która będzie bronić serca FunnyGuilds ❤️
> 
> Ale op pomysł

Totalnie op



> Panda tez może być ważne żeby kiedyś powstało takie coś

Yes

**Comment by DevangerTM** [comment]
- ### **Ochroniarz gildii** - Jest to golem, którego można ulepszać za bloki złota. Wtedy jego wytrzymałość jest większa. Golem pojawia się wtedy, gdy przeciwnik zaatakuje serce. Golem z czasem wygasa i trzeba go odnowić za golda. Gdy nie odnowimy ważności jego to gdy ktoś zaatakuje serce to nie pojawi się. 
-  #1772 

> ![Opera Zrzut ekranu_2022-07-08_031434_www youtube com](https://user-images.githubusercontent.com/41342020/177903058-0af7b0c6-f4d7-4b5a-8f7e-c3cd6f408eed.png)
> ![Opera Zrzut ekranu_2022-07-08_031857_www youtube com](https://user-images.githubusercontent.com/41342020/177903049-40c147a1-fe31-45bd-b3dc-940655590db5.png)
> ![Opera Zrzut ekranu_2022-07-08_031849_www youtube com](https://user-images.githubusercontent.com/41342020/177903051-0dcc3c2e-6117-4ddd-bab3-b8bf037342d2.png)
> ![Opera Zrzut ekranu_2022-07-08_031830_www youtube com](https://user-images.githubusercontent.com/41342020/177903052-c30eda31-d0bd-4c9d-86e7-b011c388cf93.png)
> ![Opera Zrzut ekranu_2022-07-08_031512_www youtube com](https://user-images.githubusercontent.com/41342020/177903053-8264edbc-ffc4-4872-9bae-5e77be52d446.png)
> ![Opera Zrzut ekranu_2022-07-08_031455_www youtube com](https://user-images.githubusercontent.com/41342020/177903055-d6b28d81-108e-494d-b38e-b61e2538d7ef.png)
