### ISSUE TITLE
Zmiana w hologramie na sercem gildi

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1773]
Zmiana polega na tym ze np zamiast liczb 3 Zycia  pokazywalo poprostu serduszka (emotke serduszek)

**Comment by grabeq123** [comment]
Proponuje jednak powiekszenie tych serduszek bo z daleka jak sredniej wielkosci kropki a nie jak serc
![Zrzut ekranu 2022-01-06 104932](https://user-images.githubusercontent.com/77630265/148363873-93d8339f-96f3-4f06-9845-7f7a821e77e6.png)
e

**Comment by grabeq123** [comment]
zeby np wygladaly tak jak na ss wyslanym wyzej

**Comment by P3ridot** [comment]
To sobie zmien w configu w lives-repeating-symbol

**Comment by grabeq123** [comment]
Nie wiedziałem że się da. Dzięki za pomoc

**Comment by grabeq123** [comment]
W takim razie proponuje zrobienia pustych serduszek  tak jak jest to pokazane na ss wyżej  aby były pełne serdruszka (ile gildia ma życia) i puste serduszka ile straciła.

**Comment by P3ridot** [comment]
To stwórz kolejne Issue
