### ISSUE TITLE
/g napraw

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1778]
Przychodze z ciekawym pomyslem jakim jest /g napraw polegajacym na tym ze jezeli twoja gildia zostala zrejdowana ( napadnieta,rozwalona) Owner czy jego zastepca moga uzyc komendy /g napraw ktora bedziesz kosztowala jakaś dokladna ilosc itemow np: 64 diamentow i 32 koxy. Wtedy Gildia zaczyna sie naprawiac klocek po klocku do momentu przed rozwaleniem.

**Comment by kacorvixon1337** [comment]
czyli inaczej g regeneruj

**Comment by grabeq123** [comment]
może być

**Comment by P3ridot** [comment]
Duplicate #1208
