### ISSUE TITLE
Propozycja do Symbolu Serduszek

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1781]
proponuje zrobienia pustych serduszek tak jak jest to pokazane na ss niżej aby były pełne serduszka (ile gildia ma życia) i puste serduszka ile straciła.
![Zrzut ekranu 2022-01-06 104932](https://user-images.githubusercontent.com/77630265/148365654-8611868d-4f03-4574-8215-0dc735e4f1de.png)

**Comment by P3ridot** [comment]
Teraz LIVES-SYMBOL wyświetla puste serduszka kiedy brakuje życia. Dodatkowo żeby placeholder działał jak wcześniej wyświetlając wszystkie dostępne serduszka można użyć placeholder LIVES-SYMBOL-ALL
