### ISSUE TITLE
Opcja urozmaicenia serca gildii

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1783]
TODO:
- [ ] Głowa gracza (właściciela?) jako serce
  - [ ] Jako item na hologramie
  - [ ] Jako część serca (blok)
- [ ] Dodatkowe efekty wizualne na około serca (particlesy etc.)

**Comment by grabeq123** [comment]
Doprecyzuje tą sugestie gdy sercem gildi bedzie jakis niestandardowy item ta glowa to zeby byla opcja do ustawienia (czy ten przedmiot na lewitowac czy poprostu stac na ziemi) gdy true to kolejna funkcja dochodzi . Jezeli true: Czy przedmiot ma sie krecic true false)

Niezaleznie jaki przedmiot bedzie sercem gildi do ustawienia true/false  (Czy przedmiot ma miec nalozony efekty ) No i jezeli tak no to jaki efekt to ma byc. Tutaj chodzi mi o takie efekty jak np plujaca lawa z serca , jakieś gwiazdki czy cos w tym stylu

**Comment by dzikoysk** [comment]
Zmiany czysto estetyczne, a wymagające trochę pracy, więc z uwagi na zupełnie inne wymagania stojące przed pluginem w przyszłości na razie to zamykam. W przypadku większego zainteresowania zawsze można do tego wrócić.
