### ISSUE TITLE
Wsparcie dla PlaceholderAPI w czatach gildyjnych

### ISSUE THREAD

**Issue by Zaaxel** [FunnyGuilds/FunnyGuilds#1812]
# Prefix w czatach gildyjnych

Witam, mam propozycję dodania wsparcia dla znacznika {PREFIX} od pluginów z uprawnieniami typu LuckPerms

Na chwilę obecną można używać 4 zmiennych: {PLAYER}, {TAG}, {MESSAGE} oraz {POS}

**Comment by P3ridot** [comment]
Myślę, że najłatwiej byłoby to rozwiązać dodaniem wsparcia dla PlaceholderAPI w czatach gildyjnych

**Comment by P3ridot** [comment]
W najnowszym Nightly wystarczy użyć odpowiedniego placeholderu z PlaceholderAPI/MVdWPlaceholderAPI aby wyświetlać prefix z LuckPerms (lub dowolnego innego) i powinno wszystko śmigens
