### ISSUE TITLE
Rewrite inventories system

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#1815]
Useful with #895 #963 #1100 #1349 #1670

**Comment by P3ridot** [comment]
After #2091 we can use this library https://github.com/stefvanschie/IF

**Comment by PinkLolicorn** [comment]
Hello, please support Polish developers, thanks.

https://github.com/OkaeriPoland/okaeri-menu

**Comment by P3ridot** [comment]
> Hello, please support Polish developers, thanks.
> 
> https://github.com/OkaeriPoland/okaeri-menu

Does your library force newer versions like 1.14+?

**Comment by P3ridot** [comment]
Użyjemy IF chyba że ktokolwiek ma lepsze alternatywy :trollface:

**Comment by dzikoysk** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/issues/2226
