### ISSUE TITLE
Możliwość ustawienia pustych wiadomości w messages.yml

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#1826]
Puste wiadomości nie będą wysyłane do gracza, dzięki czemu powiadomienia mogą być opcjonalne

**Comment by dzikoysk** [comment]
@P3ridot 😳👉👈

**Comment by Rollczi** [comment]
może dodatkowo MiniMessage Adventure?

**Comment by P3ridot** [comment]
Częściowo #1836 pozwolił już na to
