### ISSUE TITLE
Komenda /info nie działa poprawnie

### ISSUE THREAD

**Issue by opera2398** [FunnyGuilds/FunnyGuilds#1833]
siema kilka prostych bledow do naprawy:
- istnieje gildia TEST, gdy gracz wpisze /info test - gildia nie istnieje, trzeba wpisac /info TEST
- pod /info, gdy jakis gracz jest online to reszta osob za nim tez jest na zielono, po prostu nie resetujecie kolorku po osobie online

**Comment by Kamilkime** [comment]
A z jakiej dokładnie wersji FG korzystasz?

**Comment by P3ridot** [comment]
To pierwsze najprawdopodobniej występuje na najnowszym Nightly po spojrzeniu w kod. To drugie jest też prawdopodobne

**Comment by opera2398** [comment]
a i taka prosba, wezcie pod /version nazywajcie te buildy normalnie, np. FG build 200 a nie FG 67bb721

**Comment by Kamilkime** [comment]
> a i taka prosba, wezcie pod /version nazywajcie te buildy normalnie, np. FG build 200 a nie FG [67bb721](https://github.com/FunnyGuilds/FunnyGuilds/commit/67bb7215d8036d2369400869d89c0b078d95a969)

Nie, one się mają tak nazywać - użytkownikowi to tak naprawdę nie robi różnicy, a my od razu wiemy z którego momentu jest dany plugin, ten ciąg znaków to hash commita po którym zbudowano jara

**Comment by opera2398** [comment]
nie mow ze nie robi to uzytkownikowi roznicy, bo robi ogromna - za kazdym razem jak chce zaaktualizowac FG to zastanawiam sie czy mam najnowsza wersje czy moze sprzed miesiaca

ale spoko, skoro dla was to duze ulatwienie to niech zostanie tak jak jest

**Comment by dzikoysk** [comment]
Jeżeli Twój identyfikator jest inny od tego z CI, to zawsze wskazuje na to, że masz nieaktualną wersję.

**Comment by P3ridot** [comment]
W najnowszym Nightly powinno już wszystko poprawnie działać

**Comment by opera2398** [comment]
co do tego bledu z /info - tak, poprawione ale dokladnie ten sam problem jest z komenda /sojusz oraz zapewne /dolacz
