### ISSUE TITLE
Baza gildii nie jest zapisywana

### ISSUE THREAD

**Issue by opera2398** [FunnyGuilds/FunnyGuilds#1835]
ustawiajac nowy spawn komenda /ustawbaze i tak jestesmy tepani do serca, po prostu lokalizacja z jakiegos powodu sie nie zapisuje
wersja fg 67bb721

**Comment by P3ridot** [comment]
Na c7e0942 nie mogę zreprodukować tego błędu, spróbuj zaktualizować FunnyGuilds i sprawdź jeszcze raz

**Comment by P3ridot** [comment]
@opera2398

**Comment by opera2398** [comment]
po restarcie serwera nastepuje ten reset bazy, przy okazji jesli mozesz - to zerknij na chat gildyjny, wiadomosci nie wysylaja sie

**Comment by P3ridot** [comment]
Chat gildyjny został już naprawionyi, przynajmniej na najnowszym Nightly działa
