### ISSUE TITLE
Improve messages system (with magic of adventure)

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#1837]
TODO:
- [ ] Use [Adventure](https://github.com/KyoriPowered/adventure) and [MiniMessage](https://docs.adventure.kyori.net/minimessage/index.html)
- [ ] #1209 
- [ ] Support for #926

**Comment by dzikoysk** [comment]
~ https://github.com/FunnyGuilds/FunnyGuilds/pull/1599

**Comment by P3ridot** [comment]
Stworzyłem super fancy biblioteke do tego - [YAML](https://github.com/P3ridot/YetAnotherMessagesLibrary). która rozwiąże 2/3 tego issue out of pudełko. Dodatkowo będzie kompatybilna z aktualnym formatem pliku z wiadomościami. Where wady???

**Comment by dzikoysk** [comment]
Wirus

**Comment by dzikoysk** [comment]
Tylko wirus by tak powiedział

**Comment by P3ridot** [comment]
Real
