### ISSUE TITLE
PowerRanks doesn't work with FunnyGuilds permissions

### ISSUE THREAD

**Issue by Nikodem840** [FunnyGuilds/FunnyGuilds#1867]
Nooo mam PowerRanks i nawet jak dam permisje do pluginu to nie można go użyć
bez operatora jest tylko "You don't have permissions" a jak dam permisje to też nic. co mam zrobić?

**Comment by Kamilkime** [comment]
A jakie uprawnienie dodajesz? I co próbujesz wykonać, jaką komendę?
Raczej to problem z twoją konfiguracją PowerRanks lub dodajesz złe uprawnienie

**Comment by P3ridot** [comment]
Z tego co widziałem w zakładce reviews na spigotmc to sam PowerRanks może powodować problemy - z innymi pluginami tez tak ma (np. Essentials) różne osoby również mają problem. Stawiałbym więc na wymiane samego pluginu od systemu uprawnień na np. LuckPerms lub zgłoszenue błędu autorowi PowerRanks.
