### ISSUE TITLE
Podwójny minus

### ISSUE THREAD

**Issue by Keendi** [FunnyGuilds/FunnyGuilds#1878]
Naprawcie podwójny minus w wiadomości jak się kogoś zabija bo dalej to nie jest naprawione

**Comment by Kamilkime** [comment]
Najlepiej podeślij nam swój config i ustawienia wiadomości - może po prostu coś jest źle poustawiane

**Comment by Keendi** [comment]
rankDeathMessage: '{ATAG}&b{ATTACKER} &7(&a+{+}&7) zabil {VTAG}&b{VICTIM} &7(&c-{-}&7) uzywajac &b{WEAPON} {WEAPON-NAME}'

Domyślny config.

**Comment by Kamilkime** [comment]
Wygląda że masz po prostu niezmienioną wiadomość - nadal jest taka jak była przed poprawkami. Teraz najlepiej używać nowych zmiennych `{MINUS-FORMATTED}` i `{PLUS-FORMATTED}` - ich dokładniejsza konfiguracja jest w configu, w sekcji `kill-points-change-format`

**Comment by Keendi** [comment]
No to się zgadza w takim razie zamykam
