### ISSUE TITLE
Nie dzialja zmienne na BungeeTaba na wersji 4.10.0 a na wersji 4.9.7 dzialaja

### ISSUE THREAD

**Issue by nifeno** [FunnyGuilds/FunnyGuilds#1897]
[15:23:19 INFO]: [FunnyGuilds] Enabling Guilds v4.10.0 Snowdrop-2277e1b
[15:23:19 INFO]: [FunnyGuilds] Loaded users: 19
[15:23:19 INFO]: [FunnyGuilds] Loaded regions: 1
[15:23:19 INFO]: [FunnyGuilds] Loaded guilds: 1
[15:23:19 WARN]: [FunnyGuilds] Cannot register EntityPlaceEvent listener on this version of server
[15:23:19 INFO]: [FunnyGuilds] Vault plugin could not be found, some features may not be available
[15:23:19 INFO]: [FunnyGuilds] MVdWPlaceholderAPI plugin could not be found, some features may not be available
[15:23:19 INFO]: [FunnyGuilds] PlaceholderAPI plugin could not be found, some features may not be available
[15:23:19 INFO]: [FunnyGuilds] LeaderHeads plugin could not be found, some features may not be available
[15:23:19 INFO]: [FunnyGuilds] WorldEdit plugin hook has been initialized!
[15:23:19 INFO]: [FunnyGuilds] HolographicDisplays plugin hook has been initialized!
[15:23:19 INFO]: [FunnyGuilds] BungeeTabListPlus plugin hook has been initialized!
[15:23:19 INFO]: [FunnyGuilds] ~ Created by FunnyGuilds Team ~

![image](https://user-images.githubusercontent.com/96879733/161763750-92bbeddb-8ca6-4d5a-b56b-205971284e1c.png)
tylko topki graczy dzialaja na tym 4.10.0

WARNING: Unknown placeholder ${server_player_count}
in 'reader', line 19, column 5:
- "&7WWW&8: &3icehc.pl &8:|: &7FB& ...
^
WARNING: Error in placeholder ${viewer funnyguilds_gtop-1}:
Unknown placeholder
in 'reader', line 49, column 12:
- {text: "&8» &71. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-TAG}:
Unknown placeholder
in 'reader', line 50, column 12:
- {text: "&8» &7Tag&8: &f${viewer funnygu ...
^
WARNING: Error in placeholder ${viewer funnyguilds_points}:
Unknown placeholder
in 'reader', line 51, column 12:
- {text: "&8» &7Punkty&8: &f${viewer funn ...
^
WARNING: Error in placeholder ${viewer funnyguilds_POSITION}:
Unknown placeholder
in 'reader', line 51, column 12:
- {text: "&8» &7Punkty&8: &f${viewer funn ...
^
WARNING: Error in placeholder ${viewer funnyguilds_gtop-2}:
Unknown placeholder
in 'reader', line 53, column 12:
- {text: "&8» &72. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-POINTS}:
Unknown placeholder
in 'reader', line 54, column 12:
- {text: "&8» &7Punkty&8: &f${viewer funn ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-POSITION}:
Unknown placeholder
in 'reader', line 54, column 12:
- {text: "&8» &7Punkty&8: &f${viewer funn ...
^
WARNING: Error in placeholder ${viewer funnyguilds_KILLS}:
Unknown placeholder
in 'reader', line 55, column 12:
- {text: "&8» &7Zabojstwa&8: &f${viewer f ...
^
WARNING: Error in placeholder ${viewer funnyguilds_gtop-3}:
Unknown placeholder
in 'reader', line 57, column 12:
- {text: "&8» &73. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-KILLS}:
Unknown placeholder
in 'reader', line 58, column 12:
- {text: "&8» &7Zabojstwa&8: &f${viewer f ...
^
WARNING: Error in placeholder ${viewer funnyguilds_DEATHS}:
Unknown placeholder
in 'reader', line 59, column 12:
- {text: "&8» &7Smierci&8: &f${viewer fun ...
^
WARNING: Error in placeholder ${viewer funnyguilds_gtop-4}:
Unknown placeholder
in 'reader', line 61, column 12:
- {text: "&8» &74. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-DEATHS}:
Unknown placeholder
in 'reader', line 62, column 12:
- {text: "&8» &7Smierci&8: &f${viewer fun ...
^
WARNING: Error in placeholder ${viewer funnyguilds_ASSISTS}:
Unknown placeholder
in 'reader', line 63, column 12:
- {text: "&8» &7Asysty&8: &f${viewer funn ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-5}:
Unknown placeholder
in 'reader', line 65, column 12:
- {text: "&8» &75. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-MEMBERS-ALL}:
Unknown placeholder
in 'reader', line 66, column 12:
- {text: "&8» &7Czlonkowie&8: &f${viewer  ...
^
WARNING: Error in placeholder ${viewer funnyguilds_LOGOUTS}:
Unknown placeholder
in 'reader', line 67, column 12:
- {text: "&8» &7Logouty&8: &f${viewer fun ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-6}:
Unknown placeholder
in 'reader', line 69, column 12:
- {text: "&8» &76. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-VALIDITY}:
Unknown placeholder
in 'reader', line 70, column 12:
- {text: "&8» &7Waznosc gildii&8: &f${vie ...
^
WARNING: Error in placeholder ${viewer funnyguilds_KDR}:
Unknown placeholder
in 'reader', line 71, column 12:
- {text: "&8» &7KD-Ratio&8: &f${viewer fu ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-7}:
Unknown placeholder
in 'reader', line 73, column 12:
- {text: "&8» &77. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-REGION-SIZE}:
Unknown placeholder
in 'reader', line 74, column 12:
- {text: "&8» &7Rozmiar gildii&8: &f${vie ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-8}:
Unknown placeholder
in 'reader', line 77, column 12:
- {text: "&8» &78. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_G-KDR}:
Unknown placeholder
in 'reader', line 78, column 12:
- {text: "&8» &7KD-Ratio&8: &f${viewer fu ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-9}:
Unknown placeholder
in 'reader', line 81, column 12:
- {text: "&8» &79. &f${viewer funnyguilds ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-10}:
Unknown placeholder
in 'reader', line 85, column 12:
- {text: "&8» &710. &f${viewer funnyguild ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-11}:
Unknown placeholder
in 'reader', line 89, column 12:
- {text: "&8» &711. &f${viewer funnyguild ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-12}:
Unknown placeholder
in 'reader', line 93, column 12:
- {text: "&8» &712. &f${viewer funnyguild ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-13}:
Unknown placeholder
in 'reader', line 97, column 12:
- {text: "&8» &713. &f${viewer funnyguild ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GUILDS}:
Unknown placeholder
in 'reader', line 99, column 12:
- {text: "&8» &7Gildie&8: &f${viewer funn ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-14}:
Unknown placeholder
in 'reader', line 101, column 12:
- {text: "&8» &714. &f${viewer funnyguild ...
^
WARNING: Error in placeholder ${viewer funnyguilds_USERS}:
Unknown placeholder
in 'reader', line 103, column 12:
- {text: "&8» &7Zarejestrowani&8: &f${vie ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-15}:
Unknown placeholder
in 'reader', line 105, column 12:
- {text: "&8» &715. &f${viewer funnyguild ...
^
WARNING: Error in placeholder ${viewer funnyguilds_HOUR}:
Unknown placeholder
in 'reader', line 107, column 12:
- {text: "&8» &7Godzina&8: &f${viewer fun ...
^
WARNING: Error in placeholder ${viewer funnyguilds_MINUTE}:
Unknown placeholder
in 'reader', line 107, column 12:
- {text: "&8» &7Godzina&8: &f${viewer fun ...
^
WARNING: Error in placeholder ${viewer funnyguilds_GTOP-16}:
Unknown placeholder
in 'reader', line 109, column 12:
- {text: "&8» &716. &f${viewer funnyguild ...

a tutaj z btlp i jak mozecie niby rozwiazac moj problem

**Comment by WygladDeveloper** [comment]
> I tak wywalilismy support BTLP - mozna dalej użyć PAPI

szybka odpowiedz  xddddd
