### ISSUE TITLE
Placeholder returns null

### ISSUE THREAD

**Issue by TAI5ON** [FunnyGuilds/FunnyGuilds#1948]
W momencie usunięcia gildii plugin zwraca mi null'a. Użyłem placeholdera: %rel_funnyguilds_prefix% w pluginie TAB (https://github.com/NEZNAMY/TAB). Wersja FG: 4.10.0 Snowdrop-2faa90b Wersja TAB: 3.1.1. Ss konsoli: 
![ss](https://user-images.githubusercontent.com/104453904/165369002-89efd2f6-6c83-42ac-90c0-a32048ae97d4.PNG)

**Comment by TAI5ON** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/104453904/165860489-08b4bc03-6f13-4c62-87c8-c246a63620c6.PNG)

**Comment by TAI5ON** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/104453904/165861824-7afa4cee-4a6b-405c-9166-c8fe1188619d.PNG)

**Comment by P3ridot** [comment]
Na najnowszym Nightly błąd nie powinien już występować
