### ISSUE TITLE
Gracze są ciągle 'online' na TAB'ie

### ISSUE THREAD

**Issue by Xayanix** [FunnyGuilds/FunnyGuilds#1986]
![image](https://user-images.githubusercontent.com/12672902/172501006-f57733ed-9295-42e5-a9cc-c88e934fcc03.png)
![image](https://user-images.githubusercontent.com/12672902/172501018-733f941f-33cf-4e2a-b4aa-e375716f0fae.png)
![image](https://user-images.githubusercontent.com/12672902/172501213-f97feb40-a591-4716-9c6c-86662afe5e93.png)

1.18.2

**Comment by Kamilkime** [comment]
Naprawione najnowszym Nightly (https://github.com/FunnyGuilds/FunnyGuilds/commit/ee11e6be34af39bcc903fc04358d96d4bbe581e0), można zamknąć
