### ISSUE TITLE
Dodanie lotu tnt

### ISSUE THREAD

**Issue by Puszki123** [FunnyGuilds/FunnyGuilds#1987]
Mam propozycje jak daliście już konfiguracje tnt takie jak poziom położenia tnt ,wybuch tylko na terenie gildii i wielkość wybuchu i obrażenia bloków. To można też dodać lot tnt aby nie spadało w dół tylko w górę lecieć tak aby ustawić prostą linie jak tnt ma coś rozwalać. Nie wiem jak to napisać lepiej

**Comment by Kamilkime** [comment]
Nie bardzo rozumiem co masz na myśli z tym lotem. No i pytanie czy to w ogóle powinno być dodane do pluginu, który jednak ma być pluginem na gildie

**Comment by P3ridot** [comment]
Myślę, że nie powinno być coś takiego dodane do pluginu na gildie, dlatego mało prawdopodobne, że kiedykolwiek taka funkcjonalność się pojawi

**Comment by P3ridot** [comment]
Nie za bardzo rozumiem jakby to miało działać i z pewnością dałoby się to zaimplementować w oddzielnym pluginie. Feature zbyt specyficzny aby go dodawać. Sorry bro
