### ISSUE TITLE
 /zapros all 

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2009]
komende zapros all gdzie było by mozna zaprosic wszystkich w obrebie nwm 5 kratek czy tam 10 kratek

**Comment by P3ridot** [comment]
#1100 - jeśli chodzi o panel

**Comment by P3ridot** [comment]
Następnym razem rób oddzielne issue na każdy feature/propozycje/etc.

**Comment by PolsatGraniePL** [comment]
skriptem w kilka sekund bez addonów można zrobić

```
command /zaprosAll [<integer>]:
    trigger:
        loop all players in radius arg-1 around player:
            execute player command "zapros %loop-value%"
        send "&eZaprosiłeś każdego gracza w obrębie %arg-1% kratek!"
```

**Comment by dzikoysk** [comment]
Jak ktoś to szybko zaimplementuje, to zmiana może trafić do FG 4.11.0

**Comment by P3ridot** [comment]
Na najnowszym Nightly taka opcja już istnieje
