### ISSUE TITLE
Błąd tworzenia GUI

### ISSUE THREAD

**Issue by Astahiell** [FunnyGuilds/FunnyGuilds#2015]
Nightly https://ci.insertt.dev/job/FunnyGuilds/job/master/600/ 
Config źle odczytuje nazwe itemów, przy ustawieniu nazwy tak czy siak każdy item na nazwe name, przy usunięciu name plugin sie wyłącza.
Screen gui : https://imgur.com/fKsbhxI
Config gui : https://pastebin.com/TaEuVgr3
LOG: https://pastebin.com/N0LagJuw

**Comment by Kamilkime** [comment]
A no fakt, kod obecnie nie przewiduje podania itemmety bez wskazania co to (typu name: lub lore:)
