### ISSUE TITLE
Security check nie działa poprawnie, gdy sercem jest blok

### ISSUE THREAD

**Issue by Astahiell** [FunnyGuilds/FunnyGuilds#2018]
Gdy blokiem serca jest bedrock ( na innych nie testowałem), pokazuje sie security https://youtu.be/jNO03gYrrCU jak widac na filmiku, czasem pojawia sie jednoczesnie info o gildii jak i komunikat na freecamie.

**Comment by P3ridot** [comment]
Naprawione w najnowszym nightly
