### ISSUE TITLE
Problem z punktami nad głową, wyświetlaniem gildii na tabliście oraz wklejaniem schematów

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2021]
Problem polega na tym ze pkt pod głowa raz sie wyswietlaja raz nie o co mi chodzi jak wchodzisz na serwer nic sie nie pokazuje ale jak logniesz i wbijesz jeszcze raz nagle pkt sie pokazuja 

~~nastepny problem jaki zauwazylem jest to bug z schematic guilds
ciagle wyskakuje informacja wystapil blad podczas tworzenia terenu gildii 
pomimo ze schematic dobrze sie wkleja
no i raz klikniecie w jajko dziala raz nie raz pojawiaja sie informacje o g raz nie pojawiaja sie 
na dole zalaczam ss
![image](https://user-images.githubusercontent.com/25277653/175509288-5553ad56-ce87-45fa-be19-757e368add80.png)~~ Done

~~oraz zauwazyłem ze buguje sie wbudowana tablista raz pokazuje gildie jak sie zalozy raz nie i trzeba logac by pojawiła sie na tabie~~ 

![image](https://user-images.githubusercontent.com/25277653/175509965-781aaf4b-1509-4383-8da0-83c2c32d01fc.png)

Unreproducable (na najnowszym Nighty z default konfiguracją)

**Comment by P3ridot** [comment]
Duplicate #1077 jeśli chodzi o suffixy. Aktualnie możesz osiagnac to uzywając np. NametagEdit i użyć placeholdera `%rel_funnyguilds_prefix%`.

**Comment by P3ridot** [comment]
A jeśli chodzi o tabliste to pobierz najnowsze Nightly i powiedz, czy błąd dalej występuję

**Comment by P3ridot** [comment]
Oraz prosiłem żebyś robił oddzielne Issues na każdy błąd - nam jest łatwiej wtedy pracować

**Comment by P3ridot** [comment]
Oraz jeśli nie wiesz jak nazywać issues po angielsku to pisze po polsku - to jednak głównie polski plugin

**Comment by P3ridot** [comment]
Dummy można wyłączyć opcją dummy-enable w configu

**Comment by P3ridot** [comment]
Co do klikania w jajko to działa ono dobrze, mamy cooldown na to. Wystarczy popatrzeć na opcje w configu `info-player-cooldown`

**Comment by P3ridot** [comment]
Wklejanie schematów już jest naprawione na najnowszym Nightly

**Comment by zsak1** [comment]
hm dziwnie na najnowyszym  Nightly  tez tego nie mam w takim razie problem z tabem rozwiazany
