### ISSUE TITLE
Możliwość zmiany jak długo bossbar jest wyświetlany

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2025]
Wpadłem na fajna rzecz mianowiscie dodanie timer do bossbar z mozliwoscia zmiany czasu w cfg 
juz tłumacze o co mi chodzi
 jak wejdziemy na teren GUILD to pojawia sie bossbar z wiadomoscia wkroczyles na teren g
  i difultowo znika on chyba po 20 pare sek
a przydało by sie by znikał szybciej lub odrazu jak na actionbar  oczywiscie chodzi mi o wersje wyzsze niz 1.8 bo na 1.8 nie da

**Comment by P3ridot** [comment]
Ale na nowszych wersjach jest przecież bossbar  🤔 Chyba ze chodzi o cos innego

**Comment by zsak1** [comment]
by ten bossbar znikał po x czasie jak ustawimy w cfg

**Comment by oskarscot** [comment]
Moge dodac opcje do configu jak bede robil #2051

**Comment by P3ridot** [comment]
Właściwie jest to już dostępne bo można sobie dowolnie ustawić długość wyświetlania tego bossbaru dla każdej wiadomości oddzielne
