### ISSUE TITLE
Funkcja HexSystem na wersje wyższe

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2029]
Wpadłem na spoko pomysł na funkcje mozna by było dodac support hex system (custom kolorki) na wersje wyzsze niz 1.8

**Comment by PinkLolicorn** [comment]
To raczej jest już w samym API silnika, wystarczy napisać `&x` a potem wszystkie litery hex poprzedzone `&`. Dla przykładu ` &x&e&9&6&5&c&5` to wściekły różowy.

**Comment by WcaleNieWolny** [comment]
> Wpadłem na spoko pomysł na funkcje mozna by było dodac support hex system (custom kolorki) na wersje wyzsze niz 1.8

Raczej nie możliwe. Z tego co wiem to hex kolory weszły do mc w 1.16? Napewno nie w 1.9

**Comment by P3ridot** [comment]
No na 1.16 są ale pewnie mu właśnie o to chodziło - on po prostu pisze ciągle "na wersję  wyższą niż 1.8" ¯\_(ツ)_/¯
