### ISSUE TITLE
Dodanie komendy /PP  -  kordynaty członka gildii z  !! czy tam @

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2034]
Witam mozna by było dodac na bossbar i actionbar   kordynaty gracza np gracz {nick} potrzebuje pomocy {x} {y} {z}  
i wtedy w cfg by sie ustawiało czy ma sie to wyswietlac na AC CZY BOSSB
i ten bossbar by np znikał po 15 sek i ten bossbar byl by jako timer bossbar w sensie ze pasek by szedl w dol 

 jesli ktos wpisze /pp to sie to wyswietla wszystkim członką g 
 jest to bardziej przydatne niz ta @ czy !! na chacie poniewaz jak jest duzo ludzi to czat zapierdziela i czasami trudno jest wylapac taka wiadomosc  i fajnie by było jak by było to  na actionbar lub bossbar

**Comment by P3ridot** [comment]
Niech inni ocenią, ale to może być poza scope pluginu na gildie - w końcu łatwo da się coś takiego dodać w oddzielnym pluginie/skrypcie no ale nie wiem...
