### ISSUE TITLE
Dodanie peryskopu i kamer

### ISSUE THREAD

**Issue by DevangerTM** [FunnyGuilds/FunnyGuilds#2057]
- ### **Peryskop i Kamera gildii** - Peryskop i kamery mają podobne działania. Peryskop jest widokiem z góry na gildie, a kamerę można stworzyć na craftingu i ustawić w różnych miejscach na terenie gildii. Fajnie aby można było swój schemat craftingu stworzyć. 
 
 

> ![Opera Zrzut ekranu_2022-07-08_031728_www youtube com](https://user-images.githubusercontent.com/41342020/177901106-176698c7-77f4-4a2c-a05c-83ddc690687e.png)
> ![Opera Zrzut ekranu_2022-07-08_031648_www youtube com](https://user-images.githubusercontent.com/41342020/177901113-e371a912-fae7-4c3f-a0a4-2d47bb2adfcf.png)![Opera Zrzut ekranu_2022-07-08_031711_www youtube com](https://user-images.githubusercontent.com/41342020/177901112-a2f99e17-36d5-4a28-8cb3-481da2a3e8d3.png)
> ![Opera Zrzut ekranu_2022-07-08_031634_www youtube com](https://user-images.githubusercontent.com/41342020/177901114-b1ad7ab3-c795-41ce-af0b-5d528e5d29d5.png)
![Opera Zrzut ekranu_2022-07-08_031701_www youtube com](https://user-images.githubusercontent.com/41342020/177902320-50f34234-680e-49b6-ab35-007fd9d5684c.png)![Opera Zrzut ekranu_2022-07-08_031523_www youtube com](https://user-images.githubusercontent.com/41342020/177902332-05c7dc11-18c2-4bf6-8594-9e1a768a750e.png)
![Opera Zrzut ekranu_2022-07-08_031617_www youtube com](https://user-images.githubusercontent.com/41342020/177902323-639e4f1c-f09f-4c75-be25-6e204d5237cc.png)![Opera Zrzut ekranu_2022-07-08_031602_www youtube com](https://user-images.githubusercontent.com/41342020/177902328-c685fee1-7b6a-484e-a757-df087645cfee.png)
![Opera Zrzut ekranu_2022-07-08_031546_www youtube com](https://user-images.githubusercontent.com/41342020/177902329-6d3464af-71ff-49fe-b440-7800f4335e7b.png)
![Opera Zrzut ekranu_2022-07-08_031531_www youtube com](https://user-images.githubusercontent.com/41342020/177902331-e59d818d-785d-483d-a835-e166a2610574.png)

**Comment by P3ridot** [comment]
Można coś takiego dodać w oddzielnym pluginie, mechanika wybiegająca poza plugin gildyjny
