### ISSUE TITLE
Dodatkowe opcje - Dodatek do gui panelu zarządzani

### ISSUE THREAD

**Issue by DevangerTM** [FunnyGuilds/FunnyGuilds#2058]
- ### **Dodatkowe opcje** - Te opcje już są pod komendami ale jak by była możliwość już robienia tego gui Serca Gildii / Panelu Gildii to tam też można by było można dodać. Tak samo z pvp on/off lub ulepszaniem regionu gildii.

> ![Opera Zrzut ekranu_2022-07-08_031133_www youtube com](https://user-images.githubusercontent.com/41342020/177902724-92c251c4-e28a-4c60-b6c7-b40c740dbaf9.png)
> ![Opera Zrzut ekranu_2022-07-08_031115_www youtube com](https://user-images.githubusercontent.com/41342020/177902730-17c39f5c-b774-4dbf-a29a-0af80a344379.png)

**Comment by P3ridot** [comment]
Przenioslem propozycje do #1100 jako iż to związane z tamtym issue
