### ISSUE TITLE
Próba wyświetlania wiadomości w kilku miejscach jednocześnie wyrzuca błąd clienta

### ISSUE THREAD

**Issue by CHOMIKgp** [FunnyGuilds/FunnyGuilds#2059]
Jesli w config w miejsciu "region-move-notification-style" ustawisz

region-move-notification-style:
- CHAT
- TITLE

a w messages masz tylko i wylacznie wiadomosci z CHAT a w TITLE nie ustawiles wiadomosci tylko zsotawiles puste np. "notificationTitleIntruderEnterGuildRegion: '' " to podczas wchodzenia na gildie oraz wychodzenia z gildi wywala z serwera z bledem. 
![unknown](https://user-images.githubusercontent.com/54559029/178107280-d53f04cb-a26f-4aee-8e3c-3259814e4be6.png)

**Comment by P3ridot** [comment]
#1837

**Comment by P3ridot** [comment]
Mógłby ktoś przetestować czy błąd dalej występuje?

**Comment by P3ridot** [comment]
Przetestowałem i nie mogę zreprodukować więc chyba działa

![image](https://user-images.githubusercontent.com/28200355/210283685-6c501c39-e5c2-46cc-9cf6-f49ea161ba74.png)
