### ISSUE TITLE
Problem z ip-protect

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2063]
znalazlem chyba bład w ip-protect zaczelem sie napierdalac z ziomem i za ktoryms tam killem dostałem wiad ze punkty nie zaliczono bo takie same ip i dla pewnosci sprawdziłem ip moje jak i ziomka i były inne wrazie wu moge poszukac logi i podeslac jak bedzie potrzebne ssa nie mam bo nie robiłem

**Comment by DevangerTM** [comment]
Jeżeli masz bungee to sprawdź czy dobrze jest skonfigurowana, ponieważ może to też mieć znaczenie.
Źle skonfigurowane bungee = te same ip serwera, a za tym idzie macie takie same ip jak serwer więc może to być ta przyczyna.

**Comment by P3ridot** [comment]
Czy używasz bungee? Jeśli tak to, czy masz ustawione `ip_forward` na true w config.yml? Oraz na samym serwerze `bungeecord` na true w spigot.yml

**Comment by opera2398** [comment]
to nie wina `ip_forward` ani `bungeecord: false` w `spigot.yml`, blad jest w kodzie wiec rowniez prosze o naprawe tego (blad prawdopodobnie pojawia sie wtedy gdy ktos was zabije, a nastepnie wy zabijecie osobe ktora zabila was poprzednio), tak btw - ostatnio z FG dzieja sie bardzo zle rzeczy, przez pol roku zjebaliscie tyle rzeczy ile nie zjebaliscie od samego poczatku - nie mam na mysli tego ze jestescie chujowi chociaz troche to z tego wynika, po prostu moze warto zrobic to w ten sposob, ze wy bedziecie dawac z siebie wiecej a projekt bedzie mozliwy do pobrania za oplata? uwazam to za bardzo dobre rozwiazanie, bo aktualnie plugin powoli staje sie niezdatny do uzytku

**Comment by insertt** [comment]
> znalazlem chyba bład w ip-protect zaczelem sie napierdalac z ziomem i za ktoryms tam killem dostałem wiad ze punkty nie zaliczono bo takie same ip i dla pewnosci sprawdziłem ip moje jak i ziomka i były inne wrazie wu moge poszukac logi i podeslac jak bedzie potrzebne ssa nie mam bo nie robiłem

Krótki filmik/zrzuty ekranu byłyby przydatne w celu ustalenia przyczyny błędu.

**Comment by P3ridot** [comment]
> to nie wina `ip_forward` ani `bungeecord: false` w `spigot.yml`, blad jest w kodzie wiec rowniez prosze o naprawe tego (blad prawdopodobnie pojawia sie wtedy gdy ktos was zabije, a nastepnie wy zabijecie osobe ktora zabila was poprzednio), tak btw - ostatnio z FG dzieja sie bardzo zle rzeczy, przez pol roku zjebaliscie tyle rzeczy ile nie zjebaliscie od samego poczatku - nie mam na mysli tego ze jestescie chujowi chociaz troche to z tego wynika, po prostu moze warto zrobic to w ten sposob, ze wy bedziecie dawac z siebie wiecej a projekt bedzie mozliwy do pobrania za oplata? uwazam to za bardzo dobre rozwiazanie, bo aktualnie plugin powoli staje sie niezdatny do uzytku

Plugin jednak raczej pozostanie darmowy, tworzymy go hobbystycznie i no po prostu błędy trzeba nam zgłaszać a my postaramy się je naprawić. Nic więcej zrobić nie możemy - a myślę, że nawet gdyby plugin był płatny to jakoś dużo więcej by się pod tym względem nie zmieniło

**Comment by P3ridot** [comment]
> to nie wina `ip_forward` ani `bungeecord: false` w `spigot.yml`, blad jest w kodzie wiec rowniez prosze o naprawe tego (blad prawdopodobnie pojawia sie wtedy gdy ktos was zabije, a nastepnie wy zabijecie osobe ktora zabila was poprzednio), tak btw - ostatnio z FG dzieja sie bardzo zle rzeczy, przez pol roku zjebaliscie tyle rzeczy ile nie zjebaliscie od samego poczatku - nie mam na mysli tego ze jestescie chujowi chociaz troche to z tego wynika, po prostu moze warto zrobic to w ten sposob, ze wy bedziecie dawac z siebie wiecej a projekt bedzie mozliwy do pobrania za oplata? uwazam to za bardzo dobre rozwiazanie, bo aktualnie plugin powoli staje sie niezdatny do uzytku

No i ty mówisz o całkowicie innej rzeczy w tym przypadku, sam IP protect działa tak samo jak działał wcześniej. Blokada nabijania rankingu teraz działa w ten sposób i jest to przemyślany design, do którego można by dodać opcje konfiguracji.

**Comment by Kamilkime** [comment]
> tak btw - ostatnio z FG dzieja sie bardzo zle rzeczy, przez pol roku zjebaliscie tyle rzeczy ile nie zjebaliscie od samego poczatku - nie mam na mysli tego ze jestescie chujowi chociaz troche to z tego wynika, po prostu moze warto zrobic to w ten sposob, ze wy bedziecie dawac z siebie wiecej a projekt bedzie mozliwy do pobrania za oplata? uwazam to za bardzo dobre rozwiazanie, bo aktualnie plugin powoli staje sie niezdatny do uzytku

Przy projekcie pracują obecnie 2-3 osoby, do tego w wolnym czasie - staramy się jak najszybciej łatać błędy. FG jest pluginem sporym, dodajemy do niego ciągle nowe rzeczy - siłą rzeczy błędy zawsze jakieś będą. No i największym problemem nadal pozostaje nie istnienie błędów, a ich zgłaszanie - już nie raz spotykałem się z przypadkami, gdzie ludzie narzekali na błąd i jego występowanie np. od miesięcy, ale oczywiście zgłoszenia żadnego do nas nie było...

**Comment by P3ridot** [comment]
> Czy używasz bungee? Jeśli tak to, czy masz ustawione `ip_forward` na true w config.yml? Oraz na samym serwerze `bungeecord` na true w spigot.yml

Nikt podobnego błędu nie zgłaszał, więc może po prostu masz coś źle skonfigurowane? Bo wiem, że takie rzeczy mogą się zdarzać a wtedy moglibyśmy już zamknąć issue

**Comment by P3ridot** [comment]
Brak jakiegokolwiek feedbacku od autora, problem raczej nie leży po stronie FG (bo kod sie praktycznie nie zmienił)
