### ISSUE TITLE
Tagi i punkty gildii znikają

### ISSUE THREAD

**Issue by 00fr3szuuu** [FunnyGuilds/FunnyGuilds#2070]
gdy ma sie gildie i osoba ktora nie ma gildii popatrzy na nick osoby z gildia i obie zrelogaja to nagle nie ma ani pkt graczy ani tagow nikogo na serwerze tylko sam nick az usunie sie gildia albo zalozy od nowa tagi wracaja, gdy sa same nicki rowniez zauwazylem ze tagi itp wracaja po jakis 3 minutach

**Comment by DevangerTM** [comment]
Posiadam ten sam problem.

**Comment by P3ridot** [comment]
Przydałoby sie przepisać najlepiej cały ten od kiedy jest z nim wiele bugów i problemów

**Comment by P3ridot** [comment]
Powinno być naprawione w najnowszym Nightly. Najwyżej sie otworzy raz jeszcze
