### ISSUE TITLE
Ranking PERCENT nie działa poprawnie

### ISSUE THREAD

**Issue by opera2398** [FunnyGuilds/FunnyGuilds#2072]
assists-limit: 1
rank-assist-killer-share: 0.25
rank-assist-victim-always-share: true
rank-system: PERCENT
percent-rank-change: 4.0

mimo to, dzieje sie taka rzecz
![sdfgsdfg](https://user-images.githubusercontent.com/49837061/179006943-3620af64-c317-4320-9090-1fc88d4a1795.png)
HotWitold2137 516 pkt dostal +5 pkt za killa a LordMarcl121 1167 pkt dostał +8 za asyste

**Comment by P3ridot** [comment]
Ile punktów miał gracz kacper1232 przed zabójstwem?

**Comment by P3ridot** [comment]
> Dziwne jest to, że mimo użycia systemu PERCENT zostało dodane jedynie łącznie 13 punktów. Ale sama opcja `rank-assist-killer-share` działa poprawnie - ona oznacza jaką część punktów dostanie **zabójca**, czyli w tym przypadku 0.25 = 25%. Po prostu ustaw 0.75 i zabójca dostanie tą większą część

Zastosuj się do tego, z naszej strony wszystko działa poprawnie jedynie źle masz skonfigurowane same FunnyGuilds
