### ISSUE TITLE
Gracze z wrogiej gildii są pokazywani jako osoby z tej samej gildii

### ISSUE THREAD

**Issue by opera2398** [FunnyGuilds/FunnyGuilds#2086]
prefix-our: '&8[&a{TAG}&8] &f'
prefix-allies: '&8[&6{TAG}&8] &f'
prefix-enemies: '&8[&4{TAG}&8] &f'
prefix-other: '&8[&c{TAG}&8] &f'

latest nightly, paper 1.8.8

![unknown](https://user-images.githubusercontent.com/49837061/181031226-d9aeb52b-93f1-42ca-a177-01e8d80f8ba2.png)

**Comment by insertt** [comment]
Bug confirmed, introduced in https://github.com/FunnyGuilds/FunnyGuilds/commit/f24ced0796ae94e50274f51e5457731d047f553a#diff-bfd62fc948bcced530165093baf1ce2ef2d258d099dd9665aaea095e15adaae2R48.

**Comment by Mervik120** [comment]
tak samo mam

**Comment by opera2398** [comment]
kiedy bedzie poprawione?

**Comment by P3ridot** [comment]
> kiedy bedzie poprawione?

Kiedy ktoś znajdzie czas, aby naprawić - już ci kiedyś mówliśmy, że FG to dobrowolnie rozwijany projekt i nie zawsze mamy czas na to

**Comment by P3ridot** [comment]
@opera2398 na najnowszym Nightly już powinno działać, przetestuj i powiedz, czy działa to jak powinno

**Comment by Mervik120** [comment]
nadal nie działa

**Comment by Astahiell** [comment]
Na najnowszym nightly dziala poprawnie
![image](https://user-images.githubusercontent.com/84834748/183952304-60d02159-15e2-4598-ac65-7219dde837c0.png)

**Comment by Tejnox** [comment]
Problem nadal występuje w wersji ``4.10.3-SNAPSHOT Snowdrop-91863b9``

https://user-images.githubusercontent.com/68534126/184428406-f9f0c954-e772-40c2-b9b7-ebe4d2a63bf2.mp4

**Comment by P3ridot** [comment]
Correlated #2070

**Comment by Mervik120** [comment]
problem nadal jest to prawda

**Comment by P3ridot** [comment]
Naprawione w najnowszym Nightly
