### ISSUE TITLE
Remove 1.8.x-1.15.x support

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#2091]
Since most of the servers (70%) are currently using 1.16+ we could remove support for older versions.  Most of tricky hacks in code comes from giving support for both older and newer versions. And since FunnyGuilds is open-source maybe someone will create fork that brings back support for 1.8.8.

Source of version usage: https://bstats.org/plugin/bukkit/FunnyGuilds/677#minecraftVersion

**Comment by P3ridot** [comment]
Oh and maybe we could even use newer java versiom, but I'm not sure.

**Comment by 0x8008** [comment]
WERSJA 1.8 WPROWADZA DODATKOWY BLOAT DO KODU I JEST NIEBIEZPIECZNA PLUS KORZYSTA Z PRZESTARZAŁEJ WERSJI ŚRODOWISKA CZASU URUCHOMIENIOWEGO JAVY

**Comment by P3ridot** [comment]
> WERSJA 1.8 WPROWADZA DODATKOWY BLOAT DO KODU I JEST NIEBIEZPIECZNA PLUS KORZYSTA Z PRZESTARZAŁEJ WERSJI ŚRODOWISKA CZASU URUCHOMIENIOWEGO JAVY

Tak.

**Comment by nwseOOO** [comment]
1.8 to wirus

**Comment by Rollczi** [comment]
W sumie nie widzę powodu, aby usuwać wsparcie 1.8.8, kod powinien być niezależny od wersji.
Jest jakiś realny problem który faktycznie jest przeszkodą?

**Comment by Rollczi** [comment]
Ostatecznie nie jest to zły pomysł ale dopytuje się z czego wynika ten pomysł.

**Comment by dzikoysk** [comment]
Wywalenie tylu wersji samo w sobie mi nie przeszkadza, ale można to wydać tylko jako 5.0.0, a nie 4.12.0.

**Comment by P3ridot** [comment]
> W sumie nie widzę powodu, aby usuwać wsparcie 1.8.8, kod powinien być niezależny od wersji.
> Jest jakiś realny problem który faktycznie jest przeszkodą?

Trochę nowego API - takich rzeczy QOL no i nie trzeba robić jakichś dziwnych hacków w kodzie

**Comment by vLuckyyy** [comment]
> > W sumie nie widzę powodu, aby usuwać wsparcie 1.8.8, kod powinien być niezależny od wersji.
> > Jest jakiś realny problem który faktycznie jest przeszkodą?
> 
> Trochę nowego API - takich rzeczy QOL no i nie trzeba robić jakichś dziwnych hacków w kodzie

Jakie hacki ma na myśli?

**Comment by P3ridot** [comment]
> > > W sumie nie widzę powodu, aby usuwać wsparcie 1.8.8, kod powinien być niezależny od wersji.
> > > Jest jakiś realny problem który faktycznie jest przeszkodą?
> > 
> > 
> > Trochę nowego API - takich rzeczy QOL no i nie trzeba robić jakichś dziwnych hacków w kodzie
> 
> Jakie hacki ma na myśli?

Dużo refleksji w kodzie (do matchowania enchantów, jajek z mobami etc.) i zbedny nms (np. pobieranie pingu gracza, wysylania title/actionbara). Market share 1.8.8 to aktualnie jedynie 21%. Jak ktoś będzie chciał wsparcie to sobie dorobi/zapłaci komuś, my nie chcemy juz wiecej utrzymywać legacy kodu. Wspieray aktualnie 12 różnych wersji - i pytanie po co?

**Comment by nwseOOO** [comment]
> > > > W sumie nie widzę powodu, aby usuwać wsparcie 1.8.8, kod powinien być niezależny od wersji.
> > > > Jest jakiś realny problem który faktycznie jest przeszkodą?
> > > 
> > > 
> > > Trochę nowego API - takich rzeczy QOL no i nie trzeba robić jakichś dziwnych hacków w kodzie
> > 
> > 
> > Jakie hacki ma na myśli?
> 
> Dużo refleksji w kodzie (do matchowania enchantów, jajek z mobami etc.) i zbedny nms (np. pobieranie pingu gracza, wysylania title/actionbara). Market share 1.8.8 to aktualnie jedynie 21%. Jak ktoś będzie chciał wsparcie to sobie dorobi/zapłaci komuś, my nie chcemy juz wiecej utrzymywać legacy kodu. Wspieramy aktualnie 12 różnych wersji - i pytanie po co?

"jedynie" 21% (największy spośród reszty) 💀 zamiast szukania problemów nie tam gdzie trzeba to zalecam usunięcie wsparcia dla wersji < 10% marketshare i utrzymywanie tych, które są najbardziej popularne (1.8.8, 1.16.5, 1.17.1, 1.18.2, 1.19.2) i zamiast wspierać 7 wersji których nikt nie używa można wspierać 5 z łącznym ~95% marketshare

**Comment by oskarscot** [comment]
Po to trzymać support na wersje która wyszła 8 lat temu? Najlepszym pomysłem by było wypuścić ostatnią wersje która będzie miała support na 1.8 i przenieść to na innego brancha. Zostawić informacje ze ostatnia wersja to cokolwiek, dać to jako LTS i gotowe. Ci co chcą używać 1.8 mają dalej dostęp do tego. Większość nowych funkcji i tak będzie robione pod nowsze wersje mc zwłaszcza jak będą usunięte legacy funkcje

**Comment by P3ridot** [comment]
> Po to trzymać support na wersje która wyszła 8 lat temu? Najlepszym pomysłem by było wypuścić ostatnią wersje która będzie miała support na 1.8 i przenieść to na innego brancha. Zostawić informacje ze ostatnia wersja to cokolwiek, dać to jako LTS i gotowe. Ci co chcą używać 1.8 mają dalej dostęp do tego. Większość nowych funkcji i tak będzie robione pod nowsze wersje mc zwłaszcza jak będą usunięte legacy funkcje

Myślę, ze taki LTS w ogóle powinien mieć jedynie bug-fixy bez nowych funkcji

**Comment by P3ridot** [comment]
https://howoldisminecraft188.today/

**Comment by P3ridot** [comment]
W sumie to juz to chyba zrobilośmy :trollface:
