### ISSUE TITLE
Remove Spigot support and force Paper

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#2092]
Correlated to #2091 - on newer versions probably no one is using Spigot, most of the servers are using Paper and it's forks. Developing plugin with Paper's improved API would be much easier.

**Comment by Rollczi** [comment]
Używanie paper API jest złym pomysłem. Jest niestabilne, nie posiada wsparcia między wersjami, (nadaje się tylko na wsparcie jednej lub max dwóch wersji, a nie np. do 1.17.x-1.19.x tak jak zakładano w https://github.com/FunnyGuilds/FunnyGuilds/issues/2091)

Polecam spojrzeć na
platformy adventure https://docs.adventure.kyori.net/platform/bukkit.html
minimessage https://docs.adventure.kyori.net/minimessage/api.html
i paperlib https://github.com/PaperMC/PaperLib

pozwoli to na kompatybilność 1.8 - 1.19 i używanie wielu funkcji wbudowanych w minimessage adventure itd
paperlib dodaje funkcje z papera takie jak async teleport

**Comment by CDFN** [comment]
Powinno się pisać wobec Bukkit API, żeby przypadkiem ktoś nie został wykluczony. W końcu każdy przecież używa crafbukk... oh wait..
Paper ma przeważający market share i nie ma powodów, żeby wspierać spigota a tym bardziej craftbukkita. Jeżeli ktoś nie używa paper-based silnika to ma poważniejsze problemy niż niedziałający plugin na gildie.

**Comment by P3ridot** [comment]
Możnaby usunąć check na silnik i podpiąć paper-api. Jesli silnik mialby api to by dzialal a jak nie to wina usera i elo

**Comment by Rollczi** [comment]
> Powinno się pisać wobec Bukkit API, żeby przypadkiem ktoś nie został wykluczony. W końcu każdy przecież używa crafbukk... oh wait..
> Paper ma przeważający market share i nie ma powodów, żeby wspierać spigota a tym bardziej craftbukkita. Jeżeli ktoś nie używa paper-based silnika to ma poważniejsze problemy niż niedziałający plugin na gildie.

Ale jak ma się to do tego co napisałem? Proszę przeczytaj moją wiadomość. 

Nie ma znaczenia ile osób korzysta z papera, ale jeśli chcesz go używać (w tym adventure) musisz się liczyć z tym że robisz plugin na 1/2 wersje a nie 1.16-1.19 co przeczy z planami Peridota

**Comment by P3ridot** [comment]
Dobra dizk uznał że nie ma sensu to elo
