### ISSUE TITLE
Bug z pvp

### ISSUE THREAD

**Issue by Astahiell** [FunnyGuilds/FunnyGuilds#2093]
Gdy 2 osoby z tej samej gildii uderza osobe spoza gildii moga sie uderzyc i bic nawzajem pomimo wylaczonego pvp w gildii, natomiast gdy jeszcze sojusznik uderzy osobe spoza gildii, także będzie mógl sie bić mimo wyłączonego pvp.

**Comment by P3ridot** [comment]
Próbowałem zreprodukować błąd, ale nic z tego nie wychodzi - wszystko działa jak powinno. Przydałoby się może trochę więcej informacji (o silniku, wersji etc.)

**Comment by P3ridot** [comment]
@Astahiell

**Comment by Astahiell** [comment]
Wersja: FunnyGuilds 4.10.2-SNAPSHOT Snowdrop-51b6ea9 
Silnik:  git-Paper-411 (MC: 1.17.1)

**Comment by P3ridot** [comment]
Jak sprawa wygląda na najnowszym Nightly?
