### ISSUE TITLE
Opcja automatycznego powrotu postawionych bloków na terenie gildii po określonym czasie

### ISSUE THREAD

**Issue by SparkieT** [FunnyGuilds/FunnyGuilds#2094]
Witam, piszę z propozycją gdyż według mnie i serwerów które mają funnyguilds by była wspaniałą rzeczą, natomiast chodzi mi żeby dodać do configu mozłiwość włączenia lub wyłączenia robienia waterskilla na wrogiej gildii tzn. (Rozlewanie wody przez gracza na nie swoim terenie gildii) i na przykład co ile sekund ta woda ma zniknąć.

**Comment by P3ridot** [comment]
Możnaby dodać opcję do configu, że pewne bloki po postawieniu wracają po jakims czasie do gracza. Możnaby to wtedy połączyć razem z `placing-blocks-bypass-on-region`
