### ISSUE TITLE
TNT blokuje budowanie po wybuchu mimo blokady wybuchu w określonych godzinach

### ISSUE THREAD

**Issue by stefankielbasa** [FunnyGuilds/FunnyGuilds#2106]
Problem polega na tym że mam ustawione TNT w pluginie które pozwala na niszczenie bloków od godziny 18:00 do 22:00

i TNT jest blokowane i nic nie niszczy jednak dalej blokuje możliwość budowy na terenie gildi jak w przypadku Rajdu.

Blokada budowy powinna zadziałać tylko wtedy kiedy TNT może rozwalić bloki a nie tylko po wybuchu

**Comment by P3ridot** [comment]
Trzeba by dodać opcje w configu od tego
