### ISSUE TITLE
Dodanie do configu opcji kompleksowego wyłączenia scoreboarda (nametagi i dummy)

### ISSUE THREAD

**Issue by kerpsondev** [FunnyGuilds/FunnyGuilds#2110]
Witam, aktualnie w configu da się wyłączyć dummy i widok nametagów, lecz siłą rzeczy nowy scoreboard i tak przypisuje się do gracza.
Była by to przydatna opcja, gdy ktoś chciałby robić system nametagów we własnym w pluginie, chociażby w przypadku gdy chciałby zmienić pozycję tagu gildii z prefixu na suffix.

I tak na zakończenie wiem, że da się we własnym pluginie nadpisać graczowi scoreboard, ale jednak była by to przydatna opcja w mojej skromnej opinii.

(No chyba, że jest taka opcja a ja jestem zbyt tępy i jej nie zauważyłem)

**Comment by P3ridot** [comment]
Correlated with #2070

**Comment by P3ridot** [comment]
Dodane w najnowszym Nightly
