### ISSUE TITLE
Błędne ustawianie relacji gildyjnych w nametagach

### ISSUE THREAD

**Issue by Tejnox** [FunnyGuilds/FunnyGuilds#2115]
Problem dotyczy najnowszej wersji pluginu FunnyGuilds 4.10.2 w której czasami zdarza się iż plugin błędnie ustawia kolory relacji gildii w nametagach (lub/i nie tylko tam), przykładowo dla osoby będącej członkiem danej gildii ustawiło kolor relacji wrogiej co widać na załączanych niżej zdjęciach. 

```
# Wygląd tagu osób w tej samej gildii
prefix-our: '&a[{TAG}] '

# Wygląd tagu gildii sojuszniczej
prefix-allies: '&9[{TAG}] '

# Wygląd tagu wrogiej gildii
prefix-enemies: '&c[{TAG}] '

# Wygląd tagu gildii neutralnej, widziany również przez graczy bez gildii
prefix-other: '&c[{TAG}] '
```

![image](https://user-images.githubusercontent.com/68534126/184421865-348110b2-a9a6-4869-a622-33b1ad819ca0.png) ![image](https://user-images.githubusercontent.com/68534126/184421833-487d9cfd-2235-48dc-9ff1-8f33e0e16c2e.png)

**Comment by Kamilkime** [comment]
Wygląda na powiązane z https://github.com/FunnyGuilds/FunnyGuilds/issues/2086
Na najnowszym nighly powinno już być ok
