### ISSUE TITLE
Nowe komendy admina logout, asysty

### ISSUE THREAD

**Issue by Astahiell** [FunnyGuilds/FunnyGuilds#2124]
Komendy admina do resetowania logout'ów i asyst
/ga logouts [nick] [logouts]
/ga assists [nick] [assists]

**Comment by the-codeboy** [comment]
Hi. I'd like to work on this. Although I do not speak Polish so somebody would have to translate the messages

**Comment by dzikoysk** [comment]
Sure, feel free to submit PR and we'll try to help you with translations :)
