### ISSUE TITLE
Placeholder {GUILD-PROTECTION} doesn't work

### ISSUE THREAD

**Issue by Incluuu** [FunnyGuilds/FunnyGuilds#2134]
{GUILD-PROTECTION} doesn't work in messages.yml
![image](https://user-images.githubusercontent.com/67196311/187023927-8fdff55a-e4b3-4d84-ac15-1b45a0ef2ea7.png)

**Comment by P3ridot** [comment]
Replace it with {PROTECTION}, {GUILD-PROTECTION} has been removed
