### ISSUE TITLE
Punkty nie naliczają się po wyjściu w trakcie anty logout-u

### ISSUE THREAD

**Issue by tezzzy** [FunnyGuilds/FunnyGuilds#2135]
Wersja serwera paper 1.18.2, plugin CombatLogX, wersja funny guilds 4.10.2 - Snowdrop.
Po wyjściu w trakcie trwania anty logoutu po wyjściu z serwera gracz umiera, jednak nie traci funny guildsowych punktów.

**Comment by opera2398** [comment]
podpinam sie, prosilbym o fixa bo blad wystepuje od ponad roku

**Comment by P3ridot** [comment]
> podpinam sie, prosilbym o fixa bo blad wystepuje od ponad roku

To było go zgłosić bo to już któryś raz kiedy zamiast zgłosić błąd to narzekasz, że błąd występuje. Czy to takie trudne do zrozumienia, że my nie naprawimy błedu jeśli nikt go nam nie zgłosi?

**Comment by P3ridot** [comment]
Na najnowszym Nightly wszystko powinno już śmigens, więc proszę przetestować

**Comment by P3ridot** [comment]
Jak ja testowałem to wszystko działało. Nikt nie napisał, że nie działa - jeśli jednak dalej nie będzie working to się otworzy
