### ISSUE TITLE
Bład z PlayerTeleportEvent

### ISSUE THREAD

**Issue by opera2398** [FunnyGuilds/FunnyGuilds#2138]
gdy jestesmy w bloku lub gdy rzucimy perle kresu za kazdym razem pojawia sie komunikat 'wkroczyles na teren gildii jakiejs tam' + dostajemy mega mocny dmg

niestety nie mam mozliwosci tego nagrania, ale wystarczy wejsc na serwer z FG, wpisac /gm 3, zejsc na dol do podziemi gdzie bedziemy sie "dusic w scianie" i wpisac /gm 0

to bardzo powazny blad, bo na serwerach gilldii sytuacji gdzie ktos jest w scianie jest bardzo wiele - prosilbym o szybka naprawe

latest nightly z 30 sierpnia

**Comment by opera2398** [comment]
kiedy naprawicie? wiem ze projekt robicie za friko ale to krytyczny blad

**Comment by P3ridot** [comment]
> kiedy naprawicie? wiem ze projekt robicie za friko ale to krytyczny blad

To napraw albo znajdź kogoś co naprawi, my magicznie nie znajdziemy czasu na to

**Comment by insertt** [comment]
Potrzebujemy więcej informacji aby zreprodukować błąd: na jakiej wersji serwera występuje błąd, czy gracz posiada gildie i czy musi się znajdować na terenie gildii aby wystąpił ten błąd?

**Comment by P3ridot** [comment]
> Potrzebujemy więcej informacji aby zreprodukować błąd: na jakiej wersji serwera występuje błąd, czy gracz posiada gildie i czy musi się znajdować na terenie gildii aby wystąpił ten błąd?

Brak odpowiedzi przez 3 dni, zamykamy
