### ISSUE TITLE
Support custom regex patterns

### ISSUE THREAD

**Issue by UniqueUserName500** [FunnyGuilds/FunnyGuilds#2139]
I don't understand the Polish requirement, so I will write about the problem really short. Sorry!

I ask on Discord, and people agree I should report this an issues

Server that use Geyser, require the Bedrock users to have the prefix on their name (depend on how the owner config the prefix)
Why? Because Geyser need prefix to identify which is a Bedrock player which is a Java player.

So for example an username `Steve123` play on bedrock edition join a geyser server.
If the owner config the prefix as `*`
Geyser will change his name to `*Steve123`

P/S: Geyser use `*` as prefix by default.
https://wiki.geysermc.org/geyser/faq/#can-i-remove-the-prefix-of-floodgate-players

---> `GuildRegex.java` prevent player with special character join the server

---> `UserManager.java` the `create` method `Validate.isTrue(FunnyValidator.validateUsername(name), "name is not valid!");`
also prevent player from joining the server

The `GuildRegex` can prevent non-latin username to play the game, such as Japanese, Korean, Chinese.

Solution: Make `GuildRegex` configurable.

Thanks!

**Comment by P3ridot** [comment]
We just should add option to set any regex and remove these hardcoded regexes

**Comment by PinkLolicorn** [comment]
There is no reason not to support current values and treat any other value as standard Pattern.

**Comment by P3ridot** [comment]
> There is no reason not to support current values and treat any other value as a standard Pattern.

FunnyPattern ( ͡° ͜ʖ ͡°)

~~FG developers~~ Peridot trying not to implement own wrapper for java type

![84A980DC-4B31-4944-A9CF-57887C213275](https://user-images.githubusercontent.com/28200355/188176282-c0948a6e-d83a-4189-8843-f5761528a6d3.gif)

**Comment by P3ridot** [comment]
On the latest Nightly we added this feature - you can download it from our [Jenkins](https://ci.insertt.dev/job/FunnyGuilds/)
