### ISSUE TITLE
Antylogout combatlogx nie dziala poprawnie pomimo fixa

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2158]
Witam antylogout combatlogx  nie dziala poprawnie z fg pomimo fixa 
problem polega na tym ze jak atakujacy hitnie  gracza i atakujacy lognie to gracz ktory zostal uderzony przez atakujacego nie dostaje punktow title message oraz chat message
a jesli atakujecy uderzy ofiare i ofiara lognie to ofiara dostaje punkty wyswietla sie title ale nie ma na czacie wiadomosci o smierci

**Comment by Kamilkime** [comment]
Jakiej wersji MC używasz? Jakiego silnika? Jakiej dokładnie wersji FG? Jakiej dokładnie wersji CombatLogX?

**Comment by zsak1** [comment]
1.8.8 flamepaper

**Comment by zsak1** [comment]
na wersjach wyższych niz 1.8 nie sprawdzalem ale podejrzewam ze tak samo sie buguje

**Comment by Kamilkime** [comment]
No nie odpowiedziałeś na moje pytanie w pełni

**Comment by zsak1** [comment]
juz dopisałem

**Comment by zsak1** [comment]
silnik: 1.8.8 paperspigot
wersja Funnyguild: nocna
wersja CombatLogX: 11.1.0.6.998

**Comment by P3ridot** [comment]
Nie mogę zreprodukować
