### ISSUE TITLE
Dodanie systemu antylogout w celu naprawnienia problemów błedow logouta ktore wystepuja w fg 

### ISSUE THREAD

**Issue by endixons** [FunnyGuilds/FunnyGuilds#2159]
nie wiem czy juz była taka propozycja jak była to posze o zamkniecie jak nie to 
Mam propozycje dodanie wlasnego systemu logout do fg moim zdaniem fg powinno posiadac swoj system antylogout poniewaz rozwiazało by to wszystkie problemy z logout ktore wystepuja 
oraz wywalic wsparcie combatlogx bo by było one zbedne jak by fg miało swoj system logout 

mozna by było dodac opcje wlaczenia oraz wylaczenia owego antylogout oraz dodac api w celu dodania tego logouta do własnego pluginu

**Comment by Kamilkime** [comment]
FG nie może mieć w sobie każdej możliwej funkcji - są na antylogout dobre pluginy i po prostu będziemy je wspierać.

**Comment by zsak1** [comment]
niby masz racje  ale jak by był wbudowany antylogout to rozwiazało by to dotychczasowe problemy

**Comment by Kamilkime** [comment]
Raczej by stworzyło nowe, bo musielibyśmy kolejną rzecz utrzymywać, więc na pewno nie
