### ISSUE TITLE
/zapros all nie zaprasza ludzi w okolicy

### ISSUE THREAD

**Issue by zsak1** [FunnyGuilds/FunnyGuilds#2161]
w zapros all pojawia sie mały bład mianowicie jak wyslemy zapros all to zadnem gracz w promieniu x kratek  nie otrzymuje zaproszenia do gildiii mimo wyslania zapro

**Comment by Astahiell** [comment]
Gdy uzyjesz komendy /zapros all to zaden z graczy nie dostaje zaproszenia ?

**Comment by zsak1** [comment]
tak

**Comment by WcaleNieWolny** [comment]
Czy na chacie pojawia się jakaś wiadomość?

**Comment by zsak1** [comment]
wiadomosci na chacie nie ma jedynie jest zapraszam w promieni 10 kratek

**Comment by zsak1** [comment]
moge wyslac ss

**Comment by P3ridot** [comment]
Jest to ktoś w stanie przetestować/potwierdzić?

**Comment by P3ridot** [comment]
Nie da sie tego zreprodukować, więc zamykam
