### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnyGuilds#2165]
Cześć, chciałbym użyć w TabLiscie placeholderów które stworzyłem w osobnym pluginie, ale FunnyGuilds nie wspiera w całości PlaceholderAPI :(, a więc czy istnieje metoda która pozwala tworzyć zmienne ({TEST}) które będą wyświetlać się na tabliście?

Jeżeli nie bardzo prosiłbym o dodanie metody/wsparcia placeholder api, dziekuje.

**Comment by P3ridot** [comment]
Wsparcie PlacolderAPI na tabliscie jest. Używa sie jedynie formatu z % czyli np. `%mojplugin_placeholder%`

**Comment by pawelkuwa** [comment]
okej, w takim razie coś zepsułem, jak wrócę do domu to sprawdzę
