### ISSUE TITLE
Player death message is not displayed

### ISSUE THREAD

**Issue by eki-github** [FunnyGuilds/FunnyGuilds#2172]
[FunnyGuilds] [Debug] > [MCStats] Value isn't numeric.
When I kill a player, the notification is not displayed in the chat: "rankDeathMessage: '{ATAG}&b{ATTACKER} &7({PLUS-FORMATTED}&7) zabil {VTAG}&b{VICTIM} &7({MINUS-FORMATTED}&7)'".
[latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/9804601/latest.log)
paper-1.17.1-388
Plugins (46): _ekiAntiAd*, AdvancedBan, ChestCommands, Citizens, CustomCrafting, Essentials, ExcellentCrates, FancyBags, FunnyGuilds, GSit, HolographicDisplays, HolographicExtension, InventoryRollback, ItemEdit, kSwear*, LPC, LuckPerms, Matrix, MineResetLite, Multiverse-Core, MVdWPlaceholderAPI*, NexEngine, PL-Hide, PlaceholderAPI, PlayerKits, PlotSquared, ProtocolLib, PvPManager, Report*, SafeMC-AntiCrash*, Shopkeepers, SkinsRestorer, Skript, SuperVanish, TAB, TradeSystem, ViaBackwards, ViaRewind, ViaVersion, Vouchers, Vulcan, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by P3ridot** [comment]
It looks like `config.yml` is miss configured (key: `items`) with wrongly configured items
