### ISSUE TITLE
Add support for LPC

### ISSUE THREAD

**Issue by Astahiell** [FunnyGuilds/FunnyGuilds#2175]
Add support for [LPC](https://www.spigotmc.org/resources/lpc-chat-formatter-1-7-10-1-19.68965/) in chat formatters like {POINTS}.

**Comment by P3ridot** [comment]
It's LPC problem (they're using wrong priority for chat event). And we can't do much about it.

I created [PR](https://github.com/wikmor/LPC/pull/24), but repo doesn't seem to be active
