### ISSUE TITLE
Dodanie wsparcia formatu kolorów hex (&#RRGGBB)

### ISSUE THREAD

**Issue by querko242** [FunnyGuilds/FunnyGuilds#2178]
Tak jak w tytule, fajnie by było jakby można było kolorować wiadomości za pomocą kolorów hex. Kolory hex działają od wersji 1.16 w górę

**Comment by Kamilkime** [comment]
Dla koloru `#ABCDEF` powinna bez problemu działać notacja: `&x&A&B&C&D&E&F`

**Comment by querko242** [comment]
Rzeczywiście działa 😁, jednak super by było jakby była np. taka forma: &#ABCDEF krótsza troszkę

**Comment by querko242** [comment]
Kiedy może zostać to dodane?

**Comment by Kamilkime** [comment]
Ma to raczej mały priorytet, bo jest działający zapis z &x, jak będzie to będzie
