### ISSUE TITLE
zmienić w wiki i readme adres repo i zmiany wersji na 4.9.7

### ISSUE THREAD

**Issue by robalmeister** [FunnyGuilds/FunnyGuilds#2183]
bo reposlite zostało zmienione

**Comment by P3ridot** [comment]
Nie rozumiem, przecież zarówno na wiki jak i w readme adresy są aktualne więc na co chciałbyś je zmieniać?

**Comment by robalmeister** [comment]
`maven { url "https://repo.panda-lang.org/releases" }` tu wlasnie jak wejdzie bedzie 404 a w wiki jest jeszcze stara wersja funnyguilds (4.10.0)

**Comment by P3ridot** [comment]
Ten URL działa, po prostu to jest ścieżka dla gradle/mavena. Do przeglądania artefaktów jest inny adres, łatwo do niego przejść klikając po prostu tu
![image](https://user-images.githubusercontent.com/28200355/200142670-0c86519d-297f-42e5-88c6-6e1d95499f16.png)

A na wiki za chwile zmienię
