### ISSUE TITLE
KDA Ratio

### ISSUE THREAD

**Issue by Tobiczek** [FunnyGuilds/FunnyGuilds#2191]
![image](https://user-images.githubusercontent.com/114435370/202548307-5655f30e-2e92-4429-9d28-494cfdd92ea7.png)
Tak jak na załączonym ss, wnosze propozycje o dodanie mozliwosci sprawdzania za pomocą placeholdera KDA Ratio

**Comment by DomiRusz24** [comment]
KDA ratio w sensie:
kille + assysty 
~~--------------------~~
zgony
?

**Comment by P3ridot** [comment]
tak
