### ISSUE TITLE
Puste linijki pojawiające się same na początku configu

### ISSUE THREAD

**Issue by iipanda** [FunnyGuilds/FunnyGuilds#2202]
Przy włączaniu serwera pojawiają się puste linijki na początku configu (tylko głównego `config.yml`, w messages i tab nie), jedna linijka przy każdym włączeniu serwera.

Paper 1.19.2 Latest / Java 17 / Latest FG

![obraz](https://user-images.githubusercontent.com/29822201/205171564-75e6282f-3c7a-4cf6-a400-b561d237fbd9.png)

**Comment by CDFN** [comment]
user issue

**Comment by erg43hergeg** [comment]
nieudacznicy kod napisali to jest jak jest pzdr

**Comment by dzikoysk** [comment]
to ja pisałem przepraszam wszystkich pokrzywdzonych

**Comment by P3ridot** [comment]
@PinkLolicorn do you know what is causing thus issue?

**Comment by P3ridot** [comment]
Trzeba wymyślić jak to zreprodukować... Bo to ułatwi debugowanie tego
