### ISSUE TITLE
[ViaVersion] Tablist is broken 1.19.3 client on 1.19.2 paper

### ISSUE THREAD

**Issue by Incluuu** [FunnyGuilds/FunnyGuilds#2206]
Hi, i am reporting a problem with tablist on version 1.19.3 client [paper version 1.19.2]
Install funnyguilds and join the server click TAB. Plugins: viaversion, viabackwards, protocolLib

**Comment by Kamilkime** [comment]
What exactly is the problem? You didn't provide any error logs, screenshots, etc.
We need to know what the issue is to fix it.

**Comment by P3ridot** [comment]
I think it's some issues with ViaVersion...

**Comment by Incluuu** [comment]
This TAB | Free trial 3.1.5 on builtbybit (by [NEZNAMY]) work perfectly

**Comment by P3ridot** [comment]
But IIRC `Tab` doesn't modify tablist cells - FunnyGuilds does

**Comment by P3ridot** [comment]
I tested it and it's confirmed issue... But stil I think it's `ViaVersion` issue since tablist on `1.19.2` clients works...

**Comment by P3ridot** [comment]
Like I mentioned it's not FunnyGuilds issue, it's ViaVersion issue and I already [reported it](https://github.com/ViaVersion/ViaVersion/issues/3186). Also we recently added 1.19.3 support in Nightly and maybe updating from 1.19.2 to 1.19.3 would be good idea.

**Comment by P3ridot** [comment]
#2276
