### ISSUE TITLE
Główki graczy na tabie zależne od wartości komórki

### ISSUE THREAD

**Issue by mring0707** [FunnyGuilds/FunnyGuilds#2207]
chcialbym aby w lewej strony nicku gracza byla głowka jego skina w plikach nie widziałem takiej opcji. Czy w ogóle da sie cos takiego zrobic i jak 

z góry dziekuje 
pozdrawiam 
![obraz_2022-12-11_155244585](https://user-images.githubusercontent.com/120321936/206910771-b773f1de-466c-4979-a3e8-b56d2fc7e6e6.png)

**Comment by Kamilkime** [comment]
Obecnie nie ma takiej opcji, trzeba by takie coś do systemu główek dopiero dodać

**Comment by P3ridot** [comment]
Correlated #1902

**Comment by P3ridot** [comment]
GH-2349
