### ISSUE TITLE
Brak możliwości ustawienia - TITLE

### ISSUE THREAD

**Issue by Lokuu321** [FunnyGuilds/FunnyGuilds#2210]
Po ustawieniu - TITLE i starcie serwera automatycznie zmienia się z powrotem na - ACTIONBAR

```
# Gdzie mają pojawiać się wiadomości związane z poruszaniem się po terenach gildii
# Możliwe miejsca wyświetlania: ACTIONBAR, BOSSBAR, CHAT, TITLE
region-move-notification-style:
- ACTIONBAR
```

**Comment by Kamilkime** [comment]
A jak dokładnie tu ustawiasz ten TITLE? I jaka to wersja FG i MC?

**Comment by Lokuu321** [comment]
# Czy powiadomienie o zabójstwie gracza powinno się wyświetlać dla zabójcy jako title
display-title-notification-for-killer: true

# Czy powiadomienia o wejściu na teren gildii członka gildii powinny byc wyświetlane
notification-guild-member-display: false

# Gdzie mają pojawiać się wiadomości związane z poruszaniem się po terenach gildii
# Możliwe miejsca wyświetlania: ACTIONBAR, BOSSBAR, CHAT, TITLE
region-move-notification-style:
- TITLE

1.16.5 
4.10.2 Snowdrop

**Comment by P3ridot** [comment]
Mógłby ktoś przetestować?

**Comment by P3ridot** [comment]
Testnąłem i u mnie wszystko działa

![image](https://user-images.githubusercontent.com/28200355/210283551-192ae492-1052-40a2-bcdd-8cc851870f21.png)
