### ISSUE TITLE
Heart of the guild appearing in other world

### ISSUE THREAD

**Issue by Incluuu** [FunnyGuilds/FunnyGuilds#2215]
Hi, I'm reporting a serious problem with the heart of the guild in nether_world.
Guild heart is in two worlds: world and world_nether after create guild.

![image](https://user-images.githubusercontent.com/67196311/209558216-35df50bb-382f-4587-8d47-cca1fbc24ae9.png)

**Comment by Incluuu** [comment]
Step by step:
1. create guild in world
2. go to nether_world on the same cords

**Comment by Kamilkime** [comment]
What FunnyGuilds version are you using? And what Minecraft version is this?

**Comment by Incluuu** [comment]
> What FunnyGuilds version are you using? And what Minecraft version is this?

PaperSpigot 1.19.2 and FunnyGuilds 4.10.3-SNAPSHOT - 681

**Comment by nwseOOO** [comment]
funnysectors pre-release
