### ISSUE TITLE
Recolor Nametag after every placeholder have been replaced

### ISSUE THREAD

**Issue by Incluuu** [FunnyGuilds/FunnyGuilds#2227]
Hi, colors from placeholderapi are not included in the suffix. I will add that the plugin Tab from NEZNAMY - works placeholders.
Server version: 1.19.2 + FunnyGuilds 4.10.3-SNAPSHOT - 687

![image](https://user-images.githubusercontent.com/67196311/209916039-5723a843-1fdc-4e42-94f2-c56bb5cf99c5.png)
![image](https://user-images.githubusercontent.com/67196311/209916110-e2fc9d94-e151-45f6-9ad5-c6660a242da9.png)

**Comment by P3ridot** [comment]
Adding this is easy, only `value = ChatUtil.colored(value);` has to be added [here](https://github.com/FunnyGuilds/FunnyGuilds/blob/4a453f7b8e7ec8094d74b8257b0f87b3e8ed4aed/plugin/src/main/java/net/dzikoysk/funnyguilds/feature/scoreboard/nametag/IndividualNameTag.java#L147)
