### ISSUE TITLE
Konfiguracja wartości zwracanej przez PlaceholderAPI

### ISSUE THREAD

**Issue by alfoons** [FunnyGuilds/FunnyGuilds#2257]
Dodać konfiguracje wyświetlanej wiadomości dla danego placehordera np **%funnyguilds_g-tag%**

config do placehorderow znajdywał by się w np **placehorders.yml** wyglądal by on tak:

mam nadzieje ze bedzie to dodane

![image](https://user-images.githubusercontent.com/88468043/210665870-0439c2bb-ef71-4bfe-9850-14aaceb6e1c5.png)

**Comment by P3ridot** [comment]
Mało kto tego użyje a implementacje tego zrobi tylko syf w kodzie
