### ISSUE TITLE
Dodanie możliwości HP do serca - Ilość uderzeń w serce

### ISSUE THREAD

**Issue by alfoons** [FunnyGuilds/FunnyGuilds#2259]
Polegało by to na tym ze zeby pobić gildie musisz np 100 znisczyc  serce zeby podbic 1 zycie gildii
wszystko dalo by sie ustawic w configu
hp by sie regenerowalo np co 5 sekund 1 hp (1 uderzenie/znisczenie)

**Comment by Kamilkime** [comment]
Zaproponowane w #1725
