### ISSUE TITLE
Nie dzialajacy schemat

### ISSUE THREAD

**Issue by macasonhuzuni** [FunnyGuilds/FunnyGuilds#2260]
Siema, przychodze z takim problemem poniewaz na serwerze gdy probuje wkleic schemat i w cfg i w folderze fg sie wszystko zgadza wkleja sie sam end crystal bez klatki ktora byla w schemacie czyli poprostu schemat nie dziala. zapisalem go komenda //schem save funnyguilds o to zdjecie configu
![schem](https://user-images.githubusercontent.com/97892727/211160116-42c83038-5bd9-4c58-ac97-c62ea7e79cef.png)

**Comment by P3ridot** [comment]
a przerzuciles ten schemat z folderu WorldEdita do folder FunnyGuilds? Tego samego co config bez żadnych dodatkowych katalogów

**Comment by macasonhuzuni** [comment]
no wlasnie tak dlatego dziwie sie ze nie dziala

**Comment by P3ridot** [comment]
A jakiej wersji FunnyGuilds używasz? Oraz jakoej wersji serwera?

**Comment by macasonhuzuni** [comment]
serwer 1.8.9      fg 4.6.0 snowdrop

**Comment by Kamilkime** [comment]
> 4.6.0 snowdrop

Nie ma nawet takiej wersji. Użyj najlepiej najnowszej wersji Nighly

**Comment by macasonhuzuni** [comment]
XDDD tak mam napisane najwyzej ktos nazwe zmienil ale dobra dzieki sprobuje

**Comment by macasonhuzuni** [comment]
nie dziala nawet z najnowsza wersja

**Comment by P3ridot** [comment]
A co ci sie wkleja jak robisz `//schem load funnyguilds` a potem //patse? Normalnie sie wkleja?

**Comment by macasonhuzuni** [comment]
tak, normalnie

**Comment by P3ridot** [comment]
A wyslij zawartość katalogu FunnyGuilds (w sensie screenshota jakie masz tam pliki)

**Comment by macasonhuzuni** [comment]
![Uploading GHB.png…]()

**Comment by P3ridot** [comment]
Zle wrzuciles ten obrazek... Bo sie nie wgrał innie da sie fo zobaczyć

**Comment by macasonhuzuni** [comment]
internet mi idzie na spacer czekaj

**Comment by macasonhuzuni** [comment]
![GHB](https://user-images.githubusercontent.com/97892727/211164800-e0856529-60bf-4c89-bdd6-49ea2a7accf8.png)

**Comment by P3ridot** [comment]
Bylbys w stanie podeslac plik schematu oraz logi serwera?

**Comment by macasonhuzuni** [comment]
nie moge schematu wyslac nie obsolguje tego pliku

**Comment by P3ridot** [comment]
Bylbys w stanie wbic na naszego discorda? https://discord.gg/bookkity-254623242914889729

**Comment by macasonhuzuni** [comment]
no jestem ale aktualnie nie mam nawet mikrofonu w sluchawkach i srednio

**Comment by P3ridot** [comment]
https://discord.com/channels/254623242914889729/278157499851341825/1061349837452345475

Na serwerze jest WorldEdit 5.6 (ktora notabene jest pos Minecrafta 1.7 nie 1.8) a my wspieramy jedynie WE 6 i 7
