### ISSUE TITLE
Ustawiać nametag gracza nawet jeśli patrzy sam na siebie

### ISSUE THREAD

**Issue by alfoons** [FunnyGuilds/FunnyGuilds#2266]
![image](https://user-images.githubusercontent.com/88468043/212327593-c98fad12-6a4d-4427-bae5-9e6cb1e7bd87.png)
 tutaj prosze o usuniecie returna

**Comment by alfoons** [comment]
jaki low

**Comment by P3ridot** [comment]
tldr; niektóre klienty pozwalają na coś takiego (czyli widzenie samemu swojego nametagu)
![image](https://user-images.githubusercontent.com/28200355/212327892-75eae270-39cf-4a0a-a37b-a8a5b6ea722a.png)
