### ISSUE TITLE
Zakładanie gildii na spawnie

### ISSUE THREAD

**Issue by Bedroczek** [FunnyGuilds/FunnyGuilds#2274]
Dzień Dobry chciałem pobrać wasz plugin aby zrobić serwer megadrop ale zauważyłęm dziwną rzecz poniewasz po założeniu gildi założyła się na spawnie. Myślałem że dlatego bo jestem właścicielem i mam opa więc go zabrałem i zmieniłem rangę na default ale nadal mogłem zakładać ją na spawnie mimo założonego regionu. Kiedy oddaliłem się od spawna i wpisałem komendę na założenie gildi i tym razem nie była na spawnie a 100 bloków wyżej niż powierzchnia. Co może być przyczyną?

**Comment by Kamilkime** [comment]
FG spawn sprawdza pobierając go z mapy. Jeśli masz spawn ustawiony jakimś pluginem - może on nie przestawiać tego mapy, więc się to nie pokrywa ze sobą. Najlepiej idź na spawn i użyj tam komendy `/setworldspawn`, to przestawi spawn mapy i powinno naprawić problem.

**Comment by P3ridot** [comment]
Brak feedbacku zamykamy 🤪
