### ISSUE TITLE
Integracja FunnyGuilds z pluginem ViaVersion w celu naprawy wyświetlania TAB dla starszych wersji

### ISSUE THREAD

**Issue by ghost** [FunnyGuilds/FunnyGuilds#2276]
Cześć, posiadam serwer Minecraft postawiony na silniku Paper 1.19.3 (Silnik na biężąco aktualizowany) zauważyłem że dla starszych wersji Minecraft co umożliwia plugin ViaVersion, ViaBackwards oraz ViaRewind niepoprawnie wyświetla się własna TAB lista pluginu FunnyGuilds.
Pytałem oczywiście o ten problem na oficjalnym serwerze Discord Bookkity i otrzymałem odpowiedź od jedno z członków.
![Zrzut ekranu (158)](https://user-images.githubusercontent.com/112986097/215288096-590c4929-2d8e-4a40-871c-055a421a8161.png)
Myślę, że taka integracja z pluginem ViaVersion byłaby świetnym rozwiązaniem względem FunnyGuilds 😀
Praktycznie każdy publiczny serwer korzysta z ViaVersion dla graczy grających na starszych wersjach gry
Z tego co widziałem w configu FunnyGuilds istnieje już integracja z takimi pluginami jak WorldEdit, HolographicDisplays itd

**Comment by opera2398** [comment]
Podbijam, to mega wazne - zdziwilem sie ze w ogole wypusciliscie update nie myslac o tak podstawowej rzeczy

**Comment by Kamilkime** [comment]
To jest plugin na gildie, tab nie jest priorytetem. Dostarczamy zmienne PlaceholderAPI, zawsze można użyć dodatkowego pluginu, np. TAB.

Dodatkowo nie jest to podstawowa rzecz. Kompatybilność tworzy się dla danej wersji - działanie serwera 1.19.3 z clientami starszymi, albo clienta 1.19.3 ze starszymi serwerami, wykracza już poza podstawowe działanie takiego np. taba.

No ale też zmiana z tym czeka już na dodanie: https://github.com/FunnyGuilds/FunnyGuilds/pull/2304

**Comment by P3ridot** [comment]
> Podbijam, to mega wazne - zdziwilem sie ze w ogole wypusciliscie update nie myslac o tak podstawowej rzeczy

Zawsze możemy nigdy więcej nie wypuszczać update'u bo może dla kogoś nie ma jakiejs funkcji która jest przecież PODSTAWOWA. A najlepiej to usuńmy cały plugin bo jest taki NIEDOPRACOWANY.
