### ISSUE TITLE
PROTECTION-TIME

### ISSUE THREAD

**Issue by kowadl0** [FunnyGuilds/FunnyGuilds#2293]
Po zaatakowaniu gildii nadaje ochrone gildi lecz na -
Po ataku ochrona -23h -58min -54s (lecz odlicza normalnie tylko te "-" z dupy
Po najnowych buildach tak sie zrobilo

**Comment by P3ridot** [comment]
A jak wcześniej sie to wyswietlalo?

**Comment by kowadl0** [comment]
Wczesniej nie, bylo normalnie wszystko z tym

**Comment by P3ridot** [comment]
Co? Pytam sie jaka wartość tam wcześniej sie wyświetlała

**Comment by kowadl0** [comment]
A jak wczesniej
Bylo normalnie "Atak mozliwy za: 23h 58m 54s"
A teraz jest "Atak mozliwy za: -23h -58h -54s"
Tak samo w hologramach jest pokazanyxtak protection time
