### ISSUE TITLE
Automatyczne odświeżanie nametagów powoduje lag serwera przy dużej liczbie graczy

### ISSUE THREAD

**Issue by 0VERR** [FunnyGuilds/FunnyGuilds#2295]
Witam, 

Przy większej ilości Graczy na serwerze (100+) co jakiś czas cyklicznie występuje lekka ścinka wszystkich Graczy, robiąc timingsy zauważyłem podejrzanie duże użycie jakiegoś taska z FunnyGuilds

Używam najnowszej wersji FG Nightly
Wersja serwera 
![Duzo](https://user-images.githubusercontent.com/47013041/217052902-a425eca2-fde4-4f45-b58e-fb5e1b4a87a7.png)
![dziwne](https://user-images.githubusercontent.com/47013041/217052964-cdd068a2-001a-42dd-b92d-30cc183e5538.png)
1.19.3

**Comment by Kamilkime** [comment]
Możesz podesłać całe timingi?

**Comment by Kamilkime** [comment]
A może tak... Po prostu link do tego być podesłał?

**Comment by 0VERR** [comment]
https://timings.aikar.co/dev/?id=c65648fad79e49c8ba751022dc6792a8

**Comment by P3ridot** [comment]
Jaka wersje FG dokładnie używasz? Wpisz /funnyguilds i podaj jaka wersje ci zwraca

**Comment by 0VERR** [comment]
Przy więcej niz 100 Graczy ścinki są odczuwalne, no i czym więcej Graczy online tym są one dłuższe, poniżej 100 osób online praktycznie ich nie czuć https://spark.lucko.me/8K3ffgGvEF

**Comment by P3ridot** [comment]
Problemem jest system nametagów a dokładniej jego automatyczne odświeżanie dla wszystkich graczy co x czasu. Możesz spróbować wyłączyć to auto odświeżanie w `scoreboard.nametag.update-rate` ustawiajac wartość na 0. Problem jednak się pojawi jeśli używasz dodatkowych placeholderów (np. aktualnej pozycji gracza w gildii) bo wtedy te dane mogą nie być wystarczajaco aktualne. Postaramy się zoptymalizować system ale nie jesteśmy w stanie dokładnie określić jak długo to może zająć

**Comment by P3ridot** [comment]
Otwieram ponieważ nie jest to w pełni zoptymalizowane. Przydałoby się jeszcze dodać Queue, aby dzielić większe update'y na kilka ticków.

Jednakże na najnowszym Nightly powinno być już trochę lepiej (zmniejszyliśmy o około 50% liczbę iteracji)

**Comment by P3ridot** [comment]
@0VERR mógłbyś przetestować najnowsze Nightly i powiedzieć, czy jest poprawa? I niezależnie czy jest czy nie fajnie by było jakbyś znów podesłał spark profiler :P

**Comment by P3ridot** [comment]
Problem powinien byc juz rozwiazany na najnowszym Nightly, zapraszam do testowania
