### ISSUE TITLE
Straszne problemy z wydajnoscia.

### ISSUE THREAD

**Issue by inzynierr** [FunnyGuilds/FunnyGuilds#2300]
Witam. Tak jak w tytule.

Plugin ma straszne problemy z wydajnoscia przy wiekszej ilosci osob niz 100. Rzeczy, ktore bazuja na graczach (np. nametagi) i sa wywolywane dosc czesto, strasznie wykraczaja poza normalny tick rate serwera (50ms). Np. jezeli jest zalozmy 600 osob, to ponad 2 razy leci stream przez online graczy na serwerze, w glownym watku.
Do tego jeszcze system regionow. Dlaczego lookup regionow zostal zrobiony w taki sposob, jak teraz? Dlaczego zamiast skorzystac z mozliwosci hashmapek i szukac regionow po jakims kluczu, badz uzyc jakiegos sensownego algorytmu na szukanie regionow, to jest robiony stream przez mape i sprawdzane czy jestes w regionie? To juz samo w sobie odpada jako dobry pomysl, jezeli zalozmy bedzie ponad 200 regionow w tej mapie, przez ktora sie iterujecie, a funkcja szukajaca regionu jest dosc czesto wykonywana (bo co kazdy movement gracza, co kazdy block break etc).
Nie rozumiem tez dlaczego movement gracza zostal zrobiony w taki sposob. Dlaczego co kazdy movement odpalany jest asynchroniczny task w schedulerze? Gdyby ten system regionow byl jakkolwiek zoptymalizowany, to uniknelibyscie takich problemow.
Juz nie mowie o tym ze ktos madry postanowil zamienic wszystkie zwykle petle na streamy w kodzie, ktory wykonuje sie dosc czesto (co pod minecrafta jest bardzo zlym pomyslem, patrzac na to, iz tickrate to 50ms).

Tutaj zalaczam przyklad z timingsow, w tym przypadku z nametagami:
![image](https://user-images.githubusercontent.com/45458831/218274727-e931a7ea-36b9-462c-ac7b-9e1343cae9e8.png)
Na serwerze jest najnowszy commit z githuba.

**Comment by Kamilkime** [comment]
Akurat zmiana na streamy nic wielkiego tu nie zmienia, nie liczy się tu każda nanosekunda, już bez przesady.
Nametagi są aktualnie poprawianie, a dodatkowo wygląda, że twój jar jest jeszcze sprzed innej poprawki - task ma interval 60 zamiast 1200, co zostało już poprawione.
Lookup regionów czy movement nie są jakieś wybitne, ale dotychczas nie sprawiały żadnych większych problemów. Jedynie te nametagi są obciążające, ale nad tym już pracujemy.

**Comment by Kamilkime** [comment]
O nametagach dyskusja toczy się w #2295

**Comment by inzynierr** [comment]
Akurat w tym przypadku zmienia, moze nie jakos wiele, ale na pewno przez to, ze jest tutaj duzo allokacji (jak i w sumie tez iteracji) kod wykonuje sie wolniej, niz normalnie powinien.
Interval wiele razy zmienialem ja. Ale zmiana intervala w tym przypadku nic nie da, co jakis czas i tak bedzie lagspike.
Z lookupem regionow jest problem w przypadku tnt, i duzego wybuchu, w przypadku gdy tych regionow jest duzo.

**Comment by Kamilkime** [comment]
Zapewniam cię, że z FG jest trochę innych problemów obecnie - użycia streamów zamiast zwykłej pętli nawet nie odczujesz.
Lag spike będzie powoli poprawiany, ale już sama poprawka z intervalem dużo pomaga - w końcu 20x rzadziej ten lag będzie.
A lookup regionów - tak jak mówię, nigdy nie było z tym większych problemów, nie wiem jak twoim zdaniem miałoby to być ulepszone jeszcze obecnie.

**Comment by inzynierr** [comment]
Czy ja wiem czy nie odczujesz. Fakt, mniejsze serwery tego nie odczuja, ale wieksze serwery, majace po 600-700 osob online, a nawet wiecej na jednej instancji to odczuja, zwlaszcza, w przypadku TNT. Mimo wszystko, postaralbym sie ulepszyc caly ten system w jakis sposob. System regionow mozna by bylo zoptymalizowac do kilku iteracji, a nie, tak jak teraz, ze jest petla/stream przez cala mape regionow.

Jezeli zalozmy byloby malo tych regionow, to taki system moze byc, ale nie oszukujmy sie - plugin ten jest uzywany przez wieksze serwery, ktore czesto maja bardzo duzo gildii. Moze nikt nie zglaszal problemow z lookupem regionow, w sumie nie wiem, ale wiem, ze od jakiegos czasu takowe problemy sie pojawiaja. Przynajmniej ja tak mialem.

**Comment by Kamilkime** [comment]
No ale to co wysyłasz, to problem z nametagami, który jest nam już znany. I nadal mówisz - 'zoptymalizowac do kilku iteracji', ale nie widzę tu jakichś konkretnych rozwiązań zaproponowanych. Gdyby można to było łatwo przy obecnym systemie poprawić, to by to zostało dawno zrobione.

**Comment by inzynierr** [comment]
Lookup po chunkach, spatial partitioning - jakikolwiek algorytm/sposob w tym przypadku by dzialal szybciej, niz ten lookup ktory jest aktualnie zrobiony.
Tak, wiem, ze to co wysylam to problem z nametagami, ale problemow w aktualnej wersji FunnyGuilds jest wiecej, jezeli chodzi o optymalizacje. Niektore nie sa inwazyjne, jak np. te nametagi, ale fakt faktem mozna by bylo to lepiej zrobic.

**Comment by Kamilkime** [comment]
Większy rewrite FG jest planowany, to wtedy możemy o tym myśleć. Na razie poprawimy nametagi ile się da, ale to już niech zostanie w #2295, a to issue już zamknę.

**Comment by dzikoysk** [comment]
@inzynierr Poza jakimiś krytycznymi poprawkami do wersji 4.x nie planujemy większych rewrite na ten target. To wymaga sporo czasu i dłubnia w kodzie, który ma szereg problemów. Mając do dyspozycji czas chętnych do pisania fg osób, wolę żeby skupili się na 5.x i napisaniu tego na spokojnie od nowa. 

Do reszty: Pod postem widzę dużo reakcji, więc w między czasie przypominam o istnieniu drugiej zakładki [pull requests](https://github.com/FunnyGuilds/FunnyGuilds/pulls). Podstawa tego pluginu istnieje od 7 lat i w dużej części stan ten do dzisiaj wpływa na to, jak wygląda impl - nawet po częściowo przepisanych fragmentach. Pisząc plugin sam uczyłem się w trakcie, tak samo było z osobami, które zdecydowały się zrobić coś w pluginie na przestrzeni lat i byliśmy w tej kwesti otwarci. Myślę, że dowolna osoba programująca dłużej niż miesiąc zauważy problemy w tym kodzie - fajnie by było, gdyby przekładało się to na faktyczne zmiany w projekcie, bo aktualnie dyskusja zawsze się kończy na rzucaniu losowych zdań na różnych discordach :<
