### ISSUE TITLE
"Nie masz gildii!"

### ISSUE THREAD

**Issue by celakeniock** [FunnyGuilds/FunnyGuilds#2320]
wiec zrobilem serwer dla kolegow na aternosie oraz wszystko bylo okej
teraz przy wpisaniu "/baza" ze nie mam gildi, mimo ze jestem w niej. jakis pomysl jak naprawic? 

patrzylem w config oraz wszystko jest.
![image](https://user-images.githubusercontent.com/49827604/223217793-e881575b-a7c7-42c1-922e-8e8dcd94fc65.png)

**Comment by Kamilkime** [comment]
Nia było np. zmiany online-mode po drodze? Możliwe, że jest w plikach jeden gracz, ale pod dwoma różnymi UUID.

**Comment by celakeniock** [comment]
muszę sprawdzić, czy liczy się osoba z tym samym ip ale z drugim kontem czy jak?

**Comment by celakeniock** [comment]
> Nia było np. zmiany online-mode po drodze? Możliwe, że jest w plikach jeden gracz, ale pod dwoma różnymi UUID.

tak było z kilka, co z nimi zrobic? usunac?

**Comment by P3ridot** [comment]
Najlepiej by było usunąć ale pamiętaj że utracisz wtedy postęp (ranking, liczba zabójstw/śmierci etc). Ale z drugiej strony chyba nie ma innej opcji (oprócz ręcznej zmiany uuid wszystkich graczy). No i na przyszłość nie zmieniaj opcji online-mode bo ona psuje UUID i się potem dzieją takie rzeczy.
