### ISSUE TITLE
Enderpearl does not trigger GuildRegionLeaveEvent

### ISSUE THREAD

**Issue by WcaleNieWolny** [FunnyGuilds/FunnyGuilds#2327]
Steps to reproduce:
1. join a guild
2. throw an enderpearl outside of the guild region

**Comment by Rollczi** [comment]
Teleportacja nie wywołuje go eventu

**Comment by WcaleNieWolny** [comment]
Czy to jest intended behavior? Teleportacja do gildi wywołuje `GuildRegionEnterEvent`

**Comment by WcaleNieWolny** [comment]
Nie widzę powodu, dlaczego to miało by być intended
