### ISSUE TITLE
Usunięcie tablisty

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#2349]
Utrzymanie `tablisty` ostatnio zajmuje coraz więcej zasobów a istnieją pluginy, które pozwalają na zrobienie tego samego co aktualny tab w FG (np. plugin `Tab`) a nawet więcej i łatwiej. Powinniśmy zrobić co najwyżej jakiś default config właśnie np. dla `Tab` aby ludzie wiedzieli jak skonfigurować nowy plugin

**Comment by P3ridot** [comment]
Przez 3 dni nie ma sprzeciwu, można usuwać

**Comment by ghost** [comment]
Liberum veto

**Comment by P3ridot** [comment]
Odrzucam, mieliście 3 dni i nic nie zrobiliście

**Comment by Rollczi** [comment]
Popieram

**Comment by oskarscot** [comment]
#FreePalestine usuwamy tabliste

**Comment by devangerpl** [comment]
Nie no wasz lepiej działa nie jak nie które ;D

**Comment by bopke** [comment]
Szanowni Państwo,

Chciałbym wyrazić swoje obawy w sprawie planowanego usunięcia tablisty z pluginu Funnyguilds. Uważam, że jest to tragiczny pomysł, który nigdy nie powinien mieć miejsca.

Tablista jest ważnym elementem, który pozwala graczom na śledzenie wyników innych graczy, a także na interakcję z nimi w grze. Bez niej, rozgrywka staje się znacznie mniej atrakcyjna i mniej konkurencyjna.

Ponadto, tablista jest również niezbędna dla administratorów serwerów, którzy muszą śledzić działania graczy i egzekwować regulamin. Jeśli usuniemy tablistę, administratorzy będą mieli znacznie trudniejsze zadanie w nadzorowaniu serwera.

Dlatego też, apeluję do Państwa, aby nie usuwali tablisty z pluginu Funnyguilds. Jest to niezbędny element gry i jego usunięcie wpłynie negatywnie na całą społeczność graczy.

Dziękuję za uwagę i liczę na Państwa wsparcie w tej kwestii.

Z poważaniem,
Bopke

**Comment by oskarscot** [comment]
Szanowni Państwo,

Chciałbym wyrazić swoje poparcie dla propozycji usunięcia listy graczy (tablisty) z wtyczki FunnyGuilds dla Minecrafta. W mojej opinii, usunięcie tablisty byłoby korzystne dla naszej społeczności z kilku powodów.

Po pierwsze, tablista narusza prywatność graczy. Wyświetlanie nicków graczy i informacji o ich poziomach może ujawnić wrażliwe informacje o nich, co nie jest zgodne z ich prywatnością. Zdajemy sobie sprawę, że wielu graczy chce zachować swoją prywatność, a usunięcie tablisty będzie dla nich korzystne.

Po drugie, usunięcie tablisty wprowadzi bardziej realistyczne doświadczenie gry. Bez tablisty gracze będą mieli większą swobodę w podejściu do tworzenia gildii i rywalizacji z innymi graczami. Będą mieli też więcej swobody w wyborze swojego stylu gry.

Po trzecie, usunięcie tablisty zwiększy złożoność gry i stworzy nowe wyzwania dla graczy. Gracze będą musieli bardziej się skupić na rozwoju swoich postaci i strategii gry, aby osiągnąć sukces. To z kolei stworzy bardziej satysfakcjonujące doświadczenie gry dla tych, którzy są bardziej zaangażowani w grę.

W związku z powyższym, uważam, że usunięcie tablisty z FunnyGuilds dla Minecrafta byłoby korzystne dla naszej społeczności. Chcemy zapewnić naszym graczom jak najlepsze doświadczenie gry i zrozumieć ich potrzeby. Mam nadzieję, że nasza społeczność poprze tę decyzję.

Z poważaniem,
oskarszkot

**Comment by Rollczi** [comment]
Temat: Czy usunięcie TabListy z pluginu FunnyGuilds jest korzystne dla graczy i programistów?

Plugin FunnyGuilds to popularne rozwiązanie w grze Minecraft, które umożliwia tworzenie gildii i prowadzenie walk z innymi gildiami na serwerach. Jednym z elementów tego pluginu jest TabLista, która wyświetla informacje o graczach, takie jak nicki, poziomy czy statusy. Jednakże, w ostatnim czasie pojawiła się debata na temat tego, czy usunięcie TabListy z pluginu FunnyGuilds jest korzystne dla graczy i programistów. W niniejszej rozprawie przedstawiam argumenty za usunięciem TabListy z pluginu FunnyGuilds.

Po pierwsze, usunięcie TabListy pozwoli na zwiększenie prywatności graczy. Wielu graczy, szczególnie tych, którzy cenią sobie swoją prywatność, może czuć się niekomfortowo z faktem, że ich nicki czy poziomy są wyświetlane publicznie na serwerze. Usunięcie TabListy pozwoliłoby graczom na zachowanie swojej prywatności i koncentrację na grze, a nie na wyświetlanych informacjach.

Po drugie, usunięcie TabListy z pluginu FunnyGuilds pozwoli na zwiększenie elastyczności interfejsu gry. Bez TabListy, programiści będą mieli więcej swobody w projektowaniu i modyfikowaniu interfejsu gry, co pozwoli na lepsze dostosowanie go do potrzeb i preferencji graczy. Możliwość dostosowania interfejsu do indywidualnych potrzeb graczy jest bardzo ważna, ponieważ wpływa na doświadczenie i satysfakcję z gry.

Poza tym, usunięcie TabListy z pluginu FunnyGuilds pozwoli na optymalizację serwera. TabLista wymaga dużej ilości zasobów serwera, co może powodować spadki wydajności i przeciążenia. Usunięcie TabListy pozwoliłoby na poprawę wydajności serwera i stabilności gry.

Wnioskując, usunięcie TabListy z pluginu FunnyGuilds ma wiele zalet i korzyści dla graczy i programistów. Poprawa czytelności, estetyki, wydajności serwera, prywatności graczy oraz elastyczności interfejsu to tylko niektóre z korzyści, które przemawiają za tym rozwiązaniem.

**Comment by devangerpl** [comment]
Nie no jakieś boty tu piszą teraz naprawdę 👯 
Wiele pluginów z tablistami nie dorastają piętami do funnyguilds tablist.
Zrób cię po prostu opcję wyłącz tabliste i tyle.

**Comment by bopke** [comment]
Cześć @DevangerTM,

Chciałbym Cię poinformować, że pomimo mogę brzmieć jak robot, to jednak jestem człowiekiem i nie jestem robotem. Mogę tak brzmieć, ponieważ przez całe dnie zajmuję się dywagowaniem nad pozostawianiem lub usuwaniem poszczególnych funkcji, aby zapewnić jak najlepsze wrażenia użytkownikom. Staram się zadbać o to, aby plugin działał jak najlepiej, co wymaga dużo czasu i pracy. Plugin jest w tym momencie pełen dużej ilości funkcjonalności które wykraczają poza kompetencje pluginu na gildie, a ich utrzymanie kosztuje zespół wiele godzin pracy i utrudnia dalszy rozwój. Dobrym pomysłem może być wydzielenie funkcjonalności tablisty z pluginu funnyguilds do osobnego pluginu, który mógłby wpinać się w plugin funnyguilds i oferować te funkcjonalności tablisty.

Z poważaniem,
Bopke

**Comment by Szczurowsky** [comment]
Siema
Tablista do wyjebania, a zamiast niej użyjcie TABa.

Problem rozwiązany pora na CS'a

**Comment by P3ridot** [comment]
> Siema Tablista do wyjebania, a zamiast niej użyjcie TABa.
> 
> Problem rozwiązany pora na CS'a

Literalnie jest o tym w treści issue :trollface:

**Comment by opera2398** [comment]
w jaki sposob w pluginie TAB mozna zrobic taka tabliste jak w FG? korzystam z tego pluginu od 2 lat i wydaje mi sie ze nie jest to wykonalne

**Comment by Kamilkime** [comment]
Da się też dowolnie ustawiać sloty: https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Layout
A zawartość zrobić używając PlaceholderAPI. Jeśli dobrze kojarzę, to nawet relacyjne placeholdery działają ok

**Comment by inzynierr** [comment]
jak juz chcecie usuwac key part takiego pluginu, to najlepiej usuncie caly. pozdrawiam

**Comment by P3ridot** [comment]
Myślę, że tablista to nie jest key-part pluginu na gildie bo jest to plugin na gildie a nie na tabliste. Ta funkcjonalność zawsze było jednak dodatkowa do samego pluginu.

Co do `to najlepiej usuncie caly` to jest to już planowane. W FG 7.x plugin dokona autodestrukcji. Pozdrawiam

**Comment by Kamilkime** [comment]
> jak juz chcecie usuwac key part takiego pluginu, to najlepiej usuncie caly. pozdrawiam

To chyba jednak jest plugin na gildie, nie na TAB, a gildie zostają. Plus wszystko to, co FG robi z tabem, można spokojnie zrobić innym pluginem, np. TAB - potrafi on raczej wręcz więcej niż FG, jest na pewno lepiej aktualizowany w przypadku problemów z tabem (w FG jak się tab zepsuje, to ma on niższy priorytet), itd.

**Comment by najlex** [comment]
> jak juz chcecie usuwac key part takiego pluginu, to najlepiej usuncie caly. pozdrawiam

zatwierdzam. Pozdrawiam

**Comment by sandrwich** [comment]
Szanowni Państwo,

Chciałbym przedstawić argumenty za usunięciem funkcji tablisty z pluginu. Moim zdaniem, decyzja ta przyczyni się do rozwiązania wielu problemów związanych z kompatybilnością z tablistami z innych wtyczek.

Po pierwsze, wiele wtyczek oferuje swoje własne rozwiązania dotyczące tablist. Niestety, często te rozwiązania kolidują ze sobą i powodują problemy, które są bardzo trudne do rozwiązania. Usunięcie funkcji tablisty z FunnyGuilds oznacza, że ​​nie będzie już konfliktów z innymi wtyczkami i będziemy mieli pewność, że nasza wtyczka działa bezproblemowo.

Po drugie, funkcja tablisty jest często źródłem problemów wydajnościowych. Każda dodatkowa funkcja, która musi być wyświetlana na ekranie, wpływa na wydajność serwera. Usunięcie funkcji tablisty oznacza, że ​​serwer będzie mógł działać szybciej i obsłużyć więcej graczy.

Po trzecie, usunięcie funkcji tablisty oznacza, że ​​będziemy mieli więcej miejsca na inne funkcje. W FunnyGuilds istnieją inne funkcje, które są równie ważne, a które mogą być dodawane bez konieczności uwzględniania ograniczeń związanych z tablistą.

Podsumowując, usunięcie funkcji tablisty z pluginu FunnyGuilds jest dobrym pomysłem. Nie tylko pozwoli to na rozwiązanie wielu problemów związanych z kompatybilnością z innymi wtyczkami, ale także przyczyni się do poprawy wydajności serwera i umożliwi dodanie innych ważnych funkcji do wtyczki.

Z poważaniem,
Kukurydz

**Comment by dzikoysk** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/issues/2226
