### ISSUE TITLE
Źle wyliczany rozmiar regionu po ostatnich zmianach

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#2363]
![obraz](https://user-images.githubusercontent.com/4235722/226328051-33dbc0c1-3636-40a8-b642-17e904948f2d.png)

**Comment by P3ridot** [comment]
https://discord.com/channels/254623242914889729/278157499851341825/1087360018128568363

**Comment by P3ridot** [comment]
Po testach @insertt  wyszło, że wszystko działa poprawnie. Nikt nam też nie zgłaszał problemów z tym
