### ISSUE TITLE
Remove FunnyTelemetry feature

### ISSUE THREAD

**Issue by bopke** [FunnyGuilds/FunnyGuilds#2380]
Hi everyone,

I wanted to bring to your attention that FunnyTelemetry has been down for more than a year now, and it has been causing confusion for new users who think that it is a useful part of our software. However, the reality is that FunnyTelemetry is a broken feature that no one really cares about, and it is holding us down.

As part of our debloating initiative, it would be useful to remove FunnyTelemetry, as it is not adding any value to our software and is only adding to the confusion for new users. This will help us streamline our software and make it more user-friendly.

If anyone has any objections or concerns about this, please feel free to share them. Otherwise, I suggest that we should proceed with removing FunnyTelemetry from our software.

Thank you for your understanding.

Best regards,
Bopke

**Comment by that-apex** [comment]
No

**Comment by bopke** [comment]
Dear @that-apex,

I hope this message finds you well. As you may be aware, our project FunnyGuilds has been facing some difficulties due to a broken feature called funnytelemetry. This feature has been down for over a year and is causing confusion among new users who think it is a useful part of our software, when in fact, it is not functional and no longer serves a purpose.

As a result, we have decided to remove the funnytelemetry feature to ensure the smooth functioning of our project and to avoid further delays or errors. This is a crucial step towards achieving our business objectives and debloating our software.

We understand that deleting a feature may seem like a small matter, but it is essential for our project to continue successfully. It is imperative that we take this action as soon as possible to ensure that our project moves forward without any further hindrances.

If you have any questions or concerns regarding this decision, please do not hesitate to reach out to me directly. Your feedback and suggestions are always welcome.

Thank you for your time and understanding.

Best regards,
Bopke

**Comment by that-apex** [comment]
nie
usuwaj
ja przepisze
telemetrie
i bedzie
git
git
bedzie
spoko
bedzie
bobek
bedzie
dobrze
spoko
bedzie

**Comment by bopke** [comment]
Dear @that-apex,

Thank you for reaching out to us regarding the broken feature, FunnyTelemetry. We appreciate your interest in helping us improve our project, and we would like to inform you that we are open to considering your proposal to rewrite the feature in the future.

However, for now, we have decided to remove the FunnyTelemetry feature due to the issues it has been causing and to streamline our project. We are constantly working towards improving the quality and efficiency of our software, and this is an essential step towards achieving our goals.

We understand that you may be disappointed with our decision, but we would like to encourage you to continue to contribute to our project in other ways. We value your expertise and knowledge, and we are confident that you can bring value to our team in various other aspects.

We would also like to assure you that we are open to bringing back the FunnyTelemetry feature in the future if it is deemed necessary and beneficial for our project. We appreciate your interest and enthusiasm for our project, and we welcome any further suggestions or feedback you may have.

Thank you for your understanding and cooperation.

Best regards,
Bopke

**Comment by Rollczi** [comment]
Witajcie wszystkim,

Chciałbym poruszyć kwestię telemetrii w naszym oprogramowaniu. Telemetria odgrywa ważną rolę w zbieraniu informacji o sposobie korzystania z naszego oprogramowania przez użytkowników. Dzięki temu możemy lepiej zrozumieć potrzeby naszych użytkowników i dostosować nasze rozwiązania do ich potrzeb.

Choć FunnyTelemetry może wydawać się funkcją, która nikomu nie przeszkadza, to faktycznie dostarcza ona nam bardzo cenne informacje. Zbieranie danych z FunnyTelemetry pozwala nam na dokładniejsze zrozumienie, jakie funkcje są najczęściej wykorzystywane, a jakie są rzadziej używane lub wręcz niepotrzebne. Dzięki temu możemy zoptymalizować nasze oprogramowanie i udoskonalić je na przyszłość.

Co więcej, zostawienie FunnyTelemetry może pomóc nam w przyciągnięciu nowych użytkowników. Nowi użytkownicy, którzy jeszcze nie mają doświadczenia z naszym oprogramowaniem, mogą być bardziej skłonni do wypróbowania naszych rozwiązań, gdy zobaczą, że mamy rozbudowany system telemetrii, który pomaga nam lepiej zrozumieć ich potrzeby.

Mając na uwadze powyższe argumenty, sugeruję, abyśmy zrezygnowali z planów usunięcia FunnyTelemetry z naszego oprogramowania. Dzięki temu będziemy mieli dostęp do cennych informacji, które pomogą nam w udoskonalaniu naszych rozwiązań i przyciągnięciu nowych użytkowników.

Jeśli ktoś ma jakieś zastrzeżenia lub pytania, zachęcam do dyskusji na ten temat.

Pozdrawiam serdecznie
