### ISSUE TITLE
Opcja zmniejszenia liczby slotów na tabliście

### ISSUE THREAD

**Issue by PamuSMC** [FunnyGuilds/FunnyGuilds#2404]
Witam 
robiac TABLISTe nie potrzebuje az tyle slotow i jak mniejszyc wyswietlanie slotow te ktore pomijam 
aktualnie jest po 20 zlotow i 4 pionowe słupki a jak zrobic zeby wyswietlalo po 16 slotow na kazdy słupek

**Comment by dzikoysk** [comment]
Obecna implementacja tablisty przez wszystkie wspierane wersje nie jest przystosowana do takiej funkcji. Najwcześniej można by to było rozważyć przy jakimś większym rewrite:

* https://github.com/FunnyGuilds/FunnyGuilds/issues/2226
