### ISSUE TITLE
Kolejkowanie odświeżania scoreboard'u powoduje duże problemy z wydajnością

### ISSUE THREAD

**Issue by opera2398** [FunnyGuilds/FunnyGuilds#2405]
dummy & nametags https://prnt.sc/6jX_g-t2xxIN

  queue-configuration:
    # Co jaki czas kolejka (nametagów/dummy) powinna być odświeżana
    # Wartość podawana w tickach (1 sekunda = 20 ticków)
    # Wyższe wartości mogą powodować opóźnienia w aktualizacji nametagów/dummy, ale zmniejszają ryzyko lagów
    update-rate: 4
    
    # Maksymalna liczba update'ów w trakcie trwania jednego ticku
    # Wyższe wartości zmniejszają ryzyko opóźnień podczas aktualizacji nametagów/dummy, ale mogą powodować lagi
    max-updates-in-tick: 50

na domyslnych wartosciach jest tragedia, na tych zreszta tez (wywalcie te queue bo ona w niczym nie pomoze, tu trzeba naprawic blad ktory zaczal powodowac problemy z wydajnoscia przy odswiezaniu)

przy procku 5ghz i 100 osobach potrafia byc spadki do 10 tps, bez FG normalnie 300 osob na 20 tps

**Comment by P3ridot** [comment]
Problemem jest sprawdzanie unikalności zakolejkowanych update'ów, które przy dużej liczbie graczy zabiera ponad 40% ticku serwera (nic dziwnego skoro z każdym dodaniem do kolejki musi itertować po niej całej). Po prostu wyrzuciłem to sprawdzanie unikalności i problem powinien już się nie pojawić.

Samo queue musi zostać bo by trzeba revertować zmiany w scoreboardzie a przy tym usuwać feature'y, których już ludzie używają ¯\\\_(ツ\)_/¯. Nawet nie koniecznie feature'y a po prostu stary system działał jak chciał i nametagi/dummy potrafiły się w ogóle nie wyświetlać. Zresztą nie ma po co go usuwać bo sam w sobie jest napisany dobrze oprócz 1 prostego buga, którego dopiero nam ktoś teraz zgłosił

**Comment by P3ridot** [comment]
Dodatkowo queue musi zostać bo by trzeba revertować zmiany w scoreboardzie a przy tym usuwać feature'y, których już ludzie używają ¯\\\_(ツ\)_/¯

**Comment by opera2398** [comment]
kiedy mozna sie spodziewac wrzucenia builda?

**Comment by P3ridot** [comment]
W najnowszym Nightly 4.x problem plwinien być już rozwiązany

**Comment by opera2398** [comment]
cos build nie pyknal, moglbys zerknac?
