### ISSUE TITLE
build nie dziala

### ISSUE THREAD

**Issue by opera2398** [FunnyGuilds/FunnyGuilds#2418]
https://ci.insertt.dev/job/FunnyGuilds/job/4.x/12/

build nie dziala

**Comment by P3ridot** [comment]
Wiemy

**Comment by opera2398** [comment]
mozna prosic o jakis download gdzies indziej?

**Comment by Kamilkime** [comment]
Poczekaj po prostu, będzie niedługo naprawione

// edit: już działa https://ci.insertt.dev/job/FunnyGuilds/job/4.x/13/
