### ISSUE TITLE
Tab-complete podpowiada fake graczy z tablisty

### ISSUE THREAD

**Issue by qyczq** [FunnyGuilds/FunnyGuilds#2429]
![image](https://github.com/FunnyGuilds/FunnyGuilds/assets/120599733/b9c77249-35f0-43d4-a731-ff3f29b6c36e)

**Comment by Kamilkime** [comment]
No, wygląda że niestety nie da się z tym nic zrobić, tak już działa minecraft od 1.19.3. Jedyne co ewentualnie można zrobić to przesunąć te fake nicki na dół listy - jak by było sporo graczy na serwerze, to nie będzie ich od razu widać.
![obraz](https://github.com/FunnyGuilds/FunnyGuilds/assets/10383567/f90face9-2101-4397-93a4-2197c3748f16)

**Comment by P3ridot** [comment]
> No, wygląda że niestety nie da się z tym nic zrobić, tak już działa minecraft od 1.19.3. Jedyne co ewentualnie można zrobić to przesunąć te fake nicki na dół listy - jak by było sporo graczy na serwerze, to nie będzie ich od razu widać.

Tymczasowo można tak zrobić jednak w przyszłości można by dodać fake graczy z tablisty do teamów (ponazywanych 00, 01 etc.). To powinno pozwolić na ukrycie fake graczy przez ustawienie im pustych nicków i zachować sortowanie. Wymagałoby to jednak znacznie więcej zasobów pracy i nikt nie ma chyba tyle czasu.

**Comment by P3ridot** [comment]
W najnowszym Nightly może nie jest to naprawione, ale jest zrobione tak jak pisał Kamil - doklejamy ~ na początek aby te nicki były na samym końcu. W przyszłości zrobione to będzie teamami, ale na razie nikt nie ma na to czasu

**Comment by P3ridot** [comment]
Jednak nie da się z tym zrobić nic więcej niż dodać te `~` na początku. Może kiedyś się uda to rozwiązać jeśli zajdą jakieś zmiany w samym mc ale nie wiadomo czy kiedykolwiek coś się zmieni aby to naprawić. Takie życie i nic na to nie poradzimy
