### ISSUE TITLE
Support mysql 8

### ISSUE THREAD

**Issue by deestt** [FunnyGuilds/FunnyGuilds#2437]
Proponuje abyście zrobili jak LiteBans, support postgres mysql mariadb i h2. Ale tak jak litebans pobiera driver wtedy kiedy wybierzemy baze danych.  Unknown system variable 'transaction_isolation' taki error mi wskakuje gdy ustawiam dane do bazy danych

**Comment by Kamilkime** [comment]
To jest zgłoszenie propozycji? Czy zgłoszenie błędu? Bo nie do końca rozumiem

**Comment by deestt** [comment]
To i to.

**Comment by Kamilkime** [comment]
To proszę zrobić dwa oddzielne issue - w jednym opisać **dokładnie** błąd (wersja FG, silnika, bazy danych, jakiś stacktrace, itd.), a w drugim ładnie zaproponować jakie bazy danych i opisać zaproponowany system działania z tymi driverami.
