### ISSUE TITLE
Unknown system variable 'transaction_isolation' - latest mysql z Docker Hub

### ISSUE THREAD

**Issue by deestt** [FunnyGuilds/FunnyGuilds#2438]
https://pastes.dev/QPDtWEJVng - było tak na litebansie jak nie zmieniłem wersji drivera na najnowsza

**Comment by dzikoysk** [comment]
To problem z MariaDB & driverem MySQL. Ostatnio coraz częściej sypie podobne rzeczy  najlepszym rozwiązaniem byłoby dodać do fg po prostu oficjalny driver do mariadb i pozwolić go zmieniać w cfg.

**Comment by deestt** [comment]
To właśnie mówiłem w zamkniętym issue - #2437

**Comment by dzikoysk** [comment]
Inne db akurat wymagałyby zmian w dialekcie przy zapytaniach, bo chociażby postgres ma znaczące zmiany, ale mariadb to w dużym stopniu rozwiązanie kompatybilne. Chcesz spróbować dodać to wsparcie w PR?

**Comment by deestt** [comment]
jaka wersja 5.X czy 4.X

**Comment by P3ridot** [comment]
Można jeszcze 4.x

**Comment by deestt** [comment]
Zobaczie PR.

**Comment by P3ridot** [comment]
Powinno być już rozwiązane w najnoszym nightly 4.x w #2452
