### ISSUE TITLE
Blokada niszczenia w okolicach serca gildii

### ISSUE THREAD

**Issue by macasonhuzuni** [FunnyGuilds/FunnyGuilds#2454]
Siema ja mam takie pytanie, jest mozliwosc zablokowania niszczenia klatki z sercem gildii? wiecie te co sie tworzy z sercem.

**Comment by P3ridot** [comment]
w config.yml jest opcja `heart-configuration.interaction-protection` i tam masz opcje do ustawienia, musisz to włączyć a potem odpowiednio narożniki ustawić bo defaultowe ustawienia są zrobione pod standardowe wymiary serca
