### ISSUE TITLE
Wrap FunnyGuilds.database in Option

### ISSUE THREAD

**Issue by deestt** [FunnyGuilds/FunnyGuilds#2457]
Możliwe NullPointer w onDisable przy wyłączaniu bazy danych. Proponuję dodania zmiennych w onEnable

**Comment by P3ridot** [comment]
Fixed in #2456

**Comment by deestt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/4.x/plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java#L158 Może nie rozumiesz, mnie Option w onDisable może zwrócić nulla

**Comment by P3ridot** [comment]
No nie rozumiem, gdzieś przypisywana jest wartość null do tego fielda zamiast Option.none(), że ma zwrócić nulla? Bo nigdzie nie widzę, aby był przypisywany tam null

Bo w onDisable jest zrobione peek więc sie wykona jedynie jesli nie bedzie null

**Comment by deestt** [comment]
właśnie jest w bukkitcie ze w onEnable dasz zmienna to ci będzie działać w onDisable, miałem problem z lateinitem wlasnie i musiałem nullowe

**Comment by P3ridot** [comment]
co, to pole ma już przypisaną wartość, więc o ile nie przypiszesz mu nulla to sie NPE nie pojawi

**Comment by Rollczi** [comment]
> https://github.com/FunnyGuilds/FunnyGuilds/blob/4.x/plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java#L158 Może nie rozumiesz, mnie Option w onDisable może zwrócić nulla

W polu nie będzie nulla tylko pusty option (Option.none()), a peek() nie uruchamia się gdy option jest pusty

**Comment by deestt** [comment]
> > https://github.com/FunnyGuilds/FunnyGuilds/blob/4.x/plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java#L158 Może nie rozumiesz, mnie Option w onDisable może zwrócić nulla
> 
> W polu nie będzie nulla tylko pusty option (Option.none()), a peek() nie uruchamia się gdy option jest pusty 

Chodzi mi o to że już przy tworzeniu jest przypisane (tak jak lateinit) bukkit jakoś w onDisable te już odrazu przypisane pola daje na nulla, z onEnable jest inaczej
