### ISSUE TITLE
Ograniczenie wyswietlania liczb po przecinku przy użyciu topki KDR

### ISSUE THREAD

**Issue by jetrikx** [FunnyGuilds/FunnyGuilds#2460]
Witam Mam pytanko czy jest możliwość ograniczenia pokazywanej liczby kdr w top 10 graczy po kropce?
![image](https://github.com/FunnyGuilds/FunnyGuilds/assets/138619578/9c919d21-253c-4d43-8dd0-f2d6e5da1d80)

**Comment by dzikoysk** [comment]
Błąd naprawiony w najnowszym nightly 4.x
