### ISSUE TITLE
HP serca gildii

### ISSUE THREAD

**Issue by Zbaatt** [FunnyGuilds/FunnyGuilds#2466]
Mam propozycje odnosnie serca gildii. Mianowicie mam propozycje aby byla mozliwosc ustawienia w configu HP serca gildii np ze serce ma 100HP i kazdy 1 hit w serce przy podbijaniu 1HP w dol, zeby nie bylo tak ze serce jest na 1 hita i podczas przebity 1 hit i elo po przebicie.

**Comment by P3ridot** [comment]
Duplicate #1725
