### ISSUE TITLE
Wiadomości o zabójstwie nie wyświetlają się w konsoli

### ISSUE THREAD

**Issue by 1337kamillll** [FunnyGuilds/FunnyGuilds#2479]
nie wyświetlają się wiadomości o zabójstwie w konsoli, na chacie się wyświetlają

wersja pluginu: FunnyGuilds version 4.12.1-SNAPSHOT Snowdrop-678bf4f
wersja silnika: git-Purpur-1171 (MC: 1.16.5)

**Comment by P3ridot** [comment]
Na najnowszym Nightly problem nie powinien już występować
