### ISSUE TITLE
Use `adventure` in more places

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#2485]
Places in implement:
- [ ] TabList
- [ ] Scoreboards
  - [ ] NameTags
  - [ ] Dummy
- [ ] Holograms
- [ ] Placeholders
  -  When we implement `adventure` in every place, we could implement it in placeholders. In most cases it would be simple, but in other we could really benefit it. Example of it would be simple `/info` with info, who is owner of the guild - we could add hover text to it with info about its stats, whether is online etc.

**Comment by dzikoysk** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/issues/2226
