### ISSUE TITLE
API

### ISSUE THREAD

**Issue by macasonhuzuni** [FunnyGuilds/FunnyGuilds#2490]
Czesc, dziwne "pytanie" ale potrzebuje pomocy z API chcialem napisac plugin pod Skarbiec, ale cos nie działa gdy dodaje plik jar funnyfuilds do eclipse dodaje public class MyPlugin extends JavaPlugin {

    private FunnyGuilds funnyGuilds;
    
    @Override
    public void onEnable() {
        funnyGuilds = FunnyGuilds.getInstance();
    }
    
}
pod moj plugin i wgl i gdy chce zaimportować co kolwiek z funnyguilds np. net.dzikoysk.funnyguilds.FunnyGuilds; to jest bląd cannot be rosolved // pewnie cos zle robie ale jak mozecie to pomozcie prosze was xd

**Comment by P3ridot** [comment]
A dodałeś FG jako deendency w mavenie/gradle'u?

**Comment by macasonhuzuni** [comment]
chodzi o dodanie tego : <dependency>
  <groupId>net.dzikoysk.funnyguilds</groupId>
  <artifactId>plugin</artifactId>
  <version>4.10.2</version>
  <scope>provided</scope>
</dependency>
compileOnly "net.dzikoysk.funnyguilds:plugin:4.10.2" do pom.xml? czy zle zrozuimialem

**Comment by macasonhuzuni** [comment]
<dependency>
  <groupId>net.dzikoysk.funnyguilds</groupId>
  <artifactId>plugin</artifactId>
  <version>4.10.2</version>
  <scope>provided</scope>
</dependency>
compileOnly "net.dzikoysk.funnyguilds:plugin:4.10.2"

**Comment by macasonhuzuni** [comment]
nie wiem nie moge tu wkleic

**Comment by P3ridot** [comment]
Tak o to chodzi, dodałeś przy okazji repozytorium które również jest w README?

**Comment by macasonhuzuni** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>pl.rozrywka</groupId>
    <artifactId>funnysge</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>FunnySafe</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>

        
        <repository>
            <id>panda-repository</id>
            <url>https://repo.panda-lang.org/releases</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.17.1-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.dzikoysk.funnyguilds</groupId>
            <artifactId>plugin</artifactId>
            <version>4.12.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>

**Comment by macasonhuzuni** [comment]
tak ma wygladac pom?

**Comment by macasonhuzuni** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>pl.rozrywka</groupId>
    <artifactId>funnysge</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>FunnySafe</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>panda-repository</id>
            <url>https://repo.panda-lang.org/releases</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.17.1-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.dzikoysk.funnyguilds</groupId>
            <artifactId>plugin</artifactId>
            <version>4.12.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>

**Comment by P3ridot** [comment]
Masz dodane złe repozytorium panda, w README jest podane nowe a ty używasz starego które nie dziala

**Comment by P3ridot** [comment]
oraz jakiego IDE używasz?

**Comment by macasonhuzuni** [comment]
uzywam Intelij mogbys mi na dc jakos pomoc? szybciej by bylo

**Comment by P3ridot** [comment]
Wejdź na discorda FG: https://bukkit.pl

**Comment by P3ridot** [comment]
Rozwiązane na [Discordzie](https://discord.com/channels/254623242914889729/278157499851341825/1143891915515908126)
