### ISSUE TITLE
Tablist broken in latest version

### ISSUE THREAD

**Issue by Incluuu** [FunnyGuilds/FunnyGuilds#2516]
![image](https://github.com/FunnyGuilds/FunnyGuilds/assets/67196311/5308f91f-b41d-4b63-96b1-539a874bf9c1)

**Comment by dzikoysk** [comment]
Fixed in https://github.com/FunnyGuilds/FunnyGuilds/commit/48646b0dadc68ad4bf7fe7693fd85d6511131d40
