### ISSUE TITLE
Migajaca tabela

### ISSUE THREAD

**Issue by KARAKANY** [FunnyGuilds/FunnyGuilds#2527]
Hejka! Dzisiaj zainstalowałem plugin FunnyGuilds na swoim serwerze i zauważyłem pewien błąd dotyczący wyświetlania wyników. Otóż, wszystko działa poza tym,ze  chwilowo, na tabie pojawia sie komunikat "Wiadomości braku (pokazuje się, gdy gracz nie ma gildii) można to zmienić w pliku messages.yml". Dodatkowo, chciałbym wspomnieć, że nawet po utworzeniu gildii ten błąd nie znika.

https://github.com/FunnyGuilds/FunnyGuilds/assets/75690251/40ac1d15-9f75-4e8d-9575-a1992ffbe0d1

Dla jasności, informuję, że plik "rar" powstał dopiero teraz, aby naprawic ewentualne problemy, proszę nie zwracać na niego uwagi.

**Comment by insertt** [comment]
Zbyt mało informacji, ale wygląda na to, że jakiś dodatkowy plugin również próbuje wysłać tablistę do gracza co powoduje ten efekt.
