### ISSUE TITLE
Dodać wsparcie dla silnika Folia 1.20.x

### ISSUE THREAD

**Issue by tenfajnybartek** [FunnyGuilds/FunnyGuilds#2540]
Tak jak w temacie ^

**Comment by P3ridot** [comment]
Nie dodamy bo codebase na to nie pozwala i w projekcie jak ten ti wiecej niż zrobienie wrappera na scheduler

A poza tym to jeśli używasz Folii (silnika na ogromne serwery, na których grają setki, a nawet tysiące graczy) to musisz mieć i tak własnych programistów, więc niech oni ci ogarną, a najlepiej napiszą dedykowany plugin na gildię pod Folie

Decyzja nasza się nie zmieni, chyba że wydarzy się cud i będzie sens dodawać support dla Folii
