### ISSUE TITLE
Komendy z pluginu nie działają

### ISSUE THREAD

**Issue by vejder** [FunnyGuilds/FunnyGuilds#2546]
Witam 
Mam problem z pluginem minecraft funnyguilds
Nie mogę założyć gildii, wpisuje /zaloz tag nazwa
i nie wyświetla sie nic. Mam przy sobie itemy na gildie. 
- wersja serwera spigot 1.17.1
- wersja pluginu funnyguilds 1.17.1
- mam pare innych pluginów (19) na serwerze
- w configu zmieniałem dosłownie 10 linijek wszystko wydaje sie dobrze działać
Proszę o poradę

**Comment by Kamilkime** [comment]
Przydałby się jeszcze latest.log z serwera w takim razie, bo pewnie tam znajdziemy jakiś problem

**Comment by vejder** [comment]
> Przydałby się jeszcze latest.log z serwera w takim razie, bo pewnie tam znajdziemy jakiś problem

W sensie  config czy błąd który wyskakuje bo nie ogarniam

**Comment by Kamilkime** [comment]
No logi z serwera podeślij, najlepiej cały latest.log

**Comment by P3ridot** [comment]
Brak logów, więc zamykam dopóki nikt ich nie podeśle
