### ISSUE TITLE
Komendy z pluginu nie działają

### ISSUE THREAD

**Issue by Quejti** [FunnyGuilds/FunnyGuilds#2547]
Witam, mam problem z pluginem próbuję wpisać /g /zaloz nic z tych komend nie działa plugin pokazuje się na zielono serwer jest na wersję 1.20.4 wie ktoś jak to naprawić?
![image](https://github.com/FunnyGuilds/FunnyGuilds/assets/160282068/1d1c8fbe-8954-4fbc-967f-7f3adaf4b7ad)

**Comment by Kamilkime** [comment]
Przydałby się jeszcze latest.log z serwera w takim razie, bo pewnie tam znajdziemy jakiś problem

**Comment by P3ridot** [comment]
Może ktoś przekonfigurował plugin, aby używał innych komend?

**Comment by P3ridot** [comment]
Prawdopodobnie relates do #2546
