### ISSUE TITLE
Czy to będziesz jeszcze aktualizował? Jesli..

### ISSUE THREAD

**Issue by TheAzaveR** [FunnyGuilds/FunnyGuilds#374]
Jesli tak, to dodasz AntyLogout?
No i czy będziesz aktualizował do wersji 1.10/1.11.X? (lub wogle do innych)

**Comment by wvffle** [comment]
Wersja czwarta jest pisana pod najnowsza wersje gry.

**Comment by dzikoysk** [comment]
Tak jak mówi @wvffle, FunnyGuilds 4.0 będzie pisane pod najnowsze wersje. Jako że jest pisane od nowa, to raczej anty logout od razu się nie pojawi, ale mamy to w planach :)

**Comment by kszysztof-a** [comment]
Fajnie byłoby zobaczyć też /skarbiec ;)

**Comment by wvffle** [comment]
zrob nowy issue i wytlumacz dokladnie @kszysztof-a ;p

**Comment by TheMolkaPL** [comment]
@wvffle Chodzi o to, aby poprzez komendę mieć dostęp do wirtualnego ekwipunku, do którego będą mieli dostęp wszyscy członkowie gildii. Ekwipunek jest zapisywany, więc przedmioty nigdy nie są w nim stracone. Osobiście myślę, że to ciekawa idea, ale powinny być z nim jakieś utrudnienia, aby była z tym ciekawa rozgrywka. Na przykład, aby taki skarbiec miał swojego reprezentera w postaci rzeczywistej skrzyni na terenie gildii, którą może zniszczyć ktoś spoza tej gildii. Dzięki temu istnieje zawsze ryzyko utracenia tych przedmiotów.

Dodatkowo może istniałaby blokada dostępu do skarbca, gdy ten (rzeczywista skrzynia) znajduje się zbyt daleko gracza/
