### ISSUE TITLE
Wyrzucanie gracza przy kliknięciu na kryształ kresu

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#375]
Mam podłączony serwer pod bungeecord i gdy ktoś kliknie na kryształ kresu to wyrzuca go na lobby. W logach bungeecorda znalazłem to: https://hastebin.com/pasiwaheho.lua

**Comment by dzikoysk** [comment]
Tak sobie przeglądam tematy z tym błędem i z tego co się zdążyłem zorientować, to w kilku przypadkach pomaga zmiana wersji bungee. 

Co do samego błędu, to niestety nie jestem w stanie teraz powiedzieć co jest przyczyną. Jak możesz, to jeszcze podaj listę wszystkich pluginów.

**Comment by kamcio96** [comment]
Silnik 1.7 czasami potrafi wysłać pusty pakiet, co jest poważnym błędem. Chyba nikt nie wskazał konkretnego miejsca gdzie, to się dzieje. FG korzysta z nms, więc ciężko będzie to fixnac. Czekajmy na updaty wersji :D
To co mówi dziki, Waterfall chyba pozwala akceptować puste pakiety :wink:

**Comment by FastJoe0** [comment]
Ech... sprawdzałem najnowsze wersje ale dalej wyrzuca. Jak usunąłem plugin ChatControl to bug już nie występował ale typek od tego pluginu mówi że jego plugin nie ingeruje w kryształy kresu (to by się zgadzało bo w końcu ChatControl to plugin od czatu). Mógłby mi ktoś wytłumaczyć czemu tak się dzieje? Co właściwie się robi gdy ktoś kliknie na ten kryształ?

**Comment by dzikoysk** [comment]
Gdy klikasz w kryształ, to klient wysyła packet o tym zdarzeniu. FG go sobie później wyłapuje.

 Tak jak mówi kamcio, nikt nie wskazał konkretnie miejsca, gdzie ten błąd powstaje. Ja na to za specjalnie wpływu też nie mam, tym bardziej, że przy kliknięciu w kryształ to klient wysyła ten packet.

**Comment by kamcio96** [comment]
proponuje wykorzystać event zamiast pakietów do tego

**Comment by dzikoysk** [comment]
Nie jestem od dawna w temacie, ale coś mi się kojarzy, że dla fake entity eventy raczej niespecjalnie miały sens.

**Comment by FastJoe0** [comment]
W sensie, że taki sam by błąd występował? Jeśli nie jesteś pewien to sprawdź, może się uda.

**Comment by dzikoysk** [comment]
To akurat bez związku, bo błąd o którym mówisz pojawia się wcześniej i nie dotyczy tego sposobu.

**Comment by FastJoe0** [comment]
No to co. W nowej wersji to naprawisz czy jest to błąd którego nie da się za skarby świata naprawić ;)?

**Comment by dzikoysk** [comment]
Błąd nie dotyczy FG, więc nie jestem w stanie go naprawić. Zmieniałeś wersję bungee w końcu?

**Comment by FastJoe0** [comment]
Zmieniłem ale to nic nie daje. Teraz się dowiedziałem że nawet gildii nie można podbić.

**Comment by TheMolkaPL** [comment]
> Silnik 1.7 czasami potrafi wysłać pusty pakiet, co jest poważnym błędem.

Wynika z tego to, że jest to błąd związany z silnikiem, a nie z FunnyGuilds. Wydaje mi się, że w związku z tym ten issue można zamknąć.
