### ISSUE TITLE
Problem z sojuszami

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#376]
Dostałem właśnie zgłoszenie od graczy o dość poważnym bugu. Mianowicie, gdy gildia A nawiąże sojusz z gildią B przez jakiś czas wszystko jest ok (prawdopodobnie do restartu serwera) a potem w opisie gildii (/info) B nie ma sojuszu z gildią A, ale za to w opisie gildii A jest sojusz z gildią B. To nie jest bug wizualny, ponieważ gildia B może bić gildię A, a już gildia A nie może bić gildii B. Nie jest to też przypadek, ponieważ parę gildii już doświadczyło podobnego problemu.

Wersja pluginu: 3.9.9.5

**Comment by ProgrammingWizzard** [comment]
@FastJoe0 czy wcześniej ten błąd występował? Teraz wgrałem sobie 1.7.10 i obecną wersje gildii, jednak takiego błędu nie uświadczyłem na localhoście. Jeżeli też możesz, to podaj rodzaj zapisu danych - być może tam jest jakiś problem.

**Comment by FastJoe0** [comment]
Czy występował na poprzednich wersjach to nie wiem. Raczej pewnie nie bo nikt mi nie zgłaszał błędu. Korzystam z MySQL

**Comment by dzikoysk** [comment]
Musiał występować, bo nic się od dawna w sojuszach nie zmieniało

**Comment by ProgrammingWizzard** [comment]
@FastJoe0 ano widzisz, ja testowałem na FLAT i u mnie błąd nie występował. Czyli pewnie zawinił zapis do bazy.

**Comment by FastJoe0** [comment]
@dzikoysk naprawiłbyś ten błąd w najbliższym czasie czy nie dasz rady? Nie chciałbym specjalnie przechodzić na flat teraz.

**Comment by FastJoe0** [comment]
Projekt został ponownie porzucony czy jak? @dzikoysk daj chociaż odpowiedź, że robisz coś z tym lub że po prostu teraz (lub nigdy :P) nie masz na to czasu ;).

**Comment by TheMolkaPL** [comment]
Po części porzucony. Jest zbyt mała aktywność po ostatniej aktualizacji.

**Comment by FastJoe0** [comment]
OK, to może pomóc w naprawieniu tego buga. Logi - https://hastebin.com/zegijiqeki.md

@dzikoysk zerknij na to :D

**Comment by dzikoysk** [comment]
Spróbuj wersji 3.9.9.6

**Comment by sokrates1231** [comment]
W 3.9.9.7 poprawione sojusze ;) Testowane.
