### ISSUE TITLE
Problem z TabListą

### ISSUE THREAD

**Issue by Mialw** [FunnyGuilds/FunnyGuilds#379]
Siemka.

Piszę tu, ponieważ mam problem z tablistą. Otóż wgrywałem różne wersje pluginu FunnyGuilds i wszystko dobrze działało oprócz tablisty. Próbowałem różnych sposobów ale dalej tablista buguje się. Nie mam zielonego pojęcia jak to naprawić i proszę Was o pomoc.

Screenshot tablisty:
![2017-02-03_20 06 14](https://cloud.githubusercontent.com/assets/25535996/22604534/54b630aa-ea4c-11e6-9bf7-c107873f3e16.png)

http://pastebin.com/L5qabqKB

**EDIT** Przeniosłem `config.yaml` na Pastebin. /TheMolkaPL

**Comment by kamcio96** [comment]
Następnym razem config na pastebin pls. Tablista na 1.8+ nie działa poprawnie

**Comment by Mialw** [comment]
kamicio96, ale ja posiadam serwer na 1.7.2

**Comment by artur9010** [comment]
Używasz starego gówna i liczysz na wsparcie?

**Comment by wvffle** [comment]
```
Bloczek code :<
```

**Comment by dzikoysk** [comment]
Zmień kodowanie configu na UTF-8

**Comment by kamcio96** [comment]
@artur9010 mogę podjebac ten tekst? ;D

Ustaw 60 lub więcej slotów, bo masz za małego taba

**Comment by Mialw** [comment]
@kamcio96 dzięki,  już działa :D
