### ISSUE TITLE
Problem integracji pluginu z PerWorldPlugins

### ISSUE THREAD

**Issue by Sixsenior** [FunnyGuilds/FunnyGuilds#381]
Witam.
Mam pytanie czy da się tak skonstruować ten plugin aby plugin perworldplugins mógł go zblokować.
Na dzień dzisiejszy plugin perworldplugins wykrywa funnyguilds ale nie blokuje  skonfigurowaniu pliku config.yml. inne pluginy blokuje normalnie, tylko tego nie. próbowałem różnych wersji perworldplugins i funnyguilds ale nic to nie dało.
HHHHHEEEELLLLPPPP!!!!!!!!!!

**Comment by ProgrammingWizzard** [comment]
A można wiedzieć, po co Ci to potrzebne?

**Comment by Sixsenior** [comment]
Mam kilka światów i chciałbym zablokować gildie aby nie można było zakładać ich na każdej mapie.

**Comment by ProgrammingWizzard** [comment]
Póki nie działa integracja z tym pluginem, proponuje zamienne rozwiązanie. Spróbuj na danym świecie, za pomocą WorldGuarda zrobić flagę o nazwie "__global__", i zablokuj w niej komendy dot. FG. Efekt osiągniesz ten sam, a to rozwiązanie będzie zastępcze, dopóki @dzikoysk nie wprowadzi takowej blokady światów w najnowszej aktualizacji.

**Comment by ProgrammingWizzard** [comment]
@Sixsenior dokładnie opisane masz to tutaj: [click](https://worldguard.enginehub.org/en/latest/regions/global-region/)

**Comment by Sixsenior** [comment]
Dzięki będę próbował.

**Comment by gabixdev** [comment]
Możesz po prostu usunac permisje...
`/pex group gracz add -funnyguilds.* swiat`

**Comment by Sixsenior** [comment]
Witam.
Poradziłem sobie z globalnymi flagami. w Permission wpisywałem ujemne permisje ale po odpaleniu wpisaniu /pl zaznaczały się na czerwono. Sprawdzałem dziesiątki razy czy nie ma tam tabulatora, za dużo spacji czy jeszcze jakiś innych błędów i nic. po usunięciu ujemnej permisji wszystko grało. 
Ogólnie temat do zamknięcia, jednak gdyby  **@dzikoysk** chciał poprawić na tyle plugin by współgrał z Perworldpermisions był bym wdzięczny.

**Comment by ProgrammingWizzard** [comment]
Zostawiam otwarte, bo jednak to jest drobny błąd, który można naprawic :)

**Comment by ProgrammingWizzard** [comment]
Będzie dostępne w najnowszej aktualizacji.
