### ISSUE TITLE
Funny guilds crashuje serwer.

### ISSUE THREAD

**Issue by NNorbertPL** [FunnyGuilds/FunnyGuilds#382]
Witam, mam następujący problem. Co jakiś czas pojawiają się problemy z FunnyGuilds. Poprostu zaczyna NAGLE lagować cały serwer.. Pomaga jedynie jego unloadowanie/zreloadowanie (plugman reload FunnyGuilds). Lecz za jakiś czas znów się to robi. Wydaje mi się że to może być zamierzone działanie jakiegoś gracza (??? crasher ???)
https://timings.spigotmc.org/?url=faradojoyo
[18:33:37 INFO]: NNorbertPL issued server command: /plugman reload FunnyGuilds
[18:33:37 INFO]: [FunnyGuilds] Disabling FunnyGuilds v3.9.9.1 Cleaned
[18:33:40 INFO]: [FunnyGuilds] Enabling FunnyGuilds v3.9.9.1 Cleaned
[18:33:40 INFO]: [FunnyGuilds] Available Processors: 8
[18:33:40 INFO]: [FunnyGuilds] Active Threads: 97
[18:33:49 INFO]: [FunnyGuilds] Loaded users: 9621
[18:33:49 INFO]: [FunnyGuilds] Loaded regions: 483
[18:33:49 INFO]: [FunnyGuilds] Loaded guilds: 484
[18:33:49 WARN]: [FunnyGuilds] Repaired conflicts: 1
(Tak wiem mam wersje 3.9.9.1, ale na 3.9.9.5 dzieje się to samo.) Jakieś pomysły??

**Comment by dzikoysk** [comment]
No to używaj 3.9.9.5, bo tam już kilka poprawek weszło. 

Tia, ktoś chyba wysyła na prawdę sporo packetów przechodzących przez ten listener. Trzeba by jakiś checker tam wstawić
![ss](https://panda-lang.org/screenshot/pxqv634R.png)

**Comment by NNorbertPL** [comment]
Znalazłem timing z wczoraj jeszcze https://timings.spigotmc.org/?url=butesucaxo tu widać 6x większą wartość od tej. Będziesz w stanie to naprawić?

**Comment by NNorbertPL** [comment]
Znowu się to stało. Spamuje też takie coś http://pastebin.com/K4s9dfME

**Comment by dzikoysk** [comment]
To jedna z tych rzeczy, która została poprawiona w 3.9.9.5

**Comment by NNorbertPL** [comment]
Tylko że przejście z 3.9.9.1 do 3.9.9.5 jest możliwe podczas normalnej edycji? Kolega mówił ze się resetuje config. I nie wiem czy bez problemów mogę przejść.

**Comment by dzikoysk** [comment]
Tak, wszystko powinno być ok. Możesz sobie na wszelki wypadek zrobić backup configu

**Comment by NNorbertPL** [comment]
Ok, udało się zmienić wersję. Pod wieczór napiszę czy problem nadal występuje.

**Comment by dzikoysk** [comment]
Wgraj wersję 3.9.9.6, powinno być lepiej

**Comment by NNorbertPL** [comment]
Dalej, otwarłem nowy temat.
