### ISSUE TITLE
Blad z sojuszamy przy MYSQL

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#383]
Witam, 
Nadal istnieje blad z sojuszami przy MYSQL.
Po restarcie serwera usuwa sie sojusz w gildii która akceptuje sojusz.
Widzialem przed chwila napisales zeby spr. 3.9.9.6, ale nadal istnieje ten blad. 
Wersja najnowsza: 3.9.9.6
Blad: http://screenshot.sh/m1UI4VwIa6xt3

**Comment by dzikoysk** [comment]
Wiesz co, zerkałem nawet na miejsce gdzie są te sojusze i wszystko wydawało mi się być w porządku. Nie sypie Ci coś w konsoli?

**Comment by sokrates1231** [comment]
Bledow nie ma, wszystko dodaje(sojusz) w mysql, a po restarcie usuwa się sojusz w gildii która zaakceptowała sojusz.

**Comment by dzikoysk** [comment]
Jesteś mi w stanie sprawdzić, czy na zapisie flat też występuje ten błąd?

**Comment by sokrates1231** [comment]
Sprawdzilem i dziala poprawnie.

Tylko przy mysql jak na kazdej innej wersji jest blad z sojuszami.

**Comment by dzikoysk** [comment]
Oki, a możesz sprawdzić w bazie, czy w tabelce z gildiami w "allies" wpisane są te gildie?

**Comment by sokrates1231** [comment]
Pisalem, po restarcie jest ze usuwa sojusz gildii ktora zaakceptuje sojusz(http://screenshot.sh/n9KRHokeYrUOD)

Przed restartem byly gildie w tabeli, a po restarcie nagle zniknela :D

**Comment by dzikoysk** [comment]
Tak, tylko mi chodziło o złapanie momentu kiedy ten wpis znika - ułatwi szukanie :P 
Nawiąż sojusz, wyłącz serwer, nie włączaj i powiedz, czy wtedy ta gildia tam jest Bo być może źle odczytuje dopiero przy starcie i w tedy ją wcina

**Comment by sokrates1231** [comment]
Masz racje gildie po wylaczeniu(serwer jest off) i sojusze sa: http://screenshot.sh/oB2DoqQWPjEGD

Czyli cos po starcie serwera nie wczytuje sojuszu.

**Comment by dzikoysk** [comment]
Chyba wiem czemu to nie działa. Gildie się jeszcze nie załadowały wszystkie i po prostu pomija te, których jeszcze nie ma. 

To jest serio bardzo poważny bug o.O Dziwię się, że jeszcze nikt krzyczał po takim czasie

**Comment by sokrates1231** [comment]
Dasz rade poprawic? Jesli tak, to na kiedy?

**Comment by dzikoysk** [comment]
Dobra, na szybko ale powinno być ok, później (kiedyś tam) się to zrobi sensowniej. Sprawdź czy teraz na tej Ci się wszystko zapisuje

https://funnyguilds.net/download/cleaned/3.9.9.7/funnyguilds-3.9.9.7.jar

**Comment by sokrates1231** [comment]
dam znac do 19? ok?

**Comment by sokrates1231** [comment]
chwilowo dziala za chwile zalozymy kilka gildii i kilka sojuszow, zobacze wtedy co dzieje sie ;).

**Comment by sokrates1231** [comment]
OK DZIALA ;). Dziekuje.
