### ISSUE TITLE
Serwer nadal się crashuje!

### ISSUE THREAD

**Issue by NNorbertPL** [FunnyGuilds/FunnyGuilds#384]
Witam, upgrade do wersji 3.9.9.5 nie pomógł tak jak mówiłeś. (Teraz dałem już 3.9.9.6 bo widze że jest)
https://timings.spigotmc.org/?url=qubasubite

**Comment by NNorbertPL** [comment]
Po wgraniu 3.9.9.6 niby się ogarnęło (za krótko by mówić ze napewno) ale przez jakiś czas spadało do 16 TPS.
PS. To napewno nie od innych pluginów raczej. Na starcie było 250 graczy, a potem grało przez dluzszy czas po 200 i było OK :/ do czasu.

**Comment by dzikoysk** [comment]
Skoro crashuje, to daj log.

Spróbuj tej wersji:
https://funnyguilds.net/download/cleaned/3.9.9.7/funnyguilds-3.9.9.7.jar
Jeżeli znowu wysypie, to nie wina fg

**Comment by NNorbertPL** [comment]
Zle napisałem, nie crashuje się tylko się robią lagi jak wcześniej. I zauważyłem że użycie ramu (normalnie 3-4gb) wzrasta wtedy do 7-9gb

**Comment by dzikoysk** [comment]
Parę rzeczy, sprawdź czy nie wariuje

**Comment by sokrates1231** [comment]
Dzikoysk purse laguje od tablisty, dzikoysk ja anazliowałem to i nawet tablista od kamcia laguje ;).

**Comment by dzikoysk** [comment]
"Purse"?

**Comment by sokrates1231** [comment]
purse albo parse

**Comment by dzikoysk** [comment]
To tu bez związku tak czy inaczej. Packety stoją na tym evencie, więc go wywaliłem, niech zobaczy jak sytuacja ma się na tej wersji, którą dałem wyżej

**Comment by sokrates1231** [comment]
3.9.9.7 sprawdz kumplu :D

**Comment by NNorbertPL** [comment]
3.9.9.7 wgrane! Zobaczymy, miejmy nadzieje ze bedzie OK.

**Comment by sokrates1231** [comment]
NNorbertPL i jak?

**Comment by NNorbertPL** [comment]
Narazie jest OK. Albo naprawiło się albo nikt nie atakuje, lecz zauważyłem wyższe używanie ramu, obecnie jest zużyte 9GB a normalnie bylo po 3GB. Nic poza funnyguilds nie zmieniałem. - Nie wiem czy to ma coś wgl związane z FunnyGuilds. Ale RAMU pod dostatkiem, potężny dedyk.

**Comment by sokrates1231** [comment]
i jak? Bledy sa?

**Comment by NNorbertPL** [comment]
Wszystko śmiga jak narazie pięknie.
