### ISSUE TITLE
Blad z waznoscia gildii

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#385]
W configu mam ustawione tak: 
# Jaka waznosc ma gildia po jej zalozeniu
validity-start: 14d
# Ile czasu dodaje przedluzenie gildii
validity-time: 14d
# Ile dni przed koncem wygasania mozna przedluzyc gildie (wpisz 0, jezeli funkcja ma byc wylaczona)
validity-when: 14d
# Koszt przedluzenia gildii
validity-items:
- 10 diamond

Opłaciłem, a gdy próbuje 2 raz: http://screenshot.sh/m8U4gjjGS0XVx

ze niby za 27 dni... Jak mi za 27 dni gildia wygasa xDDD

**Comment by dzikoysk** [comment]
To na szczęście błąd tylko w wiadomości, będzie poprawiony w oficjalnym 3.9.9.7

**Comment by sokrates1231** [comment]
to czekam na poprawki ;3
