### ISSUE TITLE
Dzikoysk

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#387]
Siema dzikoysk mam interes moge jakis do cb kontakt?

**Comment by GotoFinal** [comment]
Wiesz że możesz jak człowiek wejść na jego profil na githubie i napisać na maila tam podanego zamiast spamic zbędnym issue?

**Comment by sokrates1231** [comment]
GotoFinal mozesz wejsc na gg? :) Szybki interes = przelew git.

**Comment by GotoFinal** [comment]
Nie używam już gg

**Comment by sokrates1231** [comment]
zerknij meila
