### ISSUE TITLE
Komunikaty na czacie

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#388]
Witam, od jakiegos x czasu nie dzialaja poprawnie komunikaty.
Admini je widzą: http://screenshot.sh/n7YyWOrCvUy2j
Mimo to że mają permisje: funnyguilds.player
Gracze tych komunikatów nie widzą.

**Comment by Inuun** [comment]
Takie dziwne rzeczy potrafi powodować ujemne uprawnienie -bukkit.* i inne podobne, nie masz przypadkiem takiego?

**Comment by sokrates1231** [comment]
Wystarczyło usunąć u gracza " -bukkit.* " i działa, dzięki <3

**Comment by piratjsk** [comment]
To ja tak tylko wyjaśnię dlaczego tak się dzieje, bo to nie do końca są 'Takie dziwne rzeczy'.

Odmówienie graczom wszystkich uprawnień zaczynających się od `bukkit.` odmawia im między innymi uprawnienia `bukkit.broadcast.user`, które jest odpowiedzialne za możliwość widzenia wiadomości wysyłanych za pomocą metody [`broadcastMessage(String message)`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Server.html#broadcastMessage(java.lang.String)) z `org.bukkit.Server` (czyli metody [`broadcast(String message, String permission)`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Server.html#broadcast(java.lang.String,%20java.lang.String)) gdzie `permission` ma [wartość](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Server.java#70) `org.bukkit.Server.BROADCAST_CHANNEL_USERS`). Metoda ta jest też wywoływana przez komendy `/me` i `/say` (czyli blokując wszystkie uprawnienia `bukkit.*` blokujesz graczom też możliwość widzenia wiadomości wysyłanych za pomocą tych komend).

Więc jeśli chcesz, to nadal możesz blokować uprawnienia `bukkit.*` musisz tylko odblokować pojedyncze uprawnienie `bukkit.broadcast.user`.

Można też w FunnyGuilds podmienić wykonania metody `broadcastMessage(String message)` na `broadcast(...)` z uprawnieniem (np. `funnyguilds.player`) wtedy nawet jak ktoś zablokuje graczom uprawnienia `bukkit.*` to wiadomości będą się wyświetlać (pod warunkiem, że gracze będą mieli uprawnienie `funnyguilds.player`). Najfajniej byłoby chyba dodać uprawnienia typu `funnyguilds.create.notify`, rozwiąże to wspomniany tutaj problem i pozwoli na większą kontrolę nad komunikatami wyświetlanymi przez FG.
