### ISSUE TITLE
Plugin spami w konsoli, pomocy!!

### ISSUE THREAD

**Issue by KamperTV** [FunnyGuilds/FunnyGuilds#389]
[FunnyGuilds] Task #-1648215162 for FunnyGuilds v3.9.9.1 Cleaned generated an exception
java.lang.NullPointerException

Wersja pluginu: FunnyGuilds Cleaned (#3.9.9.4)

Silnik serwera: Spigot 1.7.10-R0.1 (1.7.2, 1.7.4, 1.7.5, 1.7.9, 1.7.10)

Wersja javy serwera: 8

I tab jest pusty i nic na nim nie ma a jest poprawnie skonfigurowany w 100%

Logi z konsoli: http://pastebin.com/ppmk89wc

Wygląd taba: http://screenshot.sh/mK9M7uxZs1PEV

Config taba: http://pastebin.com/w5zrGMma

**Comment by Inuun** [comment]
> v3.9.9.1

Wgraj najnowszą wersję.

**Comment by KamperTV** [comment]
@Inuun A da się przenieść graczy, gildie i regiony gildii na najnowszą wersje?

**Comment by Inuun** [comment]
Tak, nie powinno być problemów. W razie czego możesz zrobić backup ;)

**Comment by KamperTV** [comment]
@Inuun Ale jak wklejam dokładnie cały tab do najnowszej wersji to wyświetla się że całe formatowanie zostanie usunięte.

**Comment by dzikoysk** [comment]
Nie wiem co robisz, ale robisz to źle. Przejrzyj na spokojnie domyślny config i porównaj go ze swoim, pewnie coś masz źle

**Comment by KamperTV** [comment]
@dzikoysk A jak wstawię cały plik config.yml na pastebin to powiesz mi co mam źle?

**Comment by Inuun** [comment]
@KamperTV sprawdz najpierw na http://www.yamllint.com/

**Comment by KamperTV** [comment]
@Inuun Wklejam cały config to pisze, że "Valid YAML"

**Comment by KamperTV** [comment]
@Inuun @dzikoysk Tutaj macie mój cały plik config.yml z mojego serwa http://pastebin.com/fQAvWPby
Powiedzcie co jest źle

**Comment by Inuun** [comment]
Wygląda normalnie. Jedynie player-list-ping: 9999 to dość duża wartość, przy 1000 powinien być podobny efekt. Ale to raczej nie jest przyczyną. Podaj logi ze startu serwera.

**Comment by KamperTV** [comment]
@Inuun Logi ze startu serwera: http://pastebin.com/qPALF6HB
Captcha bo długie są

**Comment by Inuun** [comment]
Poza kradzionymi pluginami widzę niezaktualizowane FunnyGuilds. Wgraj najnowszą wersję pluginu..

**Comment by KamperTV** [comment]
@Inuun Ok.

**Comment by ProgrammingWizzard** [comment]
@KamperTV odinstaluj Skripta, to zawsze działa.
