### ISSUE TITLE
Asysty

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#390]
Witam.
Mam kilka propozycji, a czy ogólnie w FunnyGuilds będą dodawane jakies nowe dodatki/zmiany?
Np. 1 propozycja jest dodanie ASYST
Zeby mozna bylo dodac wiecej zmiennych w /gracz i /info(np. rozmiar cuboida, czy mozna atakowac gildie)

Jak dziala ochrona 48h w gildii, zauwazylem ze wybuchaja creepery jak zablokowac ich eksplozje?

**Comment by sokrates1231** [comment]
ref

**Comment by Inuun** [comment]
Z mpc przyszedłeś, że odświeżasz issues?

> Jak dziala ochrona 48h w gildii, zauwazylem ze wybuchaja creepery jak zablokowac ich eksplozje?
Dopisz sobie swój addon do fg 🐼
