### ISSUE TITLE
Aktualizacja?

### ISSUE THREAD

**Issue by xMrJoint** [FunnyGuilds/FunnyGuilds#395]
Witam,
Czy istnieje możliwość przeniesienia pluginu na wyższe wersje (najlepiej 1.11.2)?

**Comment by ProgrammingWizzard** [comment]
@dzikoysk

**Comment by kamcio96** [comment]
możliwość jest, chęci i czas już mniej :v

**Comment by TheMolkaPL** [comment]
Plugin powinien działać na najnowszej wersji. Chyba, że Spigot coś znowu popsuł (jak zawsze) i teraz coś się stypie. Jak będziesz miał błędy w konsoli to je pisz w [nowym issue](https://github.com/FunnyGuilds/FunnyGuilds/issues/new). ;)
