### ISSUE TITLE
Aktualizacja #2

### ISSUE THREAD

**Issue by xMrJoint** [FunnyGuilds/FunnyGuilds#396]
Witam,
Wcześniej stworzyłem temat, ale został on zamknięty, więc tworze nowy.
Błędy:
http://pastebin.com/ysfH2Um0

Cel: próba włączenia pluginu na najnowszej wersji MC.

**Comment by dzikoysk** [comment]
```[15:36:19] [Server thread/INFO]: This server is running Paper version git-Paper-1063 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)```

Plugin jest pod 1.7.x, tak jak pisze w wymaganiach:
![img](https://panda-lang.org/screenshot/mjrViPdp.png)
