### ISSUE TITLE
Aktualizacja #3

### ISSUE THREAD

**Issue by xMrJoint** [FunnyGuilds/FunnyGuilds#397]
Piszę ponownie, kolejny raz zakładam temat z zapytaniem kiedy będzie aktualizacja do najnowszej wersji gry, osoba TheMolkaPL zamknęła mój pierwszy temat z zapytaniem kiedy będzie aktualizacja do 1.11.2.
Więc ponawiam pytanie kiedy będzie aktualizacja do 1.11.2? #Dzikoysk Nie zamykaj tematów, gdy problem nie został rozwiązany, proszę Cie bardzo. Nie chce po raz czwarty zakładać tego samego tematu.

**Comment by TheMolkaPL** [comment]
Aktualizacja będzie wtedy gdy ktoś będzie miał ochotę go zaktualizować. Jeżeli byłaby to aktualizacja do kolejnych wersji Minecrafta, to bardzo duże prawdopodobieństwo, że bazowałaby ona na obecnym kodzie pluginu.

Spigot usunął z API Bukkita metodę getOnlinePlayers(), która zwracała Player[]. Jest to ich wina bo **wszystkie** pluginy skompilowane na tej metodzie stały się bezużyteczne. Możesz ewentualnie zobaczyć [mojego forka](https://github.com/TheMolkaPL/FunnyGuilds/releases), który ma aktualizację do 1.9. Było to jednak dawno i nie potwierdzę, że działa ona na 1.10 wzwyż (w tym 1.11). Dodatkowo nie ma tam kilku poprawek tutaj od tamtego czasu wprowadzonych.

Nie musisz otwierać nowego issue, jeżeli temat dalej dotyczy tego stare. Dalej pisz na #395, jeżeli masz pytanie takie jak to. Zamykam ten issue bo rozwiązałem go moim komentarzem.

**Comment by dzikoysk** [comment]
Aktualizacja do wersji wyższej niż 1.7.x nie jest na razie planowana z mojej strony, bo nie mam na to czasu. Wersja 4.x miała być na nowsze wersje, ale zainteresowanie było słabe, więc pomysł podupadł
