### ISSUE TITLE
Wybuchy TNT podczas ochrony gildii

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#398]
Elo, podczas ochrony gildii wybucha tnt :)

**Comment by dzikoysk** [comment]
Jakiej ochrony gildii

**Comment by sokrates1231** [comment]
niewazne " # Po jakim czasie od zalozenia mozna zaatakowac gildie
war-protection: 48h" 

to tylko do ataku serca. XDD


mozna dodac ochrone ;) w nie których gildiach jest ochrona na tnt i inne wybuchy do ustalenia mozna dodac do funnyguilds. Moge zaplacic i mozesz nawet ta wersje opublikowac... $ i tak z serwera wiec mnie one nie interesuja, mysle o graczach ;).

Kontakt jakis do cb czy cos bo poprosilbym cos takiego na szybko bo bez ochronki takiej nie ma sensu teraz gry na serwerach sv + gildie?

**Comment by dzikoysk** [comment]
Nie mam obecnie czasu, ale postaram się dodać przy następnej aktualizacji. Może jakaś pojawi się za kilka dni, ale nic nie obiecuję

**Comment by sokrates1231** [comment]
prosba, sprawdzisz meila?

**Comment by ProgrammingWizzard** [comment]
Gotowe, będzie dostępne w najnowszej wersji :)
