### ISSUE TITLE
Pusta TabLista

### ISSUE THREAD

**Issue by Dziubakowy** [FunnyGuilds/FunnyGuilds#399]
https://pastebin.com/jkLEqQqA
http://imgur.com/a/F8UrD 
Ktoś pomoże?

**Comment by ProgrammingWizzard** [comment]
@Dziubakowy wersja silnika, clienta, pluginu, oraz fragment konfiguracji dot. tablisty.

**Comment by Dziubakowy** [comment]
@ProgrammingWizzard PaperSpigot 1.7-1.8, najnowsza wersja, podałem na pastebinie

**Comment by ProgrammingWizzard** [comment]
A spróbuj czystego PaperSpigot'a, obsługującego tylko 1.7.10.

**Comment by Dziubakowy** [comment]
@ProgrammingWizzard  Ten tab działał normalnie, po restarcie serwerka się tak zrobiło, przed tem na tej wersji działało

**Comment by ProgrammingWizzard** [comment]
To nie używaj komendy /reload, tylko jak człowiek zatrzymuj serwer, i włączaj od nowa. Nawet jest komunikat, dot tej komendy, podczas jej użycia.

**Comment by Dziubakowy** [comment]
@ProgrammingWizzard  /reload wywala mi serwerek, więc używam restartu w panelu na enderchescie

**Comment by dzikoysk** [comment]
Bug powodowany przez konflikt z pluginem iDisguise, zamykam
