### ISSUE TITLE
błąd z tnt

### ISSUE THREAD

**Issue by NNorbertPL** [FunnyGuilds/FunnyGuilds#400]
Witam, błąd z tnt wygląda następująco.
Gdy na terenie gildii osoba która jest w gildii wybuchnie tnt to nie można budować przez 150 sekund(tam mam ustawione w configu)
ale gdy zrobi to jakaś wroga gildia to można ciągle budować..

Czyli podczas przebijania mogą się ciągle coblować itd

**Comment by ProgrammingWizzard** [comment]
Podczas testów nie udało mi się spowodować tego samego błędu - proponuje zaktualizować plugin do najnowszej wersji ;)
