### ISSUE TITLE
Nie da sie dolaczyc

### ISSUE THREAD

**Issue by queee** [FunnyGuilds/FunnyGuilds#401]
Nie moglem dolaczyc nie wiem czy tylko ja tak mam ale po prostu sie nie dalo 
- 5 stone
- 5 dirt
mialem te rzeczy i nic
usunalem i dalej
Koledzy tez nie mogli dolaczyc ale juz gildie moglem robic

**Comment by TheMolkaPL** [comment]
Logi, błędy?

**Comment by Inuun** [comment]
Kiedyś miałem podobną sytuację, błędów nie było ale chciało ileśtam AIR jeszcze :D

**Comment by dzikoysk** [comment]
Brak kontaktu z op + niewystarczająca ilość informacji, zamykam

**Comment by queee** [comment]
juz dziala
