### ISSUE TITLE
Brak zadawania samemu sobie HP

### ISSUE THREAD

**Issue by Dziubakowy** [FunnyGuilds/FunnyGuilds#407]
Cześć
Znalazłem buga w FunnyGuilds
Podczas wyłaczonego PVP w gildii, nie mozemy zabijac innych osob z gildii, lecz również nie zadajemy sobie obrażeń, np. po strzelniu w siebie strzałą lub rzutu perełką nie ubywa HP, może jak ktos ma enchant diaxowy set to z tą perełką nic nie zmienia, lecz jedak jak by tak rzucić z 5 perełek to 1 serduszko zejdzie, a tak to nawet bez seta nie schodzi :/
https://www.youtube.com/watch?v=-bKcp10_6aw&feature=youtu.be Tutaj  filmik (Sorka za muzyczke w tle ;d)

**Comment by ProgrammingWizzard** [comment]
Czyli proponujesz, żeby swoim sojusznikom nie zadawać HP, jednak sobie można, tak?

**Comment by Dziubakowy** [comment]
Tak, ponieważ takie coś ułatwia grę. Można rzucać perełkami bez zadawania sobie HP, czyli można takową perełkę użyć w fosy, i upaść bez obrażeń.

**Comment by ProgrammingWizzard** [comment]
Spoko, zaraz dodamy ;)

**Comment by ProgrammingWizzard** [comment]
To "zaraz" troszku trwało, ze względu na to, że męczyłem się ciutke z MySQL - ale gotowe :)
Zostanie wprowadzone w 3.9.9.9
