### ISSUE TITLE
TabLista na 1.8-1.7, informacja o ochronie gildii i wiadomości po wybuchu tnt

### ISSUE THREAD

**Issue by pepq** [FunnyGuilds/FunnyGuilds#408]
* Dodałbym do wersji 3.9.9.9 tablistę na 1.8-1.7, wiadomo że na 1.8 bardzo ładnie się prezentuje, gracz wchodzący z 1.8 ma rozjechaną i brzydką.
* Drugą propozycją byłoby wprowadzenie zmiennej która wyświetlałaby czy dana gildia posiada ochronę, przykład /info (gildia), w informacjach wyskoczy wiadomośc: Ochrona: Brak lub Aktywna (Licznik ile pozostało do końca). 
* Ostatnią propozycją byłoby dodanie wiadomości po wybuchu TNT podczas ochrony, która informowała by że gildia posiada ochronę, w wiadomości mógłby znajdować się licznik ile pozostało do konca. (możliwość zmienienia wiadomości w configu).

Oraz fix który naprawiłby możliwość zniknięcia jajka (nie jestem pewien czy po /stoplag znika endercrystal), 
gracze na moim serwerze znikali życia i ich gildie były nie do podbicia..

**Comment by ProgrammingWizzard** [comment]
Tablista na nowsze wersje będzie dopiero przy 4.0 - natomiast co do reszty, nie ma raczej problemu :)
