### ISSUE TITLE
Buz związany z tnt!

### ISSUE THREAD

**Issue by lakstick** [FunnyGuilds/FunnyGuilds#413]
Witam gildia posiada ochronę, na samym terenie nie niszczy nic lecz jeżeli tnt jest wysadzone poza terenem i przeleci na teren to niszczy bloki na terenie.

**Comment by ProgrammingWizzard** [comment]
Cześć, dzięki za zgłoszenie błędu. Zostanie naprawiony w najnowszej wersji ;)

**Comment by ProgrammingWizzard** [comment]
Będzie dostępne w najnowszej aktualizacji ;)
