### ISSUE TITLE
Strefa bez tracenia punktów

### ISSUE THREAD

**Issue by Dziubakowy** [FunnyGuilds/FunnyGuilds#415]
Cześć! Mam propozycję do FunnyGuilds. 
Dokładniej strefy, na której nie traciło by się punktów.
Administrator by zaznaczał drewnianą siekierką obszar (jak w World Edicie), wpisywal by np. /ga nopoints NazwaStrefy i w niej gracze by nie tracili, ani nie dostawali punktów.
Było by to przydatne jak ktoś ma serwer, gdzie ma np. SkyWarsy, bo na takowych traci się punkty (sprawdzałem), oraz na jakimś warpie, jak ktoś chce się pozabijać nie dla rankingu, lecz dla przyjemności. 😄

**Comment by Inuun** [comment]
+1

**Comment by MrGregorix** [comment]
Dodane w wersji 3.9.9.11 jako flaga WorldGuarda (fg-no-points)
