### ISSUE TITLE
Nie wybucha TNT na terenie gildi.

### ISSUE THREAD

**Issue by pepq** [FunnyGuilds/FunnyGuilds#417]
Posiadam najnowszą wersje FG 3.9.9.9, Gildia posiada ochrone 12h, minął tydzień i nadal TNT nie wybucha na terenie gildi, brak błędów. Gracze narzekają że nie działa TNT.. prosiłbym o fixa jak najszybciej :)

**Comment by lakstick** [comment]
Mam ten sam błąd. Kiedy zamierzacie to naprawić?

**Comment by dzikoysk** [comment]
Bug był zgłoszony w #414 i obecnie jest rozwiązany w wersji 3.9.9.10
