### ISSUE TITLE
Pisanie bez logowania

### ISSUE THREAD

**Issue by Dziubakowy** [FunnyGuilds/FunnyGuilds#418]
https://www.youtube.com/watch?v=zQt9G46n-Jc
Znalazłem to serfując po YouTubie, oczywiście to nie mój filmik (Testowałem, i działa)

**Comment by kamcio96** [comment]
Błąd pluginów do logowanie, nie gildii.

**Comment by NorthPL** [comment]
@kamcio96 
No nie powiedziałbym, to raczej wina FunnyGuilds że nie sprawdza czy event jest anulowany/jest na zbyt niskim priority.

**Comment by kamcio96** [comment]
A tak, też możliwe. 🕹 zepsuł
