### ISSUE TITLE
Usuwanie gildii gdy przeciwnik jest obok

### ISSUE THREAD

**Issue by Dziubakowy** [FunnyGuilds/FunnyGuilds#420]
Cześć! Dzisiaj sobie gracze podbijają gildie, i już drugi raz się tak zdarzyło, że gracz zamiast grać to woli zrobić /usun aby gildia nie dostała żyć. Może zrobić tak, że jak ktos jest na terenie, gildii nie można usunąć?

**Comment by Inuun** [comment]
+1

**Comment by MrGregorix** [comment]
Dodane w wersji 3.9.9.11
