### ISSUE TITLE
info-player-sneaking

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#421]
Może byście wprowadzili możliwość całkowitego wyłączenia lub jakiś cooldown na sprawdzanie informacji o graczu podczas klikania na niego. Wiele ludzi wykorzystuje tę funkcje do lagowania serwera poprzez spam makro.

**Comment by Inuun** [comment]
+1
Sam musiałem to jakiś czas temu usuwać w kodzie, bo nakładalo się na inne funkcje.

**Comment by MrGregorix** [comment]
Dodane w wersji 3.9.9.11
