### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#422]
Przy uruchamianiu pluginu występuje taki błąd - https://hastebin.com/omumobicor.sql
Nie wiem czy to coś groźnego czy nie ale wole tutaj to zamieścić.

**Comment by kamcio96** [comment]
To od biblioteki `HikariCP`. Możesz zignorować 😉

**Comment by ProgrammingWizzard** [comment]
Tak jak wspomniał @kamcio96 - komunikat nic nie znaczy.
