### ISSUE TITLE
Problem z MYSQL

### ISSUE THREAD

**Issue by pepq** [FunnyGuilds/FunnyGuilds#424]
Witam, w najnowszej wersji 3.9.9.11 po każdym uruchomieniu serwera z configu usuwa się database: blabla.., nie mogę podłączyć serwera pod mysql gdyż mam dostęp tylko do jednej bazy danych i jest odmowa dostępu. W dodatku przy każdym restarcie/włączeniu serwera w configu z tablistą robi się coś takiego:
https://pastebin.com/vz1HXV7V
Usuwa puste pola i daje '' zamiast "" + usuwa "" gdy mam zrobione coś takiego: "   &e&lTwoja Gildia"
Po każdym włączeniu serwera wyrzuca błąd że nie może połączyć się z bazą danych + https://pastebin.com/hRwRyGE1 + (nie pokazuje gdy znow dodaje "" i włączam jeszcze raz , lecz po następnym resecie znow sie usuwa i wyświetla..) https://pastebin.com/LDhudxLv

**Comment by MrGregorix** [comment]
Poprawiona wersja: https://repo.funnyguilds.net/content/repositories/funnyguilds-repo/net/dzikoysk/funnyguilds/3.9.9.11/funnyguilds-3.9.9.11.jar
