### ISSUE TITLE
komuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupa

### ISSUE THREAD

**Issue by komuznimKupa** [FunnyGuilds/FunnyGuilds#474]
komuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupakomuznimKupa

**Comment by szymex73** [comment]
Idź się zabij dzieciaku, nie ogarniasz że GitHub to miejsce dla normalnych i takich co chcą pomóc a nie takich jak ty?

**Comment by komuznimKupa** [comment]
a zajebac ci kopa na banie ty dziwko szmato suko pierdolona? mam cie na hita jebany idiota github to miejsce dla jebanych zwierzat
