### ISSUE TITLE
jebacTheMolke!ICalaRodzineJegoWszyscyRazem!tYtEZBopke

### ISSUE THREAD

**Issue by komuznimKupa** [FunnyGuilds/FunnyGuilds#483]
jebacTheMolke!ICalaRodzineJegoWszyscyRazem!tYtEZBopke

**Comment by TheMolkaPL** [comment]
?

**Comment by komuznimKupa** [comment]
a nic tak se pisze pewnie jutro juz nie bede boto nudne

**Comment by TheMolkaPL** [comment]
Tu jest lekarz potrzeby. Masz problemy w domu? Występuje tam przemoc domowa? Musisz zaczerpnąć porady psychologa. To może mieć bardzo negatywne skutki w przyszłości dla Ciebie i społeczeństwa. To bardzo prosta droga do wykluczenia społecznego.
