### ISSUE TITLE
Poważny błąd

### ISSUE THREAD

**Issue by Retrumek** [FunnyGuilds/FunnyGuilds#499]
Jest kilka problemów mianowicie z /baza - zamiast teleportować do gildii to ustawia bazę gildii.

Następnie jeżeli jest o to taka przerwa w messages.yml to plugin się crashuje...

- "&a/usun &8- &7Usuwa gildie"
- " "    <---- o tutaj
- "&aGildia tworzy sie na 45 kratce"

**Comment by dzikoysk** [comment]
Naprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/2b82c47d9407a0e6847006f2784576304a84a61 (https://github.com/FunnyGuilds/FunnyGuilds/issues/498)

Co do drugiego to podaj error z consoli i utwórz osobny temat
