### ISSUE TITLE
Gdzie jest te 3.9.9.13?

### ISSUE THREAD

**Issue by lakstick** [FunnyGuilds/FunnyGuilds#501]
Wszędzie info, że jest 3.9.9.13 ale pobrać się nie da :)

**Comment by RikoDEV** [comment]
Widocznie jeszcze nie "poprali" całości.

**Comment by lakstick** [comment]
Oh przepraszam za ten błąd, mea culpa...

**Comment by RikoDEV** [comment]
I gdzie ty masz te informacje że 3.9.9.13 jest. Devki pewnie są leniwi i zaktualizowali wersje w kodzie do nadchodzącej wersji.

**Comment by dzikoysk** [comment]
#[3.9.9.14](https://github.com/FunnyGuilds/FunnyGuilds/releases/tag/3.9.9.14)
