### ISSUE TITLE
Baza

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#505]
/baza ustawia lokalizacje bazy, a komenda /ustawbaze nie istnieje.
@dzikoysk @TheMolkaPL @MrGregorix @kacperduras @adiantek

**Comment by Revelacyjny** [comment]
Dobra, poprawiłem Commands, łapcie poprawkę: https://own-cloud.info/index.php/s/LuxArHf0F2RuUKa/download

**Comment by dzikoysk** [comment]
Jest już poprawione w repo, tylko @MrGregorix nie zbuildował 3.9.9.13 :<
