### ISSUE TITLE
Tablista

### ISSUE THREAD

**Issue by krzukosz** [FunnyGuilds/FunnyGuilds#507]
Witam, czy można było by dopisać sprawdzanie na jakiej wersji gracz znajduję się na serwerze a następnie wczytywanie odpowiedniej tablisty, można też zostawiać na 1.8 ostatnią rubrykę pustą Lub chociaż żeby na 1.8 tablista była pusta. Pozdrawiam

**Comment by kacperduras** [comment]
Ile płacisz? ( ͡° ͜ʖ ͡°)
A tak serio, wsparcie nowszych wersji będzie dopiero w 4.0, a ta wersja wyjdzie wtedy... kiedy wyjdzie, no po prostu.

**Comment by kacperduras** [comment]
@krzukosz Gdybyś dalej był zainteresowany tab listą dla nowszych wersji: [klik](https://github.com/kacperduras/FunnyTab)
