### ISSUE TITLE
Wyświetlanie zabójstw i zgonów gracza

### ISSUE THREAD

**Issue by Tiql** [FunnyGuilds/FunnyGuilds#509]
Siemka czy jest dodane zabójstwa i zgony danego gracza? (chodzi o to, żeby dodać główki na własnej stronie :D).
Jeżeli nie byłaby taka możliwość? ;p

**Comment by kacperduras** [comment]
Nie rozumiem, wyjaśnij dokładniej.

**Comment by Tiql** [comment]
Chodzi o to, żeby zapisywało zabójstwa i zgony danego gracza :) żebym mógł wyświetlić to w panelu gracza na własnej stronie w "Zabójstwa gracza" i "Zgony Gracza"

**Comment by kacperduras** [comment]
Przecież zapisuje, masz do wyboru zapis FLAT lub MySQL. Jeżeli chcesz zrobić zapis do MySQL, musisz wszystkie dane ustawić w pliku konfiguracyjnym.

**Comment by Tiql** [comment]
Tak ale pokazuje tylko ile zabójstw i zgonów ma dany gracz a mi chodzi o takie coś http://imgur.com/7Hmar9T

**Comment by Tiql** [comment]
Dokładniej o to chodzi, żeby do bazy było zapisywane nicki gracza którego się zabiło oraz gracza przez którego zostaliśmy zabici :D

**Comment by kacperduras** [comment]
Obecnie nie ma takiej funkcjonalności, musiałby ktoś na zlecenie przerobić plugin, specjalnie pod Ciebie. Pisz do mnie na maila (masz w profilu) lub do kogoś z ekipy FG, na pewno się dogadasz ;)

**Comment by kacperduras** [comment]
@dzikoysk @MrGregorix nadajcie plakietki, ew. zrobcie cos z tym zgloszeniem.

**Comment by Tiql** [comment]
Dzięki za odpowiedź! :D jak coś napisałem do Ciebie @kacperduras
