### ISSUE TITLE
Wybranie co tworzy się po stworzeniu gildii.

### ISSUE THREAD

**Issue by DaanielZ** [FunnyGuilds/FunnyGuilds#510]
Cześć, wpadłem na pomysł, aby dodać możliwość wybrania co tworzy się po stworzeniu gildii. Polegało by to, na ustawieniu w configu jaka budowla tworzyła by się po stworzeniu gildii. Było by do wybrania np.3 inne budowle. 1.Te co jest teraz, czyli te jajkowate koło z obsa xD 2.Kwadratowe pomieszczenie z obsydianu, 3.Nic, tylko sam krzyształ (ewentualnie to co jest  ustawione w configu).

**Comment by kacperduras** [comment]
A nie lepszym rozwiązaniem byłoby opcjonalne wsparcie WorldEdita i wklejanie schematu, a np. na miejscu gąbki w tymże schemacie byłoby serce gildii?

**Comment by MrGregorix** [comment]
A co jeśli ktoś chciałby zbudować to z gąbek ? :/

**Comment by DaanielZ** [comment]
Bedrock?

**Comment by kacperduras** [comment]
@MrGregorix takowy blok byłby także do skonfigurowania. Podobny patent funkcjonuje bodajże w ASkyblock.
