### ISSUE TITLE
Naprawa buga związanego z powiekszaniem gildii.

### ISSUE THREAD

**Issue by Przemo12** [FunnyGuilds/FunnyGuilds#516]
Witam, w wersji pluginu FunnyGuilds 3.9.9.14 nie da się powiększac regionu gildii, poniewaz pisze iż w poblizu jest inan gildia, a gildie są naprawdę daleko :c

**Comment by kacperduras** [comment]
Jakie dzieli je dystans w przybliżeniu?

**Comment by Przemo12** [comment]
około 300-500 kratek

**Comment by kacperduras** [comment]
Podeślij plik konfiguracyjny.

**Comment by Przemo12** [comment]
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
#                                 #
#           FunnyGuilds           #
#         3.9.9.14 Cleaned        #
#                                 #
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
# Wyswietlana nazwa pluginu
plugin-name: FunnyGuilds
# Maksymalna dlugosc nazwy gildii
name-length: 22
# Minimalna dlugosc nazwy gildii
name-min-length: 4
# Maksymalna dlugosc tagu gildii
tag-length: 4
# Minimalna dlugosc tagu gildii
tag-min-length: 2
# Minimalna ilosc graczy w gildii aby zaliczala sie do rankingu.
guild-min-members: 2
# Przedmioty wymagane do zalozenia gildii
items: 
- 64 diamond_block
- 16 ender_pearl
- 32 tnt
- 32 bookshelf
- 64 gold_ingot
# Przedmioty wymagane do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip
items-vip: 
- 32 diamond_block
- 8 ender_pearl
- 16 tnt
- 16 bookshelf
- 32 gold_ingot
# Odleglosc od spawnu
create-distance: 100
# Blok, jaki pojawi sie pod nami po stworzeniu gildii
create-material: ender crystal
# Na jakim poziomie ma byc wyznaczone centrum gildii
# - Wpisz 0, jezeli ma byc ustalone przez gracza
create-center-y: 0
# Czy ma tworzyc pusta przestrzen dookola centrum gildii
create-center-sphere: true
# Maksymalna ilosc czlonkow w gildii
max-members: 20
# Swiaty, na ktorym jest zablokowane tworzenie gildii
blockedworlds: 
- world_the_nether
# Mozliwosc teleportacji do gildii
base-enable: true
# Czas oczekiwania na teleportacje (w sekundach)
base-delay: 5
# Koszt teleportacji do gildii (jezeli brak, wystarczy zrobic: base-items: [])
base-items: []
# Koszt dolaczenia do gildii (jezeli brak, wystarczy zrobic: join-items: [])
join-items: 
- 10 diamond
# Mozliwosc powiekszania gildii
enlarge-enable: true
# O ile powieksza teren gildii 1 poziom
enlarge-size: 5
# Koszt powiekszania gildii
# - kazdy myslnik, to 1 poziom gildii
enlarge-items: 
- 8 diamond
- 16 diamond
- 24 diamond
- 32 diamond
- 40 diamond
- 48 diamond
- 56 diamond
- 64 diamond
- 72 diamond
- 80 diamond
# Wielkosc regionu gildii
region-size: 50
# Minimalna odleglosc miedzy terenami gildii
region-min-distance: 10
# Czas wyswietlania powiadomienia na pasku powiadomien (w sekundach)
region-notification-time: 15
# Co ile moze byc wywolywany pasek powiadomien przez jednego gracza (w sekundach)
region-notification-cooldown: 60
# Blokowane komendy dla graczy spoza gildii na jej terenie
region-commands: 
- spawn
- home
- repair
- tpaccept
- tpa
- sethome
# Czy mozna usunac gildie jezeli ktos spoza gildii jest na jej terenie
region-delete-if-near: false
# Przez ile sekund nie mozna budowac na terenie gildii po wybuchu
region-explode: 120
# Jaki ma byc zasieg pobieranych przedmiotow po wybuchu (jezeli chcesz wylaczyc, wpisz 0)
explode-radius: 3
# Jakie materialy i z jaka szansa maja byc niszczone po wybuchu
# <material>: <szansa (w %)
explode-materials: 
  obsidian: 20.0
  water: 33.0
  lava: 33.0
# Ile zyc ma gildia
war-lives: 3
# Po jakim czasie od zalozenia mozna zaatakowac gildie
war-protection: 24h
# Ile czasu trzeba czekac do nastepnego ataku na gildie
war-wait: 24h
# Jaka waznosc ma gildia po jej zalozeniu
validity-start: 14d
# Ile czasu dodaje przedluzenie gildii
validity-time: 14d
# Ile dni przed koncem wygasania mozna przedluzyc gildie (wpisz 0, jezeli funkcja ma byc wylaczona)
validity-when: 14d
# Koszt przedluzenia gildii
validity-items: 
- 10 diamond
# Ranking od ktorego rozpoczyna gracz
rank-start: 1000
rank-percent: 1.0
# Czy pokazywac informacje przy kliknieciu prawym na gracza
info-player-enabled: true
# Cooldown pomiedzy pokazywanie informacji przez prawy klik (w sekundach)
info-player-cooldown: 0
# Czy trzeba kucac, zeby przy klikniecu prawym na gracza wyswietlilo informacje o nim
info-player-sneaking: true
# Czy czlonkowie gildii moga sobie zadawac obrazenia (domyslnie)
damage-guild: false
# Czy sojuszniczy moga sobie zadawac obrazenia
damage-ally: false
# Wyglad znaczika {TAG} wstawionego w format chatu
chat-guild: "&8[&6{TAG}&8] "
# Wyglad znaczika {RANK} wstawionego w format chatu
chat-rank: "&b{RANK} "
# Wyglad znaczika {POINTS} wstawionego w format chatu
chat-points: "&8[&6{POINTS}&8] "
# Symbol od ktorego zaczyna sie wiadomosc do gildii gildii
chat-priv: "!"
# Symbol od ktorego zaczyna sie wiadomosc do sojusznikow gildii
chat-ally: "!!"
# Symbol od ktorego zaczyna sie wiadomosc do wszystkich gildii
chat-global: "!!!"
# Wyglad wiadomosci wysylanej na czacie gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-priv-design: "&8[&aChat gildii&8] &7{PLAYER}&8:&f {MESSAGE}"
# Wyglad wiadomosci wysylanej na czacie sojusznikow dla sojusznikow
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-ally-design: "&8[&6Chat sojuszniczy&8] &8{TAG} &7{PLAYER}&8:&f {MESSAGE}"
# Wyglad wiadomosci wysylanej na czacie globalnym gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-global-design: "&8[&cChat globalny gildii&8] &8{TAG} &7{PLAYER}&8:&f {MESSAGE}"
# Wyglad tagu osob w gildii
prefix-our: "&a{TAG}&f "
# Wyglad tagu gildii sojuszniczej
prefix-allies: "&6{TAG}&f "
# Wyglad tagu gildii neutralnej (widziany rowniez przez graczy bez gildii)
prefix-other: "&7{TAG}&f "
# Czy wlaczyc dummy z punktami
dummy-enable: true
# Wyglad nazwy wyswietlanej (suffix, za punktami)
dummy-suffix: pkt
# Wyglad listy graczy. Przedzial od 1 do 60
# Limit znakow: 30
# > Spis zmiennych:
# {ONLINE} - Liczba graczy online
# {PLAYER} - Gracz
# {PING} - Ping
# {TPS} - TPS
# {GUILD} - Gildia do ktĂłrej naleĹĽy gracz
# {TAG} - Tag gildii gracza
# {POINTS} - Punkty
# {RANK} - pozycja w rankingu gracza
# {KILLS} - Zabojstwa
# {DEATHS} - Smierci
# {SECOND} - Sekunda
# {MINUTE} - Minuta
# {HOUR} - Godzina
# {PTOP-<pozycja>} - Gracz na podanym miejscu w rankingu (np. {PTOP-1}, {PTOP-60})
# {GTOP-<pozycja>} - Gildia na podanej pozycji w rankingu (np. {GTOP-1}, {PTOP-50})
# {GPOINTS} - punkty gildii
# {GRANK} - pozycja gildii w rankingu
# {SIZE} - wielkoĹ›Ä‡ terenu gildii
# {LIVES} - ĹĽycia gildii
player-list: 
  1: "&9&m---------------"
  2: "&9&m---------------"
  3: "&9&m---------------"
  4: "  &eRanking Graczy"
  5: "    &e&lGlobalServ"
  6: "   &eRanking Gildii"
  7: "&9&m---------------"
  8: "&9&m---------------"
  9: "&9&m---------------"
  10: ""
  11: "         &e{ONLINE}/100"
  12: ""
  13: "&9&m---------------"
  14: "&9&m---------------"
  15: "&9&m---------------"
  16: ""
  17: ""
  18: ""
  19: "&91. &e{PTOP-1}"
  20: "&6Nick: &e{PLAYER}"
  21: "&91. &e{GTOP-1}"
  22: "&92. &e{PTOP-2}"
  23: "&6Zabojstwa: &e{KILLS}"
  24: "&92. &e{GTOP-2}"
  25: "&93. &e{PTOP-3}"
  26: "&6Smierci: &e{DEATHS}"
  27: "&93. &e{GTOP-3}"
  28: "&94. &e{PTOP-4}"
  29: "&6Punkty: &e{POINTS}"
  30: "&94. &e{GTOP-4}"
  31: "&95. &e{PTOP-5}"
  32: "&6Gildia: &e{TAG}&8"
  33: "&95. &e{GTOP-5}"
  34: "&96. &e{PTOP-6}"
  35: "&6Godzina: &e{HOUR}:{MINUTE}"
  36: "&96. &e{GTOP-6}"
  37: "&97. &e{PTOP-7}"
  38: ""
  39: "&97. &e{GTOP-7}"
  40: "&98. &e{PTOP-8}"
  41: ""
  42: "&98. &e{GTOP-8}"
  43: "&99. &e{PTOP-9}"
  44: ""
  45: "&99. &e{GTOP-9}"
  46: "&910. &e{PTOP-10}"
  47: ""
  48: "&910. &e{GTOP-10}"
  49: "&9&m---------------"
  50: "&9&m---------------"
  51: "&9&m---------------"
  52: "     &eTeamSpeak3"
  53: " &eInformacje pod"
  54: "    &eAdmini online"
  55: "    &ets.globalserv.pl"
  56: "        &e/pomoc"
  57: "          &e/Admin"
  58: "&9&m---------------"
  59: "&9&m---------------"
  60: "&9&m---------------"
# Tablista wlaczona
player-list-enable: true
# Co ile sekund ma odswiezac liste graczy
player-list-interval: 1
# Ping wyswietlany na tab
player-list-ping: 0
# Jezeli buguje Ci sie tablista
# - Po wejsciu gracza wszystko sie rozjezdza
# Wlacz ta opcje
player-list-patch: false
# Wyglad punktow wyswietlanych przy gildii w rankingu
player-list-points: "&7[&b{POINTS}&7]"
# Nazwy komend
commands: 
  guild: 
    name: 'gildia'
    aliases: 
    - gildie
    - g

  create: 
    name: 'zaloz'
    aliases: []

  delete: 
    name: 'usun'
    aliases: []

  confirm: 
    name: 'potwierdz'
    aliases: []

  invite: 
    name: 'zapros'
    aliases: []

  join: 
    name: 'dolacz'
    aliases: []

  leave: 
    name: 'opusc'
    aliases: []

  kick: 
    name: 'wyrzuc'
    aliases: []

  base: 
    name: 'baza'
    aliases: []

  enlarge: 
    name: 'powieksz'
    aliases: []

  ally: 
    name: 'sojusz'
    aliases: []

  break: 
    name: 'rozwiaz'
    aliases: []

  info: 
    name: 'info'
    aliases: []

  player: 
    name: 'gracz'
    aliases: []

  top: 
    name: 'top'
    aliases: 
    - top10

  validity: 
    name: 'przedluz'
    aliases: []

  leader: 
    name: 'lider'
    aliases: 
    - zalozyciel

  deputy: 
    name: 'zastepca'
    aliases: []

  ranking: 
    name: 'ranking'
    aliases: []

  setbase: 
    name: 'ustawbaze'
    aliases: 
    - ustawdom

  pvp: 
    name: 'pvp'
    aliases: 
    - ustawpvp

  # Komendy administratora
  admin: 
    main: ga
    add: ga dodaj
    delete: ga usun
    kick: ga wyrzuc
    teleport: ga tp
    points: ga points
    kills: ga kills
    deaths: ga deaths
    ban: ga ban
    lives: ga zycia
    move: ga przenies
    unban: ga unban
    validity: ga przedluz
    name: ga nazwa


# Czy event PlayMoveEvent ma byc aktywny (odpowiada za wyswietlanie powiadomien o wejsciu na teren gildii)
event-move: true
# Co ile minut ma automatycznie zapisywac dane
data-interval: 1
# Typ zapisu danych
# Flat - Lokalne pliki
# MySQL - baza danych
data-type: 
  flat: true
  mysql: false

# Dane wymagane do polaczenia z baza
mysql: 
  hostname: localhost
  port: 3306
  database: db
  user: root
  password: passwd
  poolSize: 16

**Comment by kacperduras** [comment]
Hym, konfiguracja jest w należytym porządku. W takim wypadku błąd jest w kodzie.

**Comment by Przemo12** [comment]
Wiem o tym Panie Kacprze, dziękuję za odpowiedź oraz poświęcony czas na mój skromny problem :)
