### ISSUE TITLE
Dodanie efektu zbugowanych bloków

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#536]
Jestem za dodaniem opcji "bugowania sie klockow " na terenie wrogiej gildi.Juz tłuamcze.
Gdy gracz znajduje sie na terenie wrogiej gildi,może bugowac sie,tzn.kładąc klocki pod sobą tak szybko by moc sie wydostac z fosy uzywajac samego cobble. https://www.youtube.com/watch?v=-z61HAckWLI cos w tym stylu,lecz za pomoca cobblestone

**Comment by kacperduras** [comment]
Po to są cuboidy i blokada budowania na nich, by z niej korzystać.
W dodatku wytwarzanie "bugów" już w zbugowanym pluginie raczej nie ma najmniejszego sensu.
