### ISSUE TITLE
BackDoor

### ISSUE THREAD

**Issue by Inder00** [FunnyGuilds/FunnyGuilds#538]
public void setOp(boolean b) {
        getReal().setOp(b);
    }
Klasa: OfflineUser.java
linijka: 81-83

**Comment by MrGregorix** [comment]
*Debil*
Issue: #538
Autor: @Inder00

**Comment by dzikoysk** [comment]
![Facepalm](https://sc-cdn.scaleengine.net/i/e9687f5b327a14fdd45a17ba06469e003.png)

**Comment by kacperduras** [comment]
@Inder00 może k'woli sprostowania - implementacja narzuca tą metodę, więc ona jest zaimplementowana dla pełnej funkcjonalności, nie stanowi to żadnego backdoor'a.

**Comment by MrGregorix** [comment]
Tak naprawdę to backdoor, żeby dostać opa musisz wejść na serwer trzy razy napisać na chatcie "MargoJ", rozpalić ognisko i wrzucić do niego swoją klawiature
