### ISSUE TITLE
Aktualizacja FG do wersji 4.0

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#541]
Czekam od kilku miesiecy na update pod 1.8+, moze ktos wie kiedy bd?

**Comment by dawidsawicki** [comment]
Podobno za dwa dioryty

**Comment by sokrates1231** [comment]
?

2017-09-11 16:14 GMT+02:00 dawidsawicki <notifications@github.com>:

**Comment by kacperduras** [comment]
Dobra, ten wpis potraktujmy jako jeden zbiorczy, tak na przyszłość, gdyby ktoś zadał podobne pytanie. Więc  - dlaczego nie ma aktualizacji FG 4.0? Otóż wyjaśniam, powodów jest kilka:
1. Kluczowy powód, a nosi nazwę **życie** (tak, nie przesiadujemy cały okres wegetacji na tym świecie w piwnicy przed monitorem!). Mamy rodziny, znajomych, obowiązki, szkołę również. Niekiedy po całym dniu niektórzy ludzie potrafią mieć dość. Np. w chwili pisania tego posta mam godzinę 17:04, ja wróciłem coś około 30 minut temu, a zajęcia miałem (wliczam też w to dojazd, bo mieszkam poza miastem) na 7. Można być trochę styranym, co? W dodatku trzeba się też niekiedy **uczyć**, w końcu Minecraft to nie całe życie. *I pomyśleć, że mam na jutro tyle zadane z pszyrki. Meh, znowu facetka nie da mi spokoju.* Pominę fakt, że każdy ma raczej jakieś hobby, nad którym spędza też jakąś część czasu z życia.
2. **Brak opłacalności** - być może wiesz, być może nie, ale była ankieta nt. płatnej wersji FunnyGuilds. Pewnie myślisz: *Ty [ciach] grubasie, no i co z tego że była? Co to ma wspólnego? Dawaj aktualizacje FG chciwy programisto!!!!* W tej ankiecie naprawdę wypowiadali się ludzie, którzy mieli zamiar płacić za nasz produkt, i Ci, którzy nie mieli. Zgadnij - kto stawiał najwięcej wymagań? Oczywiście zwolennicy bezpłatnej wersji :-). Nom, pominę fakt, iż @dzikoysk ponosi inne opłaty, m.in. ze swoimi VPSami, domenami, a raczej nie zamierza płacić za całość z własnej kieszeni w nieskończoność. Come on, myślmy logicznie.
3. Ambicje - słuchaj, nie każdy chce siedzieć tylko i wyłącznie w klockach bo wbrew pozorom **nie są całym życiem** ~~tylko MargoJ nim jest~~. Niektórzy wolą np. tworzyć projekty, niezwiązane z Minecraftem. Tego też nie przemyślałeś? Niektórym też kończą się chęci, i wolą np. pisać dla ludzi, **którzy im płacą**, a nie dla bandy gimbusów, która na widok aktualizacji FG, podnieca się do granic możliwości ~~bardziej niż na widok aktorki porno~~.

Ale dobra, żeby nie było, że to Ty jesteś tym **poszkodowanym w tej całej sprawie i ponosisz przez to straty finansowe z rzędu kwoty większej niż cały majątek takiego Facebooka**. Proponuje 3 rozwiązania:
1. Jeżeli chcesz być traktowany jako Jezus, Ten Wybawiciel (tylko ze sceny MC PL! *to nie miało na celu obrazić Jego*), który doprowadził do **tak ważnego przełomu w historii**, to możesz zapłacić. Tak, zapłacić za aktualizacje. Wszystko do dogadania na PM (jak nie ze mną, to pewnie z @dzikoysk ).
2. Użyj innego pluginu. Od siebie mogę polecić [NovaGuilds](https://github.com/MarcinWieczorek/NovaGuilds), od użytkownika @MarcinWieczorek. Serio, on na dzień dzisiejszy działa lepiej niż te FG *gdzie jak to powszechnie wiadomo, było jednym z pierwszych projektów @dzikoysk i ma błędy, o których mamy świadomość, że one egzystują w tym kodzie*, oraz oferuje więcej funkcjonalności. Działa na najnowszą wersję gry ~~tylko support średni, w porównaniu do naszego to Niebo i Piekło, kappa~~. W dodatku wiesz jaką radość sprawisz na twarzy autora? Nareszcie użytkownikiem jego produktu nie będzie ktoś pochodzący z Państwa Środka ~~tylko może z jego rodzimego kraju~~.
3. Czekać, czekać i czekać. Rzecz jasna tej opcji nie polecamy, bo to może jeszcze trochę potrwać. Jeżeli się pytasz dlaczego, przeczytaj całość jeszcze raz.

To tyle, czołem!

**Comment by MarcinWieczorek** [comment]
Dzięki za wspomnienie o mnie. Do używania NG nie zachęcam ze względu na szacunek dla konkurencji, w końcu wszyscy się znamy i szanujemy. Pragnę tylko przypomnieć, że jest możliwość przeniesienia danych z FG do mojego pluginu, a sposób tworzenia regionów nie odbiega od metody znanej wszystkim z FunnyGuilds, zaznaczam, PO ODPOWIEDNIEJ KONFIGURACJI i przygotowaniu serwera dla graczy. Zanim ktoś wyjdzie z bólem tyłka niech zna możliwości pluginu. Dziękujemy za lata wspierania projektu i stworzenie najpopularniejszych gildii w Polsce :)

**Comment by dzikoysk** [comment]
Dodam tylko, że tego typu projekty wrzucane są na GitHuba między innymi po to, by każdy mógł wnieść coś od siebie. Jeżeli tylko pull request jest sensowny, to zostaje zaakceptowany :)
