### ISSUE TITLE
Dodanie KD-Ratio, możliwość dodania przedrostka "g" przed komendami.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#551]
Więc tak; KD-Ratio chyba jasne co to jest, np. 0.52, 1.80 itd.
Co do przedrostka to, chodzi o to, aby po wpisaniu samego "g", nie wyrzucało errora, a pokazywało dostępne komendy. Tak samo, gdy ktoś zrobi literówkę, np. "g zalozx" - znowu wyrzuci errora.

**Comment by kacperduras** [comment]
```
[...] KD-Ratio chyba jasne co to jest
```

Po prostu stosunek liczby zabójstw i śmierci, łatwiej i lepiej się wytłumaczyć nie da.

```
Co do przedrostka to, chodzi o to, aby po wpisaniu samego "g", nie wyrzucało errora, a pokazywało dostępne komendy. Tak samo, gdy ktoś zrobi literówkę, np. "g zalozx" - znowu wyrzuci errora.
```

Przy samym przedrostku `g` tak sie nie dzieje, bo dzisiaj testowalem i zawsze uzywam tego skrotu. Co do literowek - przeciez to sa bledy, wiec komunikat o bledzie jest stosowny.

**Comment by marcinkowalczyk2** [comment]
No właśnie, zamień komendy na "g zaloz", "g usun" itd. I jak potem wpiszesz "g" to wyrzuca błąd.

**Comment by kacperduras** [comment]
Ale dlaczego myślisz tylko o sobie? Może nie pomyślałeś, że innym to nie odpowiada? Obecnie wszystkimi komendami da się zarządzać z poziomu pliku konfiguracyjnego, a od 4.0.0.2 będzie można nawet zmienić komendę `/funnyguilds`.

**Comment by kacperduras** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/commit/28b15e3876b89dfe11186935a39bed72f1b06717
