### ISSUE TITLE
Wsparcie dla TitleManager + problem z przeładowaniem tabu.

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#552]
Może dodalibyście wsparcie dla tego pluginu https://www.spigotmc.org/resources/titlemanager.1049/

Wiem że dodaliście header i footer ale mi zależy na animacji a tego funnyguilds nie ma wbudowanego.
Próbowałem ustawić to tak:

player-list-header: ''
player-list-footer: ''

jednak co ok. sekundę wyskakuje to co ustawiłem w TitleManager a raz to co ustawiłem w FunnyGuilds czyli puste pole.

Kolejna sprawa jest taka, że po wpisaniu /funnyguilds reload przeładowuje się wszystko tylko nie tab/header/footer

**Comment by insertt** [comment]
Tablista po reloadzie za pomocą /funnyguilds reload zmienia się po przelogowaniu się, w miarę czasu i możliwości może dodam funkcję od ponownego ustawiania bez konieczności przelogowania.
