### ISSUE TITLE
Brak repleace'owania zmiennych.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#553]
Nie podmienia takich jak: {RANK}, {G-RANK}, {LIVES} (jest {G-LIVES}), {SIZE}.

**Comment by kacperduras** [comment]
Nie wiem skąd wytrasnąłeś niektóre zmienne, jak ich nawet nie ma w komentarzach konfiguracji:
* odpowiednikiem {G-RANK} i {RANK} jest {G-POINTS};
* {SIZE} nigdy nie było zaimplementowane, zostanie usunięte z komentarzy (moje niedopatrzenie)
* {LIVES} zostało zastąpione przez {G-LIVES} (tez moje niedopatrzenie).

Dzieki za zgłoszenie ;)
