### ISSUE TITLE
Wsparcie Scoreboard'a z pluginu TitleManager

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#557]
#552 - Dodaje do tamtej propozycji propozycje szerszego wsparcia TitleManager (zmienne FG na ScoreBoardzie).
![image](https://user-images.githubusercontent.com/32804020/31579790-44954e04-b13e-11e7-9362-bc963b31a2a1.png)

**Comment by MentosPL** [comment]
Jest szansa że zostanie to w najbliższych dniach dodane?

**Comment by kacperduras** [comment]
Huh, obecnie czasowo u mnie średnio, ale się postaram to dopisać. Być może w weekend, ale nic nie obiecuje - jednak jest spore prawdopodobieństwo :D

**Comment by MentosPL** [comment]
Ok, dzięki wielkie, planuje start ok 17-tego więc jakby dało w ten weekend to by było superowo ;)
Przypinam pokrewny wątek: https://github.com/FunnyGuilds/FunnyGuilds/issues/572

**Comment by WybuchowyAnanas** [comment]
@refresh

**Comment by kacperduras** [comment]
Issue się nie odświeża, nie daje to żadnego efektu.
