### ISSUE TITLE
System asyst i opcjonalne cuboidy

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#558]

**Comment by kacperduras** [comment]
Na jakiej zasadzie miałby niby działać sytem asyst?

**Comment by marcinkowalczyk2** [comment]
Bijemy z gildią kogoś i punkty są rozdzielane przez osoby które biły i zabójstwo dostaje osoba, która miała najwięcej uderzeń zadanych.

**Comment by kacperduras** [comment]
Mało sensowne, poniewaz niekoniecznie osoba ktora uderzyla najwiecej razy, mogla zabic. Czasem starczy jeden cios, strzal z luku etc.

**Comment by marcinkowalczyk2** [comment]
Niby tak, ale załóżmy, że ktoś bił się z kimś przez 3 minuty, a ktoś inny strzelił z łuku i dostał z niego wszystko.

**Comment by kacperduras** [comment]
1. Nie modyfikuj tytulu issue.
2. To sprawa graczy. Mozna zrobic tak, ze glowny zabojca dostaje 50% rankingu z gracza X, a reszta jest rozdzielana miedzy asystujacych w zaleznosci od wartosci zadanego damage.

**Comment by marcinkowalczyk2** [comment]
A co jeżeli ktoś zadał tylko 1 hit, gdy był kogoś z tylko 1 kolegą? Również dostanie 50%?

**Comment by kacperduras** [comment]
To byl przyklad, wszystko zalezy od tego, kto zadal smiertelny cios i jakiej wartosci (nie ile uderzen) zadal obrazenia.

**Comment by marcinkowalczyk2** [comment]
Można i tak, w sumie na wszystkich serwerach to tak właśnie działa.

**Comment by MentosPL** [comment]
można dać jak np. w lolu (tak wiem że to mc) że ten który zadał ten ostateczny damage ma 75% a drugi albo pozostałe osoby maja asystę i maja 25% (resztę)

**Comment by marcinkowalczyk2** [comment]
No te 50% i reszta rozdzielana jest lepszym rozwiązaniem.

**Comment by kacperduras** [comment]
Ciekawy zamysl ;)

**Comment by MentosPL** [comment]
To można zrobić tak że jak było 2V1 to jeden otrzymuje 75% drugi 25%
a jak jest np 5vs1 to zabójca ma 50% a druga połowa jest dzielona między pozostałych czterech i mają asystę hue hue :D
