### ISSUE TITLE
Modyfikacja aliasow

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#559]
1. Propozycja:
allias komendy /FunnyGuilds reload (/FG reload) oraz inne komendy Funnyguilds
2. Propozycja:
wybranie opcji między /zaloz tag nazwa a /g zaloz tag nazwa.

**Comment by kacperduras** [comment]
Wszystko z punktu 2 da sie modyfikowac z poziomu pliku konfiguracyjnego.
Punkt 1 odpada, brak sensu + obawa o proby zatuszowania pochodzenia pluginu.

**Comment by dzikoysk** [comment]
Niech tuszują, ale przynajmniej wygodnie będzie. Pisać cały czas /funnyguilds to też niezbyt wygodnie
