### ISSUE TITLE
Wyświetlanie informacji za pomocą title/actionbar

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#560]
Propozycja wiadomości do wyboru między [CHAT/TITLE/ACTIONBAR/BOSSBAR] podczas:
Wejścia na czyjaś gildię np. Title 
![image](https://user-images.githubusercontent.com/32804020/31579936-e19b7a90-b141-11e7-9486-ced575fa7f8e.png)
Gdy Nasza Gildia jest atakowana. np ActionBar
![image](https://user-images.githubusercontent.com/32804020/31579944-255970de-b142-11e7-8346-ded4d9b0b3c7.png)
Oraz gdy sojusznicza gildia jest atakowana
![image](https://user-images.githubusercontent.com/32804020/31579951-57316eae-b142-11e7-8afa-9e1c113bd7d8.png)

**Comment by WybuchowyAnanas** [comment]
@refresh
