### ISSUE TITLE
Własny schemat wyglądu obszaru początkowego gildii

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#561]
Propozycja wspierania własnego .schematic przy stworzeniu gildii

Przykładowy Schematic:
![image](https://user-images.githubusercontent.com/32804020/31579992-6c98ab30-b143-11e7-907f-5c0888242e63.png)
![image](https://user-images.githubusercontent.com/32804020/31579994-744a4f64-b143-11e7-8faa-0e883de042f9.png)
wymiary X:7 Y:6 Z:7

Moim zdaniem lepsze niż "kula" albo brak

**Comment by kacperduras** [comment]
Dodam też od siebie, że najlepiej zastosować wg. mnie patent z pluginu ASkyblock. W nim spawn pojawia się w miejscu ustalonego w konfiguracji bloku, domyślnie to gąbka. Proponuje w FG zrobić to samo, by jakoś nie ograniczać tego :P

**Comment by WybuchowyAnanas** [comment]
@refresh

**Comment by kacperduras** [comment]
Issue się nie odświeża, nie daje to żadnego efektu.

**Comment by insertt** [comment]
Zaimplementowano w https://github.com/FunnyGuilds/FunnyGuilds/commit/9564574a4baad6ac41df6545e8cacd748f0e9834.
