### ISSUE TITLE
Wsparcie Tab'a z pluginu BungeeTabListPlus

### ISSUE THREAD

**Issue by ReconV** [FunnyGuilds/FunnyGuilds#563]
Proponuje wsparcie BungeeTabListPlus. 
Między innymi wsparcie na  zmienne.
Animacje tab-listy, indywidualne ikony użytkowników i więcej.

**Comment by kacperduras** [comment]
```
[...] indywidualne ikony użytkowników i więcej.
```

A co my, wróżki? Może jakieś konkrety?

**Comment by RabbitTheDEV** [comment]
Większość serwerów jest na serwerach non-premium, ażeby korzystać z ikonek potrzebny jest tryb online mode przełączony na true. BungeeTablistPlus ma bardzo fajne API, w 3 prostych krokach można zrobić replacement dla danego stringa i dodać go na tablistę, więc nie ma sensu takie wsparcie.

**Comment by Kamilkime** [comment]
No, tak jak napisałeś - BungeeTablistPlus ma API, więc można do FG dodać wsparcie dla niego
