### ISSUE TITLE
Błąd poczas pierwszego uruchomienia pluginu (#4.0.0.1)

### ISSUE THREAD

**Issue by RikoDEV** [FunnyGuilds/FunnyGuilds#564]
Podczas pierwszego uruchomienia pluginu na czystej instalacji wywala błąd:

![firstrun](https://user-images.githubusercontent.com/18230443/31582528-5087756e-b186-11e7-979b-2bfac3c8c3f7.PNG)

**Comment by kacperduras** [comment]
Naprawione w 091d062be9c3a2ad5bf1cc8129ef3d151844eba9
