### ISSUE TITLE
Wbudowany antylogout

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#565]
Chciałbym wytłumaczyć dlaczego wbudowany antylogout jest potrzebny. Z zewnętrznymi pluginami typu CombatLog jest o tyle kłopot, że jeśli gracz się wyloguje, zabije się spadając z wysokości, utonie lub udusi się w blokach w czasie trwania antylogouta on nie odejmuje punktów oraz też ich nie dodaje osobie która przeżyła walkę. Wielu graczy się na to skarży bo często bijąc się z innym graczem i prawie wygrywając ten nagle się wylogowuje i tym samym unika tracenia punktów bo bardziej zależy mu na miejscu w rankingu niż przedmiotach.

Wiem, że to trochę rozbudowana sprawa ale może znaleźlibyście kiedyś czas na dodanie tego.

**Comment by MentosPL** [comment]
Zazwyczaj jest tak że osoba "logająca" albo jest zabita przez plugin i traci itemy, albo otrzymuje tymczasowego bana (albo oba). nie uważam by to było konieczne, ale z drugiej strony oszczędziło by to miejsca bo nie trzeba było mieć specjalnie drugiego pluginu.

**Comment by iSopik** [comment]
Popieram to rozwiązanie! Bo po co obciążać serwer dodatkowymi pluginami? Wiem ,że mały ma to wpływ ale zawsze coś. Można by dodać coś w stylu: http://pokazywarka.pl/noo09k/ oraz jakaś wiadomość na chacie.

**Comment by TheMolkaPL** [comment]
To jest częściowo wina pluginu na ten anty-logout. Jeżeli gracz się wyloguje podczas walki, to plugin powinien podać fakeowy PlayerDeathEvent - bo przecież gracz umiera.

Można też pogrzebać w ComatLog i zobaczyć czy ma jakiś event od wylogowania się podczas walki go wykorzystać.

**Comment by iSopik** [comment]
Ale... poco się bawić z tymi osobnymi pluginami?!?! skoro wbudowany antylogout:
- zwiększa wydajność
- dodaje więcej możliwości
- jest łatwiejszy w użytku
- JEST LEPSZZYYY!

Hihi

**Comment by Kamilkime** [comment]
Wcale nie musi być wydajniejszy - jak fg musi obracać większymi danymi do tego, to będzie minimalnie wolniej

Wygodniej - też nie musi być, jak się zrobi integrację z CombatLog'iem, to fg może nie mieć żadnej dodatkowej konfiguracji, wszystko się zrobi samo, wystarczy CombatLog

**Comment by kacperduras** [comment]
```
To jest częściowo wina pluginu na ten anty-logout. Jeżeli gracz się wyloguje podczas walki, to plugin powinien podać fakeowy PlayerDeathEvent - bo przecież gracz umiera.
```
Popieram, nie odpowiadamy za walnięte pluginy - FG robi wszystko ze swojej strony w tej kwestii raczej dobrze :\ Można ew. zmienić priorytet eventu, no i w sumie tyle.

**Comment by TheMolkaPL** [comment]
Chociaż i tak wiele serwerów używa CombatLog. Na jego naprawe wpływu raczej większego nie mamy (plugin nie wygląda na open source). Natomiast nie powinno być większym problemem dodanie hooka z jednym listenerem.
