### ISSUE TITLE
Zakładanie i zarządzanie gildią w Gui

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#568]
![image](https://user-images.githubusercontent.com/32804020/31586198-4b560d6a-b1ce-11e7-97dc-6943cf0477a4.png)

**Comment by WybuchowyAnanas** [comment]
@refresh

**Comment by PanKlipcio** [comment]
Issue się nie odświeża, nie daje to żadnego efektu.

**Comment by TheMolkaPL** [comment]
GUI ma strasznie ograniczone wprowadzanie danych. Nie wiem czy komuś by się to przydało...

**Comment by IceMeltt** [comment]
@TheMolkaPL zawsze można w GUI zrobić literkę co jedną kratkę i tak zrobić wpisywanie tagu / nazwy :kappa:

**Comment by Kamilkime** [comment]
Tyyyy, ale to jest myśl...

**Comment by PanKlipcio** [comment]
a nie można zrobić wpisywanie tagu gildii na tabliczce albo w kowadle?
_tego sposobu używają popularne serwery do wpisywania kodu sms (w sklepie)_

**Comment by PanKlipcio** [comment]
Zawsze można zrobić że w gui są tylko ustawienia typu true / false np. pvp w gildii

**Comment by Kamilkime** [comment]
Ojjj tam, ten pomysł z literami w GUI jest fajny

**Comment by IceMeltt** [comment]
> Ojjj tam, ten pomysł z literami w GUI jest fajny

Ale oporny ;_;

**Comment by PanKlipcio** [comment]
w #744 @kacperduras zaproponował dodanie do configu własnego regexa do nazw gildii i tagów połączenie go z gui było by trochę czasochłonne

**Comment by Kamilkime** [comment]
Eee, wszystko do zrobienia i to w sumie nie tak trudno

**Comment by jasuogra** [comment]
Będzie trzeba tylko wysilić się z dobrym połączeniem tego.

**Comment by PanKlipcio** [comment]
![Przykładowa klawiatura](https://user-images.githubusercontent.com/21959209/35973913-751f6d44-0cd7-11e8-9670-766f82023e19.png) Chodzi Ci o mniej więcej takie gui @Kamilkime ?

**Comment by Kamilkime** [comment]
A nie wiem, nad szczegółami nie myślałem

**Comment by PanKlipcio** [comment]
ciężko w takim znaleźć jakąś literę. Jedyne co można zrobić odróżnić liczby od liter, ale co dalej? Najlepiej by było jak by taka klawiatura była ułożona qwerty, ale sądzę że i tak nie było by to jakoś bardzo wygodne.

**Comment by GotoFinal** [comment]
@PanKlipcio @Kamilkime @TheMolkaPL a może jak ludzie? za pomocą kowadła lub command blocka?

**Comment by PanKlipcio** [comment]
@GotoFinal pisałem już o kowadle wyżej, a na command blocka nie wiem czy są pakiety

**Comment by jasuogra** [comment]
JA bym zrobił lejami :lenny:

**Comment by PanKlipcio** [comment]
lejami to można chyba tylko binarnie wpisywać nazwę gildii xd

**Comment by TheMolkaPL** [comment]
I to wygodne będzie w kowadle? Okno małe, nawet chyba nie da się kursora przesuwać... poza tym to okno pod kowadło, a nie wprowadzania tekstu. Jeszcze tabliczka... ale limit znaków, brak możliwości przesuwania kursora, 4 linijki...

A w komendzie mamy całe długie pole, tab-complete, copy/paste.

**Comment by TheMolkaPL** [comment]
Przecież to będzie całkowicie niewygodne... klawiatura ekranowa xD

Przerost formy nad treścią po prostu. Użytkownik - gracz ma już przecież fizyczną klawiaturę.

**Comment by PanKlipcio** [comment]
a jak by dodać do fg moda który dodaje gui w którym można wpisywać znaki klawiaturą? :)

**Comment by GotoFinal** [comment]
@TheMolkaPL w kowadle da się przesuwać kolor dowolnie jak chcesz, nawet wklejać można itd. Kowadło jest całkiem wygodne do takiego GUI do zarządzania.

**Comment by jasuogra** [comment]
Jestem jak najbardziej na tak, jakaś innowacja, plus milion nowych bugów, tak czy siak funnyguilds ma ich dużo.

**Comment by PanKlipcio** [comment]
![GUI Kowadła](https://user-images.githubusercontent.com/21959209/35975831-66d8c42c-0cde-11e8-89c2-73dcc87403e9.png)
Okno małe, ale jak na wpisanie samego tagu i nazwy gildii, wystarczające

**Comment by GotoFinal** [comment]
@TheMolkaPL @PanKlipcio do tego kowadło może validować input już przy wpisywaniu, do razu pokazać że za długie itd. Jeśli mamy dłuższą operacje za pomocą GUI to kowadło to jedyna sensowna opcja, ale komendy też warto by oczywiście zostały.

**Comment by kacperduras** [comment]
https://github.com/WesJD/AnvilGUI

**Comment by MentosPL** [comment]
Nie łatwiej jakiś listener nna chacie? Zakładając gildie wyskakuje na chacie komunikat:
" podaj tag gildii"
po wpisaniu drugi:
"podaj nazwę gildii"
A nie zabawy w kowadła/tabliczki czy ekranowe klawiatury, które nawet nadawały by się do obsługi gdyby miały układ "qwerty" a nie "abcdef".

**Comment by kacperduras** [comment]
To musi być proste, klarowne i czytelne. Chat spełnia tylko ten pierwszy warunek.

**Comment by karabin14** [comment]
przyłączam się

**Comment by karabin14** [comment]
ja myślę że najlepiej by było wpisywać w command blocku

**Comment by karabin14** [comment]
najbardziej przejrzyste by było

**Comment by Kamilkime** [comment]
Ale po co w ogóle GUI? I tak trzeba to gdzieś wpisać, więc jedyna różnica jest taka, że nie trzeba wpisywać samej komendy - co jest w sumie niewielką zmianą, a wymagałoby tylko więcej kodu w pluginie

**Comment by karabin14** [comment]
ładniejszy wygląd

**Comment by TheMolkaPL** [comment]
> ładniejszy wygląd

Natomiast z drugiej strony tabliczki służą do pisania tabliczek, kowadła do obsługi kowadła.

Już dawno temu zdecydowano, że do wprowadzania danych do serwera służą komendy na chacie. Nie za bardzo widzę potrzeby, żeby teraz to tak wyjątkowo zmieniać.

Zresztą... gdyby to było nawet taki ważne to już by powstały forki pluginu, dodatki do niego i skrypty które dodałyby tą funkcję.

Nawet takie największe pluginy jak WorldEdit, WorldGuard, Essentials czy VoxelSniper nie mają obsługi GUI - a nawet jeżeli są do nich takie dodatki, to muszą być mało popularne.

**Comment by dzikoysk** [comment]
#895
