### ISSUE TITLE
Pozbycie się liczby pingu 0 na Tabie

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#570]
![image](https://user-images.githubusercontent.com/32804020/31586250-9bb9bd2e-b1ce-11e7-91de-db23d34f7b42.png)

**Comment by Inuun** [comment]
a to juz nawet edytowac konfiguracji taba sam nie potrafisz?

**Comment by MentosPL** [comment]
Ekhem, czytaj ze zrozumieniem... Pozbycie się pingu z taba (config)
![image](https://user-images.githubusercontent.com/32804020/31586395-9efd07e6-b1d0-11e7-8e52-26ba189e8164.png)

czyli liczby 0 przy zielonym pasku

**Comment by Inuun** [comment]
i tutaj akurat screen z mojego serwera byl taki potrzebny 👍

**Comment by RabbitTheDEV** [comment]
@dzikoysk Analizując kod, 0 jest wtedy gdy gracz jest nullem, gdy gracz nie jest nullem to wyświetla jego poprawny ping.

**Comment by PanKlipcio** [comment]
Na moim serwerze ping ( to 0 ) się nie pojawia, dziwne
