### ISSUE TITLE
Dodanie Listenera Do nagłówka i Stopi Tabu oraz Scoreboarda do Replacementowana Zmiennych z Gildii

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#571]
Dodanie Listenera Do nagłówka i Stopi Tabu oraz Scoreboarda do Replacementowana Zmiennych z Gildii

**Comment by kacperduras** [comment]
Sformułuj całe issue inaczej i stwórz nowe, nic z tego nie rozumiem.
