### ISSUE TITLE
Błedy oraz propozycje.

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#573]
Witam, mam pewne błędy które są w pluginie.
Błędy:
 1. Zmienna - {RANK}, nie działa wgl. 

 2. W configu minimalny błąd:
 # {G-LIVES} - liczba zyc gildii
 A na dole jeszcze jest: 
 # {LIVES} - życia gildii

 Propozycje:
 + Dodać lepszy ranking (nie jak -18 +18 tylko coś w stylu jak na skkf)
 + Tagi z dużych liter np. HELP (nie jak teraz help)
 + Dodanie do tablisty zmiennej typu {G-RANK-TOP1}, żeby pokazywało ranking gildii z topek.
 + Dodanie do tablisty zmiennej {G-ONLINE}, liczba online w gildii graczy.
 + Dodanie dużej litery w opsie (na tabie {GUILD} np. Pomagamy  (nie jak teraz pomagamy)
 + Dodanie możliwość wyłączania bugowania się klocków 
 + Dodanie antylogauta (cbblowanie od 40 do tej opcji bym dał, że nie można cbblować wgl. na każdym poziomie) - Wiem, że to plugin na gildie ale warto dodać antylogauta.
 + Dodać możliwość dodania alertów (Opuściłeś teren gildii: HELP) itp. - Alerty.

Wiem, że trochę jest czasochłonne ale bardzo fajnie jak byś dodał chociaż te najważniejsze rzeczy.
Pozdrawiam.

**Comment by insertt** [comment]
Zamiast {RANK} jest {POINTS}, w którymś commicie poprawiałem już to, co do rankingu - jest w planach, inne propozycje może się pojawią, nic nie obiecujemy.

**Comment by kacperduras** [comment]
Zaimplementowane.
