### ISSUE TITLE
Nie działa ranking gildii na tabie, możliwość konfiguracji "Brak"

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#574]
Witam, mam znowu błąd nie działa wgl. zmienna {GTOP-1}.
Posiadam gildie ale nie pokazuje na tabie tylko pisze "Brak"
 Przy okazji dodam, że byście mogli dodać opcje, że można wyłączyć, żeby nie pisało "Brak" po prostu pustka :)

**Comment by insertt** [comment]
Czy Twoja gildia posiada 3 lub więcej członków i czy inne poprawnie się wyświetlają?

**Comment by SzymoonDev** [comment]
Nie tworze nowego issue, ale zapytam. Dlaczego zmienna, pokazujaca na ktorym miejscu jest gildia/gracz w rankingu zostala usunieta?

**Comment by kacperduras** [comment]
A ona byla wgl zaimplementowana?

**Comment by dzikoysk** [comment]
Tak, pytałem czemu to wywaliliście :/

`{GRANK}` https://github.com/FunnyGuilds/FunnyGuilds/blob/4fe93a78e68d56a158ede4e46e8a653c1375e749/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L362

`{RANK}` https://github.com/FunnyGuilds/FunnyGuilds/blob/4fe93a78e68d56a158ede4e46e8a653c1375e749/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L353
