### ISSUE TITLE
Błąd z powiadomieniem o intruzie na terenie gildii

### ISSUE THREAD

**Issue by REQUSEST** [FunnyGuilds/FunnyGuilds#575]
Gdy ktos z wrogiej gildi wejdzie na teren naszej gildi nie wyskakuje powiadomienie "Intruz wkroczyl na teren twojej gildi"

**Comment by Przemo12** [comment]
Błąd nie jest naprawiony. teraz wiadomość o intruzie się pojawia, lecz wysyła się ona osobie która wchodzi na teren gildii nie ludziom z gildii, na którą intruz wchodzi.

**Comment by kacperduras** [comment]
@Przemo12 wiemy, zgłaszałeś to w #592. Nie musisz tego ogłaszać wszem i wobec.
