### ISSUE TITLE
pomys na mega kilof

### ISSUE THREAD

**Issue by bopke** [FunnyGuilds/FunnyGuilds#578]
Dostępny Jest Crafting Kilofa Pod /megakilof

Dla Adminów /dajkilofa daje itemy na crafting

Łatwy Do Edycji 

Link Do Pobrania Na Dole

https://github.com/Inuun/megakilof/releases 

Dodajcie Takie do Gildi

**Comment by MrGregorix** [comment]
Zostanie dodane w kolejnej wersji

**Comment by kacperduras** [comment]
+1

**Comment by DrejkBR** [comment]
Hahaha dobre ;)

**Comment by Reedzev** [comment]
Nareszcie jakaś pożądna propozycja

**Comment by Inder00** [comment]
Nie no, mega kilof +10 do prawilności :D i prestiżu -gówno- serwerka :D

**Comment by Inder00** [comment]
@kacperduras postaram się dzisiaj :1st_place_medal:

**Comment by Bambo1423** [comment]
dodajcie to
