### ISSUE TITLE
Poprawienie /powieksz

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#579]
Witam, to znowu ja ;).
Wiem, że to jest minimalny błąd albo według was może to wgl. nie jest błąd ale jeżeli ktoś ma wyłączone funkcje "powiększ", to jeżeli ktoś wpisuje komendę /powieksz i ją oczywiście wyśle to wyskakuje:
An internal error...
Dodałbym bym do tego wiadomość oczywiście do edytowania np.
![bez tytulu](https://user-images.githubusercontent.com/32819810/31616195-4dcb128e-b28c-11e7-8b69-771f8b1ffd33.png) Tak wiem, że jest błąd orto :+1:

**Comment by kacperduras** [comment]
Wyślij całą tresć loga z konsoli podczas wpisania tejże komendy.
