### ISSUE TITLE
Dodanie przedrostka

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#582]
Witam chciałbym się spytać/prosić o dodanie przedrostka "g" przed komendami, czyli zamiast "/zaloz" byłoby "/g zaloz" zamiast "/usun" byłoby "/g usun" itd. Jezeli istnieje taka opcja prosiłbym o wytłumaczenie jak jej używać.

**Comment by kacperduras** [comment]
#551
