### ISSUE TITLE
Customowa zmienna podczas zabicia

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#583]
Chodzi mi o to że podczas zabójstwa pisało by z czego dany gracz został zabity np.
Player został zabity przez Player z diamentowy/kamienny/zloty/drewniany miecz 
I jeżeli ten miecz będzie miał nazwę to wyglądało by to mniej więcej tak:
Player został zabity przez Player z diamentowy/kamienny/zloty/drewniany miecz [nazwa_miecza]

Jestem za dodaniem tylko kilku przedmiotow jak ręka, siekierka, łopata, miecze.

**Comment by kamcio96** [comment]
https://github.com/kamcio96/ItemNames

**Comment by insertt** [comment]
Dodane w https://github.com/FunnyGuilds/FunnyGuilds/commit/1e6b1339e047e8a2b740786ae578df9733921e8d
