### ISSUE TITLE
Bład z pluginem WorldGuard po wgraniu FunnyGuilds 4.0.0.2

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#584]
https://hastebin.com/okezusigow.sql

Te błędy pojawiają się tylko wtedy gdy umieszczam na serwerze najnowszą wersję FunnyGuilds

**Comment by kacperduras** [comment]
W tym logu nie ma ani jednej wzmianki o klasach z FunnyGuilds.
Można pełny log z uruchomienia serwera?

**Comment by insertt** [comment]
Posiadasz WorldEdita na serwerze? Z tego co widzę, to ten błąd dotyczy klasy, która jest zawarta w pluginie WorldEdit, na którym opiera się WorldGuard.

**Comment by kacperduras** [comment]
@insertt dlatego poprosiłem o pełen log, żeby sprawdzić czy na pewno WE znajduje się na serwerze.

**Comment by FastJoe0** [comment]
Nie, to nie przez to. Od dłuższego czasu szukam przyczyny.
Z tego co znalazłem jak na razie to to, że jeden z pluginów wyrzuca błędy tylko wtedy gdy FunnyGuilds jest zainstalowane na serwerze.

Tutaj podaje logi. Pluginy te same z tą różnica, że na jednym z logów FG jest na serwerze a na drugim nie ma.

https://hastebin.com/asofesumud.sql <--- FG jest
https://hastebin.com/titumupoqo.sql <--- GFG nie ma

Próbuje znaleźć winowajce tego drugiego błędu co podałem w temacie ale jak na razie nic.

**Comment by kacperduras** [comment]
Jakimś cudem gryzie się z ShopGUIPlus, podeślij źródło, skąd masz ten plugin.

**Comment by FastJoe0** [comment]
https://www.spigotmc.org/resources/shopgui-admin-gui-shop-plugin.6515/

**Comment by kacperduras** [comment]
Tak średnio - z tego co widzę, to plugin płatny i nie posiada dostępnego źródła. Niestety, na dzień dzisiejszy nie mamy jak tego naprawić. Spróbuje napisać do autorów, może uda znaleźć się nić porozumienia w celu załatania tego błędu. Póki co zostawiam otwarte - będę infirmował o rezultatach.
