### ISSUE TITLE
Rozjazd tablisty

### ISSUE THREAD

**Issue by KrifixYT** [FunnyGuilds/FunnyGuilds#587]
Witam! Na wersji 1.8.x tablista mi sie rozjezdza, to znaczy, że tablista działa według systemu:
1
2
3
4
ITD. zamiast
1  2   3
4   5  6

Czy da rade to przekonwertować, czy coś?
KOD: https://pastebin.com/1UnQuAw3

**Comment by Kamilkime** [comment]
No... może siądź i pozmieniaj numery sekcji, i tyle

**Comment by KrifixYT** [comment]
Eh, myslalem ze istnieje na to inna opcja, dzieki! :/
