### ISSUE TITLE
Przez FunnyGuilds da się otwierać skrzynki i inne bloki.

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#590]
Witam, chciałbym zrobić targi graczy na swoim serwerze, przy użyciu np. PlotSquared z dzialkami 5x5 do targów. Problem polega na tym że da się otwierać cudze skrzynie, oraz inne bloki wchodzące w interakcję na takim "terenie" za sprawą FunnyGuilds.

Aktualnie to wygląda tak:
Bloki które można otwierać przez FunnyGuilds na cudzym Targu:
- Zwykła Skrzynia
- Enderchest
- Piec
- stół do zaklęć
- kowadło

Proszę o wydanie łatki naprawiającej ten problem.

**Comment by kacperduras** [comment]
```
Oraz mam mały problem z FunnyCreatorem, nie za bardzo mi chce działać, mimo posiadania JDK x32 oraz x64.
http://prntscr.com/h63yv6
Po tym błędzie, który wyświetla się przez 0.5 sekundy, ładuje mi się strona z linkami do pobrania JDK ;-;
```
https://github.com/FunnyGuilds/FunnyCreator/issues/

**Comment by MentosPL** [comment]
Ok stworzyłem oddzielny issue i edytuję ten issue.
