### ISSUE TITLE
Title i subtitle

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#593]
W nawiązaniu do #592, proponuje usunięcie paska smoka i zastąpienie go elementami z tytułu issue - title i subtitle.

**Comment by dzikoysk** [comment]
Możesz dodać jako dodatkową opcję do włączania/wyłączania tak jak tamten pasek, będzie można wybrać jeden z nich, albo włączyć oba, co tam kto woli

**Comment by iSopik** [comment]
Bardzo dobry pomysł! Mogło by to zostać dodane w wersji np. 4.2.1 , 4.2.2

**Comment by kacperduras** [comment]
@iSopik kiedy zostanie dodane, to zostanie dodane. Nie ma sensu się nad tym rozwodzić.

**Comment by CzokusDEV** [comment]
Hmmm :) A moze dodac przy takie same wiadmosci przy Zabojstwie?
