### ISSUE TITLE
Bląd: Głowy gracza TabLista

### ISSUE THREAD

**Issue by ReconV** [FunnyGuilds/FunnyGuilds#594]
Kiedy wgramy Plugin FastLogin jaki automatyzmie loguje graczy PREMIUM występują takie problemy.
![dasd](https://user-images.githubusercontent.com/22893288/32415872-16cfb554-c241-11e7-8914-437e6f1ef3e0.png)

Nie lepiej dodawać customowe głowy gracza do tablisty:  (Przykład znalazłem z google)
![dasdasd](https://user-images.githubusercontent.com/22893288/32415978-5aa09cac-c242-11e7-8b53-5301541842a6.png)

**Comment by insertt** [comment]
Jest to błąd związany z samym FastLoginem, a nie z FunnyGuilds, ponieważ tablista zaimplementowana w FunnyGuilds aktualnie nie wspiera główek:
`https://www.spigotmc.org/threads/fastlogin.101192/page-17#post-1763837`

**Comment by ReconV** [comment]
No słabo. A jakieś plany na dodanie wspierana główek?
