### ISSUE TITLE
Pasek smoka nie działa.

### ISSUE THREAD

**Issue by Przemo12** [FunnyGuilds/FunnyGuilds#597]
Witam, nie wiem gdzie zniknęło poprzednie issues, lecz pasek smoka nie działa w tym funnyguilds. Sprawdzałem także bez uprawnień, na wersji 1.8.8 przy silniku paperspigot 1.8.8 nic się nie wyświetla, nawet powiadomienie na czacie że ktoś wszedł na teren Twojej gildii.

**Comment by kacperduras** [comment]
#592
