### ISSUE TITLE
Parę propozycji

### ISSUE THREAD

**Issue by JucyJ** [FunnyGuilds/FunnyGuilds#600]
Parę propozycji:
+ antilogout na actionbarze;
+ powiadomienia na actionbarze o wejściu i wyjściu z terenu;
+ bany za śmierć (można je włączyć i wyłączyć);
+ zmienna tablista;
+ możliwość zmiany początkowego wyglądu terenu (ta kula z obsa) na zasadzie schematici (nawiązanie do #561);
+ możliwość wyłączenia i włączenia bugowania się;

**Comment by McKoxu** [comment]
Najbardziej mi się podoba pomysł z tym schematiciem i tą zmienną tablistą :3

**Comment by MentosPL** [comment]
możliwość zmiany początkowego wyglądu terenu (ta kula z obsa) na zasadzie schematici;

dawałem już jako propozycja
https://github.com/FunnyGuilds/FunnyGuilds/issues/561

**Comment by kacperduras** [comment]
@MentosPL dzięki że nawiązałeś, już zedytuje treść issue ;)

**Comment by MentosPL** [comment]
Proszę bardzo ;)

**Comment by insertt** [comment]
#565, https://github.com/FunnyGuilds/FunnyGuilds/commit/f863e5060f22b8fbd11d221315b4b4f46a0bc928, https://github.com/FunnyGuilds/FunnyGuilds/commit/afb85896439d74d00dfb2bc9aad2fcb0d2b82bbf, https://github.com/FunnyGuilds/FunnyGuilds/commit/9564574a4baad6ac41df6545e8cacd748f0e9834
