### ISSUE TITLE
FunnyGuilds 4.0.1 - WorldGuard

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#602]
FunnyGuilds 4.0.1 znowu powoduje problemy z WorldGuardem.
Wprawdzie wystarczy ustawić tak jak było wcześniej czyli - `loadbefore: [WorldEdit, WorldGuard]` 
zamiast `softdepend: [WorldGuard]` aby wszystko działało, jednak nie rozumiem czemu to zmieniliście jak było dobrze.

Logi z błędami:
https://hastebin.com/ezunenenuf.sql

**Comment by Kamilkime** [comment]
Ej, właśnie, czemu jest stary plugin.yml, ten skopany

**Comment by dzikoysk** [comment]
Emm chyba @kacperduras wybrał lokalne zmiany zamiast tych z repo przy merge https://github.com/FunnyGuilds/FunnyGuilds/commit/026b8272b3cc26b330f0b408ff0888adb23b45c9#diff-e1b8882fdef124feb34fdd8f4a6ab801

**Comment by dzikoysk** [comment]
@FastJoe0 pobierz FG 4.0.1 jeszcze raz z tego samego linku i powiedz czy działa

**Comment by kacperduras** [comment]
@Kamilkime potwierdzam wersję @dzikoysk, jak już kliknąłem było po - moje przeoczenie.

**Comment by dzikoysk** [comment]
Dobra, możesz pobierać ze starego linku już :)

**Comment by FastJoe0** [comment]
Działa, dzięki :)

**Comment by dzikoysk** [comment]
Naprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/a382b21b35575011c1262327cf2766bba1dec404, zamykam
