### ISSUE TITLE
Błąd czy moja wina? ;x

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#604]
Witam, krótko i na temat pobieram nowa wersje i pisze, że nie posiadam najnowszej (posiadam 4.0.1), a pisze mi, że jest już nowsza (4.0.1 tribute).
Chodzi o to, że jest nowsza w funnycreator czy co? ;x

**Comment by dzikoysk** [comment]
Sprawdź teraz, powinno być ok :)

**Comment by DrejkBR** [comment]
@dzikoysk 
Działa możesz zamknąć temat ;)
