### ISSUE TITLE
Błąd? 

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#605]
- zaraz podam ss (proszę nie brać taba bo będzie na publicznym serwerze)
![2017-11-08_11 00 46](https://user-images.githubusercontent.com/32819810/32542839-2cf76888-c474-11e7-8bb5-9b583783b9dc.png)

Topka gildii nie działa nadal.
Posiadam gildie w informacjach pisze, ze mam gildie tag oraz name itp,
Ale w top od 1 do 17 pisze, ze brak.

**Comment by kacperduras** [comment]
Napisz nowe issue lub podepnij pod obecne (jeżeli takowe istnieje), jak człowiek. To nie jest chat, to jest tracker.
