### ISSUE TITLE
Topka Gildii

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#606]
- proszę nie brać taba bo będzie na publicznym serwerze (to nie będzie podróba skafa ;x)

![2017-11-08_11 00 46](https://user-images.githubusercontent.com/32819810/32542934-776796a4-c474-11e7-83ea-5b8fdcd01699.png)

Topka gildii nadal nie działa.
Posiadam gildie w informacjach pisze, ze mam gildie tag oraz name itp,
Ale w top od 1 do 17 pisze, ze brak.

**Comment by Przemo12** [comment]
W gildii musi być przynajmniej 3 osoby, chyba że ustawiles inaczej. Mi ten tab działa normalnie

**Comment by DrejkBR** [comment]
@Przemo12 
Rozumiem ale trochę to dziwnie wygląda, że niby masz gildie ale nie jest w topce.
Może powinni dodać jakiś komunikat jak się zakłada i oczywiście do edytowania np.
Ranking topki gildii zostanie stworzony kiedy w twojej gildii będą trzy osoby!

**Comment by kacperduras** [comment]
@DrejkBR posiadasz gildie powyżej X osób? Jak nie, to sprawdz.

**Comment by DrejkBR** [comment]
@kacperduras 
Rozumiem ale trochę to dziwnie wygląda, że niby masz gildie ale nie jest w topce.
Może powinni dodać jakiś komunikat jak się zakłada i oczywiście do edytowania np.
Ranking topki gildii zostanie stworzony kiedy w twojej gildii będą trzy osoby!

**Comment by kacperduras** [comment]
```
Rozumiem ale trochę to dziwnie wygląda, że niby masz gildie ale nie jest w topce.
```
Dziwniej wygląda gdy gildia jest 1 w topce, a w niej jest tylko 1 osoba.

```
Ranking topki gildii zostanie stworzony kiedy w twojej gildii będą trzy osoby!
```

A po co, obecne komunikaty na to przecież pozwalają, wystarczy pomyśleć :D

Temat wyczerpany, zamykam.
