### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#607]
Witam, wiem, że macie może mnie dość i mogę wypierdalać ;x
Ale dodałem kiedyś propozycje taka, że możecie dodać, że na tabie oraz na chat wszystko pisze z dużych np. 
HASA - teraz można założyć tak: hAsA   (trochę dziwnie to wygląda na tabie) 
A name (opis gildii) - fUnnyGuilds - możecie dać tak: Funnyguilds pierwsza litera duża i tyle wiem, że możecie to zostawić ale dodajcie chociaż ten tag z dużych ;).
I jeszcze jedna propozycje nie wiem czy to działa ale możecie dodać możliwość tabowania (nie wiem jak się dobrze pisze) np. /zaproś Drake_PL    /zaproś d[tab]    /zaproś Drake_PL, chyba wiecie o co chodzi ;).

**Comment by kacperduras** [comment]
Dopisz do obecnego issue, a nie twórz nowego ;)
Te propozycje się łączą.
