### ISSUE TITLE
Problem z Tabem

### ISSUE THREAD

**Issue by JakubPL34** [FunnyGuilds/FunnyGuilds#608]
Witam. Po ostatniej aktualizacji przestał mi działać tab.

**Comment by kacperduras** [comment]
No dobra, ale nam nic to nie mówi. Jakieś logi i bardziej szczegółowy opis sytuacji jak i serwera?

**Comment by JakubPL34** [comment]
No gdy zainstalowałem nową wersję pluginu cały tab przestał działać i mam zwykłą listę graczy.
Nie wiem czy te logi dotyczą tego problemu ale tylko takie wyskakują po przeładowaniu pluginu/restarcie serwera
https://pastebin.com/gcfxnCwC

**Comment by Kamilkime** [comment]
A jakbyś zrobił restart całego serwera?

**Comment by kacperduras** [comment]
@JakubPL34 zainstaluj od nowa FG, pobierajac od nowa binarke i daj caly log z uruchomienia serwera.

**Comment by JakubPL34** [comment]
@kacperduras wysłałem ci na maila

**Comment by kacperduras** [comment]
@JakubPL34 na PM pomagam tylko i wyłącznie odpłatnie, wyślij tutaj.

**Comment by JakubPL34** [comment]
https://pastebin.com/JdFceX00

**Comment by JakubPL34** [comment]
@kacperduras

**Comment by kacperduras** [comment]
@Kamilkime +1

```
[09:48:45] [Craft Scheduler Thread - 7/INFO]: [FunnyGuilds][Updater] > 
[09:48:45] [Craft Scheduler Thread - 7/INFO]: [FunnyGuilds][Updater] > A new version of FunnyGuilds is available!
[09:48:45] [Craft Scheduler Thread - 7/INFO]: [FunnyGuilds][Updater] > Current: 4.0.1
[09:48:45] [Craft Scheduler Thread - 7/INFO]: [FunnyGuilds][Updater] > Latest: 4.0.1 Tribute
[09:48:45] [Craft Scheduler Thread - 7/INFO]: [FunnyGuilds][Updater] > 
```
@JakubPL34 napisałem:
```
zainstaluj od nowa FG, pobierajac od nowa binarke [...]
```
wiesz po czym się zorientowałem? Po [tym](https://github.com/FunnyGuilds/FunnyGuilds/commit/b6ebc1b70b62241f4c298aeec3d0d32a7c3bf125). @dzikoysk przypadkiem usunął kluczowe słówko z pliku, i updater nie zadziałał jak powinien, czego przyczyną jest tenże komunikat. Więc zrób to, o co Cię proszę.

**Comment by JakubPL34** [comment]
@kacperduras Jaką binarke bo za bardzo nie rozumiem?

**Comment by Kamilkime** [comment]
@JakubPL34 .jar'a nowego sobie ściągnij

**Comment by JakubPL34** [comment]
Komunikat znikł ale tab nadal nie działa

**Comment by Kamilkime** [comment]
A jakbyś użył najnowszego silnika?
https://yivesmirror.com/grab/spigot/spigot-1.12.2-R0.1-SNAPSHOT-b1438.jar

**Comment by JakubPL34** [comment]
Po wielokrotnych instalacjach komunikat się wyświetla a tab nie działa. @kacperduras @dzikoysk

**Comment by Kamilkime** [comment]
A sprawdzałeś na tym najnowszym silniku?

**Comment by JakubPL34** [comment]
a co do najnowszej wersji silnika to mam najnowszą @Kamilkime

**Comment by Kamilkime** [comment]
Podeślij może jeszcze raz log z odpalania serwera

**Comment by DrejkBR** [comment]
@JakubPL34 @kacperduras 
Zobacz jakub czy masz pod tabem włączona funkcje ;)
# Tablista wlaczona
player-list-enable: true

**Comment by JakubPL34** [comment]
tak sprawdzałem ten silnik jest jakiś lipny skript mi na nim nie działa @Kamilkime

**Comment by kacperduras** [comment]
@JakubPL34 w jakim sensie nie działa? Nie wyświetla się czy jest tylko w jednym, niezmiennym stanie?

**Comment by DrejkBR** [comment]
@JakubPL34 
Podaj config zobaczę może masz jakiś błąd w configu.

**Comment by JakubPL34** [comment]
o kurczę ale mi wstyd XD miałem player-list-enable na false

**Comment by DrejkBR** [comment]
@JakubPL34 Mówiłem, żebyś sprawdził
