### ISSUE TITLE
Problem z Tag'iem i propozycja do TabList'y

### ISSUE THREAD

**Issue by VauxHalll** [FunnyGuilds/FunnyGuilds#609]
Witam,
Sprawa z Tagiem gildii jest prosta, chodzi o wielkie i małe litery... Co by się nie wpisało zawsze daje małe litery, czy dodacie opcje w configu wybierania jakimi literami można stworzyć gildie ? Była by to super opcja, a jak nie to naprawcie to że jakimi się wpisze, to takimi zrobi tag.

Druga opcja to Tab, aby w miejscu gdzie są głowy randomów, można było podać jakieś uuid i np. ustawić własne typy takie jak bloki siana xd Pomyślcie nad tym xd

**Comment by kacperduras** [comment]
#573

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/ac47ad8912e5765a250277a9877986548632df83/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L441-L444
