### ISSUE TITLE
LogBlock dla Gildii

### ISSUE THREAD

**Issue by VauxHalll** [FunnyGuilds/FunnyGuilds#610]
Proponuje dodanie LogBlock'a ale tylko dla lidera i zastępcy gildii, i aby zapisywał tylko dane z gildii, a nie całego świata.

**Comment by kacperduras** [comment]
Sensowniejszym rozwiązaniem byłoby dodanie wsparcia dla pluginu LogBlock, aniżeli kopiowanie czegoś, co jest dobre i skuteczne.

**Comment by VauxHalll** [comment]
No co lepsze, nie ogarniam za bardzo programowania, dla tego daję propozycje

**Comment by CzokusDEV** [comment]
VanuxHalll
javastart.pl 👍

**Comment by krzukosz** [comment]
Dodanie LogBlocka było by dobrą opcją. Żeby można było z niego korzystać przez założyciela/lidera gildii tylko na jej terenie.

**Comment by Rollczi** [comment]
Raczej mi się wydaje, że ciężko o LogBlock'a w pluginie na gildie.
"Wsparcie" też ciężko zrobić, bo nie wiadomo na czym miało by polegać i też jak patrzyłem to nie ma jednolitego API na każdą wersję LogBlocka.

Linki do logblocka:
1.16 - 1.15 https://www.spigotmc.org/resources/logblock.67333/
1.13 - 1.12 https://github.com/LogBlock/LogBlock/releases
1.9 i niżej: https://dev.bukkit.org/projects/logblock/files
jakby ktoś chciał dokładnie poszukać to tu jest wszystko (też beta 1.17): https://www.iani.de/jenkins/job/LogBlock/

Do zamknięcia?

**Comment by P3ridot** [comment]
Myślę, że nie. Troche abstrakcji i różnorodność api nie będzie wielkim problemem. Po tym jak fg będzie miało podstawy ogarnięte (przepisanie systemu rankingu itd.) to można takie rzeczy pododawać.

**Comment by xpiREC** [comment]
Jeśli miało być to na zasadzie 'wsparcia' pluginu, jest dostępny coreprotect (nie wiem jak ze wsteczną kompatybilnością < 1.14), który wyprowadza API.


Tutaj przykład pobrania danych o bloku z ostatnich 60 sekund;
```
CoreProtectAPI CoreProtect = getCoreProtect();
if (CoreProtect != null){ // Ensure we have access to the API
  List<String[]> lookup = CoreProtect.blockLookup(block, 60);
  if (lookup != null){
    for (String[] result : lookup){
      ParseResult parseResult = CoreProtect.parseResult(result);
      int x = parseResult.getX();
      int y = parseResult.getY();
      int z = parseResult.getZ();
      //...
    }
  }
}
```
