### ISSUE TITLE
Problem z rankingiem.

### ISSUE THREAD

**Issue by Przemo12** [FunnyGuilds/FunnyGuilds#611]
Witam, czy mógłby mi ktoś wytłumaczyć jak działa ranking? Chyba tego nie ogarniam. 
Mój config:
```
# Lista stalych obliczen rankingowych ELO, uzywanych przy zmianach rankingu - im mniejsza stala, tym mniejsze zmiany rankingu
# Stale okreslaja tez o ile maksymalnie moze zmienic sie ranking pochodzacy z danego przedzialu
# Lista powinna byc podana od najmniejszych do najwiekszych rankingow i zawierac tylko liczby naturalne, z zerem wlacznie
# Elementy listy powinny byc postaci: "minRank-maxRank stala", np.: "0-1999 32"
# * uzyta w zapisie elementu listy oznacza wszystkie wartosci od danego minRank w gore, np.: "2401-* 16"
elo-constants: [0-10000 30]
# Dzielnik obliczen rankingowych ELO - im mniejszy, tym wieksze zmiany rankingu
# Dzielnik powinien byc liczba dodatnia, niezerowa
elo-divider: 80.0
# Wykladnik potegi obliczen rankingowych ELO - im mniejszy, tym wieksze zmiany rankingu
# Wykladnik powinien byc liczba dodatnia, niezerowa
elo-exponent: 50.0
# Czy pokazywac informacje przy kliknieciu prawym na gracza
info-player-enabled: true
# 
```

Gdy tak mam ustawione, gracz zabije gracza, maja standardowy ranking po 1000, zabiera osobie która umarła 985 pkt, a osobie ktora wygrała dodaje 1015 pkt. 
Jak to skonfigurować, by zabierało zawsze 20 pkt za zabicie, tyle dodawało też, lub tak jak to było w poprzednich wersjach pluginu?

**Comment by kacperduras** [comment]
Ostatnie zmiany w rankingu nakładał @Kamilkime w #577, co później dodałem w #581. Poczekajmy na niego i pewnie Tobie objaśni jego działanie ;)

**Comment by Przemo12** [comment]
Dziękuję za odpowiedź Kacper

**Comment by Kamilkime** [comment]
System rankingowy, który zrobiłem, jest stworzony na podstawie rankingu szachowego ELO. System działa tak, że bierze oba rankingi i zmiany wyznacza na ich podstawie, w zależności od przypadku. Założenie jest takie, że gracze z podobnym podobnym rankingiem tworzą sobie duże zmiany rankingu dzięki walce, ale już zabicie słabego gracza przez silnego przyniesie praktycznie żadną zmianę. Wartości początkowe do tego systemu, które są w pluginie, są dobrane na podstawie rankingu szachowego i powinny być całkiem dobrze zbalansowane, żeby nie było potrzeby grzebania się z nimi, co może być trudne dla większości osób :)

Co do tego stałego zabierania i dawania punktów - no, ELO nie przewiduje czegoś takiego, trzeba by dodać po prostu taką funkcję do pluginu, żeby używało ELO albo stałej różnicy :/

**Comment by Przemo12** [comment]
Przy standardowych ustawieniach, zabierało graczowi tyle samo punktów, ustawiałem spory czas i jest tak samo. Na ten czas niestety zrezygnuję z użytkowania pluginu, ma strasznie dużo bugów, proponuję dodać też włączanie starego rankingu.

**Comment by Kamilkime** [comment]
No, to potestuję jeszcze mocniej to ELO, chociaż w czasie testów było ok i może dodam tę opcję ze starym rankingiem. A na jakich mniej więcej rankingach to testowałeś, jak miałeś domyślne ustawienia?

**Comment by Przemo12** [comment]
Ustawiałem różne wartości elo-exponent:, oraz elo-divinder, caly czas bylo tak samo niestety.

**Comment by Kamilkime** [comment]
Mi chodzi o to, jakie rankingi mieli gracze, na których testowałeś te zmiany

**Comment by kacperduras** [comment]
@Kamilkime 
```
Gdy tak mam ustawione, gracz zabije gracza, maja standardowy ranking po 1000, zabiera osobie która umarła 985 pkt, a osobie ktora wygrała dodaje 1015 pkt.
```

**Comment by Kamilkime** [comment]
A, sorry, nie zauważyłem

**Comment by Kamilkime** [comment]
@Przemo12 Zbuduj sobie najnowszą wersję FG przy użyciu FunnyCreator'a

**Comment by kacperduras** [comment]
Albo poczekaj na release, który zaraz wyjdzie ;)

**Comment by Przemo12** [comment]
Sory że zapytam w zamkniętym, ale czy został poprawiony już bug  z intruzem?

**Comment by Kamilkime** [comment]
@Przemo12 
W sensie że?

**Comment by Przemo12** [comment]
Wiadomość że intruz wchodzi na teren gildii, wyświetlała się intruzowi, zamiast ludziom gildii, pisałem o tym już wcześniej.

**Comment by bgK1NG** [comment]
Było coś tam wspomniane o naprawie tego
