### ISSUE TITLE
Błąd / problem.

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#614]
Na hostingu nie miałem takiego problemu (nie wiem dlaczego).
Na lokalnym serwerze mam spam głów na tabie.
PS. Pisze, ze jest nowsza wersja a mam 4.0.1.1
![dadada](https://user-images.githubusercontent.com/32819810/32692352-d787cb22-c716-11e7-9758-7a6a7ce0a8b9.png)

**Comment by insertt** [comment]
#594
