### ISSUE TITLE
Irytujący błąd podczas uruchamiania FunnyGuilds 4.0.1.1

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#615]
Tak wiem że się czepiam i ten błąd raczej nie wpływa negatywnie na plugin ale czy możecie go jakoś ukryć lub usunąć? Chodzi o to: `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".`

Logi:
https://hastebin.com/umopomepaq.sql

**Comment by kacperduras** [comment]
To wina konfiguracji loggera SLF4J dla HikariCP, idzie zrobić.
