### ISSUE TITLE
Tag gildii.

### ISSUE THREAD

**Issue by Przemo12** [FunnyGuilds/FunnyGuilds#616]
Witam, chciałbym zgłosić kolejny nie tyle błąd, co estetyczną sprawę. 
Gildia gdy się ją założy tag zawsze jest z małych liter, nawet gdy zakładając wpiszemy duże.

**Comment by Kamilkime** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L478

**Comment by Przemo12** [comment]
To się trochę ośmieszyłem... Zamknij albo usuń to jak możesz :)
