### ISSUE TITLE
Problem z pozycją gildii w rankingu.

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#617]
Jakiś czas temu wprowadziliście opcje minimalnej ilości graczy w gildii aby pokazywała się w rankingu. Niestety nie działa to najlepiej. Wprawdzie nie pokazuje takiej gildii w {GTOP-pozycja} jednak w {G-POSITION} już tak. Moim zdaniem powinno się zmienić, że gdy gildia nie ma wymaganej liczby graczy to wtedy {G-POSITION} pokazuje `0` lub `Brak`.

**Comment by Kamilkime** [comment]
Zbuduj sobie najnowsze FG przy użyciu FunnyCreator'a
https://github.com/FunnyGuilds/FunnyCreator/releases/tag/1.0.5

**Comment by kacperduras** [comment]
Zakładam, że zaimplementowane i działa, więc zamykam. Jak się pojawią z tym błedy - pisz w tym issue.
