### ISSUE TITLE
Brak wiadomości o owym intruzie na terenie danej gildii. 

### ISSUE THREAD

**Issue by VilOPL23** [FunnyGuilds/FunnyGuilds#618]
Dobry wieczór! Napotkałem otóż taki problem, mianowicie nie widać żadnej informacji przy tym jak osoba z innej gildii bądź zwykły gracz wejdzie na teren naszej gildii. Pozdrawiam :)

Próbowałem też zmieniać już linijki jak było pisane w innych tematach, nic nie dało.

**Comment by Kamilkime** [comment]
Zbuduj sobie najnowsze FG przy użyciu FunnyCreator'a
https://github.com/FunnyGuilds/FunnyCreator/releases/tag/1.0.5

**Comment by kacperduras** [comment]
Wygląda na naprawione, póki co zamykam. Jakby dalej błąd występował - pisz tutaj.
