### ISSUE TITLE
Problem z tab listą

### ISSUE THREAD

**Issue by mhaas11** [FunnyGuilds/FunnyGuilds#621]
Mam problem z tablistą a mianowicie nie działa mi tablista korzystam z silnika spigot 1.8 (Sprawdzałem czy działa tab na Craftbukkicie 1.8 i dupa) i nie działało pokazywało jedynie taba z vanili wiem że fg 4x ma zaimplementowane ProtocolTab lib i funnytab ale próbowałem również z tym i znów dupa możesz mi pomóc ?

**Comment by Kamilkime** [comment]
Podeślij log z uruchamiania serwera

**Comment by kacperduras** [comment]
Włączyłeś tab listę w ustawieniach?

**Comment by mhaas11** [comment]
Tak już podsyłam logi, na moje oko nie ma błędów

**Comment by mhaas11** [comment]
https://imgur.com/a/iz3li

**Comment by kacperduras** [comment]
@mhaas11 zaktualizuj serwer do wersji 1.8.8, korzystasz z trochę starego buildu, jak na 1.8.

**Comment by mhaas11** [comment]
Dobra już lece ogarnąć

**Comment by mhaas11** [comment]
Całe szczęście działa :D  Dzięki chłopaki uratowaliście mi dupe

**Comment by kacperduras** [comment]
Nie ma problemu ;)
