### ISSUE TITLE
Proszę o odbanowanie mnie na Discordzie xD 

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#624]
konto MentosPL#8665

**Comment by Kamilkime** [comment]
Da się zablokować komuś możliwość pisania issue?...

**Comment by MentosPL** [comment]
chyba musicie mnie odbanować na tamtym koncie, bym mógł wejść na tym ;d

**Comment by MentosPL** [comment]
W sumie czekam za unbanem a nie aż się naradzicie "odbanować go czy nie". i spamowanie emotikona "🤔 "

**Comment by Kamilkime** [comment]
Nie będzie żadnego unbana - masz bana i tyle, koniec tematu

**Comment by MentosPL** [comment]
Poprosiłem was, byście odbanowali moje konto, a zbanowali te drugie, lecz nawet nie powiedzieliście bym wszedł na konto MentosPL i że jestem odbanowany (nawet nie wiem czy dostałem faktycznie tego UB) i bez żadnego info, daliście mi bana ;)

Więc jakby nie patrzeć, bardzo chętnie banujecie!
gorzej z odbanowaniem...

**Comment by MentosPL** [comment]
Najlepsze jest to, że ban jest bez powodu ;)

**Comment by Kamilkime** [comment]
No, ban za coś był, nie?
Na starym koncie ub nie ma i nie będzie. Na nowym dostałeś bana, bo nawet nie powinieneś móc na nim wejść, skoro już masz jednego bana - więc nowe też dostało bana, proste

**Comment by MentosPL** [comment]
Bana mam bez powodu ;) o ProgramingWizzard miał zły dzień i miał ochotę trochę po banować od tak ;)

**Comment by MrGregorix** [comment]
Mysle ze to wystarczajacy powod do unbana

**Comment by kacperduras** [comment]
```
Bana mam bez powodu ;) bo ProgramingWizzard miał zły dzień i miał ochotę trochę po banować od tak ;)
```

Oczywiscie, bo nie mam co robic, tylko rozdawac bany na lewo i prawo.
