### ISSUE TITLE
Proszę o odbanowanie mnie na Discordzie xD #2

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#625]
Poprosiłem was, byście odbanowali moje konto, a zbanowali te drugie, lecz nawet nie powiedzieliście bym wszedł na konto MentosPL i że jestem odbanowany (nawet nie wiem czy dostałem faktycznie tego UB) i bez żadnego info, daliście mi bana ;)

Więc jakby nie patrzeć, bardzo chętnie banujecie!
gorzej z odbanowaniem...
Bana mam bez powodu ;) bo ProgramingWizzard miał zły dzień i miał ochotę trochę po banować od tak ;)
Konkretniej dostałem bana za zapytanie się, kiedy będzie update pluginu, ponieważ był problem z listenerem skrzynek i innych itemów, który opisałem w zgłoszeniu #590.

Więc uważam, że powinienem otrzymać unbana ;)

**Comment by MentosPL** [comment]
Issue jest jedynym sposobem by się skontaktować z wami, dla tego zamykanie "issue" bez wyjaśnienia sprawy (czyt. odbanowania) jest bez sensu.

**Comment by Kamilkime** [comment]
Nie, dostałeś bana za formę tego pytania, gdzie zarzucałeś ekipie FG opierdzielanie się i brak zainteresowania pluginem i jego community

**Comment by Kamilkime** [comment]
A nie ma co wyjaśniać - masz bana, wiadomo za co, ub nie będzie, tyle w temacie
