### ISSUE TITLE
Problem z TabLista.

### ISSUE THREAD

**Issue by facqman** [FunnyGuilds/FunnyGuilds#652]
Mam taki problem iż w po włączeniu opcji tablisty w pliku konfiguracyjnym i restarcie serwera tablista nie działa a na konsoli wyskakują problemy. Nie znam się na tych blendach wiec nie wiem co one oznaczaj.

Logi z konsoli:
https://pastebin.com/7MVghGLr

**Comment by Kamilkime** [comment]
Użyj silnika na wersję min. 1.8.8

**Comment by facqman** [comment]
Tablista się już wyświetla tylko ze jeszcze jeden błąd w konsoli wyskakuje a dokładnie jak ktoś wchodzi na serwer. 
https://pastebin.com/Qt5KmR38

**Comment by Kamilkime** [comment]
Ściągnij najnowszą wersję FG, tam powinno być to już poprawione
