### ISSUE TITLE
Propozycja dot. przedmiotów na gildie.

### ISSUE THREAD

**Issue by Crevsers** [FunnyGuilds/FunnyGuilds#653]
Witam,
Chciałbym zaproponować nową funkcję w FG, aby można było "wyłączyć" przedmiot na gildie.
Przykład: przedmiot informacyjny np. papier o nazwie "Przedmioty gracz" z jakimś opisem.
Jest on wymagany do stworzenia gildii, a więc dobrze by było jeśli by się dało dezaktywować taki przedmiot.

**Comment by Kamilkime** [comment]
Chyba... nie ogarniam co masz na myśli @Crevsers

**Comment by Crevsers** [comment]
Może w formie graficznej to przestawie:
https://imgur.com/a/bzhlL
Nie można stworzyć tzw. przedmiotu informacyjnego, ponieważ jest on później brany jako normalny item na gildie. Dobrze by było, gdyby można było wyłączyć taki przedmiot z użytku, ale by on się wyświetlał w gui.

**Comment by Kamilkime** [comment]
No... ale to by było bez sensu trochę. Możesz za to zrobić własne GUI, za pomocą np. **Chest Commands GUI**

**Comment by Kamilkime** [comment]
Dobra, wymyślę jakiś ładny sposób i dodam

**Comment by kacperduras** [comment]
Od wprowadzenia nowej konfiguracji przedmiotow na gildie uwzgledniana jest nazwa jak i lore - zamykam.

**Comment by Kamilkime** [comment]
Dodane w https://github.com/FunnyGuilds/FunnyGuilds/commit/b0208b0a3e2fafddaf7bfec45794cfcb7170ff30
Zbuduj sobie nowe FG przy użyciu FunnyCreator'a
