### ISSUE TITLE
Propozycja oraz bug.

### ISSUE THREAD

**Issue by Crevsers** [FunnyGuilds/FunnyGuilds#654]
Witam,
1. Wprowadzić tzw. blackliste przedmiotów na gildie, aby można było "wyłączyć" dany przedmiot przy tworzeniu gildii, ale żeby było on widoczny w GUI (przedmiot informacyjny).
2. Jeśli stworzymy przedmiot z samym "name" to nie będzie wyświetlana nazwa w przedmiotach na gildie, dopiero jak się doda "lore:" to wyświetli "name". Lore może być puste, ale musi być, bo inaczej nie wyświetli "name".

To ja czekam na FG 5.0 (⌐ ͡■ ͜ʖ ͡■)

**Comment by Kamilkime** [comment]
Zacznę pracę nad tym dzisiaj, skończę pewnie jutro wieczorem

**Comment by Kamilkime** [comment]
Dodane i naprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/b0208b0a3e2fafddaf7bfec45794cfcb7170ff30
Zbuduj sobie nowe FG przy użyciu FunnyCreator'a
