### ISSUE TITLE
Błędy i problem z uruchomieniem FunnyGuilds

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#664]
Najnowsza dev wersja (eef4178) - https://hastebin.com/icuyotozik.vbs

**Comment by Kamilkime** [comment]
Podeślij jeszcze cały log

**Comment by FastJoe0** [comment]
https://hastebin.com/viwuloraba.md

**Comment by Kamilkime** [comment]
Zbuduj może FG na nowo FunnyCreator'em. U nas wszystkich działa poprawnie, więc może coś się po prostu nie zbudowało jak trzeba

**Comment by FastJoe0** [comment]
Zrobiłem to ale niestety te same błędy się pojawiają. Nie mam żadnych pluginów oprócz FunnyGuilds.

**Comment by Kamilkime** [comment]
FunnyCreator'a też masz najnowszego?

**Comment by ManiecTV** [comment]
Silnik? /ver

**Comment by Kamilkime** [comment]
@ManiecTV masz wszystko w logu

**Comment by FastJoe0** [comment]
Kompilowałem za pomocą intelij oraz funnycreatora. W obu przypadkach ten sam efekt. To raczej chyba nie tego wina.

**Comment by Kamilkime** [comment]
A gdybyś użył tego .jar'a?
https://drive.google.com/open?id=1Pd3q_J8m4dMq7wzcnEtqTudr56CxYJyQ

**Comment by FastJoe0** [comment]
To samo niestety. https://hastebin.com/wobehafubi.md

**Comment by Kamilkime** [comment]
No, to ten u mnie na pewno działał. Spróbuj użyć jakiegoś innego silnika

**Comment by FastJoe0** [comment]
Zwykły spigot 1.8.8 - https://hastebin.com/atobaliseb.md
Błędy dalej są.

**Comment by Kamilkime** [comment]
Wrzuć jeszcze na hastebin swój config FG

**Comment by FastJoe0** [comment]
Standardowy. Zmieniłem tylko to aby plugin łączył się z bazą danych. https://hastebin.com/uriroraxis.cs

**Comment by Inuun** [comment]
probowales **wlaczyc** i **wylaczyc**? 🤔 

ew. wgrac najnowsza jave od nowa

**Comment by FastJoe0** [comment]
W jakim sensie włączyć i wyłączyć?

**Comment by kacperduras** [comment]
To wina loggera HikariCP dodanego w #663. Niestety-  tego typu działań Travis nie wykrył, póki co zalecam użycie najnowszej **stabilnej** wersji pluginu.

**Comment by Ixidi** [comment]
Spróbuj użyć tej wersji https://drive.google.com/file/d/1NkjaKJWA4YYu9Xk0zL4-bAqlPaKPJlyq/.

**Comment by FastJoe0** [comment]
Niestety też nie działa. https://hastebin.com/kodexacobu.md

**Comment by insertt** [comment]
@FastJoe0 spróbuj tej wersji, daj znać czy działa: https://ufile.io/2lslb

**Comment by FastJoe0** [comment]
Po naprawieniu błędu przez @kacperduras pojawił się inny błąd przy uruchamianiu: https://hastebin.com/oqalitafef.css

**Comment by Ixidi** [comment]
A wersja podeslana przez @insertt dziala?

**Comment by kacperduras** [comment]
Podobno tak, tyle że @insertt nie dał commita z fixem.

**Comment by FastJoe0** [comment]
Wersja z tego linku: https://ufile.io/2lslb który podesłał @insertt nie działa. Błędy się wyświetlają a FunnyGuilds się nie uruchamia.

**Comment by Ixidi** [comment]
`[Server thread/WARN]: ERROR StatusLogger Unable to locate a logging implementation, using SimpleLogger` Ten błąd, nie wpływa w żadnym stopniu na działanie pluginu.

**Comment by FastJoe0** [comment]
No niby tak jednak przedtem był ten błąd (https://hastebin.com/umopomepaq.sql) a teraz dla odmiany jest ten (https://hastebin.com/oqalitafef.css). Chodziło mi bardziej o to aby żadnych tego typu błędów nie było :)

**Comment by Kamilkime** [comment]
Tego błędu chyba już nie ma, przynajmniej ja u siebie nie widzę, na żadnej wersji MC, na najnowszym FG zbudowanym z użyciem FunnyCreator'a

**Comment by Ixidi** [comment]
Ja poprzedniego też nie miałem :V
