### ISSUE TITLE
Zakladanie gildi

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#667]
Moglibyscie dodac taka opcje zakladania gildi od danego rankingu(ten ranking mozna by bylo ustawic w configu)?

**Comment by Ixidi** [comment]
#666

**Comment by bgK1NG** [comment]
Juz pr sie pojawilo takze mozecie zamknąć

**Comment by dzikoysk** [comment]
Dodane przez @Ixidi w #666. Możesz sobie wygenerować build FunnyCreatorem lub poczekać na oficajlne wydanie :)
