### ISSUE TITLE
Escape

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#670]
Czesc, moglibyscie dodac komende /escape?
Polegalo by to na tym ze gdy gracz z gildi X jest na terenie gildi Y i jest w beczce nie ma jak sie wydostać. Po wpisaniu tego musialby czekac 120 sekund a w tym samym czasie gracze z gildi Y dostali by informacje ze ktos chce ucieknac z terenu ich gildi.

**Comment by Ixidi** [comment]
Jest w planach dodanie tego.

**Comment by bgK1NG** [comment]
Wlasciwie wyszedl juz addon funnyescape : https://skript.pl/temat/23409-funnyescape-ucieknij-z-terenu-przeciwnika/ lecz lepiej miec caly system gildi w jednym configu i jednym pluginie

**Comment by kacperduras** [comment]
Zaimplementowane w https://github.com/FunnyGuilds/FunnyGuilds/commit/28b15e3876b89dfe11186935a39bed72f1b06717
