### ISSUE TITLE
Dezaktywacja gildii

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#672]
Czesc, wiem ze daje duzo issue a nie dodaje PR bo dopiero sie ucze :/
Co do ISSUE, chodzi mi to zeby mozna bylo właczac/wyłaczac gildie za pomocą jakiejś komendy.

**Comment by Ixidi** [comment]
Nie rozumiem.

**Comment by kacperduras** [comment]
W sensie ją dezaktywować? A co by miała takowa dezaktywacja obejmować?

**Comment by bgK1NG** [comment]
Troszke zle okreslilem, chodzi mi tutaj o zdalne lub automatyczne wylaczenie możliwości zakladania gildii

**Comment by TheMajster** [comment]
Dopisz sobie.
Zmienną boolean(true) ogólną lub w obiekcie usera, potem przy zakładaniu gildi sprawdzaj czy ta zmienna jest false, jak tak to return;
A żeby zmienic zmieniasz wartosc zmiennej.

**Comment by kacperduras** [comment]
@TheMajster starczy jak dopiszesz w konfiguracji, po co tak kombinować?

**Comment by Ixidi** [comment]
>  za pomocą jakiejś komendy

**Comment by kacperduras** [comment]
@Ixidi chodzi o sposób zapisywania zmiennej, bo zarządzać to można za pośrednictwem komendy.
