### ISSUE TITLE
Wsparcie FeatherBoard/ MVdWPlaceholderAPI

### ISSUE THREAD

**Issue by WybuchowyAnanas** [FunnyGuilds/FunnyGuilds#674]
proponuję dodanie wsparcia FeatherBoard/ MVdWPlaceholderAPI przez plugin FunnyGuilds ;)

**Comment by kacperduras** [comment]
Na jakiej zasadzie miałoby działać takowe wsparcie? Jaki zakres miałoby obejmować?

**Comment by WybuchowyAnanas** [comment]
By szło dodać zmienne takie jak Kille/Zgony/Punkty Gildii/Aktualna Gildia oraz topkę graczy/gildii.

Zważywszy że FeatherBoard wspiera wiele sposobów konfiguracji, można by było ustawić by co jakiś czas klasyczny scoreboard się zmieniał w top 10 Gildii i top 10 graczy.

**Comment by mhaas11** [comment]
Możesz featherboarda pod mysql podłączyć. Powinien sciągać z bazy te zmienne

**Comment by kacperduras** [comment]
@mhaas11 lepiej dodać wbudowane wsparcie, zwłaszcza że plugin [posiada API](https://www.spigotmc.org/wiki/featherboard-api/).

**Comment by darknesscraft** [comment]
nowa wersja pluginu FunnyGuilds Tribute (#4.1.0) również ma spore problemy z kompatybilnością z wspomnianym featerboardem - podczas tworzenia gildii zanika scoreboard featerboarda, po relogu natomiast on wraca natomiast nazwy gildi widziane na tabie oraz nazwy gildi w nickach przestają działać.
Pluginy niesety się gryzą i nawzajmnie wykluczają.

**Comment by Kamilkime** [comment]
Zawieszam temat wsparcia dla MVdWPlaceholderAPI do czasu naprawienia go przez autora:
https://github.com/Maximvdw/MVdWPlaceholderAPI/pull/6
https://www.spigotmc.org/threads/mvdwplaceholderapi.86664/page-9#post-2953384
