### ISSUE TITLE
Błąd z TNT

### ISSUE THREAD

**Issue by DamageDMG** [FunnyGuilds/FunnyGuilds#675]
Co X restart tnt nie działa do momentu następnego restartu całego serwera, cały czas mam z tym błąd, wersja 4.0 fg, silnik 1.7.10-R0.1-SNAPSHOT edit.
W konsoli 0 błędów, wiadomość też żadna się nie wyświetla, nie zależnie czy jest to teren gildii czy nie.

**Comment by Kamilkime** [comment]
FG od wersji 4.0 wspiera tylko wersje MC od 1.8 w górę

**Comment by WybuchowyAnanas** [comment]
aktualizuj do 1.8, fg nie wspiera 1.7 xd
i fg 4.0.2 wyszedł więc ;)

**Comment by DamageDMG** [comment]
Używam 4.0, bo mam tam małego edita związanego z tabem.

**Comment by WybuchowyAnanas** [comment]
no to używaj nieaktualnej wersji, ale użyj spigota 1.8, ale zaleca się aktualizować  pulgin do 4.0.2 i jeszcze raz edytować taba jak tak bardzo chcesz :V 

pozdrów jułtuby jak zrobisz nowe izihace.

**Comment by Kamilkime** [comment]
No, to już żadnych dziwnych i edytowanych wersji FG na pewno nie wspieramy :)

**Comment by DamageDMG** [comment]
A co Ty chcesz wspierać, buga zgłaszam lel xd
Co ma mój edit do błędu z tnt?

**Comment by WybuchowyAnanas** [comment]
Ale w czym mają ci pomóc, jak edytowałeś plugin, i nie wiedzą co zagrzebałeś.

ekipa FG wspiera tylko oficjalne wersje, nie edytowane przez xyz.

**Comment by WybuchowyAnanas** [comment]
A twój błąd z tnt jest dla tego, bo wersja 4.0 nie wspiera 1.7.10 (1.8 wzwyż)

**Comment by DamageDMG** [comment]
To może powtórzę specjalnie dla Ciebie jeszcze raz - mój edit dodaje 2 classy związane z tabulatorem, nic więcej, a napewno nie związanego z tnt...

Jeśli błąd związany byłby z wersją silnika to tnt nie działałoby cały czas..

**Comment by hamsterofficial** [comment]
Rozumiesz, że NIKT CI NIE POMOŻE z wersją która jest pod 1.8.X BO NIE MAJĄ TAKIEGO OBOWIĄZKU. Więc nie dostaniesz pomocy.

**Comment by hamsterofficial** [comment]
*z wersją ktora masz pod 1.7.X

**Comment by Kamilkime** [comment]
Sprawa jest prosta - FG wspiera MC od 1.8 w górę + na pewno nie będziemy się zajmować błędem, który występuje w zedytowanej, nieoficjalnej wersji FG

**Comment by DamageDMG** [comment]
Załóżmy że mam ją na silniku 1.8 ku*wa, bo tam buguje się dokładnie to samo.... co teraz?

**Comment by Kamilkime** [comment]
Użyj najnowszej stabilnej wersji FG

**Comment by WybuchowyAnanas** [comment]
aktualizuj do 4.0.2 jak 4.0 na 1.8 nie działa xD

Albo podszywasz się pod DamageDMG albo jesteś naprawdę tępy XD

**Comment by DamageDMG** [comment]
Ehh, nie przyszedłem tutaj po Twoje odpowiedzi kamilkime bo nic one nie wnoszą, chce naprawić buga we WSPIERANEJ wersji a napewno nie chce jej zmieniać co już raz Ci powiedziałem kamilkime.......

**Comment by hamsterofficial** [comment]
Damage, do najnowszej wersji, zaktualizuj i tam sobie dodaj te classy. Bo my nie bedziemy Ci pomagac jezeli jest to "edytowany" FG, lub starsza wersje pod 1.7.X

**Comment by WybuchowyAnanas** [comment]
Twoja edytowana wersja nic nie wnosi ;)
Albo aktualizujesz plugin do najnowszej wersji, albo nie licz na support.
Skoro edytowałeś plugin na własną rękę, to i samemu dasz radę naprawić błąd z TnT ;)

**Comment by DamageDMG** [comment]
W oficjalnej wersji jest dokładnie to samo, przecież napisałem że nic to nie wnosi do tnt.
+ Starsze wersje na 1.7 nie są wspierane.

**Comment by Kamilkime** [comment]
Użyj silnika min. 1.8 i najnowszej oficjalnej wersji FG. Jeśli błąd nadal będzie występował - wtedy pogadamy

**Comment by DamageDMG** [comment]
Wybuchowy jest to wersja wspierana, więc nie wiem dlaczego nie miałbym liczyć na pomoc :)

**Comment by WybuchowyAnanas** [comment]
Ponieważ została przez ciebie edytowana. nie ważne czy zmieniłeś Autora w plugin.yml w jarze czy połowę kodu, edytowane to edytowane ;)

**Comment by DamageDMG** [comment]
Ile mam powtarzać jeszcze XD Oficjalna ma też błąd na silniku 1.8, wy nie umiecie czytać? Napisałem to wyżej XD

**Comment by kacperduras** [comment]
`silnik 1.7.10-R0.1-SNAPSHOT edit.` Zamykam, wspieramy wersje 1.8+. Jeżeli przedstawisz faktyczne dowody tego błędu na wersjach 1.8+ i na **oficjalnych** wersjach (nie żadnych forkach) - issue otworzę.
