### ISSUE TITLE
Problemy z pingiem - nie działające komędy.

### ISSUE THREAD

**Issue by DaanielZ** [FunnyGuilds/FunnyGuilds#676]
Cześć!

W wersji 4.0.1.1 jest problem z pingiem na tabie, a mianowicie na localhoscie jest po 6 mln pingu ;p
a wersja 4.0.2 nie działają komędy.

Nie ma żadnych błędów w konsoli.
![2017-12-08_23 17 02](https://user-images.githubusercontent.com/26363821/33787618-5da88838-dc6e-11e7-8b69-d61406886ce5.png)

**Comment by DaanielZ** [comment]
+ do tego nie aktualizuje się ranking gildii na tabie ;p

**Comment by insertt** [comment]
Ping nie jest liczony przez FunnyGuilds, jest pobierany z instancji gracza i na to nie mamy wpływu.
Ranking gildii (a właściwie top gildii) działa w ten sposób, że domyślnie zaliczają się do niego tylko gildie, które mają trzech lub więcej członków w gildii, można to zmienić w konfiguracji.

**Comment by DaanielZ** [comment]
okej, dawno nie używałem tego pluginu xd nie jestem na bieżąco.

**Comment by kacperduras** [comment]
@DaanielZ podeślij silnik, jutro postaram się zreprodukować te błędy i je naprawić.

**Comment by DaanielZ** [comment]
PaperSpigot 1.8.8 pobrany z https://ci.destroystokyo.com/job/PaperSpigot/443/
[FunnyGuilds - silnik.zip](https://github.com/FunnyGuilds/FunnyGuilds/files/1544000/FunnyGuilds.-.silnik.zip)

**Comment by insertt** [comment]
Myślę, że issue został rozwiązany, jeżeli problem z komendami nadal występuje - załóż nowy issue wraz z logiem startowym.
