### ISSUE TITLE
Lepsze GUI przedmiotow

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#677]
Witam, moglibyscie dodac w /przedmioty cos takiego: plugin by sprawdzal ile itemow potrzebnych na gildie ma gracz w ekwipunku a ile w enderchestcie, poczym pokazywal by ile ma % uzbieranych przedmitow.Jezeli jest to nie jasne, mozna wejść na serwer craftcore.pl i tam mamy to idealnie ukazane

**Comment by marcinkowalczyk2** [comment]
Czyli stan przedmiotów na gildie tylko, że po prostu pod /itemy.

**Comment by Kamilkime** [comment]
Mało wydajne by to było, trzeba by za każdym razem tworzyć indywidualnie inventory i liczyć te przedmioty :/

**Comment by TheMolkaPL** [comment]
Tych slotów w ekwipunku gracza i jego endercheście wcale nie jest tak dużo. Można to jeszcze dodatkowo cachować na wszelki wypadek (o ile to ma sens, bo ekwipunek się często zmienia).

**Comment by kamcio96** [comment]
Te propozycje coraz bardziej podchodzą pod addony. A później każdy serwer ma wszystko tak samo i ludzie narzekają że jedni kopiują drugich :/

**Comment by Kamilkime** [comment]
Można by FG przestawić na core + addony, ale nie wiem czy jest sens, gdy i tak każdy chce mieć wszystko 'autorskie', itd. Chyba za dużo zachodu z tym by było ;/

**Comment by kamcio96** [comment]
Nie sprawdzałem src dawno, jest opcja całkowitego wyłączenia jakieś komendy? Jeżeli tak to na pewno bardzo łatwo można takiego addona napisać.

**Comment by Kamilkime** [comment]
Nie, FG nie ma wyłączania konkretnych komend

**Comment by dzikoysk** [comment]
Od tygodnia w wolnym czasie pracuje nad czymś większym, poniekąd będzie się mogło też wiązać z bardziej modułowym podejściem do pluginu. Na razie jednak dodawałbym tak jak wcześniej - wszystko z możliwością wyłączenia

**Comment by TheMolkaPL** [comment]
Myślicie, że dzisiaj ktoś konfiguruje FunnyGuilds? :D Wrzuca plugin na serwer i ma działać. Co najwyżej tworzy jeszcze temat na MPC z pytaniem, czy podeśle gotową konfigurację.
