### ISSUE TITLE
Dodanie "Bugowania się klockami"

### ISSUE THREAD

**Issue by iSopik** [FunnyGuilds/FunnyGuilds#678]
Jestem za dodaniem bugowania sie oraz dla tych którzy by poprostu tego nie chcieli to dodanie do configu np. BugowanieKlockami: True/False.

**Comment by MrGregorix** [comment]
#536

**Comment by iSopik** [comment]
DLA TWÓRCY PLUGINU: Gdy podałeś src fg jest potrzebne jakies api,którego nie posiadam. Mogłbyś gdzieś wstawić linka ?

**Comment by Kamilkime** [comment]
@iSopik Wszystko, co potrzebne do np. własnej edycji pluginu, znajdziesz w repozytorium pluginu tu, na GitHub'ie

**Comment by iSopik** [comment]
Dziękuję Kamilu.

**Comment by iSopik** [comment]
@Kamilkime a nie potrzebuję czasem .jar do pozbycia sie errorow ? bo z tego co tu widzę to jest tu kod nie .jar lub nie ogarniam jeszcze githuba....

**Comment by Kamilkime** [comment]
@iSopik No... nie rozumiem co masz za problem? W repo masz kod FG oraz plik pom.xml, który podpina potrzebne biblioteki za pomocą maven'a

**Comment by kacperduras** [comment]
Temat wyjaśniony, blokuję dyskusję w tym issue.
