### ISSUE TITLE
Eventy, do użycia w innych pluginach na zasadzie API

### ISSUE THREAD

**Issue by Kamilkime** [FunnyGuilds/FunnyGuilds#683]
Dodanie eventów, dzięki którym inne pluginy będą mogły używać prostego Bukkit'owego Listenera, żeby móc uzyskiwać różne informacje, np. RankChangeEvent wywoływany po śmierci gracza, który będzie zawierał zmiany rankingu i inne podobne eventy

**Comment by Koiczek** [comment]
Nie ma za co XD

**Comment by dzikoysk** [comment]
Było już w planach w sumie od dawna, ale niech wisi, może ktoś wprowadzi w końcu

**Comment by kamcio96** [comment]
Na 99% to olejecie i się nie dziwię, ale linkuje https://github.com/kamcio96/KGildieAPI

W sumie może bym dokończył to

**Comment by kacperduras** [comment]
W jakim pakiecie stworzyć klasy reprezentujące eventy wspomniane przez @Kamilkime ?

**Comment by dzikoysk** [comment]
Można albo wydzielić osobną typu `api` ogólnie - chciaż pytanie czy będzimy to rozwijać w inną sronę - albo wrzucić w `events`. Struktura i tak pewnie będzie za jakiś czas zmieniana, wieć bez różnicy, mi osobiście lepiej leży druga opcja

**Comment by Kamilkime** [comment]
Myślę, że najlepiej po prostu zrobić pakiet **event**

**Comment by dzikoysk** [comment]
Raczej nie będzie w tej paczce jakiegoś osobnego systemu eventów, więc liczba mnoga jest jak najbardziej ok :)

**Comment by TheMolkaPL** [comment]
Może podzielić na moduły Maven - `funnguilds-api` i `funnyguilds-plugin`?

**Comment by MrGregorix** [comment]
Nie można, kłóci się to z moją religia.

**Comment by TheMolkaPL** [comment]
Jaką religia? O_o

**Comment by kacperduras** [comment]
@MrGregorix wyjdź.
@TheMolkaPL teoretycznie byłoby to lepszym rozwiązaniem, w praktyce to rozwiązanie nawet nie jest warte świeczki. Nie ukrywajmy, wiemy kto będzie korzystał z tego API i nie będą to programiści Oracle czy Google. Osobny pakiet na te eventy starczy. Już się biorę do roboty. Może jakaś rozpiska tych eventów?
@kamcio96 jeszcze tylko lomboka brakuje w projekcie xD

**Comment by dzikoysk** [comment]
Zostańmy przy eventach na razie

**Comment by Kamilkime** [comment]
Moim zdaniem do zamknięcia, zostało to już dodane
