### ISSUE TITLE
Import projektu do eclipse.

### ISSUE THREAD

**Issue by KrifixYT** [FunnyGuilds/FunnyGuilds#687]
Witam!
Posiadam problem z przenoszeniem projektu do eclipse.
Moglibyscie napisac krok po kroku jak to zaimportować? Wyswietlaja mi sie takie bledy: https://imgur.com/a/azlhO

Pozdrawiam!

**Comment by Kamilkime** [comment]
No, FG używa jeszcze innych bibliotek, więc musiałbyś dograć sobie do Eclipse Maven'a, za jego pomocą pobrać kod bibliotek i dopiero wtedy edytować FG

http://www.eclipse.org/m2e/

**Comment by KrifixYT** [comment]
Dobra, dzieki odezwe sie jeszcze.

**Comment by KrifixYT** [comment]
Teraz mam inny problem: https://imgur.com/a/dh36H

**Comment by TheMolkaPL** [comment]
Jaki problem? Są tylko podkreślenia. Skąd mamy wiedzieć jaki jest problem.

**Comment by Kamilkime** [comment]
Do src masz wrzucone foldery main.java, które są typowe dla intelki. W eclipse do src wrzucasz dopiero folder net.dzikoysk...

**Comment by TheMolkaPL** [comment]
W Maven pliki .java umieszcza się w src/main/java. Tak musi zostać, bo inaczej Maven tego nie skompiluje.

**Comment by TheMolkaPL** [comment]
IDE nie ma nic wspólnego z FunnyGuilds. Eclipse nie wspiera Mavena (heh ... czego on nie wspiera :D), więc ma swoje problemy. Zawsze można pisać w notatniku. Zamykam.

**Comment by Kamilkime** [comment]
Wspiera maven'a, wystarczy plugin m2eclipse. @KrifixYT pewnie ma zwykły java project, zamiast kompatybilnego z maven'em

**Comment by KrifixYT** [comment]
Mam zwykly :)

**Comment by KrifixYT** [comment]
tylko niewiem jak stworzyc projekt maven :)

**Comment by TheMolkaPL** [comment]
Nie musisz tworzyć projektu, bo FunnyGuilds to projekt już istniejący. Pobierasz FunnyGuilds i otwierasz w IDE.
