### ISSUE TITLE
Pobieranie API.

### ISSUE THREAD

**Issue by iSopik** [FunnyGuilds/FunnyGuilds#688]
Jak niby mam wgrać to API Pandalang itp ??? tak jak Kamil mówił niby ma pobierać z pom.xml za pomocą mavena ale mi nic nie pobiera! mógł by mi ktoś wytłumaczyć jak mam pobrać to API gdzie je wrzucić jakie package ?

**Comment by Kamilkime** [comment]
Używa się maven'a i on wszystko pobiera i podpina sam

**Comment by iSopik** [comment]
A możesz mi wytłumaczyć jak go użyć ?

**Comment by TheMolkaPL** [comment]
Zainstaluj Mavena. Instrukcja instalacji znajdują się w pliku readme, po wypakowaniu pobranego archiwum. Następnie przejdź do folderu gdzie znajduje się FunnyGuilds, wciśnij shift i jednocześnie wciśnij PPM. Z menu kontekstowego wybierz otwarcie konsoli. W konsoli wpisz `mvn clean install`. Maven sam pobierze wszystkie potrzebne biblioteki i skompiluje gotowe FunnyGuilds jako plik JAR na podstawie istniejących klas kodu źródłowego.

**Comment by iSopik** [comment]
Tak ,ale ja bym potrzebował package z klasami do wrzucenia do src abym nie miał błedów i mógł go troszkę zedytować. zauważyłem już FunnyCreator ,lecz nie poterzebuje .jar ja potrzebuje folder src bez błedów!

**Comment by Kamilkime** [comment]
To przecież jest na GitHub'ie cały kod

**Comment by TheMolkaPL** [comment]
Nic nigdzie nie trzeba wrzucać. Maven pobierze i zainstaluje biblioteki samoczynnie.

**Comment by Kamilkime** [comment]
Moim zdaniem do zamknięcia

**Comment by insertt** [comment]
Pytanie uzyskało wyczerpującą odpowiedź, gdybyś miał jeszcze jakieś pytania - zapraszamy do stworzenia nowego issue.
