### ISSUE TITLE
Problem z informacjami o gildii, itemami oraz dodawaniem do gildii

### ISSUE THREAD

**Issue by Avilon1** [FunnyGuilds/FunnyGuilds#690]
* Po wpisaniu komendy /ga dodaj i losowego nicku gracz zostaje dodany do gildii i utworzony w bazie danych np. /ga dodaj TEST aidadajdkljkj - i ten gracz zostaje dodany do gildii + zostaje utworzony na tab i w bazie danych.
* Gdy chce zeby do zalozenia gildii byl np. blok diamentu i wpisuje - 64 diamond_block , - 64 diamond block itd. to pisze air lub samo diamond
* Po zalozeniu gildii i kliknieciu prawym na jajko pojawia sie 2x wiadomosc z informacjami o gildii ( z konta admin i konta gracz tez )

**Comment by insertt** [comment]
Wszystkie rzeczy są naprawione w najnowszej wersji indev, wystarczy poczekać na release lub zbudować za pomocą [FunnyCreatora](https://github.com/FunnyGuilds/FunnyCreator)
