### ISSUE TITLE
Dodanie możliwości wyłączenia itemów na gildie

### ISSUE THREAD

**Issue by Koiczek** [FunnyGuilds/FunnyGuilds#691]
Proponuję dodanie możliwości wyłączenia itemów na gildie. Chyba , że się da to prosiłbym o powiedzenie jak to moge zrobić.

**Comment by dzikoysk** [comment]
`items: []` 
`items-vip: []`

**Comment by kamcio96** [comment]
@Koiczek kiedy twoje proxy?

**Comment by PomocnyBartek** [comment]
@kamcio96 kiedy myhard?

**Comment by kamcio96** [comment]
@PomocnyBartek obserwuj fb ;)
