### ISSUE TITLE
Dodanie komendy /resetujranking?

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#696]
Witam, jest możliwość dodania komendy /resetujranking która za wybrany item w configu ustawiała by ranking gracza do domyslnej wartosci?

**Comment by PanKlipcio** [comment]
### Ranking gracza świadczy o tym jak dobrze dana osoba się bije. 
Jeśli ktoś nie umie się klepać to reset rankingu nic nie zmieni.

**Jestem na nie.**

**Comment by Kamilkime** [comment]
No... Ale co ci przeszkadza taka komenda @PanKlipcio?

**Comment by bgK1NG** [comment]
@PanKlipcio , zawsze mozna dac item ktorego gracz nie zdobedzie i tyle,a resetuj ranking nie musi resetowac zabojstw i smierci tylko sam ranking

**Comment by Kamilkime** [comment]
Z tego co wiem, to @RabbitTheDEV planował dodanie wyłączenia tej komendy w całości
