### ISSUE TITLE
Skrypty w FG 

### ISSUE THREAD

**Issue by RabbitTheDEV** [FunnyGuilds/FunnyGuilds#697]
Witam, przychodzę z propozycją dodania "skryptów".
Kiedyś była też implementacja owych skryptów w pandzie, lecz nie wszyscy "kumali" o co chodzi.
Najlepiej byłoby wykorzystywać składnie w języku angielskim i używać rozszerzeń plików .fg
Jako programista bardzo chętnie wam pomogę, pozdrawiam.

**Comment by Kamilkime** [comment]
Ale to teraz cały system skryptów pisać? Dużo trochę :/

**Comment by RabbitTheDEV** [comment]
Można byłoby nawet zrobić płatną wersję fg. Może to jest śmieszne, ale bardziej zmotywuje twórców, a dużo serwerów używa tego pluginu i używają dodatków w pluginie Skript, każdy na tym skorzysta.

**Comment by dzikoysk** [comment]
Na pewno fg nie dostanie własnego skryptowego języka oraz nie będzie płatne (jako plugin sam w sobie). Po ogarnięciu kodu i kilku wcześniejszych pomysłów będzie można myśleć o dodaniu wsparcia dla skryptów w groovym, jsie, pandzie czy skriptcie

**Comment by RabbitTheDEV** [comment]
Jak już to można dodać addona do skripta, ale phi - to jest banalnie proste i nie optymalne.
Drugą najmądrzejszą opcją jest twoja panda :)

**Comment by marcinkowalczyk2** [comment]
Na forum skript.pl jest jakiś addon do FunnyGuilds, ale on tylko zawiera expressions'y, które zwracają, np. punkty, gildie itd. Głównym powodem, dlaczego powstał to było to, aby można było w skrypcie zrobić sidebar.
