### ISSUE TITLE
Błąd z dodawaniem graczy do gildii

### ISSUE THREAD

**Issue by krzukosz** [FunnyGuilds/FunnyGuilds#698]
Witam, jest w błąd a mianowicie nie raz jest wiadomość "Ten gracz nie był nigdy na serwerze" przy próbie dodania do gildii lub występuje taki błąd jeżeli już uda się go dodać do gildii https://imgur.com/a/GGqhs

**Comment by Kamilkime** [comment]
No błagam... Po pierwsze - z samego screena nic nie wynika, brakuje twojego opisu co na nim jest błędem. Po drugie - właśnie ten opis! Opisz jakie komendy są wykonywane, co gracz robi, czy jest online, itd. - to ma być porządny opis, żebyśmy wiedzieli co dokładnie się dzieje i mogli szukać w kodzie...

**Comment by krzukosz** [comment]
1. Najpierw nie dało się zaprosić gracz do gildii bo pisało że taki gracz nigdy nie był na serwerze.
2. Dodałem go komendą /ga add niby był wpisany w gildii a pisało że ten teren nie należy do niego.
3. Usuneli gildie kazaliśmy założyć temu co nie mógł dołączyć i udało mi się założyć ale znowu nie mógł zapraszać innych osób. 
Próbowałem reloadować serwer, restartować, zapisywać dane do mysql. nic.

**Comment by Gaway69** [comment]
Problem ten u mnie na serwerze również powstał korzystając z fg 3.9.15 wszystko było git a na next edycji zaczęły się dziać takie rzeczy , dodałem regułkę do mysql zablokowującą duplikowanie się NAME co konsekwencja było to iż niektórzy gracze tracili punkty . Robiąc serwer na 1.12 na najnowszych FG dalej mam ten problem

**Comment by Kamilkime** [comment]
Coś miesza przy UUID - może bungee, może plugin od logowania, ale FG samo z siebie nic nie psuje

**Comment by insertt** [comment]
Commit https://github.com/FunnyGuilds/FunnyGuilds/commit/9032025f49135ea8fcd52cd5f371957cba118c4c sprawił, że fg od teraz działa na UUID, a nie na nazwach jak było wcześniej, więc zalecam skorzystać z [FunnyCreatora](https://github.com/FunnyGuilds/FunnyCreator)

**Comment by insertt** [comment]
Z powodu odpowiedzi zwrotnej zamykam issue - gdybyś miał jakiekolwiek pytanie/problem, stwórz nowy issue z opisem :-)
