### ISSUE TITLE
Dublowanie graczy w bazie FunnyGuilds, dosyć pilne.

### ISSUE THREAD

**Issue by SzymoonDev** [FunnyGuilds/FunnyGuilds#699]
Witam, od paru dni na serwerze używam najnowszej wersji pluginu FunnyGuilds, lecz już widzę pierwsze problemy. Nawiązując do #698: Plugin w bazie dubluje użytkowników, dlatego czasami pokazuje się, że nie można dodać gracza do gildii, albo go nie wyświetla w topce graczy, ponieważ jego konto jest zdublowane.
Moje przypuszczenia są takie, że gdy gracz wbije o nicku "ElooO134" z innym uuid, a następnie ktoś inny wbije na nicku "eLOOo134" z innym uuid, to plugin go doda do bazy, ponieważ jego uuid się różnią chociaż że nicki różnią się tylko wielkościami liter. Jak to wygląda w bazie: https://scr.hu/p23J7O 
Nie wiem czy to słuszne przypuszczenie, ale jedyne jakie zdążyłem wywnioskować. Patrząc na bazę fg, dużo graczy ma takie zdublowane konta.
Przeszukałem dokładniej bazę, znalazłem nawet takie konta: https://scr.hu/mPVJ9J
Nick nic się nie różni, a konto zdublowane. Dlaczego? Nie wiem, to już wewnętrzny bład.
Pozdrawiam i heppi nju jear.

**Comment by SzymoonDev** [comment]
Takie dodatkowe info:
BocieQ
Online-mode UUID: none
Unavailable

Offline-mode UUID: 5ece48e5-ddc0-3a88-b26b-ac63ac137c37

**Comment by Kamilkime** [comment]
@SzymoonDev Jakiego silnika używasz i na jakiej wersji MC?

**Comment by kamcio96** [comment]
Jeżeli chodzi o różnice wielkości znaków w nicku to jest to wina pluginu na logowanie. Tam powinno być `ignore case`. Zaraz zobaczę do kodu FG, może znajdę coś ciekawego 😁

**Comment by krzukosz** [comment]
![](https://image.prntscr.com/image/ZyUeTgzpQuiz_oKocm0tMg.png)
Ja mam to zabezpieczone
@kamcio96

**Comment by Kamilkime** [comment]
Sam spigot? Nie np. TacoSpigot?

**Comment by SzymoonDev** [comment]
Sam spigot.

**Comment by kamcio96** [comment]
@krzukosz to dobrze, zabezpieczyć to można na 3 sposoby. Tak że zmienia nick "w locie", kick albo traktuje tych 2 graczy tak samo. 

@SzymoonDev gracze mogą nie przejść przez lobby? Masz na pewno dobrze skonfigurowana sieć?

**Comment by SzymoonDev** [comment]
Kurcze... 900 graczy jest więc raczej dobrze jest skonfigurowane. 
Mówię, że w AuthMe jest ustawiona opcja, aby nie móc bugować nicku, zmieniając wielkość znaków, więc to odpada jak problem dublowania.

**Comment by Kamilkime** [comment]
No, ale nigdy nie było żadnych problemów z FG, nikt nic nie grzebał, a ja nie widzę nic, co by się mogło psuć :/

**Comment by SzymoonDev** [comment]
W 3.X nie było takich problemów, a w 4.X już takowe są.

**Comment by Kamilkime** [comment]
Ale która to już wersja FG 4.x, a błąd dopiero teraz ;/

**Comment by krzukosz** [comment]
@Kamilkime a może coś się ze sobą gryzie w fg?

**Comment by dzikoysk** [comment]
Meh, zmusiliście mnie do sprawdzenia :/ Trudne nie było, Wizzard zepsuł i od wersji 3.9.9.9 wychodzą takie takie kwiatki w zapisie

https://github.com/FunnyGuilds/FunnyGuilds/commit/70bd518e3cfa46d10451306240a06479c92fa1de#diff-34cb314dd284ded67bff5c902270ae5eR353

Z całego systemu pobierania userów wyleciało sprawdzanie wielkości liter, więc w cache wrzuca coraz to nowych graczy. Dodatkowo `get(Player)` zmienił też z pobierania nazwy gracza na uuid więc to już totalnie siadło.

**Comment by kamcio96** [comment]
🕹️ to wina pluginu na logowanie (gracz kamcio96 i Kamcio96 to 2 osobne konta, logowanie powinno pilnować nicków i kont). Dziwne że wgl FG sprawdza nicki w jakikolwiek sposób. Może zdecydujcie się na bazę UUID albo nicki ;P

**Comment by dzikoysk** [comment]
Głupotą jest operowanie na UUID na serwerach offline, gdzie generowane UUID jest zależne właśnie od wielkości liter. 

`UUID.nameUUIDFromBytes(("OfflinePlayer:" + name).getBytes(Charsets.UTF_8)`

To nie jest normalne, że przez wielkość liter są to 2 różne konta. Zostaje ignorowanie wielkości liter, jak to wcześniej było ¯\_(ツ)_/¯.

**Comment by kacperduras** [comment]
```
Ja mam to zabezpieczone
```
@krzukosz Świetnie, ale co nas to obchodzi?
```
Moje przypuszczenia są takie, że gdy gracz wbije o nicku "ElooO134" z innym uuid, a następnie ktoś inny wbije na nicku "eLOOo134" z innym uuid, to plugin go doda do bazy, ponieważ jego uuid się różnią chociaż że nicki różnią się tylko wielkościami liter. 
```
To nie ten sam gracz, dlatego UUID są rożne - i to jest normalne.
```
Przeszukałem dokładniej bazę, znalazłem nawet takie konta: https://scr.hu/mPVJ9J
Nick nic się nie różni, a konto zdublowane. Dlaczego? Nie wiem, to już wewnętrzny bład.
```
Miałem kiedyś podobne kwiatki u klienta, miało to związek z autoryzacją kont premium.
```
Meh, zmusiliście mnie do sprawdzenia :/
```
Wybacz :\
```
Trudne nie było, Wizzard zepsuł
```
Jak to brzmi ( ͡° ͜ʖ ͡°) i dzięki że oznaczyłeś, gdyby nie @krzukosz napisał mi na Facebooku to bym się o tym issue nie dowiedział (dzięki!). 🕹
```
to wina pluginu na logowanie
```
A że 90% użytkowników FG sobie tego nie dopilnuje to inna kwestia - za głupotę się płaci.
```
Głupotą jest operowanie na UUID na serwerach offline
```
Głupotą jest nieprzygotowanie autoryzacji pod takie ewentualności.
```
To nie jest normalne, że przez wielkość liter są to 2 różne konta.
```
Dlaczego niby to nie jest normalne? Przecież nick jest inny. Przecież taki gracz `tester` nie jest graczem o nicku `TeStEr`.
```
Na razie myślimy nad łączeniem duplikatów w jednego usera :/
```
Najlepiej zrobić komende walidującą bazę danych.
```
Naprawienie samego błędu problem nie jest
```
Bo nie jest - wystarczy odpowiednia autoryzacja, walidacja duplikatów i tyle - po co inne cuda i cudawianki na kiju? Toć to offline-mode, wiadomo co jest pisane kiedy się odłączy od autoryzacji Mojangu.

**Comment by dzikoysk** [comment]
Masz powiadomienia przecież jako członek, więc co się denerwujesz :/
* Jest tym samym graczem, znajdź mi jeden normalny serwis, gdzie to byłyby dwie różne osoby
* To nie jest jego wina, plugin powinien działać w obu przypadkach 
* Łączenie tych danych to kolejny system do napisania na podstawie lipnego już ładowania. Zostają gracze z różnymi rankingami, statami, a może i gildiami, przyjemne to nie będzie

**Comment by kacperduras** [comment]
```
Masz powiadomienia przecież jako członek, więc co się denerwujesz :/
```
Nie jestem memberem :\

```
Jest tym samym graczem, znajdź mi jeden normalny serwis, gdzie to byłyby dwie różne osoby
```
Na premium ten sam, ale tutaj teraz mowa o offline i jego urokach.
```
To nie jest jego wina, plugin powinien działać w obu przypadkach
```
Jego, świadomie wyłącza - świadomie ryzykuje.
```
Łączenie tych danych to kolejny system do napisania na podstawie lipnego już ładowania. Zostają gracze z różnymi rankingami, statami, a może i gildiami, przyjemne to nie będzie
```
+1

**Comment by kamcio96** [comment]
Nie kumam, `tester` i `TeStEr` to 2 różne konta, dlaczego FG musi mieć problem z tym? A co jeżeli gracze będą zmieniać nick nawet na premium? Po prostu operowanie na UUID jest zawsze pewne, a nick tylko jako opcja wyświetlania np na stronie. Z tego co wiem bukkit już dawno zrezygnował z identyfikacją po nicku
`To nie jest jego wina, plugin powinien działać w obu przypadkach` jakich obu przypadkach? A do tego masz jeszcze logowanie na bungee? 
Prosta zasada, logowanie nadaje UUID, FG odczytuje i na podstawie tego działa, a nicki w bazie się aktualizują i tyle.

**Comment by SzymoonDev** [comment]
Jak już mówiłem, mamy zabezpieczone aby nie bugować nicków w AuthMe więc nawet nie wiem dlaczego takie konta znalazły się w tej bazie. Sprawdziłem jeszcze raz i się nie mylę.

**Comment by Kamilkime** [comment]
Jeśli masz to zabezpieczone - to trochę nie ma jak być wina FG. FG tylko pobiera UUID, a jeśli już je generuje - zawsze tak samo, więc jeśli gracz zawsze musi wejść z tego samego nicku - FG musi dostać złe UUID dla tego samego nicku, żeby zduplikować rekord

**Comment by SzymoonDev** [comment]
https://scr.hu/mPVJ9J

**Comment by Kamilkime** [comment]
Tyle to ja wiem, ale mówię - moim zdaniem to nie wina FG, tylko coś innego psuje podawanie UUID. Ale co do samego FG - można by wywalić w ogóle nick z User'a, działać tylko po UUID, a do pobierania po nicku, itd. mieć tylko jedną, oddzielną mapę <UUID, String>, która aktualizowałaby się przy wejściu gracza na serwer

**Comment by kamcio96** [comment]
@SzymoonDev sprawdź czy Ci się nie wyłączyło przekazywanie uuid z bungee. Może być po stronie bungee lub serwera

@Kamilkime nie zapomnij o updacie do bazy dla stron 😁

**Comment by Kamilkime** [comment]
A, to nick w User'ze musi zostać, fakt ;/

**Comment by kamcio96** [comment]
Nie, update iść za każdym wejściem gracza, przy obecnym stanie FG nie wpłynie to na wydajność XD

**Comment by Kamilkime** [comment]
Tu by ogólnie wypadało wymyślić coś nowego, lepszego, na nowo ten system napisać

**Comment by Kamilkime** [comment]
@SzymoonDev @krzukosz Czy moglibyście napisać nam listę używanych pluginów, najlepiej z ich wersjami? Tylko faktyczne nazwy, bo wiem, że niektórzy sobie zmieniają na 'swoje'
