### ISSUE TITLE
Poważny error.

### ISSUE THREAD

**Issue by MrGregorix** [FunnyGuilds/FunnyGuilds#701]
Moja ranga na discordzie jest nieprawidłowa :/

**Comment by dzikoysk** [comment]
Obrażanie najlepszych gier we wszechświecie i oszukiwanie w grach :/

![image](https://user-images.githubusercontent.com/4235722/34463679-e0ef82bc-ee63-11e7-83d2-f893afbfe689.png)

**Comment by MrGregorix** [comment]
Screen jest sfabrykowany

**Comment by MrGregorix** [comment]
![image](https://user-images.githubusercontent.com/6236117/34463708-fa41eed4-ee64-11e7-982c-d371ea70df26.png)

**Comment by dzikoysk** [comment]
To tylko szkic sprawcy sporządzony przez doświadczonych specjalistów. Sprawa ma wymiar najwyższego szczebla, dlatego nie wszystkie dokumenty mogą zostać upublicznione. Jako jedne potwierdzenie słuszności tych decyzji pozostawiam ten o to dowód rzeczowy

![obraz](https://user-images.githubusercontent.com/4235722/34463711-17ae094e-ee65-11e7-9251-efa1eed025ce.png)

**Comment by happiii** [comment]
Potwierdzam, wersja grega jest prawdziwa, a dzikoyska nieprawdziwa.

**Comment by MrGregorix** [comment]
Wiadomośc którą usunałem nie dotyczyła archalaxy tylko komunizmu kamila, martwiłem się o stan serwera dlatego usunąłem jego propagandowe wiadomośći.

**Comment by Kamilkime** [comment]
Popieram dzikoyska, greg kłamie i propaguje ten szkodliwy kapitalizm

**Comment by MrGregorix** [comment]
Chyba przypadkiem pomyliły ci się tagi.

**Comment by Oskarr1239** [comment]
Popieram gregorego :/
