### ISSUE TITLE
Błędy po włączeniu tablisty (FunnyGuilds v4.0.2 Tribute-33cd1e8)

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#702]
Na serwerze nie mam nic zainstalowane oprócz FunnyGuilds

Jedyne co zmieniłem w konfiguracji to:
`player-list-enable: true`

https://hastebin.com/qojagogove.sql

**Comment by Kamilkime** [comment]
@FastJoe0 Najlepiej zmień silnik, w tym z jakiegoś powodu brakuje jednej z klas, która jest potrzebna w FG

**Comment by FastJoe0** [comment]
Zmieniłem na PaperSpigot 1.8.8 i dalej to samo. https://hastebin.com/aqozorudaz.sql

**Comment by Kamilkime** [comment]
No, był zbyt ogólny warunek, który działał na 1.8, jednak TacoSpigot powinien działać bez problemu. Jak wejdą zmiany z #703 - zbuduj sobie nowe FG [FunnyCreator'em](https://github.com/FunnyGuilds/FunnyCreator/releases/tag/1.0.5) :)

**Comment by FastJoe0** [comment]
Ok chyba naprawione :). Przynajmniej nie wyrzuca błędów.

**Comment by RabbitTheDEV** [comment]
@dzikoysk Problem został rozwiązany oraz @Kamilkime dodał fix'a. Issue do zamknięcia.

**Comment by insertt** [comment]
Problem został rozwiązany - gdybyś miał jakiekolwiek pytanie/problem, stwórz nowy issue z opisem :-)
