### ISSUE TITLE
Opcjonalność cuboida.

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#704]
Może warto rozważyć możliwość wyłączenia systemu cuboidów? Generalnie to by umożliwiło zastosowanie FG na serwerach typu PvP, gdzie takowe cuda na kiju nie są potrzebne.

**Comment by RabbitTheDEV** [comment]
Chodzi ci o to, aby jajo się nie tworzyło? Czy jak

**Comment by Kamilkime** [comment]
Żeby w ogóle regionu nie tworzyło, w sumie dobry pomysł

**Comment by KawaiiGuilds** [comment]
Dobrze myślisz Eliot

**Comment by Fumon437** [comment]
Dokładnie, dodać opcję w konfiguracji dot. wyłączenia cuboidów, innych pierdół które nie we wszystkich przypadkach są potrzebne. Fajnie by mieć większą kontrolę nad tym co chcemy a czego nie chcemy aktywować chociażby ze względu na to, że nie chciałbym aby moi gracze tworzyli jajka smoka w lobby serwera PvP. W skrócie, poniekąd przystosować ten plugin pod serwery typowo PvP, bez otwartego świata, stworzone na arenkach itp. gdzie nie chcemy griefu związanego z jajkami smoka czy innymi dziwactwami.

**Comment by Reedzev** [comment]
Funnyguilds, a może funnyteams? :thonk:

**Comment by CzokusDEV** [comment]
Dobry pomysl ;D 
Ale moze lepiej zrobic osobny plugin i stworzyc jakies FunnyApi albo cos ? I Dzieki temu stworzyc cos w stylu funnyteams?
