### ISSUE TITLE
Error przy usuwaniu gildii oraz propozycja oddawania itemów po nieudanej teleportacji

### ISSUE THREAD

**Issue by DaanielZ** [FunnyGuilds/FunnyGuilds#705]
Hej, znalazłem błąd, że jeżeli będziemy chcieli teleportować się do bazy i będziemy mieli itemy itp.
Wpiszemy /baza, a będziemy mieli pełne eq i się ruszymy, to itemów nam nie odda, wszystko pokazane na filmiku.

https://youtu.be/INB5OyS4BvY

Błędów w konsoli nie ma, było to robione na silniku spigot 1.8.8 najnowszym,
na serwerze był tylko worldedit i gildie.

I jeszcze taka propozycja xD
wszystko na filmiku xD
https://youtu.be/4RRZ3wyVCJ4

**Comment by Kamilkime** [comment]
1. Moim zdaniem to ma sens, jego wina, że się ruszył, teleportacja w końcu została rozpoczęta
2. Już jest taka propozycja w #561 

To co, #705 do zamknięcia? =)

**Comment by DaanielZ** [comment]
Dobra, to teraz znalazłem błędy.
Nie wiem czy jakieś poważne błędy, nie przyglądałem sie kodowi, język polski taki trudny xd

Konsola:
https://hastebin.com/kijaciqago.md
Setup ten sam co wcześniej.

Filmik:
https://youtu.be/kczEih2OAMI
