### ISSUE TITLE
{G-TOP} nie działa

### ISSUE THREAD

**Issue by YTSkaGamerPL** [FunnyGuilds/FunnyGuilds#707]
Proszę o pomoc, jak wpisuje komende /top to piszę mi Brak. Na tabie tak samo. Korzystam z najnowszej wersji pluginu, stąd pobrałem (Tribute 4.0.2)

**Comment by kacperduras** [comment]
Masz świadomość tego, że ranking gildii jest brany dopiero od n* ilości członków?

* - wartość do ustawienia w konfiguracji

**Comment by YTSkaGamerPL** [comment]
Sprawdze

**Comment by YTSkaGamerPL** [comment]
Niby gdzie to jest?

**Comment by Kamilkime** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L75
