### ISSUE TITLE
Błąd dodawania Gildii

### ISSUE THREAD

**Issue by RafiXDD** [FunnyGuilds/FunnyGuilds#708]
Kiedy dodaje sie gildie jest ona dodawana rozniez do top listy graczy!

**Comment by Kamilkime** [comment]
Ale że co?

**Comment by kacperduras** [comment]
Mógłbyś wytłumaczyć to jaśniej?

**Comment by RafiXDD** [comment]
Tworze gildie dodaje sie ona do Top gildii na tabie, ale również na top graczy tak jakby Pl traktował gildie jako gracza normalnie można sprawdzic 
Sprawdzić punkty Gildii w sposób jaki sie sprawdza punkty gracza /gracz TAGGILDII .

Chce dodać że w poprzedniej wersji Pl nie ma takiego błędu. Przepraszam za słaby opis sytuacji ale myslalem, ze ten temat juz jest rozpatrywany i dodalem taki błąd tylko dla rozgłosu.

**Comment by Kamilkime** [comment]
1. **PI**? Jakie **PI**?...
2. Nigdy jeszcze nie słyszałem o czymś takim i nie mam bladego pojęcia jak to jest możliwe - kod pluginu nie miałby jak się aż tak zepsuć :/
3. Podeślij może log z serwera i config do FG, oczywiście wrzuć to np. na pastebin, nie tu bezpośrednio, jako komentarz

**Comment by RafiXDD** [comment]
Pl - plugin
Postaram sie dodać logi jutro.

**Comment by kacperduras** [comment]
Jak dla mnie - do zamknięcia. Brak szczegółów apropo serwera, logów czy drogi do reprodukcji tego błędu.

**Comment by insertt** [comment]
Z powodu braku większej ilości szczegółów, screenshotów czy logów muszę zamknąć issue. Gdy będziesz posiadał większy zakres opisu błędu, stwórz nowy issue :-)
