### ISSUE TITLE
Problem z KDR

### ISSUE THREAD

**Issue by Gaway69** [FunnyGuilds/FunnyGuilds#710]
Hej , mam problem  z kdr na tabliscie gdyż zawsze pokazuje 0.00 a jak dam komendę /gracz to pokazuje dobrze . Tutaj ss :https://zapodaj.net/48f2b98c7a0d5.png.html
https://zapodaj.net/fe4513195c6a0.png.html

**Comment by Kamilkime** [comment]
U mnie wszystko wyświetla się normalnie. Podeślij może swój config i log z serwera

**Comment by Gaway69** [comment]
https://pastebin.com/JfcRZDc2 LOGI
https://pastebin.com/aGzMqsBG CONFIG

**Comment by hamsterofficial** [comment]
Jaka wersja, najnowsza?

**Comment by Gaway69** [comment]
tak

**Comment by hamsterofficial** [comment]
Wiesz, co spróbuj usunąć cały folder FunnyGuilds i configurować jedną rzecz i reload i tak cały czas, może jakiś błąd wyskoczy.

**Comment by Kamilkime** [comment]
Najlepiej nie reload, tylko restart - reload może psuć pluginy przy wczytywaniu :/

**Comment by hamsterofficial** [comment]
Mi chodzi o /fg reload :)

**Comment by Kamilkime** [comment]
A, to już się może nie zepsuje

**Comment by hamsterofficial** [comment]
Do zamknięcia.

**Comment by Gaway69** [comment]
Funny Guilds z creatora nie maja już tego problemu :) Pozdrawiam
