### ISSUE TITLE
Title nie działa.

### ISSUE THREAD

**Issue by NoName12121212** [FunnyGuilds/FunnyGuilds#712]
Pobrałem najnowszą wersję funnyguilds. Po wgraniu go na serwer nie działają mi wiadomości (Tittle/bossbar) gdy wchodzę na teren wrogiej gildii, tzn. działają ale tylko na chacie.

Mój config:
https://hastebin.com/huretucaju.cs

Logi:
https://hastebin.com/iganutalis.md

**Comment by Kamilkime** [comment]
U mnie, z tym samym configiem - wszystko działa. Może spróbuj zmienić silnik na jakiś inny

**Comment by NoName12121212** [comment]
Zmieniłem silnik na spigot 1.8.8 i nadal nie działa.

**Comment by Kamilkime** [comment]
Używam tego silnika, u mnie działa wszystko bez problemu
https://drive.google.com/open?id=0B_3Y6n86ejr0el9jNGI5QnlXUlU

**Comment by NoName12121212** [comment]
Wgrałem ten silnik i u mnie nadal nie działa.
