### ISSUE TITLE
Naprawa tagu, nie jest wielkimi literami.

### ISSUE THREAD

**Issue by Barteknooo** [FunnyGuilds/FunnyGuilds#713]
Witam, gdy założę gildię z dużych liter tagu, są małymi.
Da się to zmienić w konfiguracji, ew. naprawcie to proszę w kolejnej wersji(?).
`https://i.imgur.com/1mpqBGb.png`

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/ac47ad8912e5765a250277a9877986548632df83/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L441-L444
