### ISSUE TITLE
Pobieranie gildii po lokacji

### ISSUE THREAD

**Issue by HC4F** [FunnyGuilds/FunnyGuilds#716]
Witam nie wiem czy tu dobry wątek ale chciał bym zapytać jak pobrać gildie za pomocą danej lokacji. Chodzi mi mniej więcej tak, że chce zrobić random teleport i chce pobierać gildie na którą gracz w razie co zostanie przeleportowany

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/b6fa553929719f8ab9d1524866f886883947e27e/src/main/java/net/dzikoysk/funnyguilds/basic/util/RegionUtils.java#L45-L53

**Comment by HC4F** [comment]
A jak pobrać daną gildie ?

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/b6fa553929719f8ab9d1524866f886883947e27e/src/main/java/net/dzikoysk/funnyguilds/basic/Region.java#L124-L126

**Comment by HC4F** [comment]
@insertt dzięki !
