### ISSUE TITLE
Wchodzenie na teren gildii

### ISSUE THREAD

**Issue by RafiXDD** [FunnyGuilds/FunnyGuilds#717]
Kiedy gracz wchodzi na teren gildii pisze mu "Wkroczyles na teren gildii TAG 
Gracz nick wkroczyl na teren twojej gildii" chociaz to nie jest wcale gildia tego gracza

**Comment by insertt** [comment]
Mógłbyś dostarczyć więcej materiałów - jak to mniej więcej wygląda, najlepiej screenshootami?

**Comment by RafiXDD** [comment]
https://scr.hu/w4M4Ga

**Comment by Kamilkime** [comment]
Wersja FG i serwera?

**Comment by RafiXDD** [comment]
4.0.1.1 - FG
1.8.8 spigot - Serwer

**Comment by Kamilkime** [comment]
Użyj najnowszego FG

**Comment by RafiXDD** [comment]
nie pomogło

**Comment by RabbitTheDEV** [comment]
Zbuduj FG poprzez FunnyCreator.
