### ISSUE TITLE
Błedy jakie znalazłem w FG

### ISSUE THREAD

**Issue by Gaway69** [FunnyGuilds/FunnyGuilds#718]
Hej , wczoraj otworzyłem edycje swojego serwera , po wejściu około 140/150 graczy zaczęły pojawiać się pewne problemy mianowicie:
1. Tab lista około 30 % graczy nie działała i widzieli coś takiego : https://zapodaj.net/10a1f9713d725.png.html
2. Na czacie wysypały się niektórym graczom prefixy mianowicie było cos takiego {tag}{points}Gracz Gaway: wiadomość , dorzucam ss z live bo nie mam innego: https://zapodaj.net/8a0a20fb64f38.png.html
3.Pojawiły się błędy w konsoli takie jak : https://pastebin.com/7NFG8ZGc
Silnik jaki używam to PaperSpigot 1.8.8 najnowszy dla tej wersji . Pozdrawiam

**Comment by hamsterofficial** [comment]
Proszę o liste wszystkich pluginów.

**Comment by hamsterofficial** [comment]
A jeżeli tab się wysypuje, polecam FunnyTab :)

**Comment by Gaway69** [comment]
mam core swojego i podstawowe pluginy jak essentials , world guard , world edit , spartan

**Comment by insertt** [comment]
Błędy konsoli nie pokrywają się z tym, co jest w kodzie:
`    at net.dzikoysk.funnyguilds.listener.PlayerChat.chat(PlayerChat.java:63) ~[?:?]`
https://github.com/FunnyGuilds/FunnyGuilds/blob/b6fa553929719f8ab9d1524866f886883947e27e/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerChat.java#L61-L63

więc zalecam zaktualizowanie FunnyGuilds do najnowszej wersji (za pomocą [FunnyCreatora](https://github.com/FunnyGuilds/FunnyCreator))

Co do reszty błędów, na wstępie podrzuć output komendy /version.

**Comment by Gaway69** [comment]
![image](https://user-images.githubusercontent.com/35111884/35184022-f0e057c8-fdef-11e7-95d5-b0faf4443a49.png)

**Comment by kacperduras** [comment]
```
A jeżeli tab się wysypuje, polecam FunnyTab :)
```

@hamsterofficial jako twórca tego pluginu nie polecam go używać na wersjach 4.0 i dalszych: po prostu nie ma to żadnego sensu. W dodatku już go nie wspieram, bo po co.

**Comment by hamsterofficial** [comment]
No dobrze dobrze..

**Comment by insertt** [comment]
Brak odpowiedzi nt. aktualizacji pluginu, jeżeli błąd dalej występuje - stwórz nowy issue.
