### ISSUE TITLE
Kolejne problemy z Smesznymi Gildiami

### ISSUE THREAD

**Issue by Gaway69** [FunnyGuilds/FunnyGuilds#721]
Hej , poleciliście mi wczoraj wgrać na serwer fg z creatora jak powiedzieliście tak zrobiłem a oto błedy: https://pastebin.com/9qjRgRSS

**Comment by Gaway69** [comment]
to lipa ;/ dodałem do configu te rzeczy co zobaczyłem ze doszły , może coś przeoczyłem

**Comment by hamsterofficial** [comment]
To czyli ktoś popsuł dołączanie.

**Comment by krzukosz** [comment]
![received_543193952713863](https://user-images.githubusercontent.com/19410048/35195149-6886be8c-febf-11e7-8d5f-7bac84e788ee.png)

**Comment by Kamilkime** [comment]
Używacie zapisu do MySQL czy YAML?

**Comment by krzukosz** [comment]
Mysql

**Comment by xdev-pl** [comment]
Ciekawe jest to że ja tego problemu nie moge odtworzyć ani kamilkime.

**Comment by krzukosz** [comment]
https://hastebin.com/ubixuzonag.sql Wszystko usuniete pluginy: FunnyGuilds i EssentialsX
FunnyGuilds z funnycreatora najnowsze (jak by co) nic nie modyfikowałem w cfg oprócz usunięcia nazwy i lore przedmiotu na gildie bo coś nie działało.
