### ISSUE TITLE
Itemy do zalozenia w GUI

### ISSUE THREAD

**Issue by iSopik** [FunnyGuilds/FunnyGuilds#722]
Istniała by możliwość dodania itemów do założenia gildii w gui pod komendą /itemy lub /g itemy ? # #

**Comment by hamsterofficial** [comment]
Już jest taka komenda /przedmioty /itemy. Czytaj poprawnie config...

**Comment by insertt** [comment]
f07cd82110358d59465b9fd2a102ce663a73b8d8
