### ISSUE TITLE
Tury itemów

### ISSUE THREAD

**Issue by bgK1NG** [FunnyGuilds/FunnyGuilds#729]
Witam, składam ten issue z myślą uatrakcyjnienia poczatku edycji.Bylibyście wstanie dodać tury itemów?Polega to na tym ze dodajemy komende (/tura), polega ona na tym ze w configu ustawiamy 2 tury itemow(mozna też dodac nieskończoną liczbe tur), domyślnie itemy sa wyłączone i wlączamy je przez /tura on 1, /tura on 2 itp. idt. Natomiast w GUI itemy by sie synchronizowały z właczonymi turami :)

**Comment by TheMolkaPL** [comment]
A czym jest taka tura? Na czym ona polega, jak działa?

**Comment by insertt** [comment]
Takie coś można już zrobić na podstawie tego co jest już zaimplementowane w konfiguracji, ale pozostawiam otwarte :-)

**Comment by bgK1NG** [comment]
@themolkapl tury czyli partie itemow, np. 4 itemy w jednej turze i w drugiej 5 kolejnych

**Comment by TheMolkaPL** [comment]
Czyli chodzi o itemy na gildie, które można zmieniać komendami. Itemy zapisywane są jako gotowe zestawy w konfiguracji.

**Comment by bgK1NG** [comment]
Niezbyt, w configu ustawiamy ture 1 ture 2 itp. I te tury wlaczamy w grze przez komende. Itemow nie modyfikujemy w grze tylko w cfg

**Comment by Kamilkime** [comment]
A ja... dalej nie ogarniam o co chodzi...

**Comment by happiii** [comment]
Chodzi o to, że w configu ustawia się X tur itemów na gildie i można je włączyć z poziomu gry, a gildie można założyć dopiero jak wszystkie tury będą włączone.

**Comment by TheMolkaPL** [comment]
@happii A co jeżeli jest na serwerze powiedzmy tura 3:a, a gracz nie zdobył jeszcze 1:ej?

**Comment by happiii** [comment]
@TheMolkaPL no to może wciąż ją zdobyć, dochodzą do tego tylko kolejne itemy.

**Comment by TheMolkaPL** [comment]
Czyli takie wymuszone spowolnienie założenia gildii - tylko w sumie po co? Itemy i tak zdobędzie (a przynajmniej materiały do nich). Rezultat będzie taki, że w większości przypadków tury będę zdobywane zaraz po ich ogłoszeniu. Gildie tworzone zaraz po ich otwarciu.

**Comment by bgK1NG** [comment]
To jakie itemy będą to już nie nasza sprawa tylko właścicieli, poprostu w turach chodzi o to ze gracz nie wie o części itemów przez np. 24h przez co idzie się więcej bić co bardziej uatrakcyjnia rozgrywkę.
