### ISSUE TITLE
BAG

### ISSUE THREAD

**Issue by jogurcik122pl** [FunnyGuilds/FunnyGuilds#730]
W pluginie FunnyGuilds 4.1 **każdy gracz na serwerze** na terenie obcej gildii może stawiać enderchesta, piecyki, skrzynki. W linku poniżej daje ss. Pozdrawiam

- https://imgur.com/a/lHrua

**Comment by insertt** [comment]
Korzystasz z forka, którego niestety nie wspieramy - skorzystaj z najnowszej wersji, która działa bez problemów. Możesz uzyskać za pomocą [FunnyCreatora](https://github.com/FunnyGuilds/FunnyCreator).

**Comment by jogurcik122pl** [comment]
Zainstalowałem FunnyCreatora lecz po w pisaniu komedny /pl na serwerze i w konsoli nie pojawia się
Screny z pluginami daje w linku ----> https://imgur.com/a/bk6Ar

**Comment by dzikoysk** [comment]
FunnyCreator to aplikacja, którą uruchamiasz na swoim pc. Tworzy ona plugin z najnowszych źródeł. Wygenerowany plugin wrzucasz dopiero na serwer

**Comment by jogurcik122pl** [comment]
Wygenerowalem te pliki i co z nimi mam zrobic ? Prosze od dokładna instrukcje w punktach. ![wdawdaw](https://user-images.githubusercontent.com/35815995/35432943-052473fe-0282-11e8-90e3-3c856d052930.png)

**Comment by Kamilkime** [comment]
1. Ściągasz NAJNOWSZY FunnyCreator (jest już wersja 1.0.6)
2. Odpalasz go i czekasz aż skończy pracę
3. Otwiera ci się folder, w którym masz plik FG, który sobie wrzucasz na serwer

**Comment by jogurcik122pl** [comment]
![wadadawdawd](https://user-images.githubusercontent.com/35815995/35433302-4804812c-0283-11e8-8cbf-f12bc1278cb7.png)

**Comment by Kamilkime** [comment]
Skasuj cały folder FunnyCreator'a i odpal na nowo

**Comment by jogurcik122pl** [comment]
Usunołem i nadal bład ?![cos](https://user-images.githubusercontent.com/35815995/35433582-49bd1ece-0284-11e8-86c5-305ffabff44a.png)

**Comment by Kamilkime** [comment]
A masz zainstalowane JDK?

**Comment by jogurcik122pl** [comment]
co to jest

**Comment by Kamilkime** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by jogurcik122pl** [comment]
Ktore ? 
![awdawdaw](https://user-images.githubusercontent.com/35815995/35433786-f3468e94-0284-11e8-99b4-1122fe07b47e.png)

**Comment by Kamilkime** [comment]
Zainstaluj sobie **Java SE Development Kit 8u162**

**Comment by jogurcik122pl** [comment]
Teraz ten serwer stoi na moim pc. A potem bede chciał to przerzucić na hosting i jak to będzie wyglądać  ?

**Comment by Kamilkime** [comment]
No... przerzucisz pliki i odpalisz na hostingu? Co ma być?

**Comment by jogurcik122pl** [comment]
Zrobiło sie coś takiego. wrzucić to na serwer czy coś jeszcze ? ![awdaawd](https://user-images.githubusercontent.com/35815995/35434187-85ed25ea-0286-11e8-95f7-6e8a849a3013.png)

**Comment by Kamilkime** [comment]
Wrzuć na serwer

**Comment by jogurcik122pl** [comment]
teraz jak wpisze /g to pisze [Komenda wyłączona]
![wdawdawdawd](https://user-images.githubusercontent.com/35815995/35434276-e97b655e-0286-11e8-89e2-096653ff7dfd.png)
I znikł tab

**Comment by Kamilkime** [comment]
Pokaż swój config

**Comment by jogurcik122pl** [comment]
![wda](https://user-images.githubusercontent.com/35815995/35434406-4f64f768-0287-11e8-8beb-d5c250424162.png)

**Comment by Kamilkime** [comment]
1. Usuń ProtocolTab, FunnyTab i to _FunnyGuilds-4.1lel_
2. Wrzuć na pastebin swój config od FG i podeślij link

**Comment by jogurcik122pl** [comment]
FunnyGuilds: https://pastebin.com/vuGikKGU

FunnyTAB: https://pastebin.com/45yeMULm

**Comment by Kamilkime** [comment]
1. Masz w configu wyłączony TAB
2. Masz w configu powyłączane wszystkie komendy

**Comment by jogurcik122pl** [comment]
Która to linijka ?

**Comment by Kamilkime** [comment]
Pod koniec configu

**Comment by jogurcik122pl** [comment]
player-list-enable: true Zrestartowalem serwer i nic

**Comment by jogurcik122pl** [comment]
i dalej komenda ./g niedostepna

**Comment by jogurcik122pl** [comment]
Nie masz może pluginu FunnyGuilds z tabem i to wgram zeby wszystko działało ?

**Comment by Kamilkime** [comment]
Tak jak pisałem - są one wyłączone w configu. I musiałeś to sam zrobić, bo domyślnie są włączone

**Comment by jogurcik122pl** [comment]
# Tablista wlaczona
player-list-enable: true

I dalej nie działa

**Comment by jogurcik122pl** [comment]
Tak samo komenda /g

**Comment by Kamilkime** [comment]
1. Czy usunąłeś te pluginy, o których ci pisałem?
2. Między innymi komenda /g została przez ciebie wyłączona w configu
3. Czy w konsoli nie masz żadnych błędów? Podeślij może log z serwera

**Comment by jogurcik122pl** [comment]
zaraz wysle

**Comment by jogurcik122pl** [comment]
Pluginy: 
![awdawdaw](https://user-images.githubusercontent.com/35815995/35435195-0cdf9792-028a-11e8-9e85-f2bb67daa1e2.png)

Konfig FunnyGuilds:  https://pastebin.com/Knt5Zdtz
Logi z konsoli przy wlaczaniu: https://pastebin.com/uQYnB4mg

**Comment by Kamilkime** [comment]
Masz 2 .jar'y z FG i nadal masz FunnyTab, który mówiłem, żebyś skasował

**Comment by Kamilkime** [comment]
I najlepiej używaj silnika na wersję 1.8.8

**Comment by jogurcik122pl** [comment]
![dwadawd](https://user-images.githubusercontent.com/35815995/35435390-d033d924-028a-11e8-84c6-90ccda8c4dec.png)

**Comment by Kamilkime** [comment]
Nadal masz 2 .jar'y z FG...

**Comment by jogurcik122pl** [comment]
krory usunac ?

**Comment by jogurcik122pl** [comment]
który usunąć ?

**Comment by Kamilkime** [comment]
Ten, który nie jest najnowszy, ale to już wy musisz wiedzieć co jest co

**Comment by jogurcik122pl** [comment]
ten idev generowaliścmy przez FunyCreatora a to 2 jest z waszej strony najnowsze

**Comment by Kamilkime** [comment]
To zostaw sobie ten, który zrobiłeś FunnyCreator'em

**Comment by jogurcik122pl** [comment]
/zaloz TEST TESTUMEy nie moge założyć gildii ![dwadawd](https://user-images.githubusercontent.com/35815995/35435620-b76392e4-028b-11e8-871b-2a5f3144ac97.png)

**Comment by Kamilkime** [comment]
A jaki dokładnie przedmiot jest ustawiony w configu?...

**Comment by Kamilkime** [comment]
Nie przychodź tu z każdym problemem, szkoda czasu - poszukaj sam w configu i od razu będzie szybciej

**Comment by jogurcik122pl** [comment]
Dalej każdy może stawiac endera  i skrzynkę na terenie gildii

**Comment by Kamilkime** [comment]
Możliwe, że psuje to jakiś inny plugin. Usuń tymczasowo wszystkie pluginy poza FG i sprawdź to jeszcze raz

**Comment by jogurcik122pl** [comment]
Jest sam FG i dalej da sie

**Comment by Kamilkime** [comment]
Dobra, to tak: zrób nowe issue, tam jeszcze raz opisz problem, podeślij config z FG i log z serwera

**Comment by jogurcik122pl** [comment]
ok napisze
