### ISSUE TITLE
Błąd związany z stawianiem enderchestu, piecyka oraz skrzynki na terenie wrogiej gildii

### ISSUE THREAD

**Issue by jogurcik122pl** [FunnyGuilds/FunnyGuilds#731]
Da sie stawiać enderchesta, piecyk, skrzynke na terenie wrogiej gildii

Lista pluginow:
- FG
- PluginMetrics
Wersja gildii:  4.0.2
Na serwerze jest tylko plugin FG proszę o łatkę
Czytałem na forach że inne osoby tez miały z tym roblem

Logi z konsoli: https://pastebin.com/16CMN8kp

**Comment by Kamilkime** [comment]
Jeszcze config z FG

**Comment by jogurcik122pl** [comment]
https://pastebin.com/i7MMvZLD

**Comment by jogurcik122pl** [comment]
z/w odpisze za 10 min

**Comment by jogurcik122pl** [comment]
jestem

**Comment by kacperduras** [comment]
Powiązanie: #730
Autorowi issue, czyli @jogurcik122pl zalecam cierpliwość, nie jesteśmy 24/7/365. Także spamowanie na innych komunikatorach nie jest zalecanym działaniem.

Na moje oko to błąd pluginu, zwłaszcza żw jak widzę po nawiązanym issue jest samo FG. @dzikoysk @TheMolkaPL @insertt @MrGregorix nadajcie odpowiednie labele, przyjrze się temu we wolnej chwili.

**Comment by jogurcik122pl** [comment]
Przewidywany czas oczekiwania: ? Ten plugin jest mi taj jagby potrzebny na cito

**Comment by Kamilkime** [comment]
Nie jestem w stanie odtworzyć błędu, wszystko działa prawidłowo, w kodzie też nie ma nic, co mogłoby się psuć akurat przy skrzynkach

**Comment by jogurcik122pl** [comment]
To w takim razie jak rozwiążemy ten błąd bo przeglondalem internet i to nie tylko u mnie występowało?

**Comment by Kamilkime** [comment]
Próbowałeś może zmieniać silnik na jakiś inny?

**Comment by jogurcik122pl** [comment]
Jest to możliwość ze mogą być błędy przez to  że to serwer hamaczi ?

**Comment by Kamilkime** [comment]
Nie, to nic nie zmienia

**Comment by jogurcik122pl** [comment]
Wszystkie pluginy sa 1.8-1.8.+ jaka maszynę proponujesz

**Comment by Kamilkime** [comment]
Użyj silnika na wersję 1.8.8

**Comment by jogurcik122pl** [comment]
Lub czy jest opcja żeby ci podał wszystkie pliki serwerowe i byc zobaczył o co chodzi

**Comment by hamsterofficial** [comment]
A gdzie ProtocolLib i te potrzebne pluginy? Twoja to wina bo napewno nie masz silnika **~~Spigot 1.8.8~~**

**Comment by hamsterofficial** [comment]
Link do silnika: https://cdn.getbukkit.org/spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar

**Comment by jogurcik122pl** [comment]
Ok sprawdzę

**Comment by kacperduras** [comment]
```
Twoja to wina bo napewno nie masz silnika Spigot 1.8.8
```

Primo: `na pewno`
Secundo: Mówiłem coś na temat bezsensownych wypowiedzi.

@jogurcik122pl Nie mogę odtworzyć błędu. 
Testowany commit: f863e5060f22b8fbd11d221315b4b4f46a0bc928
Silnik: Spigot 1.12.2

**Comment by jogurcik122pl** [comment]
Czyli wszystko sie naprawi ze Bedzie blokada stawiania enderchesta i skrzynki na terenie gildii i tak sie odbaguje

**Comment by Kamilkime** [comment]
Że... co?

**Comment by jogurcik122pl** [comment]
Powiedz mi co jest nie tak ze tab jest nie pełny ? 
https://pastebin.com/GxCsi0uW
![qwdqdwq](https://user-images.githubusercontent.com/35815995/35451637-31c09d1a-02c4-11e8-8ce9-b41c0161f1b4.png)

**Comment by TheMolkaPL** [comment]
@jogurcik122pl GitHub jest miejscem na zgłaszanie nieprawidłowości i bugów związanych z pluginem. Jeżeli szukasz wsparcia konfiguracji pluginu to musisz niestety prosić na forach. Za błędną konfigurację pluginu nie odpowiadamy, a za wadliwy kod pluginu. Jeżeli twierdzisz że błąd jest w kodzie źródłowym - stwórz issue, jeżeli masz złą konfigurację - szukaj rozwiązania na forach.

**Comment by jogurcik122pl** [comment]
A nie mógł bys na to zobaczyć?

**Comment by marcinkowalczyk2** [comment]
W pliku konfiguracyjnym masz pewnie wyłączoną tablistę, linijka player-list.

**Comment by jogurcik122pl** [comment]
@marcinkowalczyk2 jest wlaczona 😀

**Comment by jogurcik122pl** [comment]
W configu
