### ISSUE TITLE
Możliwość zmiany typu płatności za założenie gildii

### ISSUE THREAD

**Issue by krzukosz** [FunnyGuilds/FunnyGuilds#732]
Witam, propozycji tak jak w tytule.
Możliwość zakładania gildii za itemy bądź hajs. Jak już zaczęliście robić FG trochę pod serwery PvP to myślę że ta opcja się przyda

**Comment by szczepix** [comment]
@krzukosz masz na myśli walutę w grze?

**Comment by krzukosz** [comment]
Tak, np z essentialsa

**Comment by kacperduras** [comment]
No to podczepienie pod Vault powinno być wystarczające ;)
