### ISSUE TITLE
Zabezpiecznenia skrzynek, przycisków, drzwi na terenie gildii

### ISSUE THREAD

**Issue by szczepix** [FunnyGuilds/FunnyGuilds#734]
Dodać możliwość ustawienia zapezpieczenia dla skrzynek, przycisków, drzwi itp. na terenie gildi tylko dla jej członków. Tak żeby można było wybrać któe zabezpiecznia są na terenie gildi aktywne w konfiguracji wtyczki: np. tylko drzwi, przyciski, włazy są zabezpieczone a skrzynki  nie są zabezpieczone :)

**Comment by xdev-pl** [comment]
dobry pomysł można dodać do configu czy skrzynki itd. mogą być używane przez innych graczy z poza gildii

**Comment by marcinkowalczyk2** [comment]
Jestem za, ale dodać, aby to gracz mógł wybrać czy dana interakcja ma być włączona dla intruza. Przykładowo:
interact-event-on:
  click-button: true
  open-chest: false

**Comment by xdev-pl** [comment]
Każda z tych opcji jest typem Interact

**Comment by MentosPL** [comment]
Ledwo zostało to usunięte bo sprawiało problemy, m.in. Szło otwierać te "przedmioty" nawet na zabezpieczonym terenie przez inny plugin. (nie tylko WorldGuard), a już tak bardzo jest to potrzebne?

**Comment by kacperduras** [comment]
Nie rozumiem skąd ton wypowiedzi @MentosPL. Wcześniej to było typowo hard-coded, bez możliwości konfiguracji.

**Comment by MentosPL** [comment]
Wybacz jeśli uraziłem kogoś tym "tonem", chodź byłem przekonany że nie powinien, po prostu ten ficzer FG, dawał mi w kość przez wiele edycji mojego serwera, i raczej nie chciał bym znów mieć podobnych problemów że gracze siebie będą okradać z "targów" bazujących na PlotSquared (tu mamy plugin który działa na zasadzie WorldGuard też ma flagi i regiony).

**Comment by Kamilkime** [comment]
W https://github.com/FunnyGuilds/FunnyGuilds/commit/6ad1b523fbb988398ff731b4255a53a8f39fa148 opcja allowe-interact została zmieniona na odwrotną, blocked-interact. Ma to na celu ułatwienie konfiguracji
