### ISSUE TITLE
Uprawnienia gildyjne.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#737]
Takie coś można spotkać na jednym z największych serwerów easyhc w Polsce. Bardzo dobrze zaprezentował to yt'ber Buzkaa. Oto film: https://www.youtube.com/watch?v=aGyj50ObdxU

**Comment by Kamilkime** [comment]
Zaproponowane już w #651

**Comment by marcinkowalczyk2** [comment]
No tak, nie widziałem, ale chociaż jest film, który łanie obrazuje jak to by miało wyglądać.

**Comment by Kamilkime** [comment]
To dopisz komentarz do #651 i zamknij #737, żeby wszystko było w jednym miejscu
