### ISSUE TITLE
Czat gildii

### ISSUE THREAD

**Issue by dilysm** [FunnyGuilds/FunnyGuilds#738]
# Witam
Napotkałem się kilka razy z takim błędem:
![obraz](https://user-images.githubusercontent.com/35742578/35630468-cd44aff2-06a1-11e8-8468-be5a799b8536.png)

![obraz](https://user-images.githubusercontent.com/35742578/35630654-42974440-06a2-11e8-8e53-a242419610cd.png)

Nie wiem nic więcej niż to co jest na tych screenshotach.

**Comment by TheMolkaPL** [comment]
Jaka wersja pluginu? Jeżeli najnowsza, to z jakiego pluginu korzystasz na format chatu?

**Comment by dilysm** [comment]
Właśnie nie wiem - nie mój serwer.
A chodzi właśnie o to, że widzę czat innych gildii.

**Comment by TheMolkaPL** [comment]
To akurat całkowicie nie powinno mieć miejsca...

**Comment by kacperduras** [comment]
Błąd niemożliwy do reprodukcji.
Testowany commit: f863e5060f22b8fbd11d221315b4b4f46a0bc928

Wniosek: najprawdopodobniej coś po stronie serwera jest winą tego błędu.

**Comment by TheMolkaPL** [comment]
Albo stara wersja, ale fork (czyli ich edytowany kod) - w takim przypadku nie możemy zaoferować supportu.

Chyba do zamknięcia.

**Comment by Kamilkime** [comment]
No, nie wiadomo co jest tam na serwerze, @dilysm zrobił issue, bo ja go o to poprosiłem - nie ma mnie w domu, to nie mogłem kodu przejrzeć, a może był jakiś błąd, to lepiej mimo wszystko napisać issue :)

**Comment by Gaway69** [comment]
Mam dosłownie ten sam problem, wystarczy wpisać /fg save-all i problem na jakis czas z głowy
