### ISSUE TITLE
Asysty propozycja do poprawy

### ISSUE THREAD

**Issue by Gaway69** [FunnyGuilds/FunnyGuilds#739]
Hej , używam najnowszych
 fg i mam propozycje aby asysty na czacie były pokazywane dopiero od 25% lub aby gracze którzy nie dostali punktów nie byli pokazywani
![przechwytywanie](https://user-images.githubusercontent.com/35111884/35767408-10392102-08ec-11e8-815e-6754d6aa7ec7.PNG)

**Comment by Kamilkime** [comment]
Dziś wrócę do domu wieczorem, to zmienię dziś albo jutro rano. Dodam w configu minimalny zysk punktowy i minimalny procent do wyświetlenia wiadomości

**Comment by kacperduras** [comment]
@Kamilkime raczej samo wykluczenie z indeksowania graczy którzy nic nie dostają starczy, po co komplikować? :D

**Comment by Gaway69** [comment]
Okej , dzięki wielkie :D

**Comment by insertt** [comment]
Problem został rozwiązany.
