### ISSUE TITLE
Wydanie stabilnej wersji pluginu

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#742]
Trochę ficzerów i poprawek doszło - to może czas na wydanie oficjalnej aktualizacji? Ostatnią (4.0.2) to wydałem jeszcze jak miałem uprawnienia :D

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/commit/a26348ea3617e5f437b8b09d516122c1dd13bb39
