### ISSUE TITLE
Dodanie możliwości korzystania z liczb przy ustalaniu tagu gildii, dodanie obsługi własnego schematu początkowego wyglądu gildii.

### ISSUE THREAD

**Issue by SeRyJnY** [FunnyGuilds/FunnyGuilds#744]
Moją pierwsza propozycją jest dodanie cyfr do tagu przy zakładaniu gildii aktualnie jest "[a-zA-Z]+", albo ustawianie w configu czy cyfry maja być włączone czy nie.

Moja drugą  propozycją jest dodanie folderu Center gdzie można umieścić schematic z własnym środkiem :)

**Comment by kacperduras** [comment]
A nie lepiej dać możliwość konfigurowania regexa dla nazw i tagów gildyjnych?

**Comment by Kamilkime** [comment]
A daj, dopiero będzie zabawnie...

**Comment by insertt** [comment]
@kacperduras więcej błędów niż korzyści

**Comment by SeRyJnY** [comment]
O jeszcze jeden pomysł można dodać, np ludzie powyżej jakiegoś rankingu maja inny format czatu POINTS np ludzie poniżej 1000 maja &7{POINTS} a powyżej &6{POINTS}!

**Comment by PanKlipcio** [comment]
Propozycja dotycząca schematic'a jest już w #561

**Comment by insertt** [comment]
Początkowy schemat gildii zaimplementowano w https://github.com/FunnyGuilds/FunnyGuilds/commit/9564574a4baad6ac41df6545e8cacd748f0e9834, co do własnych wzorów dopasowywujących - na razie nie implementujemy, prawdopodobnie wyrządziłoby to więcej szkód aniżeli pożytku, zobaczymy w przyszłości :-).
