### ISSUE TITLE
Duplikacja UUID

### ISSUE THREAD

**Issue by xdev-pl** [FunnyGuilds/FunnyGuilds#746]
Hej, uzywam waterfalla jako proxy, i tacospigot 1.8.8 i czasami z dupki mi tworzy zduplikowane rekordy w bazie danych, tutaj jest aktualna kopia z bazy funnyguilds: http://enderbox.pl/dup

Ten temat był już poruszany, pisałem do Kamila, kazał napisać kolejne issue, więc pisze ;d

**Comment by kamcio96** [comment]
Podaj liste pluginów na serwerze i proxy

**Comment by xdev-pl** [comment]
@kamcio96 @kacperduras, wydaję mi się że to przez plugin na autoryzację jak na razie nie mam żadnych problemów.
