### ISSUE TITLE
Błąd podczas tworzenia gildii

### ISSUE THREAD

**Issue by SkymaxPlay** [FunnyGuilds/FunnyGuilds#747]
Yo,
jeśli mamy jakiś item potrzebny na gildie i on posiada lore lub nazwe własną podaną w configu to podczas tworzenia gildii nie znajdzie nam tego itemu nawet jeśli go mamy. Czyli tak jakby gracz musi mieć item z tym lore i nazwą.

**Comment by jasuogra** [comment]
No i tak powinno być.

**Comment by jasuogra** [comment]
Jeśli ktoś posiada załóżmy " superprzedmiot" który można craftować z czegos tam i ten przedmiot ma swój lore I nazwę to jak chce dodać go na gildie to wpisuje dokładnie taki sam lore I nazwę.

**Comment by SkymaxPlay** [comment]
Ta tylko że to jest bez sensu jeśli chcemy by ten custom name i lore był tylko w gui z przedmiotami na gildie.

**Comment by jasuogra** [comment]
Jak tylko w gui? Skoro takowego name i lore może poszukiwać jako przedmiot na gildie

**Comment by SkymaxPlay** [comment]
Mam na myśli że item w gui ma ten lore i custom name ale przy zakładaniu nie potrzebuje. Z resztą znalazłem inny sposób jak to rozwiązać. Nie przemyślane szczerze trochę (nie praktyczne to gui z itemami). Często chcemy dać przedmioty na gildie bez zbędnych lore, które chcą by były tylko w gui.

**Comment by Kamilkime** [comment]
@SkymaxPlay I dlatego do GUI jest pełna konfiguracja, dzięki której można wstawić tam dowolny Item, także nazwany i z opisem - polecam zapoznać się z sekcjami od tego, które są w configu, jeśli dobrze pamiętam to niedaleko od konfiguracji itemów na gildię (pod nimi)

**Comment by SkymaxPlay** [comment]
domyśliłem się, ale nie jest to jaśnie wytłumaczone.

**Comment by Kamilkime** [comment]
Jest, i to bardzo jasno - z przykładami
