### ISSUE TITLE
Błąd ze sojuszami

### ISSUE THREAD

**Issue by Gaway69** [FunnyGuilds/FunnyGuilds#749]
Hej , jest jakiś bug związany z sojuszami , gracze założyli sojusze a potem je zerwali i jedna gildia nie może bić 2 a 2 może

**Comment by sokrates1231** [comment]
po prostu blad w bazie - tabelki ( polecam sprawdzic tabelki ) @kacperduras , @dzikoysk 

Ten blad jest od ponad roku :D

**Comment by kacperduras** [comment]
```
Ten blad jest od ponad roku :D
```
@sokrates1231 jeżeli jest od ponad roku i miałeś tą świadomość, to dlaczego tego nie zgłosiłeś wcześniej?

**Comment by sokrates1231** [comment]
zglaszalem i to nie raz, a pozniej sb fixa zrobilem ;p, a teraz uzywam calkiem co innego niz fg.

**Comment by PanKlipcio** [comment]
wyślij fixa do `pull requests`, pomożesz developerom

**Comment by sokrates1231** [comment]
napisalem co trzeba poprawic... / po co mi plg na 1.7.x-1.8.x jesli pracuje 1.8+?

**Comment by Gaway69** [comment]
Mordo ale fg jest juz na 1.8+xd

**Comment by sokrates1231** [comment]
^,^ nadal z bugiem ktory byl 1.7-1.8, / uzywam swoj plugin ...

**Comment by insertt** [comment]
Nie mogę odtworzyć tego błędu, czy mógłbyś podać więcej szczegółów?

**Comment by sokrates1231** [comment]
sprawdz w kodzie czy zapisuje i usuwa poprawnie tabelki, tam musisz to znalezc

**Comment by Gaway69** [comment]
Ja nie wiem jak to się dzieje ale gracze skarżą mi się ze jest taka sytuacja

**Comment by kacperduras** [comment]
Błąd występuje podczas zapisu danych, otwieram.
