### ISSUE TITLE
O co chodzi w tym errorze?!?

### ISSUE THREAD

**Issue by YTSkaGamerPL** [FunnyGuilds/FunnyGuilds#750]
expected <block end>, but found Anchor
in 'reader', line 132, column 11:
infoTag: "&cPodaj tag gildii!"
^

**Comment by YTSkaGamerPL** [comment]
https://pastebin.com/uuPbPSBD

**Comment by jasuogra** [comment]
- "&cMiejsce w rankingu: &6{RANK} ({POINTS})" <------ "

**Comment by YTSkaGamerPL** [comment]
I co? Co mam zmienic?

**Comment by PanKlipcio** [comment]
`- "&cMiejsce w rankingu: &6{RANK} ({POINTS})`
zamień na
`- "&cMiejsce w rankingu: &6{RANK} ({POINTS})"`

**Comment by YTSkaGamerPL** [comment]
Dzięki, jestem początkujący w FanyGildsach :-D

**Comment by PanKlipcio** [comment]
masz te błędy w linijkach `131.` oraz w `144.`

**Comment by YTSkaGamerPL** [comment]
I jeszcze takie cos mi wywaliło xD
org.diorite.libs.org.yaml.snakeyaml.scanner.ScannerException: while scanning an anchor
in 'reader', line 149, column 4:
- "&6MC.LOLPLAY.PL 7r>> &aTop 5 gil ...
^
expected alphabetic or numeric character, but found .(46)
in 'reader', line 149, column 8:
- "&6MC.LOLPLAY.PL 7r>> &aTop 5 gildii  ...
^

**Comment by PanKlipcio** [comment]
`7r` zapomniałeś zmienić na `&r`, ale to chyba nie jest źródło erroru

**Comment by YTSkaGamerPL** [comment]
Tez to zauważyłem, a wolał bym wiedzieć co jest źródłem erroru :-P

**Comment by PanKlipcio** [comment]
```
topList:
- "&6MC.LOLPLAY.PL 7r>> &aTop 5 gildii na serwerze"
- "&cNajlepsza gildia - &c{GTOP-1}"
```
149 kolumna 8 to wychodzi na . między mc a lolplay, nie rozumiem o co chodzi xd

**Comment by YTSkaGamerPL** [comment]
Dzięki, wszytsko juz jest OK :-D
