### ISSUE TITLE
Propozycja która umożliwi poprawę estetyki chatu.

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#752]
Moja propozycja polega na wprowadzeniu fajnego urozmaicenia do pluginu, z opcją włączenia i wyłączenia, które umożliwiło by poprawienie estetyki chatu. A mianowicie opcja, która by po najechaniu kursorem na nick gracza na chacie, wyświetlała taką "chmurkę" w której zawarte by były informacje jak Tag gildii, punkty, Śmierci, Zabójstwa, i w sumie, te informacje mogły by być dobierane zależnie od upodobań użytkownika.

**Comment by kacperduras** [comment]
Pomysł ciekawy, tyle że jak dla mnie takie ficzery leżą po stronie pluginu na chat, aniżeli samych gildii, których API można wykorzystać ;)

**Comment by MentosPL** [comment]
Gdyby taki istniał plugin, albo gdybym taki znał, chętnie bym zastosował, raczej essentials nie oferuje tego typu zastosowania.

**Comment by krzukosz** [comment]
Dodał bym możliwość oddzielnej kolorystyki do tagow gildii wyswietlanej przed nickiem a inna do wyswietlania zabojstw na chacie.

**Comment by Kamilkime** [comment]
Ale... ze co?

**Comment by bgK1NG** [comment]
@kamilkime kojarzysz na mchc jak klikales na nick na czacie zeby napisać ? Chodzi o tą chmurke żeby tam była informacja z punktami kd itp.

**Comment by Kamilkime** [comment]
1. Nie gram w MC. Jeśli już gram - co najwyżej jest to hypixel.net
2. Mi chodzi o to, co napisał @krzukosz

**Comment by TheMolkaPL** [comment]
Niestety z przykrością muszę stwierdzić, że ta opcja jest dzisiaj niewykonalna, ponieważ zdarzenie od chatu używa formatu jako String (zwykły ciąg znaków), a nie BaseComponent (wiadomości JSON). W związku z czym podmiana zmiennych typu `{GUILD}` i innych takich może zostać zamieniona tylko na twardy tekst, bez wsparcia JSON, co za tym idzie - nie może być on w żaden sposób interaktywny.

Aby to ominąć należałoby nadpisać formatowanie chatu i używać FunnyGuilds jako pluginu formatowania chatu. To się jednak miałoby z celem pluginu, który ma przede wszystkim oferować gildie, oraz pomniejsze jego funkcję.

Jesteśmy więc zdatni na jakiekolwiek wsparcie JSONowego formatowania chatu ze strony Spigota.

**Comment by kacperduras** [comment]
@TheMolkaPL Czyli prościej mówiąc:
```
Pomysł ciekawy, tyle że jak dla mnie takie ficzery leżą po stronie pluginu na chat, aniżeli samych gildii, których API można wykorzystać ;)
```

Zamykam.

**Comment by MentosPL** [comment]
Niestety, nie ma pluginu który wspiera takie ficzery.
![image](https://user-images.githubusercontent.com/32804020/36107184-92e70356-1019-11e8-9304-a44ae939fad7.png)
Warto jednak to przemyśleć.

**Comment by Kamilkime** [comment]
No, to jak masz jakiś plugin od tego - powiedz jaki, może uda się dodać wsparcie

**Comment by MentosPL** [comment]
VentureChat, ale nie posiada jednej ważnej funkcji dla mnie, koloru chatu dla każdej rangi.
I większość funkcji nie mogę ustawić/zmienić. (m.in. bypassuje essentials.chat.color, zamiast usuwać linki, sprawia że wystarczy dać byleco.cokolwiek i traktuje to jako pełnoprawny url do kliknięcia,). Więc nie zamierzam go używać. już na prawdę albo te hologramy bym sobie dodał w skripcie albo lepiej by było w waszym pluginie, ekipa essentialsX odpowiedziała tak:
https://github.com/EssentialsX/Essentials/issues/1843

Nie znam dość dobrze angielskiego by zrozumieć co miał na myśli, ale śmiem twierdzić, że raczej nie odebrał tego pozytywnie. (Essentials jest nie wspierany).

**Comment by Kamilkime** [comment]
Jeśli jest jakiś plugin na chat, który ma potrzebne funkcje - możemy dodać wsparcie. Do samego FG się tego nie doda, bo to ma być plugin na gildie, nie dodatkowo całe formatowanie chatu

**Comment by MentosPL** [comment]
FG nie ma odpowiadać za formatowanie, ma tylko dodać funkcję po najechaniu kursorem na nick :/

**Comment by Kamilkime** [comment]
Ale żeby dodać hover message - trzeba samemu wysłać wszystko. Więc trzeba samemu wysłać prefixy, nick, wiadomość, pokolorować to, itd.

Więc tak - to musi być formatowanie chatu

**Comment by kacperduras** [comment]
@Kamilkime nie znasz się, on wie lepiej :\
