### ISSUE TITLE
Bład z BugowaniemBloków

### ISSUE THREAD

**Issue by SeRyJnY** [FunnyGuilds/FunnyGuilds#753]
Gdy np mamy plugin na kopaczefosy, boyfarmery itp. I mamy włączone opcje bugowania to gdy postawi się kopacza... to on działa i tak można rozwalać innego cuba :)
Chyba, że błąd leży po mojej stronie to przepraszam !

**Comment by Kamilkime** [comment]
No, FG nie anuluje eventu od stawiania bloków, gdy są włączone bugowane bloki - więc taki np. boyfarmer pewnie zaczyna kopać, po czym znika, ale kopie nadal

**Comment by SeRyJnY** [comment]
A da się to jakoś zablokować ?

**Comment by Kamilkime** [comment]
No, najlepiej byłoby to jakoś zablokować w samym pluginie na boyfarmery

**Comment by Kamilkime** [comment]
W sumie - mógłbyś podesłać ten plugin?

**Comment by kacperduras** [comment]
Zamykam, błąd leży po stronie serwera, nie FunnyGuilds.

**Comment by SeRyJnY** [comment]
tylko że to są toolsy i nie chciałbym wysyłać
 a nie da się np do fg dodać
block-disabled:
  - Item  name: Lore:

**Comment by SeRyJnY** [comment]
tylko że to są toolsy i nie chciałbym wysyłać
 a nie da się np do fg dodać
block-disabled:
  - Item  name: Lore:

**Comment by TheMolkaPL** [comment]
Bloki nie mogą mieć własnej nazwy, ani lore. Pomieszałeś je z ItemStackami. ;)
