### ISSUE TITLE
Wsparcie dla PlaceHoldersAPI

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#755]
Proponuję dodanie wsparcia pulginu PlaceholdersAPI by zmienne FG były odczytywane przez PlaceholdersAPI i przekazywane innym pluginom które wspierają PlacehodersAPI, np. plugin na chat ;)
https://github.com/FunnyGuilds/FunnyGuilds/issues/752

**Comment by Kamilkime** [comment]
No nie do końca @kacperduras, bo są dwa różne API - to z #674 jest dla FeatherBoard'a, a @MentosPL chyba chodzi o to - https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by MentosPL** [comment]
Popieram ^
