### ISSUE TITLE
Nie da się dodać itemów o takiej samej nazwie ale o innej metadacie. 

### ISSUE THREAD

**Issue by L11NE** [FunnyGuilds/FunnyGuilds#757]
Witam. Problem polega na tym że gdy chcemy dodać item na Gildie np. Ryba   która w minecraft dzięki się na 3 przedmioty i wszystkie mają nazwę fish ale mają inna metadate. Czyli, dodaje np. 16 fish:1 wywala błąd i tak jest z innymi podobnymi itemami

**Comment by insertt** [comment]
Czy mógłbyś zaprezentować jak można ten błąd zreprodukować?

**Comment by L11NE** [comment]
Wersja pluginu: FunnyGuilds-indev-4.1.0
Spigot. 1.8.8

Blad polega na tym że jak chce dać zwykłą surową rybę do przedmiotów Na Gildie to wywala błąd i nie działa cała komenda /przedmioty

**Comment by insertt** [comment]
Podeślij swoją konfigurację oraz cały log z konsoli, gdy wystąpił ten błąd

**Comment by insertt** [comment]
Brak jakiejkolwiek odpowiedzi ze strony zgłaszającego-  gdy będziesz miał ochotę współpracować, otworzymy issue, a tymczasem zostaje ono zamknięte.
