### ISSUE TITLE
Błąd podbijania z innym entity niż Ender Crystal

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#764]
Nie jest możliwe podbijanie, brak błędów w konsoli

**Comment by Kamilkime** [comment]
A da się w ogóle ustawić inne entity?

**Comment by jasuogra** [comment]
Da się, Dzik mówił ze da się ustawiać dowolne, choć będą problemy mi się wydaje, ja bym dodał funkcje bloku też jako serce gildii.
