### ISSUE TITLE
Dodatkowe zmienne do wiadomości

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#765]
{HEALTH} - ile hp zostało zabijającemu (rankDeathMessage)
{TAG} - do sojuszy

**Comment by Kamilkime** [comment]
I gdzie ten {TAG} miałby się pojawiać? Do jakiej wiadomości chcesz to dodać?

**Comment by Revelacyjny** [comment]
@Kamilkime 
`# Dostepne zmienne: {GUILD}
allyInviteDone: "&7Zaproszono gildie &a{GUILD} &7do sojuszu!"`

**Comment by Kamilkime** [comment]
A, tu, ok
