### ISSUE TITLE
Dodatkowe zmienne do TABa

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#766]
1. Zmienna od Cuboida gildii.
2. Zmienna od waznosci gildii.
3. Zmienna od Ochrony przed atakiem

**Comment by Kamilkime** [comment]
Co masz na myśli mówiąc _Zmienna od Cuboida gildii_?

**Comment by L11NE** [comment]
Kamilkime, chyba chodzi o to że mamy zmienna {XYZ} Która wyświetla nam na tablistcie aktualny stan wielości gildii np. 50x50 albo 70x70 itd.

Dołożyłbym odrazu zmienna na ilość asyst których zrobiliśmy.

**Comment by Kamilkime** [comment]
Asysty na razie nie są zapisywane

**Comment by L11NE** [comment]
To znaczy? W przyszłych wersjach raczej będą?

**Comment by Kamilkime** [comment]
W końcu się to pewnie doda, ale na razie są inne rzeczy do roboty

**Comment by sokrates1231** [comment]
tak jak napisał wyzej kolega zeby pokazywało np 50x50
