### ISSUE TITLE
Propozycja - nowe dodatki

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#767]
Witam, mam kilka propozycji np dodać komende /g zarządzaj gdzie bd mogli kupic np ochronkę przed wybuchami ( tnt itd. ) na określony czas (zapisywanie trzeba dodać). Mozna tez dodać kupienie opcji gdzie mozna kupic zdby pokazywało nam nick intruza gdy wkracza na nasz teren gildii. Przydatna opcja ;)

**Comment by jasuogra** [comment]
No to takie boosty gildyjne, jestem jak najbardziej na tak, będzie trzeba wymyślić więcej takich rzeczy, graczom na pewno się spodoba.

**Comment by kacperduras** [comment]
Powiązane częsciowo z #651, więc można zaimplementować za jednym zamachem ;)

**Comment by Kamilkime** [comment]
![image](https://user-images.githubusercontent.com/10383567/40133792-115c58ec-5941-11e8-8146-c1fa0c062971.png)
