### ISSUE TITLE
Zwiększona ilośc zastępców

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#768]
Użytkownik na PM na Discordzie zasugerował dodanie większej ilości zastępców w gildii - oczywiście konfigurowalną w konfiguracji ;)

**Comment by Kamilkime** [comment]
Jakiś lepszy dzień, że napisałeś issue za niego?

**Comment by kacperduras** [comment]
Napisałem też #764, propozycja wynikła w trakcie dyskusji :P

**Comment by Kamilkime** [comment]
Chyba, że tak :D
