### ISSUE TITLE
Opcjonalny scoreboard

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#770]
W związku z #769 - proponuje dodanie opcjonalności scoreboarda przy działaniu pluginów - może ktoś nie chce go używać bo koliduje to z innymi rozwiązanami stosowanymi na danym serwerze.

**Comment by mhaas11** [comment]
Gut gut

**Comment by MentosPL** [comment]
A teraz proszę o unbana bo Happi ma jakieś problemy emocjonalne...
