### ISSUE TITLE
MYSQL I TAB

### ISSUE THREAD

**Issue by karabin14** [FunnyGuilds/FunnyGuilds#772]
Jak połączyłem funnyguilds z mysql wszystko ładnie śmiga strona wyczytuje wszystko ale ..... 
serwer jusz nie na tabie nie pokazuje mi top gildii np 1
  66: "      &91.&c{GTOP-1}     "
I co daje mi na tab BRAK jest gildia sam w niej jestem na stronie wyczytuje ją ale na serwerze jusz nie 

Z GÓRY SORY ZA J.POLSKI :P MAM dysgrafię ITP

A tak z innej beczki dodacie sidebar ;p

**Comment by kacperduras** [comment]
Wina skryptu strony, FG od pewnego czasu indeksuje tylko w rankingu gildie od x graczy (x - liczba ustawiona w configu). Albo zmień konfigurację, albo zmień stronę.
