### ISSUE TITLE
Błąd PlayerDeathEvent

### ISSUE THREAD

**Issue by Querko7** [FunnyGuilds/FunnyGuilds#774]
Witam,
Dziś gdy zbanowałem gracza który był podczas walki wywaliło błąd w konsoli. Oto logi: https://pastebin.com/7DQRwrzr
(Używam wersji FunnyGuilds Tribute 4.1.1)

**Comment by Kamilkime** [comment]
Poprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/b907e0e7a167472cbac1489c82c5c488411ac8e8. Zbuduj sobie najnowsze FG przy użyciu [FunnyCreator'a](https://github.com/FunnyGuilds/FunnyCreator/releases/tag/1.0.6)

**Comment by Querko7** [comment]
Ok, dziękuje.
