### ISSUE TITLE
Stawianie ramki na przedmiot oraz obrazu

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#775]
Na terenie wrogiej gildii da się postawić ramki i obrazy.

**Comment by Kamilkime** [comment]
Poprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/784158e95c0e591e18d7d2625e420396e1ff458d. Zbuduj sobie najnowsze FG przy użyciu [FunnyCreator'a](https://github.com/FunnyGuilds/FunnyCreator/releases/tag/1.0.6)
