### ISSUE TITLE
Błędna lokalizacja kryształu gildii

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#776]
![image](https://user-images.githubusercontent.com/29325155/36945474-eef980ac-1fae-11e8-9acc-c4a3f9ae1c32.png)

**Comment by Kamilkime** [comment]
To jest jakiś twój schemat środka gildii?

**Comment by Revelacyjny** [comment]
[schemat.zip](https://github.com/FunnyGuilds/FunnyGuilds/files/1778469/schemat.zip)
Schemat, którego użyłem

**Comment by Kamilkime** [comment]
Zrób schemat stojąc kratkę wyżej, bo środek gildii jest wyznaczany na podstawie pozycji gracza, która jest zapisywana w momencie tworzenia samego schematu

**Comment by Revelacyjny** [comment]
Dwie kratki wyżej załatwiło sprawę, dzięki za szybką pomoc.
![image](https://user-images.githubusercontent.com/29325155/36945554-944fb82c-1fb0-11e8-8d0e-b2642b387e10.png)
