### ISSUE TITLE
Wiecej linijek dla Stopki i nagłówka na tablistcie

### ISSUE THREAD

**Issue by L11NE** [FunnyGuilds/FunnyGuilds#777]
Proponuje dodanie więcej opcji dla Stopki i nagłówka, czyli chodzi o to że standardowo wygląda to tak: 
player-list-header: "&7FunnyGuilds &b4.1.1 Tribute"
A fajnie by było jakby wyglądało tak:
player-list-header: 
- &7FunnyGuilds
- &7 &b4.1.1 
- &7Tribute!
- Najlepszy plugin na gildie!
i żeby tak było też z stopką tabu. ew. można zrobić {NEWLINE} i też by działało.

**Comment by insertt** [comment]
`\n`

**Comment by L11NE** [comment]
insertt, te /n nie działa. Próbowałem i nic. wyświetla na tabie normalnie to /n a pisze dalej w 1 linijce.

**Comment by insertt** [comment]
Używasz `\` czy `/`

**Comment by L11NE** [comment]
Zwracam honor. Używałem / . Wszystko działa.
