### ISSUE TITLE
Zmiana główek na tab.

### ISSUE THREAD

**Issue by L11NE** [FunnyGuilds/FunnyGuilds#778]
Proponuje jeśli się da, Dodanie opcji zmiany główek na tabie. Standardowo jest alex,steve,... i tak cały czas. Fajnie by było jakby dało sie to zmienić np. TablistHeads: "tutaj_nick_kogos" i wyświetlaja sie główki lub jak jest teraz dwóch główek. TablistHeads: "Nick_1, Nick_2"

**Comment by mhaas11** [comment]
To by było gut

**Comment by SOP3K-exe** [comment]
Proponuje by zostalo to dodane :D

**Comment by kacperduras** [comment]
@SOP3K-exe Kiedy będzie to będzie - spokojnie, nie jest to task najwyższego priorytetu.

**Comment by EspaniololxPl9988** [comment]
Lux propozycja!@

**Comment by Kamilkime** [comment]
Było próbowane przez @insertt ale chyba nic z tego nie wyszło - z tego co pamiętam to były to uroki serwera no-premium

**Comment by EspaniololxPl9988** [comment]
A jestes w stanie napisać takie cos ?

**Comment by Kamilkime** [comment]
Tak jak napisałem - insertt próbował to zrobić, ale nie wychodziło, bo sposób działania serwera no-premium na to nie pozwalał

**Comment by EspaniololxPl9988** [comment]
Okej ja to rozumiem, Ale dla porównania sławny serwer CraftCore, miał na tablist zmienione głowki ;c

**Comment by Kamilkime** [comment]
A ten CraftCore nie stoi przypadkiem na tym całym BlazingPacku, który to właśnie może im pozwalać na takie zmiany?

**Comment by insertt** [comment]
Niewykonalne do zaimplementowania, gdy serwer korzysta z offline-mode.
