### ISSUE TITLE
Brak chat-points w configu, dodanie kolorów w zależności od wartości pingu

### ISSUE THREAD

**Issue by 6594k** [FunnyGuilds/FunnyGuilds#780]
Witam, zbudowałem sobie dzisiaj najnowszą wersje FunnyGuilds za pomocą FunnyCreator. Mój problem polega na tym , że nie ma chat-points w configu. Po dodaniu tego niestety plugin to ignorował.
Mam jeszcze jedną propozycje, aby dodać kolorowanie pingu czy tps na tabie.
Mogłoby to wyglądać mniej więcej tak:
ping > 30 -> "&aIDEALNY"
ping  < 100 -> "&e{PING}"
ping > 100 -> "&c{PING}"
No oczywiście najlepiej byłoby gdyby była możliwość konfiguracji tego.

**Comment by Kamilkime** [comment]
Na przyszłość - usuń domyślny tekst issue...

**Comment by Kamilkime** [comment]
_//TODO_
Przy okazji poprawić opis sekcji **create-center-sphere** w oparciu o prawdziwe działanie
https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/command/ExcCreate.java#L248-L260

**Comment by Kamilkime** [comment]
Poprawione i dodane w https://github.com/FunnyGuilds/FunnyGuilds/commit/2232413a1b2e1b4d1b2d75a811d948962be87e07
