### ISSUE TITLE
Drobna zmiana w {G-KDR}

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#781]
Tak się zastanawiam czy zamiast `user -> "0.0"` nie powinno być `user -> "0.00"`? W zmiennej {KDR} są 2 miejsca po przecinku dlatego może by dobrze było dostosować tak samo {G-KDR}.

https://github.com/FunnyGuilds/FunnyGuilds/blob/2bd467c1515fd63287c1ea29bb50a667976f01d8/src/main/java/net/dzikoysk/funnyguilds/util/element/tablist/variable/DefaultTablistVariables.java#L55

**Comment by Kamilkime** [comment]
W sumie racja...
