### ISSUE TITLE
Wsparcie dla pluginu Skript

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#782]
Nie sądziłem że to kiedykolwiek napiszę (i że dam label `Ważne`), ale najwyraźniej n-ty raz już słysze o propozycji oficjalnej integracji FG z pluginem [Skript](https://github.com/bensku/Skript) - nie wiem skąd nagle takie zapotrzebowanie, nie wnikam. Generalnie pasuje zrobić jakiś spis wszystkich wyrażeń w oparciu o Skriptowy syntax, żebym wiedział co mam implementować, bo samo napisanie dodatku będzie dość proste i błahe.

**Comment by MrGregorix** [comment]
Zgłaszam to za treści drastyczne.

**Comment by jasuogra** [comment]
Proszę to usunąć, tutaj mogą przebywać dzieci takie jak ja.

**Comment by kacperduras** [comment]
@jasuogra Już po 19, Wieczorynka była - do łóżka!

**Comment by MrGregorix** [comment]
Proponuje też dodać zakaz pisania FG w Eclipse

**Comment by happiii** [comment]
Jak to dodasz to cie zbanuje na Discordzie. >:)
