### ISSUE TITLE
Błąd w configu

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#783]
points-format: 
- 0-749 &4{POINTS}
- 750-999 &c{POINTS}
- 1000-1499 &a{POINTS}
- 1500-* &6&l{POINTS}
points-format: 
- 0-75 &7{PING}
- 76-150 &7{PING}
- 151-300 &7{PING}
- 301-* &7{PING}

Najnowszy fg z funnycreatora

**Comment by Revelacyjny** [comment]
`# Wyglad znacznika {POINTS-FORMAT} i {G-POINTS-FORMAT} w zaleznosci od wartosci punktow
# {G-POINTS-FORMAT} (tak samo jak {G-POINTS}) jest uzywane jedynie na liscie graczy
# Lista powinna byc podana od najmniejszych do najwiekszych rankingow i zawierac tylko liczby naturalne, z zerem wlacznie
# Elementy listy powinny byc postaci: "minRank-maxRank wyglad", np.: "0-750 &4{POINTS}"
# * uzyta w zapisie elementu listy oznacza wszystkie wartosci od danego minRank w gore, np.: "1500-* &6&l{POINTS}"
points-format: 
- 0-749 &4{POINTS}
- 750-999 &c{POINTS}
- 1000-1499 &a{POINTS}
- 1500-* &6&l{POINTS}
# Znacznik z punktami dodawany do zmiennej {PTOP-x} i {ONLINE-PTOP-x}
# Uzywaj zmiennych {POINTS} i {POINTS-FORMAT}
# Jesli nie chcesz wyswietlac punktow, tylko sam nick - nie podawaj tu nic
ptop-points: " &8[&7{POINTS}&8]"
# Znacznik z punktami dodawany do zmiennej {GTOP-x}
# Uzywaj zmiennych {POINTS} i {POINTS-FORMAT}
# Jesli nie chcesz wyswietlac punktow, tylko sam tag - nie podawaj tu nic
gtop-points: " &7[&b{POINTS-FORMAT}&7]"
# Wyglad znacznika {PING-FORMAT} w zaleznosci od wartosci pingu
# Lista powinna byc podana od najmniejszych do najwiekszych wartosci i zawierac tylko liczby naturalne, z zerem wlacznie
# Elementy listy powinny byc postaci: "minPing-maxPing wyglad", np.: "0-75 &a{PING}"
# * uzyta w zapisie elementu listy oznacza wszystkie wartosci od danego minPing w gore, np.: "301-* &c{PING}"
points-format: 
- 0-75 &7{PING}
- 76-150 &7{PING}
- 151-300 &7{PING}
- 301-* &7{PING}`

**Comment by Kamilkime** [comment]
Krótko mówiąc... 2 sekcje nazywają się tak samo, tak?

**Comment by Revelacyjny** [comment]
Tak

**Comment by Kamilkime** [comment]
Sekcja nazywa się już ping-format, widocznie nie zmieniłem przy kopiowaniu punktów, żeby zrobić nową sekcję. Dzięki za czujność!
