### ISSUE TITLE
Problem z ustawieniem points-format

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#784]
Gdy chcę zmienić points-format na: https://pastebin.com/raw/fscZ2gPx
To po przeładowaniu zmienia się na domyślne

**Comment by Kamilkime** [comment]
U mnie wszystko działa. Jesteś pewien, że wszystko inne w configu jest dobrze, nie ma żadnych błędów oraz nie masz np. spacji lub tabów na końcu linii lub np. spacji nierozdzielających?

**Comment by Kamilkime** [comment]
Podeślij może swój config i log z serwera

**Comment by Revelacyjny** [comment]
Jednak to mój błąd ;)
Dziękuję za poświęcony czas.
