### ISSUE TITLE
PROPOZYCJA - Ochrona TNT ( czasowa )

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#790]
Witam,
Mozna dodać ochrone przed tnt na CUBOIDACH Gildijnych  od godziny X do godziny  X

**Comment by sokrates1231** [comment]
ref

**Comment by Kamilkime** [comment]
Już to było mówione komuś przy innym issue...

**To nie mpcforum, tu się nie odświeża issue, ono nadal jest w tym samym miejscu na liście, w którym było. Jak ktoś będzie miał czas i chęć zająć się akurat tym - zostanie to dodane**
