### ISSUE TITLE
Gracz ma dostep do komendy /ga

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#791]
Niby nieduży błąd bo gracz ma tylko dostęp do wyświetlania listy komend jednak i tak bym to zablokował aby po wpisaniu komendy /ga od razu wyświetlała się informacja że gracz nie ma uprawnień.

**Comment by Kamilkime** [comment]
Ale widzę po kodzie... Że jest to dodane

**Comment by FastJoe0** [comment]
Wiesz co to nie wiem. Sprawdziłem jeszcze raz i dalej to samo.

**Comment by Kamilkime** [comment]
Też widzę, zaraz przejrzę kod dokładniej

**Comment by Kamilkime** [comment]
Poprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/af99c882e2b65b48369a7bdccac0804abae88329
