### ISSUE TITLE
Nowa zmienna na liczbę asyst

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#792]
Asysty zostały dodane więc może dodać by też zmienną do tabu/scoreboarda/messages która by pokazywała ile gracz zaliczył asyst.

**Comment by kacperduras** [comment]
Obecnie asysty nie są zapisywane, więc takowy ficzer nie jest dodany. Starczy tylko to dodać i w sumie nie ma żadnego problemu ;)

**Comment by Kamilkime** [comment]
Zaproponowane już w #735
