### ISSUE TITLE
BLAD! 

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#793]
Witam, blad na tabie:
https://scr.hu/y8OO26

config:
  23: "&71. &c{PTOP-1}"
  24: "&72. &c{PTOP-2}"
  25: "&73. &c{PTOP-3}"
  26: "&74. &c{PTOP-4}"
  27: "&75. &c{PTOP-5}"
  28: "&76. &c{PTOP-6}"
  29: "&77. &c{PTOP-7}"
  30: "&78. &c{PTOP-8}"
  31: "&79. &c{PTOP-9}"
  32: "&710. &c{PTOP-10}"
  33: "&711. &c{PTOP-11}"
  34: "&712. &c{PTOP-12}"
  35: "&713. &c{PTOP-13}"
  36: "&714. &c{PTOP-14}"
  37: "&715. &c{PTOP-15}"
  38: "&716. &c{PTOP-16}"

Najnowsza Wersja FG z FunnyCreator :D

**Comment by Kamilkime** [comment]
Wszystko jest dobrze - spójrz do pliku messages.yml

**Comment by sokrates1231** [comment]
do messages.yml?

**Comment by Kamilkime** [comment]
Tak

**Comment by sokrates1231** [comment]
przeciez mam tam wiadomosci.. XD Chodzi mi o to ze pojawilo sie  (PTOP-x) to samo w /info w sojuszach przy zmiennej: (ALLIES)

**Comment by kacperduras** [comment]
@Kamilkime napisał co masz zrobić, zobacz a zrozumiesz.

**Comment by Kamilkime** [comment]
I najlepiej zbuduj sobie nowe FG FunnyCreator'em, bo widzę u ciebie jeden błąd (że koło nazwy gildii wstawia się {PING}), który został już poprawiony
