### ISSUE TITLE
PUNKTY GRACZA

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#794]
Witam, zauwazylem taki dziwny blad:
https://scr.hu/4VZ08D

Gracz ma 0 smierci i zabojst, a ma 502 pkt(domyslnie 500), po jakims czasie dodaje pkt graczom ;o

**Comment by Kamilkime** [comment]
No... Może z asyst?

**Comment by sokrates1231** [comment]
Dobra, a przy zabojstwie osoba ktora ginie dostaje -rank, a osoba zabijajca +0?

**Comment by Kamilkime** [comment]
Eeee, że co?

**Comment by sokrates1231** [comment]
osoba ktora zabijam dostaje -x pkt, a ja +0 :D

**Comment by Kamilkime** [comment]
Ranking ELO czasem tak działa, jak są duże różnice rankingu - głównie, żeby nie można było farmić w nieskończoność ranku na słabych graczach, tylko trzeba się bić z silniejszymi

**Comment by sokrates1231** [comment]
mamy po 500 pkt?

**Comment by Kamilkime** [comment]
Jaką masz wersję FG?

**Comment by sokrates1231** [comment]
https://scr.hu/grLRXK


messages:

# Dostepne zmienne: {ATTACKER}, {VICTIM}, {-}, {+}, {POINTS}, {POINTS-FORMAT}, {VTAG}, {ATAG}, {WEAPON}, {REMAINING-HEALTH}, {REMAINING-HEARTS}
rankDeathMessage: "&8{VTAG}&c{VICTIM} &8[&4-{-}&8] &7zostal zabity przez &8{ATAG}&c{ATTACKER} &8[&2+{+}&8] &7uzywajac &b{WEAPON}"
# Zamiast zmiennej {ASSISTS} wstawiane sa kolejne wpisy o asystujacych graczach
rankAssistMessage: "&e&lAsystowali: {ASSISTS}"
# Dostepne zmienne: {PLAYER}, {+}, {SHARE}
rankAssistEntry: "&b{PLAYER} &7(&a+{+}&7, {SHARE}% dmg)"
# Znaki oddzielajace kolejne wpisy o asystujacych graczach
rankAssistDelimiter: "&8, "

nie pokazalo mi asysty na czacie a dostalem " 5 pkt " XD

**Comment by Kamilkime** [comment]
Podeślij screena informacji o śmierci, config i log z serwera (config i log wrzuć np. na pastebin)

**Comment by sokrates1231** [comment]
bledow w logach nie mam, screen z smierci(nie pokazalo asysty w wiadomosci: https://scr.hu/grLRXK )

**Comment by Kamilkime** [comment]
Pokaż log i config

**Comment by sokrates1231** [comment]
config: https://hastebin.com/fawuyikosu.cs  mowilem w logach nie ma bledow, sprawdzalem.

**Comment by Kamilkime** [comment]
Ostatni raz ci powiem - pokaż mi też log z serwera. Skoro o niego pytam, to widocznie jest mi potrzebny

**Comment by sokrates1231** [comment]
To samo z tabem: https://scr.hu/YMLjoa
Popatrz na topke gildii ^,^

logi tutaj: http://www118.zippyshare.com/v/P243CNvC/file.html bo za duzo wazy probowalem na hastebin/pastebin ale...

**Comment by sokrates1231** [comment]
bez reloada ale nadal sa warny: 

https://hastebin.com/ciseromuzi.md

**Comment by sokrates1231** [comment]
warny ktore laguja i serwer.. [ * ]
https://hastebin.com/futizawaza.md

**Comment by sokrates1231** [comment]
@Kamilkime  i jak? / wiesz o co chodzi?

**Comment by Kamilkime** [comment]
Ogólnie jest błąd z połączeniem z bazą danych, ale to już leży po stronie serwera. Po drugie przyjrzyj się sekcji **points-format** u ciebie w configu

**Comment by sokrates1231** [comment]
Inne pluginy z mysql lacza sie poprawnie, a FG nie?

# Znacznik z punktami dodawany do zmiennej {GTOP-x}
# Uzywaj zmiennych {POINTS} i {POINTS-FORMAT}
# Jesli nie chcesz wyswietlac punktow, tylko sam tag - nie podawaj tu nic
gtop-points: " &7[&b{POINTS-FORMAT}&7]"

**Comment by Kamilkime** [comment]
Mówię ci, co widzę w błędzie, a jeśli chodzi o te punkty - podałem ci konkretną sekcję

**Comment by sokrates1231** [comment]
@Kamilkime 
W bazie tworza sie tabelki/rekordy wiec jednak laczy sie, moze wina   poolSize?
  poolSize: 16

**Comment by Kamilkime** [comment]
**[16:58:51] [Server thread/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.**

Połączenie nie nastąpiło mimo 30 sek. oczekiwania

**Comment by sokrates1231** [comment]
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.1.1 Tribute-af99c88
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Available Processors: 8
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Active Threads: 17
[17:01:04] [Server thread/WARN]: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Loaded users: 40
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Loaded regions: 7
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Loaded guilds: 0
[17:01:04] [Server thread/WARN]: [FunnyGuilds] FunnyGuilds supports only WorldGuard v6.2 or newer
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Plugin: PlaceholderAPI could not be found, some features may be not available
[17:01:04] [Server thread/INFO]: [FunnyGuilds] Plugin: BungeeTabListPlus could not be found, some features may be not available
[17:01:04] [Server thread/INFO]: [FunnyGuilds] ~ Created by FunnyGuilds Team ~

**Comment by Kamilkime** [comment]
Mówię ci co widzę - może akurat wtedy baza padła? Nie wiem. Gdyby błąd się powtarzał - wtedy zrób nowe issue zamieszczając cały log z serwera
