### ISSUE TITLE
Error z konsoli

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#795]
Error: https://hastebin.com/jolivuqidu.vbs

**Comment by Kamilkime** [comment]
Co zrobiłeś, że wyskoczył ci ten błąd?

**Comment by sokrates1231** [comment]
nic, nagle taki blad w logach :D

**Comment by Kamilkime** [comment]
No, nie udało mi się go odtworzyć

**Comment by insertt** [comment]
@sokrates1231 czy mógłbyś dostarczyć jeszcze raz ten sam log? Niestety znikł i nie mam możliwości zreprodukowania tego błędu.

**Comment by sokrates1231** [comment]
zmieniłem na flat;/

W dniu wt., 13.03.2018 o 03:30 insertt <notifications@github.com>
napisał(a):

**Comment by insertt** [comment]
Na czas gdy nie posiadamy żadnych materiałów do reprodukcji błędu zamykam issue - gdy dostarczysz logi z tym błędem, ponownie otworzę issue.
