### ISSUE TITLE
Zaimplementowanie hologramów [HolographicDisplaysAPI]

### ISSUE THREAD

**Issue by ghost** [FunnyGuilds/FunnyGuilds#796]
Np. nad sercem gildii z niektórymi informacjami.

**Comment by Revelacyjny** [comment]
HolographicDisplays ma ciekawe api, co Wy na to?
https://ci.filoghost.me/job/HolographicDisplays/javadoc/index.html?com/gmail/filoghost/holographicdisplays/api/HologramsAPI.html

**Comment by Kamilkime** [comment]
Nie no, sami raczej nie będziemy pisać hologramów

**Comment by Rollczi** [comment]
Kontynuacja issue https://github.com/FunnyGuilds/FunnyGuilds/issues/1462
(tam pomysł został lepiej rozwinięty)
