### ISSUE TITLE
Zwiększenie czasu oczekiwania na bazę danych

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#797]
Po x uptime serwera wywala warn i laguje na x sekund serwer.
Warn: https://hastebin.com/iqinowuxab.css

To samo przy /stop ( restartowaniu serwera) tez pokazuje sie ten sam WARN.

**Comment by sokrates1231** [comment]
@Kamilkime  mozna przez socket laczyc sie?

**Comment by kacperduras** [comment]
```
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
```

3000ms = 3 sekundy, trochę mało. Pasuje dodać konfigurację tego.

**Comment by sokrates1231** [comment]
mysql: 
  hostname: localhost
  port: 3306
  database: xxxx
  user: xxxx
  password: haslodomysql
  poolSize: 16
