### ISSUE TITLE
Litery tagów

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#798]
Jest możliwość, aby tagi gildii nie będą zmieniane na duże/małe litery, tylko takie jak gracze sobie sami ustawią?

**Comment by kacperduras** [comment]
Tak, zainteresuj się opisem fielda w konfiguracji `name-regex`.

**Comment by Revelacyjny** [comment]
@kacperduras, chodzi mi raczej o guild-tag-uppercase, bo gdy jest na false, to wszystkie tagi są z małych liter
