### ISSUE TITLE
+0 rankingu

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#800]
![image](https://user-images.githubusercontent.com/29325155/37246056-645f05a4-24a2-11e8-82e1-afdd8988cfd1.png)
`rank-system: PERCENT`
`percent-rank-change: 1.1`

Zazwyczaj dodaje normalnie, 0 błędów w konsoli.

**Comment by Kamilkime** [comment]
Jak ktoś ma mało rankingu, to 1.1% z rankingu może wyjść poniżej 0.5 pkt, wiec będzie 0

**Comment by Revelacyjny** [comment]
Każdy miał po 1000/990

**Comment by Kamilkime** [comment]
Na razie nie mam pomysłu

**Comment by Kamilkime** [comment]
Naprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/42ab366de7c1450a9425aff81e39e96b5bb6a63d
