### ISSUE TITLE
Nie działająca baza danych.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#803]
Od razu daje logi: https://pastebin.com/hjd0AhhA

Konfiguracja mysql:

hostname: 151.80.110.153
  port: 3306
  database: xxx
  user: xxx
  password: aaa
  poolSize: 16

xxx - ta sama wartość

W innym pluginie (moim) łączy się prawidłowo i nie ma żadnych błędów.

**Comment by Kamilkime** [comment]
Używasz Javy 9 na serwerze? To nie brzmi jak dobry pomysł, Spigot i CraftBukkit nie są oficjalnie kompatybilne z nią. Co do błędu - plugin nie nawiązuje połączenia, stawiałbym raczej na konfigurację serwera SQL lub np. źle podane przez ciebie w configu dane logowania (np. niektóre hostingi mają inne IP do połączeń lokalnych niż do zewnętrznych)

**Comment by marcinkowalczyk2** [comment]
Dzięki za szybką odpowiedź, używam 9, bo taką mam aktualnie na lokalnym komputerze zainstalowaną :D No nic popróbuje i dam znać.

**Comment by marcinkowalczyk2** [comment]
Dobra dziwna sprawa, wyrzuca błędy, ale wszystko się w bazie stworzyło O_o

**Comment by marcinkowalczyk2** [comment]
Znalazłem błąd inny plugin też korzystał z tabeli users i dlatego się gryzło
