### ISSUE TITLE
Bug z Znikającymi gildiami.

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#805]
Ostatnio od graczy dostałem nieoczekiwanie zgłoszenie, że ich gildia znikła. Sprawdziłem w logach, i nie było żadnego błędu albo komunikatu że "gildia wygasła" a skoro to nie było wygaśnięcie gildii bo gildia miała 2 dni a w configu ważność założonej gildii to 15, to jest to błąd.

Bazę danych mam Flat (lokalne pliki).

FunnyGuilds: 4.1.1 Tribute, Silnik: PaperSpigot 1.12.2, Java 8

Liczę na zainteresowanie się problemem.

**Comment by Kamilkime** [comment]
Logi i config?

**Comment by MentosPL** [comment]
Czytaj ze zrozumieniem.

Sprawdziłem w logach, i nie było żadnego błędu

Config:
w configu ważność założonej gildii to 15,
Bazę danych mam Flat (lokalne pliki).

**Comment by MentosPL** [comment]
Słuchaj, czy ty myślisz że mam 5 lat? mylisz się, jeśli ja mówię że nie było żadnego komunikatu to tak jest, nie ma kompletnie nic, tylko informacje jak gracze wchodzą i wychodzą z serwera i ich rozmowy i wpisywane komendy ;) Kompletne zero null.

Config domyślny ;) z zmienioną kolorystyką na &6. podałem ci ważne informacje.

Chcesz coś co i tak ci w niczym nie pomoże.

**Comment by Kamilkime** [comment]
Powiem jeszcze jeden, ostatni raz, bo man dużo cierpliwości - config, logi i skoro ma mi to podobno nie pomóc, to jeszcze spakuj dane z fg (userów, gildie, regiony) w archiwum .zip i je też podeślij

**Comment by MentosPL** [comment]
[DATA.zip](https://github.com/FunnyGuilds/FunnyGuilds/files/1802609/DATA.zip)
A config domyślny ;) Deafult rozumiesz? odpalasz FG i masz to samo co ja, tylko bez ustawionych  itemów na gildie XD Czego ty nie rozumiesz.

Logów ci nie dam, są tam poufne dane jak Adresy IP i rozmowy graczy. I logi by ci nic nie dały, bo NIE MA NIC. 

A gildia która znikła to DARK - DarkWolves - ciekawe czy gdzieś znajdziesz.

**Comment by Kamilkime** [comment]
Z powodu braku współpracy autora - zamykam temat

**Comment by MentosPL** [comment]
Wcale nie dostałeś potrzebnych informacji i pliku z  " spakuj dane z fg (userów, gildie, regiony) w archiwum .zip i je też podeślij".....

Twoje rozumowanie jest na poziomie przedszkolaka. "Popsuł się komputer, powiedz jaka była pogoda i podeślij zdjęcie parapetu"(przykład) .... żenada..

**Comment by Kamilkime** [comment]
Mówię ci, czego potrzebuję, żeby się zająć twoim błędem - każdy z nas jest już nauczony doświadczeniem, że 90% ludzi mówi _mam wszystko dobrze_, po czym my coś po długiej kłótni i tak znajdujemy. Jeśli nie chcesz dostarczyć mi potrzebnych mi informacji - nie marnuj mojego czasu pisząc issue

Skoro przychodzisz tu i piszesz issue - chcesz, żeby developer pluginu zajął się twoim problemem. Więc rób to, co ci developer mówi, bo to on się zna na pluginach lepiej niż ty i wie, czego potrzebuje do zbadania problemu. Jeśli masz zamiar nie robić tego, co mówimy, że jest nam potrzebne - nie rób issue, szkoda czasu i miejsca na dyskach GitHub'a

**Comment by kacperduras** [comment]
Gratuluje! @MentosPL wygrałeś talon na darmowego bana z powodu reprezentowania zbyt niskiego poziomu **jak na to community**, co jest dość sporym wyróżnieniem. Przekroczyłeś wszystkie normy kretynizmu ustalone przez takie organizacje jak:
* WHO
* UNESCO
* NASA
* NSA
* FBI
* AC/DC
To co sobą reprezentujesz sięga poziomu dna, nie ukrywajmy. Karygodne traktowanie nas, twórców - zasługuje na potępienie, zwłaszcza że to prowadziło do skłócenia naszej małej społeczności wielokrotnie. Gratuluje wygrania plebiscytu!
