### ISSUE TITLE
Dalsza możliwość zakładania gildii przy granicy mapy

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#806]
Coś nie działa ta opcja z odległością od granicy mapy. Jestem na współrzędnych X:1999 Z:1999 a i tak mogę założyć tam gildię mimo tego, że tak wyglądają moje ustawienia:

server.properties: `max-world-size=2000`

```
# Minimalna odleglosc od granicy mapy, na ktorej znajduje sie gracz
# Wartosc -1 oznacza brak minimalnej odlegosci od granicy
create-guild-min-distance: 200.0
```

**Comment by FastJoe0** [comment]
Sprawdziłem najnowszy build. Dalej występuje problem.

**Comment by insertt** [comment]
Niestety, ale działanie domyślnej granicy mapy jest dość mocno popsute przez co weryfikacja odległości nie działa poprawnie. Na czas, gdy nie znajdziemy innego rozwiązania proponuję ręcznie ustawić granicę mapy za pomocą komendy `/worldborder` , dzięki której walidacja odległości będzie działać poprawnie.

**Comment by FastJoe0** [comment]
A gdyby zamiast tego podpiąć plugin WorldBorder? Moim zdaniem będzie to ciekawsza opcja.
