### ISSUE TITLE
Maly blad powiazany z nickiem

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#808]
Witam, 
Gdy istnieje gracz o nicku GraSS i np. ktos chce sprawdzic staty tej osoby czyli wpisuje /gracz grass to wyskakuje komunikat " Ten gracz nigdy nie byl na serwerze " ... :D Maly blad :D

Zeby komenda dzialala musi gracz wpisywac /gracz GraSS

**Comment by insertt** [comment]
To nie błąd, to zamierzony efekt w związku z poprawą działania uuid, ale w planach jest udoskonalenie lookupu.
