### ISSUE TITLE
Przeładowanie danych na innych serwerach połączonych BungeCord'em.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#809]
Więc, tak podam na swoim przykładzie, tworzę sektory i dodałem do tego FunnyGuilds, połączyłem MySQL i działa - teleportacja na bazę z automatyczną zmianą sektora itd. Niestety pojawia się problem, gdy gildia zostania usunięta to dane na innym sektorze - serwerze nie zostaną załadowane, gdyż nie dociera do niech informacja o usuniętej gildii czy np. dodanym członku. Może przyda się to niewielkiej ilości osób używających FG, ale części tak.

**Comment by kacperduras** [comment]
Kwestia integracji między serwerami leży w roli developera tworzącego integrację. FG nie ma w założeniu celu stworzenia takowej komunikacji, ponieważ nie ma to sensu. Sama struktura projektu mówi o tym, że jest on przeznaczony na działanie w jednej, pojedynczej instancji. Jeżeli ktoś jest zainteresowany integracją FG ze wsparciem wielu serwerów, to i tak czekają go spore modyfikacje kodu względem pierwowzoru. Zamykam.
