### ISSUE TITLE
Ukrycie graczy na vanishu w {online} na tabie

### ISSUE THREAD

**Issue by Adrian5063** [FunnyGuilds/FunnyGuilds#810]
Witam chodzi mi oto aby po wpisaniu /v ktoś został ukryty aby znikał z {online} na tabie FunnyGuilds.

(https://user-images.githubusercontent.com/37386022/37433810-af025690-27dd-11e8-8ae4-3c93a6b1f0c9.png)

**Comment by kacperduras** [comment]
Zaimplementowane w #815.
