### ISSUE TITLE
Nie pokazuje asysty!

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#813]
Witam,
Od dlugiego czasu na czacie nie pokazuja sie asysty

kawalek z messages.yml:
https://hastebin.com/elizuqipoc.m

**Comment by Kamilkime** [comment]
Na pewno masz je włączone w configu? Może asystuje na tyle dużo osób, że procentowo ludzie mają tak mały udział, że plugin ich pomija? Sprawdź to mając tylko jednego gracza asystującego, wtedy coś powinno pokazać

**Comment by sokrates1231** [comment]
@Kamilkime 
# Czy ma byc zablokowana zmiana rankingu, jesli obie osoby z walki maja taki sam adres IP
rank-ip-protect: true
# Czy system asyst ma byc wlaczony
rank-assist-enable: true
# Jaka czesc rankingu za zabicie idzie na konto zabojcy
# 1 to caly ranking, 0 to nic
# Reszta rankingu rozdzielana jest miedzy osoby asystujace w zaleznosci od zadanych obrazen
rank-assist-killer-share: 0.5

sprawdzalem, nie dziala.

**Comment by Kamilkime** [comment]
Podeślij log z serwera

**Comment by sokrates1231** [comment]
@Kamilkime 
moge gdzies na prv poniewaz tam ip graczy wiec wiesz...

**Comment by kacperduras** [comment]
To wytnij, pomocy udzielamy tutaj, przynajmniej oficjalnie.

**Comment by Kamilkime** [comment]
Niech już nie wycina i podeśle całość. Jak masz np. discorda, to tam możesz podesłać na privie @sokrates1231

**Comment by Kamilkime** [comment]
Błędu nie udało się odtworzyć, więc zamyka. Gdyby błąd znowu wystąpił - stwórz nowe issue
