### ISSUE TITLE
Nie działacje komendy,

### ISSUE THREAD

**Issue by opentanystiv** [FunnyGuilds/FunnyGuilds#817]
Witam, posiadam najnowsza wersje funnyguilds 4.1.1 tribute.
Gdy chce wpisać komende /g pisze Ta komenda jest wylaczona!
Gdy wpisuje /ga enabled to samo.. :(

**Comment by Kamilkime** [comment]
Na samym dole configu jest konfiguracja komend, a przy każdej komendzie - sekcja **enabled**, która odpowiada za to, czy komenda jest wyłączona
