### ISSUE TITLE
Bug w tabliście

### ISSUE THREAD

**Issue by Mikosikora** [FunnyGuilds/FunnyGuilds#821]
Gdy gracz np. Nie ma gildii lub na takie j pozycji w top gildiach nie ma gildii to zamiast "Brak" napisane jest dodatkowo "G-NAME/NAME" co strasznie psuje wygląd całej tablisty. to screen http://prntscr.com/itvr0j

**Comment by Kamilkime** [comment]
Wszystko można zmienić w pliku messages.yml, wiadomości domyślne są takie, aby było wiadomo zamiast czego się pojawiają
