### ISSUE TITLE
PlaceHolderApi

### ISSUE THREAD

**Issue by opentanystiv** [FunnyGuilds/FunnyGuilds#822]
Witam, chciałbym się podpytać jak zrobić placeholderapi, pod fg.

**Comment by Kamilkime** [comment]
Wszystkie placeholdery, które FG dodaje, są podane tutaj: https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-2/#funnyguilds

**Comment by opentanystiv** [comment]
Ale jak to ustawić.

**Comment by Kamilkime** [comment]
No, dodajesz je sobie po prostu w innym pluginie, który wspiera zamianę placeholderów z PlaceholderAPI

**Comment by opentanystiv** [comment]
Jakim?

**Comment by Kamilkime** [comment]
No, jest dużo innych pluginów, które wspierają użycie tych, są podane na spigotmc, na stronie PlacegolderAPI. FG tylko dodaje placeholdery i zwraca konkretne dane, gdy inny plugin chce ich użyć i je zamienić

**Comment by kacperduras** [comment]
```
No, jest dużo innych pluginów, które wspierają użycie tych, są podane na spigotmc, na stronie PlacegolderAPI. FG tylko dodaje placeholdery i zwraca konkretne dane, gdy inny plugin chce ich użyć i je zamienić
```

Objaśnione, zamykam.
