### ISSUE TITLE
Błąd przy wychodzeniu gracza z serwera

### ISSUE THREAD

**Issue by Querko7** [FunnyGuilds/FunnyGuilds#824]
Nie wiem czy naprawione czy nie, ale błąd pojawia się jak gracz wychodzi z serwera (nie w każdym przypadku.) Używam wersji 4.2.0

Błąd: https://pastebin.com/Xv0uwuR4

**Comment by insertt** [comment]
Skoro nie wiesz czy jest naprawione czy nie, to warto się upewnić i przetestować najnowszą wersję, inaczej tworzysz niepotrzebny issue, na który trzeba poświęcić czas, który można by spędzić naprawiając/dodając coś innego.

**Comment by Toranktto** [comment]
Czy to jest pełny log? Jeżeli nie i najnowsza wersja nie działa to wrzuć całość, bo akurat w tym kawałku za wiele informacji nie ma.

**Comment by Kamilkime** [comment]
Wygląda na ten sam błąd co w #823, więc już poprawiony. Zbuduj sobie tylko nowe FG [FunnyCreator'em](https://dzikoysk.net/projects/funnycreator/download/1.0.6/funnyguilds-creator-1.0.6.jar)
