### ISSUE TITLE
Brak oddawania postawionych bloków przy włączonym `bugowaniu klocków`

### ISSUE THREAD

**Issue by opentanystiv** [FunnyGuilds/FunnyGuilds#828]
Zabiera "klocki" przy bugowaniu klockami.
Czyli gdy postawimy slimeblocka, zabiera go. :-1:  
Zrobcie cos z tym ://

**Comment by kacperduras** [comment]
Jak dla mnie to powinno zabierać, w końcu to `feature`, aniżeli `bug`. Ale ok, dodam pole w konfiguracji, po którego zaznaczeniu będzie te bloki oddawało, ale to i tak jest wg. mnie dalej bez sensu.

**Comment by opentanystiv** [comment]
Chodzi mi bardziej pvp slimeblock zabiera ciagle i lipa
