### ISSUE TITLE
Nie działa top Gildi

### ISSUE THREAD

**Issue by thirdanoin** [FunnyGuilds/FunnyGuilds#831]
Witam ,
Po wgraniu pliku na serwer nie działa topka gildii serwer stoi na papierku 1.8.8 w miejscu gdzie powinna być gildia pisz BRAK

**Comment by kacperduras** [comment]
```
Nieznajomość konfiguracji szkodzi
```
a przynajmniej tak ktoś mawiał. Gdybyś przeczytał dokładnie cały plik konfiguracyjny, to byś zauważył, że ranking gildii jest uwzględniany od `n` osób, gdzie `n` to liczba całkowita podana w konfiguracji. Zamykam, temat wyjaśniony.

**Comment by Kamilkime** [comment]
Jest dokładna odpowiedź, napisana przez @kacperduras, w której opisuje jak to działa. Nie ma tu nic więcej do tłumaczenia, jest tylko config do zapoznania się

**Comment by kamcio96** [comment]
Lol, po co czytać config. Ma działać, chujowy plugin...
