### ISSUE TITLE
Pytanie co do bordera

### ISSUE THREAD

**Issue by Klaud3k** [FunnyGuilds/FunnyGuilds#832]
Witam jak ustawić że od granicy bordera nie można zakładać gildii  ?
Oraz z jakim pluginem/skryptem na granice mapy to działa :

**Comment by Kamilkime** [comment]
Na razie, jak napisane w #806, nie działa to prawidłowo, ale szukamy dobrego rozwiązania. Zamknę to issue, ewentualna informacja o naprawie tej granicy będzie w #806 :)
