### ISSUE TITLE
Dziwne tagi za "Brak"

### ISSUE THREAD

**Issue by kubalaszuk2** [FunnyGuilds/FunnyGuilds#834]
Witam,
Jak pozbyć się tego "(GTOP-X)" z tablisty?

https://imgur.com/a/zSDyK

**Comment by insertt** [comment]
W pliku `messages.yml` można zmienić wszystkie placeholdery braków.

**Comment by Kamilkime** [comment]
Jak wy ludzie możecie używać pluginu nie przeglądając dokładnie całej konfiguracji?!

**Comment by Kamilkime** [comment]
Właściwie, @kubalaszuk2, takie pytanie - jakiej wersji FG używasz (z FunnyCreator'a czy oficjalnej) i czy wgrywałeś teraz czyste FG (lub czy miałeś już wcześniej stworzony config/messages)?

**Comment by kubalaszuk2** [comment]
oficjalnej i od razu w czystym

**Comment by Kamilkime** [comment]
A, ok
