### ISSUE TITLE
Brak (GTOP-X), Brak (PTOP-X), problem

### ISSUE THREAD

**Issue by FinneK2** [FunnyGuilds/FunnyGuilds#836]
Witam. Mam taki problem, że jak mam GTOP-1 to jest tam moja gildia jak założę i tak samo w PTOP-1 jestem ja bo jestem pierwszym graczem, ale jak jest PTOP-2 to tam jest Brak bo nie ma gracza i w nawiasie jest (PTOP-X) i wygląda to tak: "Brak (PTOP-X)" Jak usunąć to w nawiasie? Żeby było samo Brak?
Proszę o pomoc :) Pozdrawiam
I jest tak w wersji 4.2.0 :)

**Comment by Kamilkime** [comment]
#834
