### ISSUE TITLE
Licencja

### ISSUE THREAD

**Issue by TheMolkaPL** [FunnyGuilds/FunnyGuilds#838]
W repozytorium brakuje pliku licencji LICENSE, przez co licencja kodu jest nieznana.

**Comment by dzikoysk** [comment]
```Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.```

**Comment by kacperduras** [comment]
Proponowałem to ostatnio @dzikoysk.
Domyślnie kod bez widocznej licencji jest na zasadzie `All rights reserved`, przynajmniej [tutaj](https://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html) pisze [Brian Doll](https://github.com/briandoll), ówczesny VP GitHub'a:
```
Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.
```

**Comment by Kamilkime** [comment]
No, skoro nie ma licencji, to po prostu autor ma pełne prawa autorskie i tylko on może coś z tym robić. To może wypadałoby dodać jakąś licencję, żeby też ludzie np. mogli sobie ten kod poprzerabiać, itd.

**Comment by TheMolkaPL** [comment]
Oficjalnie nikt nie ma prawa forkować i ulepszać, żeby zrobić pull requesta (☭ ͜  ʖ ☭)

**Comment by TheMolkaPL** [comment]
GNU GPLv3 jest bardzo restrykcyjna, Każda edycja kodu, którą można doświadczyć na publicznym serwerze musi zostać publicznie upubliczniona.

MIT jest najbardziej liberalne.

**Comment by kacperduras** [comment]
```
GNU GPLv3 jest bardzo restrykcyjna, Każda edycja kodu, którą można doświadczyć na publicznym serwerze musi zostać publicznie upubliczniona.
```

I ja to popieram, nie po to tworzymy coś za darmo by ktoś na tym zarabiał.

```
MIT jest najbardziej liberalne.
```

Wiem, wymieniłem w kolejności od najbardziej restrykcyjnej, do liberalnej.
