### ISSUE TITLE
Dodanie eventów

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#839]
Co Wy na to - aby dodać eventy do FG?
Np.: GuildCreateEvent, PlayerInviteEvent, etc.

**Comment by Kamilkime** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/tree/master/src/main/java/net/dzikoysk/funnyguilds/event

**Comment by kamcio96** [comment]
XDDDD
just mpcuser things 😁👌

**Comment by Revelacyjny** [comment]
XDDDDDDDDDD
