### ISSUE TITLE
Nieprawidłowy ping

### ISSUE THREAD

**Issue by FastJoe0** [FunnyGuilds/FunnyGuilds#842]
Coś nie tak jest ze zmienną {PING}. Pokazuje mi na przykład 0ms albo inne małe wartości (>20) a to jest niemożliwe skoro serwer leży we Francji a ja mieszkam w Polsce. Niedawno przed aktualizacją FG do najnowszej wersji wyświetlało się 40-50ms. Zero błędów w konsoli oraz config domyślny.

**Comment by Kamilkime** [comment]
Skoro pokazuje taki ping - taki widzi twój serwer MC. FG pobiera ping z serwera, nie liczy go sam
