### ISSUE TITLE
Problem z BungeeTabListPLus

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#843]
Witam, mam problem dotyczący z BungeeTabListPlus bo nie zbyt ogarniam tego, żeby dodać do taba jakieś główki itp. nigdy nie używałem bungeetablistplus ale dodałem na serwer BungeeTabListPlus_BukkitBridge-2.8.3 i nie wiem jak dodać te główki może źle zrozumiałem, ponieważ jaki pisałem nie miałem kontaktu z tym pluginem.
A co do tego, że napisałeś, że więcej info w konfiguracji to chyba, żadnej informacji nie ma w cfg.
Wiem co to bungee nie będę pierdolił co to jest ale myślałem, że będzie funkcja, że można bez proxy ogarnąć te główki jeżeli się da to proszę odpisać. 
Edit: Nie wiem czy to jest prawda ale niby bungeetablistplus ma api i tylko dodaliście do fg wsparcie.
Pozdrawiam, Drejkbr.

**Comment by Kamilkime** [comment]
Ale jakie główki? Jeśli chodzi o konfigurację samego BungeeTabListPlus - repozytorium FG nie jest miejscem na pytanie o to, nie zajmujemy się konfiguracją tego pluginu

**Comment by kacperduras** [comment]
To co @Kamilkime wspomniał, `repozytorium FG nie jest miejscem na pytanie o to, nie zajmujemy się konfiguracją tego pluginu`.
