### ISSUE TITLE
Blad

### ISSUE THREAD

**Issue by Kupis01** [FunnyGuilds/FunnyGuilds#844]
Czesc, po zaaktualizowaniu mam blad i nie odpala mi sie plugin, silinik - paper spigot 1.8.8 logi -
https://hastebin.com/kinepubuvi.hs

**Comment by Kamilkime** [comment]
Podaj w pliku **"-"** zamiast **-**

**Comment by Kamilkime** [comment]
Zakładam, że problem został naprawiony i nie ma już dalszych. Gdyby były - otwórz nowe issue
