### ISSUE TITLE
Wsparcie dla pluginu LeaderHeads

### ISSUE THREAD

**Issue by xBlaczeKx** [FunnyGuilds/FunnyGuilds#847]
Witam, proponuję przy następnej aktualizacji dodać wsparcie dla pluginu **LeaderHeads**. Byłby to ciekawy dodatek :)

**Comment by kacperduras** [comment]
[API jest](https://robindebaets.be/leaderheads/api) - leci do TODO. Dzięki za propozycję ;)

**Comment by Kamilkime** [comment]
Chciałem to dodać, ale na razie zawieszam - LeaderHeads nie ma żadnego repo, trzeba by to robić z pliku [lokalnego](https://www.robindebaets.be/LeaderHeadsAPI.jar) :/

**Comment by insertt** [comment]
Jeżeli ma ktoś możliwość przetestowania wsparcia dla pluginu LeaderHeads (niestety my nie mamy jak ze względu na to iż plugin jest płatny), to byłoby nam bardzo miło :)
