### ISSUE TITLE
Dodanie "last_mod_time" dla obiektów w bazie danych

### ISSUE THREAD

**Issue by NotJustPizza** [FunnyGuilds/FunnyGuilds#849]
Witam. Było by świetnie gdyby została dodana właściwość "last_mod_time" zawierająca ostatni czas modyfikacji obiektu dla wszystkich obiektów w bazie. Oczywiście ta wartość musiała by się automatycznie ustawiać podczas dodania lub zmiany obiektu. Po co? Dzięki dodaniu tej funkcjonalności zewnętrzne programy działające na bazie mogą potwierdzić czy załadowane dane zostały zmienione i jeżeli tak to porzucą zmiany lub wyplują błąd. Ten prosty mechanizm pozwala na uniknięcie konfiliktów.

**Comment by KrejzolekPRO** [comment]
Jak najbardziej na plus, dodać jeszcze metodę (ala API) #.getLastModTime() i będzie cool, dzięki czemu kompatybilność z sektorami będzie łatwiejsza.

**Comment by kacperduras** [comment]
@KrejzolekPRO o tym wspominać nie musisz - to jest raczej oczywiste.

**Comment by kacperduras** [comment]
Co do propozycji @SlimaKCoder - to `usprawnienie` miałoby racje bytu przy nowym systemie zapisu i odczytu danych, który jest planowany na release 5.0.0, który obecnie nie wiadomo, kiedy nastąpi.

**Comment by SlimaKCoder** [comment]
@kacperduras A jak miało by wyglądać 5.0? Jest jakiś milestone z propozycjami do niego? Co zmieniło by się w zapisie i odczycie?

**Comment by Kamilkime** [comment]
Wreszcie byłby wydajny i napisany w jakiś mądry sposób xD

**Comment by SlimaKCoder** [comment]
Jeżeli planujecie bazować na MySQL lub PostgreSQL to mogę pomóc pisać i analizować strukturę bazy oraz polecenia/funkcje do operacji na danych.

**Comment by SlimaKCoder** [comment]
Do obecnej wersji pluginu trzeba by dodać jakiś exporter danych, a w nowej importer i powinno być git z migracjami :)

**Comment by kacperduras** [comment]
Na pewno nowy system danych będzie napisany w taki sposób, by móc w prosty sposób dodawać implementację nowych rodzajów zapisu, na dzień dzisiejszy na pewno będzie to MySQL/MariaDB, rozważamy także PostgreSQL. Flat będzie najprawdopodobniej porzucone.

**Comment by Kamilkime** [comment]
To trzeba ludziom dać jakieś np. SQLite, nie każdy ma np. bazę MySQL :/

**Comment by SlimaKCoder** [comment]
Proponuje napisać 2 implementację - jedną dla SQLite, a drugą dla MySQL lub PostgreSQL. ORM wydajnościowie ssie, więc proponuje raw SQL dla danego silnika oraz konweter między nimi. W przypadku MySQL i SQLite ewentualnie można by użyć jedynie uniwersalnych zapytań dla obu silników bazodanowych.

**Comment by dzikoysk** [comment]
:)

**Comment by SlimaKCoder** [comment]
Jakieś 3 lata temu powstała nawet propozycja modelu bazy dla MySQL: https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21

Trzeba by ją troszkę udoskonalić, ale jest jakiś punkt zaczepienia :D

**Comment by dzikoysk** [comment]
#1074

**Comment by dzikoysk** [comment]
#1402
