### ISSUE TITLE
Dodanie nagrody za 1 gildie

### ISSUE THREAD

**Issue by Pak3rP** [FunnyGuilds/FunnyGuilds#854]
Może dodajcie nagrode za 1 zalozenie gildi ?? To jest fajny po mojemu sposób. Coś typu on first czy coś.
np. jak gracz zalozy gilde to automatycznie dostaje przedmiot który można ustawić w configu.
Cos to Poopozycja.
(Lubie się udzielać)

**Comment by kacperduras** [comment]
Jak dla mnie jest to bez sensu, bardziej to leży w kwestii dodatku pod FG który da się na dzień dzisiejszy wykonać, a nie samych gildii.

**Comment by jasuogra** [comment]
Chyba zacznę publikować takie dodatki :wink:

**Comment by Pak3rP** [comment]
Ale sam dodatek to kolejny plugin, a jakby to było np. W FG to by nie potrzeba kolejnych pl. Ale sam dodatek jest i tak spokoju rozwiązaniem.

Mam pytanie ktoś pomoże mi skonfigurować itemy na gildie w najnowszym FG bo jak dam 9 slotów to mam błąd czy cos takiego. 
No po prostu mi nie wychodzi.

**Comment by hamsterofficial** [comment]
@Pak3rP **Discord: hamster#0001** ;)
