### ISSUE TITLE
Błąd z TabListą!

### ISSUE THREAD

**Issue by SOP3K-exe** [FunnyGuilds/FunnyGuilds#855]
Witam, napotakałem się na problem z TabList'ą nie wiem czy mam coś źle w configu więc proszę o pomoc ,gdyż popsuły sie zmienne. Poniżej podsyłam link do ScreenShota. (Jest to wersja 4.3.0 FunnyGuilds!)

https://imgur.com/a/SANlV

**Comment by Kamilkime** [comment]
Nic się nie popsuło, spójrz w messages.yml
