### ISSUE TITLE
Bug z bugowaniem

### ISSUE THREAD

**Issue by creepek** [FunnyGuilds/FunnyGuilds#857]
Znalazlem buga, gdy wlacze opcje "bugowania klockow" to na terenie gildii moge postawic tnt i obok niego pochodnie to tnt sie podpali a pochodnia wroci do eq. Naprawcie to ;)

**Comment by kamcio96** [comment]
włączyłeś buga, co się dziwisz XD

**Comment by creepek** [comment]
@kamcio96 yyy, włączyłem bugowanie klocków, nie dynamitu #iksde

**Comment by kacperduras** [comment]
@kamcio96 to nie bug, to ficzer ( ͡° ͜ʖ ͡°)

**Comment by insertt** [comment]
Pochodnia czy TNT to też blok w rozumowaniu minecrafta :/

**Comment by creepek** [comment]
@insertt to to akurat wiem, bo sam umiem plg pisac. Wlasnie dlatego prosze was o naprawienie tego - lecz wiedze ze nikt sie tym nie zajmie :unamused:

**Comment by happiii** [comment]
Skoro umiesz pisać pluginy, to sam sobie napraw. :)

**Comment by KrejzolekPRO** [comment]
Weź pod uwagę, że ktoś inny też może mieć z tym problem i tego już nie będzie umiał naprawić :) @happiii

**Comment by happiii** [comment]
@KrejzolekPRO to może zrobić coś pożytecznego i dać pull requesta. Wtedy każdy będzie miał naprawione. :)
