### ISSUE TITLE
[Propozycja] Dodanie wparcia pluginu WorldBorder

### ISSUE THREAD

**Issue by Querko7** [FunnyGuilds/FunnyGuilds#858]
Witam,
Proponuje dodać wsparcie dla pluginu WorldBorder. Głównie chodzi o to żeby nie dało się zakładać gildii przy granicy mapy.

**Comment by Kamilkime** [comment]
#806 i WorldBorder sam w sobie nie ma dobrego API, więc trudno byłoby dodać konkretne wsparcie
