### ISSUE TITLE
Wsparcie dla pluginu LogBlock.

### ISSUE THREAD

**Issue by nowuscode** [FunnyGuilds/FunnyGuilds#861]
Witam, to znowu ja 😀
Przychodzę z pewną propozycją, a mianowicie dodaniem wsparcia dla pluginu LogBlock, bądź dopisanie tego w fg. Aby eksport bazy danych nie ważył 10 GB proponuje również dodać komendę, która by clearowała zapisy, bądź automatycznie je czyściła.    
        Pozdrawiam ;)

**Comment by kacperduras** [comment]
#610
