### ISSUE TITLE
Nowe zmienne w tabliscie.

### ISSUE THREAD

**Issue by nowuscode** [FunnyGuilds/FunnyGuilds#863]
Witam,
Przychodzę z pewną propozycją, a mianowicie z dodaniem nowych zmiennych ( {WORLD} i {REGION-NAME} ). W region name chodzi o wyświetlanie regionu z worldguard'a.
        Pozdrawiam

**Comment by Kamilkime** [comment]
Zamiast tego proponuję do wbudowanej tablisty dodać np. wsparcie PlaceholderAPI, powinien chyba mieć coś w WG

**Comment by nowuscode** [comment]
Zawsze wydawało mi się, że placeholderApi wspiera fg :/

**Comment by Kamilkime** [comment]
W drugą stronę - FG wspiera PlaceholderAPI, dodając do niego trochę swoich zmiennych

**Comment by nowuscode** [comment]
Faktycznie, przeoczyłem :D
