### ISSUE TITLE
Naprawa tabu itd.

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyGuilds#864]
Elko, to znowu ja chciałem naprawić ten błąd przy tym tabie (co wczoraj zgłaszałem) no i pobrałem i wgrałem sobie ta wersje - https://ci.kacperduras.pl/job/FunnyGuilds/17/ (orginal)
No i coś nowego się pokazuje nie wiem czy to coś pomoże przy tym błędzie od tabu.
logi:
https://pastebin.com/tNcxJmY6
cfg:
https://pastebin.com/Lj6k5hqJ
ps. wiem, że jest moje tam ip i tak mam zmienne a co do hasła to jest random ;x

**Comment by Kamilkime** [comment]
Który plik pobrałeś?

**Comment by kacperduras** [comment]
@Kamilkime oczywiście, że nie ten co trzeba - tj. ten mniejszy, bez potrzebnych bibliotek, zamykam.
