### ISSUE TITLE
Błąd z ochroną TNT w danych godzinach

### ISSUE THREAD

**Issue by dzokuxd** [FunnyGuilds/FunnyGuilds#865]
Ustawiłem że tnt nie działa po godzinie 23:00 a zaczyna się o 14:00  jest godzina 00:54 i tnt dalej działa

**Comment by Kamilkime** [comment]
W takim razie pokaż config i log z serwera

**Comment by dzokuxd** [comment]
Logi: https://pastebin.com/6j2wEaWA
config: https://pastebin.com/ZU7Mudwt

**Comment by Kamilkime** [comment]
Użyj najnowszej wersji FG, wtedy zobaczymy co jest źle

**Comment by dzokuxd** [comment]
To jest najnowsza tylko że zmieniłem ze pisze ver: 4.0 a nie 4.3.0 i zamiast FunnyGuilds to Guilds

**Comment by Kamilkime** [comment]
To... po co zmieniałeś wersję? I czy to jedyne zmiany wprowadzone przez ciebie w pluginie?

**Comment by dzokuxd** [comment]
Tak tylko takie

**Comment by insertt** [comment]
Jak zmiana nazwy pluginu jest dostępna z poziomu konfiguracji, tak wersja już nie, dlatego użyj niezmodyfikowanej wersji i jeżeli uda Ci się zreprodukować błąd, napisz ponownie.

**Comment by kacperduras** [comment]
Pozwolę sobie oznaczyć autora ficzera
/cc @Toranktto: 9162a6744c407a424c10f06a330025466f72af5b

**Comment by dzokuxd** [comment]
Powiem tak nawet na świeżo pobranym pluginie teraz dalej nie działa

**Comment by Kamilkime** [comment]
Jeśli dobrze myślę, to obecna implementacja zapisuje sobie datę i czas, więc po pewnym czasie godziny nadal powinny mieć sens, ale data już jest stara, więc serwer musiałby być restartowany raz dziennie, żeby to dobrze działało :/

https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L1128-L1138

**Comment by dzokuxd** [comment]
A jeśli dopiero włączam serwer a tnt dalej działa i np. odczekuje 15 min i ono dalej działa

**Comment by Kamilkime** [comment]
Pobierz sobie za moment nowe FG z https://ci.kacperduras.pl/job/FunnyGuilds/ (plik `funnyguilds-4.3.0.jar`, build `#18`)
