### ISSUE TITLE
Możliwość wyświetlania wiadomości w TITLE

### ISSUE THREAD

**Issue by jasuogra** [FunnyGuilds/FunnyGuilds#866]
Heja! 

Moja propozycja jest taka by dodać możliwość by wiadomości typu intruz, wszedłeś na teren czyjeś gildii, zabójstwo itd można było wyświetlać w title. Taki ficzer o :)

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java#L163-L168
