### ISSUE TITLE
Punkty gracza, po kliknięciu PPM na niego.

### ISSUE THREAD

**Issue by nowuscode** [FunnyGuilds/FunnyGuilds#867]
Witam, to znowu ja
Proponuję dodać do konfiguracji coś w stylu: ppm-point-checker: "Gracz {PLAYER} posiada {POINTS} punktów."
Pozdrawiam.

**Comment by Kamilkime** [comment]
No, można włączyć przecież odpalanie komendy /gracz przy takim naciśnięciu

**Comment by nowuscode** [comment]
Ale po wpisaniu /gracz będą tylko wyświetlone punkty..

**Comment by Kamilkime** [comment]
Że co?

**Comment by nowuscode** [comment]
Jeśli chce po wpisaniu komendy /gracz mieć punkty, zabójstwa, zgony i miejsce w rankingu. Po kliknięciu na gracza chciałbym tylko jego punkty.
