### ISSUE TITLE
Brak bibliotek po wyeksportowaniu funnyguilds z eclipse.

### ISSUE THREAD

**Issue by Querko7** [FunnyGuilds/FunnyGuilds#868]
Witam,
Mój problem polega na tym, że po wyeksportowaniu funnyguilds z eclipse nie ma żadnych bibliotek przez co plugin nie włącza się i wywala błędy noclassdeferror.
Proszę o pomoc 

(Użyłem mavena aby zainportować projekt do eclipse)

**Comment by insertt** [comment]
Budujesz projekt za pomocą mavena?

**Comment by Querko7** [comment]
Nie, jako jar file

**Comment by kacperduras** [comment]
Wszystko jasne, buduj całość jako Maven project używając dedykowanego pluginu do Eclipse,
