### ISSUE TITLE
Baza danych Redis

### ISSUE THREAD

**Issue by pnowakdev** [FunnyGuilds/FunnyGuilds#869]
Witam, 
mogę być już denerwujący lecz lubię się udzielać = ) Dowiedziałem się, że będziecie przerabiać bazy danych. Dlatego pomyślałem, że wyjdę z inicjatywą dodania możliwości wyboru MySQL czy Redis w cfg.
Pozdrawiam :p

**Comment by kacperduras** [comment]
To nie jest właściwe zastosowanie Redisa - są lepsze alternatywy, dajmy na to Cassandra.

**Comment by dzikoysk** [comment]
@kacperduras chciałeś chyba powiedzieć MongoDB, ale każdemu zdarza się literówka

**Comment by kacperduras** [comment]
@dzikoysk *PandaDB, ale spokojnie - nawet takim osobom jak Ty błędy się zdarzają D:

**Comment by nowuscode** [comment]
To jak nie Redis to proponuję sqlite

**Comment by kacperduras** [comment]
A różni się to od obecnego systemu zapisu na plikach, z wyjątkiem formy pliku w jakiej są dane przechowywane? To i to zapisuje się lokalnie, a dla większego performance i tak lepiej wybrać dedykowane do tego rozwiązania, tj. na dzień dzisiejszy bazę danych MySQL.

**Comment by nowuscode** [comment]
No to ja już nwm :/

**Comment by nowuscode** [comment]
Ale w sumie jakby ktoś chciał zrobić statystyki na stronę, to z plików info nie pobierze :/

**Comment by kacperduras** [comment]
Ale z MySQL już tak, natomiast z SQLite również, chyba że wystawi to we formie dajmy na to API REST. W sumie, to też można byłoby wtedy zrobić z plikami, więc zasadniczo byłoby to jedno i to samo.

**Comment by kamcio96** [comment]
Yyy, ale po co. MySQL jest podstawową bazą kompatybilna ze wszystkim, FG ma prostą strukturę, więc żadne cache czy bazy nie relacyjne nie są potrzebne. Jak ktoś nie ma SQL to może zapisać do pliku a wtedy już to bez znaczenia jak się zapisuje. Dodawanie czegoś dla samego dodania nie ma sensu :v

**Comment by nowuscode** [comment]
Szanuje czas osób, które tworzą fg. Gdy dodawałem propozycję - nie byłem świadomy tego, że można to odczytać z plików :c

**Comment by insertt** [comment]
No i nie zapominajmy, że w przeciwieństwie do np. MongoDB, MySQL/MariaDB jako DBMS jest oferowany w większości ofert firm hostingowych.

**Comment by nowuscode** [comment]
To, że jest polecane i oferowane to nie znaczy o tym, że jest lepsze. Chociaż w tym przypadku to się zgadza.

**Comment by Querko7** [comment]
A dlaczego FG nie korzysta z MySQL (czystego) tylko jakieś HikariCP

**Comment by Kamilkime** [comment]
HikariCP to biblioteka usprawniająca używanie róznych baz danych (w tym MySQL)
