### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by MetaX96** [FunnyGuilds/FunnyGuilds#871]
Po uruchomieniu serwera w bazie tworzy tylko 1 tabelę o nazwie null oraz przy wyłączaniu serwera wywala:
https://pastebin.com/RxLXQ9kF

**Comment by MetaX96** [comment]
Dzieję się tak nawet na default config po usunięciu całego katalogu FG.

**Comment by kacperduras** [comment]
```
edit.
Przy okazji nie działa też Top gildii (nie pobiera ich). Mimo, że są założone gildie to dalej na wszystich pozycjach w topce jest "brak".
```

Ponieważ musisz wyraźnie przeczytać konfiguracje.

**Comment by MetaX96** [comment]
Można jaśniej? Wytłumacz co mam zmienić jeśli na domyślnym configu to nie działa?

**Comment by nowuscode** [comment]
Chodzi tu o to, że jest linijka w której pisze ile musi być osób w gildii, aby ranking brał gildie pod uwagę.

**Comment by Kamilkime** [comment]
@MetaX96 to pokaż jeszcze ten pełny log z serwera

**Comment by v3ri0N** [comment]
Podbijam
Mam to samo ;D

**Comment by Kamilkime** [comment]
To też pokaż config i log z serwera

**Comment by v3ri0N** [comment]
Czego dokładnie config bo on troche duży jest :D

**Comment by insertt** [comment]
Całą konfigurację funnyguilds

**Comment by v3ri0N** [comment]
https://pastebin.com/UJzR7aiB
Tutaj config i konsolka

**Comment by Kamilkime** [comment]
Podeślij cały log z serwera. I czy to jest cały config? Bo brakuje mi tu linijek `usersTableName`, `guildsTableName` i `regionsTableName`

**Comment by MetaX96** [comment]
Właśnie ich nie ma, nie generują się. Zamiast wypytywać mnie o log, z których i tak nic nie zobaczysz i nic nie dadzą bo tak się dzieje na domyślnych ustawieniach to moglibyście coś w tym kierunku zrobić.

**Comment by Kamilkime** [comment]
Skoro u mnie się to tworzy, a u ciebie nie - pokaż log, to może wymyślę co jest źle

**Comment by v3ri0N** [comment]
tak cały config, cały log z serwera? tzn?

**Comment by Kamilkime** [comment]
Cały log, cały config - tego potrzebuję od ciebie i od @MetaX96

**Comment by kacperduras** [comment]
Wszystko jest w README.

**Comment by v3ri0N** [comment]
Wysłałem do @Kamilkime

**Comment by kacperduras** [comment]
Dobra, siedliśmy nad reprodukcją tego błędu i nie ukrywam - nie udało nam się go powtórzyć. Prawdopodobny scenariusz wygląda tak, że musicie zgłosić się do supportu hostingu, w którym trzymacie bazę danych, niestety lokalnie u mnie i @Kamilkime tworzą się pełne tabele. W razie gdyby support chciał się skontaktować z nami, niech piszą na contact@kacperduras.pl - w razie czego odpiszę jak najszybciej się da ;)

Póki co zamykam, bo IMHO błąd nie leży po stronie pluginu, tylko providera.

**Comment by kacperduras** [comment]
![unknown-6](https://user-images.githubusercontent.com/20678785/39404644-4eafaa44-4b97-11e8-84e0-6a31efa43799.png)

Otwieram ponownie, dzisiaj jeszcze przetestuje plugin, podłączając pod bazy danych u zewnętrznych dostawców, w tym TitanAXE. @v3ri0N fajnie by było gdybyś podał numer ticketa, napiszę do supportu i pasuje powołać mi się na Twoje zgłoszenie ;)

**Comment by v3ri0N** [comment]
Numer ticketa?  Trochę więcej szczegółów bo nie wiem o co chodzi

**Comment by kacperduras** [comment]
@v3ri0N numer zgłoszenia, bo pewnie napisałeś do supportu przez ich system.

**Comment by v3ri0N** [comment]
dobra czyli tak jak myślałem zaraz wam to podeślę

**Comment by v3ri0N** [comment]
Zgłoszenie #14352, to chyba to xd

**Comment by kacperduras** [comment]
Dzięki! Napiszę potem do nich, chce sobie wszystkie powyższe ustalenia zweryfikować, jakoś zaufania do ich supportu zbytnio nie mam D:

**Comment by v3ri0N** [comment]
Proszę bardzo! Jak mogę jeszcze jakoś pomóc to piszcie :D

**Comment by MetaX96** [comment]
Nie wiem nad czym siedzicie kiepy dalej. Błąd polega na tym, że jak nie usunie configu ze starszych wersji i wgrasz nowa wersje FG samego .jar to do cfg nie doda tych 3 linijek, gdzie są nazwy Tabel. Bach i rozwiązane.

**Comment by kacperduras** [comment]
```
Nie wiem nad czym siedzicie kiepy dalej. 
```

Nie wiem czy to jest odpowiedni zwrot do nas, ale ok. I tak - siedzimy, i właśnie miałem odpisywać.

```
Błąd polega na tym, że jak nie usunie configu ze starszych wersji i wgrasz nowa wersje FG samego .jar to do cfg nie doda tych 3 linijek, gdzie są nazwy Tabel. Bach i rozwiązane.
```

No to Twoja wina, bo wprowadziłeś nas w błąd. W treści issue:
```
Po uruchomieniu serwera w bazie tworzy tylko 1 tabelę o nazwie null oraz przy wyłączaniu serwera wywala
```

nigdzie nie napisałeś, że robisz upgrade ze starszej wersji FG. 

```
Przy okazji zobacz dlaczego czasem gracze nie widzą serca gildii.
```

Propozycja na nowe issue, zaraz odpowiednie założe.

Zamykam.
