### ISSUE TITLE
Pasek smoka nie pokazuje się przy mniejszym renderze

### ISSUE THREAD

**Issue by 6594k** [FunnyGuilds/FunnyGuilds#872]
Witam, zauważyłem , że jeżeli mam na serwerze render-distance: 4 to trzeba zejść poniżej 35 kratki aby ujrzeć ten pasek. Moja propozycja jest taka aby zastapic tego smoka niewidzialnym witherem 15 kratek przed graczem powinno być ok.

**Comment by happiii** [comment]
Template się usuwa. 🤦‍♂️

**Comment by kacperduras** [comment]
@happiii propozycja była napisana w template, trzeba było się wczytać - poprawiłem, ostatni raz.

**Comment by insertt** [comment]
Naprawiono w 1629fee.
