### ISSUE TITLE
Niewidzialne serca gildii

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#876]
Błąd wyciągnięty z #871 

@MetaX96 proszę o więcej szczegółów - wersja pluginu, serwera, logi itd.

**Comment by MetaX96** [comment]
Wersja serwera 1.12.2
Wersja pluginu najnowsza
W logach brak jakichkolwiek błedów.

Gracze narzekają, że nie widzą serca gildii. Po przeteleportowaniu zauważyłem, że też go nie ma i po chwili jak odszedłem dalej i wróciłem do miejsca gdzie powinno być serce, to się ono pojawiło.
