### ISSUE TITLE
Pomysły na komendy (limit, efekty i inne)

### ISSUE THREAD

**Issue by dzokuxd** [FunnyGuilds/FunnyGuilds#878]
Dodanie komendy która służy do powiększania limitu graczy w gildii /g limit /jak na mchc
Znów komenda: która losuje efekty gildii /g efekt
Może pora zmiany że jak ktoś powiększy teren gildii lub podbije gildie wyświetli się to na głównym chacie a nie tylko graczowi/graczowi gildii
Opcja?
Jeśli w gildii jest więcej niż X graczy na /g info lub /info zależy wyświetlają się kordy danej gildii
Gdy gildia wygasa pisze każdemu graczowi że gildia za niedługo wygaśnie

**Comment by kacperduras** [comment]
#767

**Comment by dzokuxd** [comment]
xd? Gdzie ty widzisz duplikat?

**Comment by kacperduras** [comment]
@dzokuxd podpinam całość pod jedno issue odwołując się do niego, dzięki temu nie musimy tworzyć setki nowych propozycji.
