### ISSUE TITLE
GUI z itemami - dodawanie lore do slotów ITEM i VIPITEM niezależnie od wybranego GUI

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#880]
Kolejny problem :/ Jeśli ustawimy to samo GUI z przedmiotami dla VIPa i gracza, to lore, z ile danego przedmiotu posiada nie jest wyświetlana dla przedmiotów dla vipa {VIPITEM-x}. 
Screeny: https://imgur.com/a/REaH2JV

**Comment by Kamilkime** [comment]
Pokaż config do tego

**Comment by marcinkowalczyk2** [comment]
Deafultowy, tylko dodałem {VIPITEM-x} to tego gui. I zaznaczyłem common-gui na true.

**Comment by Kamilkime** [comment]
A, no to FG działa tak, że to lore dodaje do jednego zestawu itemów, w zależności od tego jakie GUI jest otwarte - zwykłe, czy VIP. Dlatego dodaje ci tylko do zwykłych itemów

**Comment by marcinkowalczyk2** [comment]
Hmm.. dziwne trochę ale logiczne. Ale warto było by dodać to, bo co jeśli ktoś używa tak jak ja jednego GUI, a jest vipem i jemu stan przedmiotów sie nie pokazuje ;)

**Comment by Kamilkime** [comment]
Czyli zmienimy to na propozycję =)

**Comment by marcinkowalczyk2** [comment]
Jeszcze jedno pytanko, dlaczego (po co) komendy mimo tego, że je wyłączy się w configu są rejestrowane?

**Comment by Kamilkime** [comment]
Bo wyłączenie jest sprawdzane w innym miejscu - po prostu żeby można było wyświetlić informację, że komenda jest wyłączona, a nie po prostu by jej nie było
