### ISSUE TITLE
ASYSTY NIE WYŚWIETLAJĄ WIADOMOŚCI!

### ISSUE THREAD

**Issue by GLNUWA** [FunnyGuilds/FunnyGuilds#881]
Wersja: 4.3.0
Asysty dodają ranking lecz nie wyświetlają wiadomości na chacie dlaczego ?!

**Comment by kacperduras** [comment]
Rzeczywiście, zmienna od wiadomości przy asystach nie jest kompletnie używana w kodzie, jak znajdę chwile to naprawie ;)

**Comment by Kamilkime** [comment]
Też właśnie miałem w tym grzebać, więc zostaw na razie

**Comment by GLNUWA** [comment]
Dobra, a na kiedy będzie to naprawione?

**Comment by Kamilkime** [comment]
I czemu issue pojawia się dopiero, jak sam to znalazłem przypadkiem po 2.5 mies. niebytu? ;/

**Comment by GLNUWA** [comment]
Bo ludzie nie myślą ja dziś pobrałem plugin i już to odkryłem :)

**Comment by Kamilkime** [comment]
I naprawię to dzisiaj i przy okazji dodam jedną rzecz

**Comment by Kamilkime** [comment]
Poprawioną wersję znajdziesz tu: [FunnyGuilds Nightly](https://ci.kacperduras.pl/job/FunnyGuilds/)
