### ISSUE TITLE
SideBar do FUNNYGUILDS!

### ISSUE THREAD

**Issue by GLNUWA** [FunnyGuilds/FunnyGuilds#882]
Proponuje dodać sidebar do funnyguilds co wy na to ?

**Comment by vellde** [comment]
Po co?

**Comment by GLNUWA** [comment]
Niektórym serwerom może się przydać np. ja potrzebuje ;)

**Comment by Kamilkime** [comment]
Użyj pluginu [TitleManager](https://www.spigotmc.org/resources/titlemanager.1049/) i [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/), które jest wspierane przez FG
