### ISSUE TITLE
Kompatybilność z OpenSectors

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#884]
Chyba nie trzeba tłumaczyć.
https://github.com/SocketByte/OpenSectors

**Comment by Kamilkime** [comment]
No... Właśnie może byś wytłumaczył? Co dokładnie masz na myśli?

**Comment by insertt** [comment]
Jesteśmy otwarci na pull requesty ;)

**Comment by kacperduras** [comment]
```
Chyba nie trzeba tłumaczyć.
```

Jesteś pewny? :)

**Comment by Kamilkime** [comment]
@SocketByte i tak robi OpenSectors2, więc nie wiem czy byłby nawet sens za ewentualne zabieranie się za coś związanego ze starą wersją

**Comment by marcinkowalczyk2** [comment]
OpenSectors jest to plugin, który rozkłada nam obciążenie na daną ilość serwerów. Sektory służą temu, aby wszystko wyglądało jak na jednym serwerze.

**Comment by insertt** [comment]
Tu bardziej chodzi o wytłumaczenie na czym miałoby polegać wsparcie owego pluginu.

**Comment by marcinkowalczyk2** [comment]
Aby, dane między serwerami (sektorami) były synchronizowane

**Comment by SocketByte** [comment]
Tak jak mówi @Kamilkime, nie ma sensu za zabieranie się za starą wersję. Poza tym uważam że moje API jest na tyle rozbudowane żeby móc ew. wsparcie napisać sobie samemu. Napisanie wersji która by działała BEZ sektorów, a zarazem Z sektorami byłoby raczej skrajnie trudne, a pisanie osobnego projektu ma średnio sens i wątpie że chłopakom z FG się chce :)

**Comment by kacperduras** [comment]
Wiąże to issue z #849

**Comment by Cyramek** [comment]
Problem z OpenSectors2 może być taki, że jest pisany w kotlinie, sam Socket pisał, że może być kiepsko z kompatybilnością Java -> Kotlin.

**Comment by SocketByte** [comment]
Nie o to mi chodziło mówiąc "kompatybilność" ._.
Po prostu API OpenSectors2 używane w javie będzie dużo brzydsze i "na około" niż jakby się pisało w Kotlinie :)

**Comment by dzikoysk** [comment]
https://github.com/SocketByte/OpenSectors - archived, eot
