### ISSUE TITLE
 when the new version?

### ISSUE THREAD

**Issue by dzokuxd** [FunnyGuilds/FunnyGuilds#886]
Kiedy nowa ver?
po prostu ciekawość co będzie nowego/poprawionego xd

**Comment by vellde** [comment]
Może zamiast pytać, dałbyś twórcą pomysł co dodać/zmienić?

**Comment by dzokuxd** [comment]
już dawałem i to nie raz xd

**Comment by Kamilkime** [comment]
Przecież FG z najnowszymi zmianami możesz pobrać w dowolnym momencie: [FunnyGuilds Nightly](https://ci.kacperduras.pl/job/FunnyGuilds/)

**Comment by dzokuxd** [comment]
a cóż jest tam dodane od ostatniej ver?

**Comment by Kamilkime** [comment]
Zmiany można obserwować bez problemu po nazwach kolejnych commitów: [LINK](https://github.com/FunnyGuilds/FunnyGuilds/commits/master)
Na serwerze [FunnyGuilds Nightly](https://ci.kacperduras.pl/job/FunnyGuilds/) wersje pluginu budowane są automatycznie co commit

**Comment by dzokuxd** [comment]
aaa dziena

**Comment by dzokuxd** [comment]
chodziło mi tez o jakieś zmiany typu nowe komendy i wgl

**Comment by Kamilkime** [comment]
No, to widzisz przecież jakie issue czekają na wprowadzenie. Poza tym - możesz zaproponować swoje, w taki sam sposób. Jeśli ktoś z teamu FG znajduje błąd lub ma jakiś pomysł - też zwykle pojawia się issue, żeby było wiadomo co jest do wprowadzenia

**Comment by dzokuxd** [comment]
swoje propozycje już dałem :)
https://github.com/FunnyGuilds/FunnyGuilds/issues/878
