### ISSUE TITLE
Funnyguilds - dodanie do wlasnego projektu i błąd przy buildzie

### ISSUE THREAD

**Issue by yooniks** [FunnyGuilds/FunnyGuilds#888]
Witam witam, dodaje sobie funnyguilds do mojego projektu:
```
<dependency>
            <groupId>net.dzikoysk</groupId>
            <artifactId>funnyguilds</artifactId>
            <version>4.3.0</version>
          </dependency>
<repository>
        <id>panda-repo</id>
        <name>Panda Repository</name>
        <url>https://repo.panda-lang.org/</url>
      </repository>
 ```

- builduje projekt i taki blad mi wyskakuje:

> Error:java: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor not found

* mam to samo gdy nie uzywam mavena tylko dodaje recznie funnyguilds.jar w project structure -> libraries
* uzywam intelki
(potrzebuje usera z funnyguilds, np. do pobrania jego rankingu)

Blad jest chyba od adnotacji, tylko nie wiem co dokladniej, blad lezy raczej nie po mojej stronie, dlatego zakladam tutaj issue. Jak moge to poprawic? Mecze sie z tym juz jakos od 3 dni, a w pluginie dorabiam wsparcie dla funnyguilds ;/

**Comment by Xierip** [comment]
`<dependency>
            <groupId>net.dzikoysk</groupId>
            <artifactId>funnyguilds</artifactId>
            <version>4.3.0</version>
            <scope>provided</scope>
          </dependency>`
.....

**Comment by yooniks** [comment]
dalej to samo 👎

**Comment by yooniks** [comment]
Projekt builduje uzywajac build > artifacts,
przy buildowaniu mavenem mam taki blad:
```[ERROR] Failed to execute goal on project drop: Could not resolve dependencies for project xyz.yooniks:drop:jar:0.1-SNAPSHOT: Failure to find net.dzikoysk:funnyguilds:jar:4.3.0 in https://repo.panda-lang.org/ was cached in the local repository, resolution will not be reattempted until the update interval of panda-repo has elapsed or updates are forced -> [Help 1]
```

**Comment by yooniks** [comment]
do buildowania uzywam build > artifacts, a gdy builduje za pomoca mavena to mam takie cos:
```
[ERROR] Failed to execute goal on project drop: Could not resolve dependencies for project xyz.yooniks:drop:jar:0.1-SNAPSHOT: Failure to find net.dzikoysk:funnyguilds:jar:4.3.0 in https://repo.panda-lang.org/ was cached in the local repository, resolution will not be reattempted until the update interval of panda-repopository has elapsed or updates are forced -> [Help 1]
```

**Comment by dzikoysk** [comment]
Spróbuj usunąć katalog `{home}/.m2/net/dzikoysk/`
