### ISSUE TITLE
Dodanie uprawnień gildyjnych.

### ISSUE THREAD

**Issue by mati12844** [FunnyGuilds/FunnyGuilds#889]
Witam czy jest możliwość dodania do FG coś takiego jak uprawnienia gracza. Wszystko by było w GUI znajdowało by się tam czy gracz może niszczyć,stawiać,otwierać np.skrzynie,piece lub zadawanie członka damage ( życia ). I do właczenia i wyłaczenia w configu.

**Comment by happiii** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/issues/651
