### ISSUE TITLE
Nie dziala ranking gildii

### ISSUE THREAD

**Issue by thirdanoin** [FunnyGuilds/FunnyGuilds#892]
Po zainstalowaniu pluginu gracze normalnie dostają punkty i na tabie zapisują się ich wyniki  jednak po założeniu gildi nie widać by gracz ją posiadał nie pokazuje się ona ani na tabie ani w /top

Wersja 1.8.8
java 8
wersja pluginu 4.3.0

**Comment by Kamilkime** [comment]
Zobacz proszę w config.yml sekcję **guild-min-members** i na przyszłość czytaj config
