### ISSUE TITLE
Problem z tablistą.

### ISSUE THREAD

**Issue by nowusmajster** [FunnyGuilds/FunnyGuilds#893]
Witam, 
kiedyś pisałem już o tym problemie, lecz problem nie jest rozwiązany na wersji 1.8.8. 
moj cfg:
```
# Wyglad naglowka w liscie graczy.
player-list-header: '""
# Wyglad stopki w liscie graczy.
player-list-footer: "&7Polajkuj nas na fb! &3fb.com/mctryhard".
```
W efekcie nie powinien być wyświetlany header, a jest wyświetlana pusta przestrzeń.
Pozdrawiam.

**Comment by insertt** [comment]
Mógłbyś przedstawić jak to wygląda w grze?

**Comment by nowusmajster** [comment]
Właśnie wyszedłem z domu, za jakieś pół godziny wyśle ;]

**Comment by nowusmajster** [comment]
![2018-06-17_16 32 42](https://user-images.githubusercontent.com/37052785/41509337-807344e6-7252-11e8-92e5-e8d9c786a9e5.png)

**Comment by Cyramek** [comment]
ale potezny serwer easyhc

**Comment by nowusmajster** [comment]
Dokładnie ;]

**Comment by Kamilkime** [comment]
To chyba już rzecz z 1.8 -na 1.12.2 po prostu się nie pokazuje, bo kiedyś sprawdzałem

**Comment by Kamilkime** [comment]
W ogóle, to czemu masz:
`# Wyglad naglowka w liscie graczy.
player-list-header: '""
# Wyglad stopki w liscie graczy.
player-list-footer: "&7Polajkuj nas na fb! &3fb.com/mctryhard".`

A nie:
`# Wyglad naglowka w liscie graczy.
player-list-header: ""
# Wyglad stopki w liscie graczy.
player-list-footer: "&7Polajkuj nas na fb! &3fb.com/mctryhard."`

**Comment by nowusmajster** [comment]
Może missclick, jak wrócę do domu to sprawdzę, ale wątpię że zadziała.

**Comment by Kamilkime** [comment]
No, potestowałem i wstawienie pustego Stringu na 1.12.2 powoduje zniknięcie linii, a na 1.8 nie - nadal jest po prostu pusty header. Moim zdaniem to już wina 1.8
