### ISSUE TITLE
Bardziej "dynamiczne" gui z przedmiotami na gildie

### ISSUE THREAD

**Issue by ghost** [FunnyGuilds/FunnyGuilds#895]
Witam, z tej strony Tofik0 chcialbym aby plugin posiadal bardziej rozwiniete gui tzn. jakies dodatki typu zmiana gui po zebraniu odpowiedniej ilosci przedmiotów. Dziękuje i pozdrawiam :)

**Comment by Kamilkime** [comment]
Podobne do zasady widocznej w tym: https://www.mpcforum.pl/topic/1524621-plugin-fgitemsz-itemy-na-gildie-w-gui-ze-stanem-w-eq-i-enderchest/

**Comment by Tofik000** [comment]
Tak

niedz., 24 cze 2018, 14:12 użytkownik Kamilkime <notifications@github.com>
napisał:
