### ISSUE TITLE
Przywrócenie wsparcia BungeeTabListPlus

### ISSUE THREAD

**Issue by Querko7** [FunnyGuilds/FunnyGuilds#896]
Witam,
Proponuje przywrócić bezpośrednie wsparcie dla BungeeTabListPlus z uwagi na to, że nie każdy korzysta z PlaceholderAPI i tylko BungeeTabListPlus im wystarczy.

**Comment by kacperduras** [comment]
Jakieś inne sensowniejsze powody? Technicznie wpierane PlaceholderAPI jest lepsze aniżeli każdego pluginu z osobna.

**Comment by Gaway69** [comment]
jestem za przywróceniem wsparcia

**Comment by Kamilkime** [comment]
To może nie być taki zły pomysł, bo BungeeTabListPlus obsługuje tego PlaceholderAPI, ale znalezienie informacji o tym graniczy z cudem i jest mało oczywiste :/
