### ISSUE TITLE
Umożliwienie użycia jajka smoka jako serca gildii

### ISSUE THREAD

**Issue by nowusmajster** [FunnyGuilds/FunnyGuilds#897]
Witam, 
jeśli w configu fg ustawimy wartość `create-type: ` na `dragon_egg` w środku gildii jajo smoka tworzy się normalnie. Natomiast jeśli klikniemy na niego prawym - teleportuje się w inne miejsce. Pozdrawiam.

**Comment by Kamilkime** [comment]
No... tak działa dragon egg 🤔

**Comment by kacperduras** [comment]
To nie feature, to bug @Kamilkime

**Comment by vellde** [comment]
@Kamilkime to bug javy

**Comment by Kamilkime** [comment]
Feature, bo nigdy nikt nie mówił, że takie coś jest zaimplementowane - miało być tylko ustawianie serca gildii, a żeby się nie dało przemieszczać to już inna sprawa
