### ISSUE TITLE
Addons Funnyguilds

### ISSUE THREAD

**Issue by Dragoniit** [FunnyGuilds/FunnyGuilds#898]
Witam szukam osoby która napisała by mi addons do Funnyguilds. Ten addons polegałby na tym że osoby z poza gildii nie mogą otwierać drzwi oraz furtek na terenie wrogiej gildii

**Comment by hamsterofficial** [comment]
Dlaczego szukasz do tego osoby na githubie, dodatkowo w ISSUE? Dlaczego po prostu nie poczekasz na zaimplementowanie tego w funnyguilds.

**Comment by Kamilkime** [comment]
Issues nie są miejscem na poszukiwania programisty, tylko miejscem na zgłaszanie propozycji/błędów dotyczących FG. A podobna propozycja była już w #734

**Comment by Dragoniit** [comment]
1. A gdzie mogę poszukać do tego osoby?
2. Potrzebuje tego jak najszybciej

**Comment by Kamilkime** [comment]
@Dragoniit możesz szukać na forach, na discordzie FG (https://discordapp.com/invite/CYvyq3u)... pełno masz możliwości. Albo może zostanie to niedługo dodane, skoro jednak jest dość potrzebne
