### ISSUE TITLE
Nie aktualizuję mi się baza danych

### ISSUE THREAD

**Issue by bartek1126** [FunnyGuilds/FunnyGuilds#900]
FG stworzyło mi tabele w bazie danych ,a nie aktualizują się. w bazie lokalnej flat wszystko działa ładnie.

Serwer jest na localhost jak i mySQL (XAMPP)

**Comment by Kamilkime** [comment]
Ale... Jaki ty masz problem, bo nie rozumiem?

**Comment by bartek1126** [comment]
rekordy się nie tworzą w tabelach

**Comment by bartek1126** [comment]
http://prntscr.com/k65v6j

http://prntscr.com/k65vul

**Comment by Kamilkime** [comment]
No, dobra, ale rozumiem, że błędów nie ma - pamiętasz też o tym, że FG zapisuje dane raz na jakiś czas, domyślnie chyba co 5 minut

**Comment by bartek1126** [comment]
tylko że 5 minut juz dawno mineło a danych nadal nie ma .

**Comment by Kamilkime** [comment]
To podeślij logi z serwera

**Comment by bartek1126** [comment]
http://prntscr.com/k65z5c

**Comment by Kamilkime** [comment]
Log, cały, plik latest.log

**Comment by bartek1126** [comment]
[latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/2193824/latest.log)

**Comment by Kamilkime** [comment]
Ogółem - wejdź może na serwer, załóż gildię jakąś, wejdź może jeszcze jednym kontem jeśli możesz, poczekaj z 10 minut, poużywaj trochę komend z FG i podeślij log z tego wszystkiego

**Comment by Kamilkime** [comment]
Aha...
