### ISSUE TITLE
[Blad] Czlonkowie gildii nie moga budowac na swoim terenie!

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#901]
Witam, tak jak tytul zgloszenia bledu, czlonkowie gildii nie moga wstawic(budowac) blokow na swoim terenie gildii - cofa im :D  
~najnowsza wersja gildii

**Comment by sokrates1231** [comment]
Najnowsza wersja gildii ;)

**Comment by kamcio96** [comment]
Nie wiem, może coś ze mną jest nie tak, ale jak tworzy się nowy issue to jest dokładna instrukcja tego co trzeba podać: http://i.kamcio96.pl/NNbkJEHN6jpW.png Do tego wrzuć cały config na pastebina i podlinkuj tutaj. 

Testowałeś bez innych pluginów? Cieżko uwierzyć że to błąd tylko i wyłącznie FG, tego pluginu używa sporo serwerów.

**Comment by sokrates1231** [comment]
config: https://pastebin.com/sdJp8bKY
mam teraz dokladnie 55 builda jesli chodzi o FG, a wczesniej mialem innego i bylo wszystko okey, po aktualizacji pojawila sie taka sytuacja

**Comment by kamcio96** [comment]
wersja silnika, lista pluginów, błędy w logach? sprawdzaj buildy po kolei w dół i powiedz dokładnie pomiędzy którymi błąd przestaje występować

**Comment by sokrates1231** [comment]
w tym wszystko smigalo: 4.3.0 Tribute-20d1d46

**Comment by Kamilkime** [comment]
A jak zostawisz samo FG na serwerze?

**Comment by sokrates1231** [comment]
na serwerze testowym to samo. Moge niszczyc ale budowac/wstawic bloku juz nie moge.. Tylko FunnyGuilds jest. Logi czyste

**Comment by Kamilkime** [comment]
I czy nie przegiąłeś trochę z poziomami powiększenia regionu? - przecież przy tak dużym powiększeniu możesz regiony na siebie nałożyć...

**Comment by sokrates1231** [comment]
nie nic nie zrobilem ;-; czytasz wgl? Na testowym tak samo ;/

**Comment by Kamilkime** [comment]
Czytam, ale mówię ci ogólnie co sądzę o tylu poziomach powiększania gildii. Co do błędu - znalazłem go już i niedługo poprawię.

**Comment by sokrates1231** [comment]
ok! :D
