### ISSUE TITLE
Coś się wywaliło, naprawi się razem z #901 i #806

### ISSUE THREAD

**Issue by Kamilkime** [FunnyGuilds/FunnyGuilds#902]
![image](https://user-images.githubusercontent.com/10383567/42734805-2a0c7164-884a-11e8-87ff-1d6641adf8f1.png)

Bo @bmstefanski się nie chciało ;/

**Comment by bmstefanski** [comment]
Kroki do reprodukcji:
- wchodzenie i wychodzenie z serwera kilka razy  :)

**Comment by Kamilkime** [comment]
Pewnie więcej mi kod i tak powie, to jest FG
