### ISSUE TITLE
Wywala errory w funnygulids [diorite configs]

### ISSUE THREAD

**Issue by mhaas11** [FunnyGuilds/FunnyGuilds#903]
W skrócie:
Działało wszystko pięknie, śpiewało, grało, ale przy odpaleniu serwera bez ingerencji w config i bez wgrywania żadnych pluginów zaczął wyrzucać błędy

Link do błedu: https://pastebin.com/rKmauvsP
Silnik: paperspigot 1.8.8 (podpiety pod bungeecorda)

**Comment by Kamilkime** [comment]
Możesz podesłać swój config?

**Comment by mhaas11** [comment]
Bez kitu, nie wiem ale obcieło końcówke configu

https://pastebin.com/CmHGZvUz

**Comment by Kamilkime** [comment]
Ale co, FG obcięło?

**Comment by hamsterofficial** [comment]
Raczej issue do zamknięcia :D @kacperduras lub @Kamilkime
