### ISSUE TITLE
Plugin nie tworzy gildii nawet gdy gracz posiada itemy.

### ISSUE THREAD

**Issue by WolfGamesPL** [FunnyGuilds/FunnyGuilds#904]
Witam, przyszedłem z pewnym problemem.
Nawet gdy gracz posiada itemy wymagane do założenia gildii to plugin nadal woła od niego pierwszego
w kolejce wymaganego przedmiotu, tak jak by go nie miał (ale tak naprawde ma).

**Comment by Kamilkime** [comment]
Pokaż config pluginu

**Comment by WolfGamesPL** [comment]
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
#                                 #
#           FunnyGuilds           #
#          4.2.0 Tribute          #
#                                 #
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
# Wyswietlana nazwa pluginu
plugin-name: FunnyGuilds
# Czy informacje o aktualizacji maja byc widoczne podczas wejscia na serwer
update-info: true
# Mozliwosc zakladania gildii (mozna zmienic takze za pomoca komendy /ga enabled)
guilds-enabled: true
# Czy tworzenie regionow gildii (i inne zwiazane z nimi rzeczy) maja byc wlaczone
# UWAGA - dobrze przemysl decyzje o wylaczeniu regionow!
# Gildie nie beda mialy w sobie zadnych informacji o regionach, a jesli regiony sa wlaczone - te informacje musza byc obecne
# Jesli regiony mialyby byc znowu wlaczone - bedzie trzeba wykasowac WSZYSTKIE dane pluginu
# Wylaczenie tej opcji nie powinno spowodowac zadnych bledow, jesli juz sa utworzone regiony gildii
regions-enabled: true
# Maksymalna dlugosc nazwy gildii
name-length: 22
# Minimalna dlugosc nazwy gildii
name-min-length: 4
# Maksymalna dlugosc tagu gildii
tag-length: 4
# Minimalna dlugosc tagu gildii
tag-min-length: 2
# Zasada sprawdzania nazwy gildii przy jej tworzeniu
# Dostepne zasady:
# LOWERCASE - umozliwia uzycie tylko malych liter
# UPPERCASE - umozliwia uzycie tylko duzych liter
# DIGITS - umozliwia uzycie tylko cyfr
# LOWERCASE_DIGITS - umozliwia uzycie malych liter i cyfr
# UPPERCASE_DIGITS - umozliwia uzycie duzych liter i cyfr
# LETTERS - umozliwia uzycie malych i duzych liter
# LETTERS_DIGITS - umozliwia uzycie malych i duzych liter oraz cyrf
# LETTERS_DIGITS_UNDERSCORE - umozliwia uzycie malych i duzych liter, cyrf oraz podkreslnika
name-regex: LETTERS
# Zasada sprawdzania tagu gildii przy jej tworzeniu
# Mozliwe zasady sa takie same jak w przypadku name-regex
tag-regex: LETTERS
# Minimalna liczba graczy w gildii, aby zaliczala sie ona do rankingu
guild-min-members: 3
# Przedmioty wymagane do zalozenia gildii
# Tylko wartosci ujete w <> sa wymagane, reszta (ujeta w []) jest opcjonalna
# Wzor: <ilosc> <przedmiot>:[metadata] [name:lore:enchant:eggtype:skullowner:armorcolor]
# Zamiast spacji wstawiaj podkreslnik: _
# Aby zrobic nowa linie lore wstaw hash: #
# Aby w lore uzyc znaku # wstaw {HASH}
# eggtype to typ jajka do spawnu moba, uzywane tylko gdy typem przedmiotu jest MONSTER_EGG
# skullowner to nick gracza, ktorego glowa jest tworzona, uzywane tylko gdy typem przedmiotu jest SKULL_ITEM
# armorcolor to kolor, w ktorym bedzie przedmiot, uzywane tylko gdy przedmiot jest czescia zbroi skorzanej
# Kolor musi byc podany w postaci: "R_G_B"
# UWAGA: Nazwy przedmiotow musza pasowac do nazw podanych tutaj: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# UWAGA: Typ jajka musi pasowac do typow entity podanych tutaj: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
items: 
- 12 diamond
- 24 gold_ingot
- 40 iron_ingot
# Wymagana ilosc doswiadczenia do zalozenia gildii
required-experience: 0
# Wymagana ilosc pieniedzy do zalozenia gildii
# UWAGA: Aby ta opcja mogla dzialac, na serwerze musi byc plugin Vault oraz plugin dodajacy ekonomie
required-money: 0.0
# Przedmioty wymagane do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip.items
items-vip: 
- 8 diamond
- 18 gold_ingot
- 32 iron_ingot
# Wymagana ilosc doswiadczenia do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip.items
required-experience-vip: 0
# Wymagana ilosc pieniedzy do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip.items
# UWAGA: Aby ta opcja mogla dzialac, na serwerze musi byc plugin Vault oraz plugin dodajacy ekonomie
required-money-vip: 0.0
# Czy opcja wymaganego rankingu do zalozenia gildi ma byc wlaczona?
rank-create-enable: true
# Minimalny ranking wymagany do zalozenia gildi
rank-create: 1000
# Minimalny ranking wymagany do zalozenia gildi dla osoby z uprawnieniem funnyguilds.vip.rank
rank-create-vip: 800
# Czy GUI z przedmiotami na gildie ma byc wspolne dla wszystkich?
# Jesli wlaczone - wszyscy gracze beda widzieli GUI stworzone w sekcji gui-items, a GUI z sekcji gui-items-vip bedzie ignorowane
use-common-gui: false
# GUI z przedmiotami na gildie dla osob bez uprawnienia funnyguilds.vip.items
# Jesli wlaczone jest use-common-gui - ponizsze GUI jest uzywane takze dla osob z uprawnieniem funnyguilds.vip.items
# Kazda linijka listy oznacza jeden slot, liczba slotow powinna byc wielokrotnoscia liczby 9 i nie powinna byc wieksza niz 54
# Aby uzyc przedmiotu stworzonego w jednym slocie w innym mozna uzyc {GUI-nr}, np. {GUI-1} wstawi ten sam przedmiot, ktory jest w pierwszym slocie
# Aby wstawic przedmiot na gildie nalezy uzyc {ITEM-nr}, np. {ITEM-1} wstawi pierwszy przedmiot na gildie
# Aby wstawic przedmiot na gildie z listy vip nalezy uzyc {VIPITEM-nr}
gui-items: 
- "1 stained_glass_pane name:&r"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "1 paper name:&b&lItemy_na_gildie"
- "{GUI-1}"
- "{ITEM-1}"
- "{ITEM-2}"
- "{ITEM-3}"
- "{GUI-1}"
- "{GUI-11}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
# Nazwa GUI z przedmiotami na gildie dla osob bez uprawnienia funnyguilds.vip.items
# Nazwa moze zawierac max. 32 znaki (wliczajac w to kody kolorow)
gui-items-title: "&5&lPrzedmioty na gildie"
# GUI z przedmiotami na gildie dla osob z uprawnieniem funnyguilds.vip.items
# Zasada tworzenia GUI jest taka sama jak w przypadku sekcji gui-items
# Ponizsze GUI bedzie ignorowane jesli wlaczone jest use-common-gui
gui-items-vip: 
- "1 stained_glass_pane name:&r"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "1 paper name:&b&lItemy_na_gildie"
- "{GUI-1}"
- "{GUI-1}"
- "{VIPITEM-1}"
- "{GUI-3}"
- "{GUI-1}"
- "{GUI-11}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
# Nazwa GUI z przedmiotami na gildie dla osob z uprawnieniem funnyguilds.vip.items
# Nazwa moze zawierac max. 32 znaki (wliczajac w to kody kolorow)
gui-items-vip-title: "&5&lPrzedmioty na gildie (VIP)"
# Czy do przedmiotow na gildie, ktore sa w GUI, maja byc dodawane dodatkowe linie opisu?
# Linie te mozna ustawic ponizej
add-lore-lines: true
# Dodatkowe linie opisu, dodawane do kazdego przedmiotu, ktory jest jednoczesnie przedmiotem na gildie
# Dodawane linie nie zaleza od otwieranego GUI - sa wspolne dla zwyklego i VIP
# Mozliwe do uzycia zmienne:
# {PINV-AMOUNT} - ilosc danego przedmiotu, jaka gracz ma przy sobie
# {PINV-PERCENT} - procent wymaganej ilosci danego przedmiotu, jaki gracz ma przy sobie
# {EC-AMOUNT} - ilosc danego przedmiotu, jaka gracz ma w enderchescie
# {EC-PERCENT} - procent wymaganej ilosci danego przedmiotu, jaki gracz ma w enderchescie
# {ALL-AMOUNT} - ilosc danego przedmiotu, jaka gracz ma przy sobie i w enderchescie
# {ALL-PERCENT} - procent wymaganej ilosci danego przedmiotu, jaki gracz ma przy sobie i w enderchescie
gui-items-lore: 
- ""
- "&aPosiadzasz juz:"
- "&a{PINV-AMOUNT} przy sobie &7({PINV-PERCENT}%)"
- "&a{EC-AMOUNT} w enderchescie &7({EC-PERCENT}%)"
- "&a{ALL-AMOUNT} calkowicie &7({ALL-PERCENT}%)"
# Minimalna odleglosc od spawnu
create-distance: 100
# Minimalna odleglosc od granicy mapy, na ktorej znajduje sie gracz
# Wartosc -1 oznacza brak minimalnej odlegosci od granicy
create-guild-min-distance: -1.0
# Blok lub entity, ktore jest sercem gildii
# Zmiana entity wymaga pelnego restartu serwera
# Bloki musza byc podawane w formacie - material:metadata (tak jak przedmioty na gildie, tylko bez ilosci, nazwy czy opisu)
# Typ entity musi byc zgodny z ta lista (i zdrowym rozsadkiem) - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# UWAGA: Zmiana bloku, gdy sa juz zrobione jakies gildie, spowoduje niedzialanie ich regionow
create-type: ender_crystal
# Na jakim poziomie ma byc wyznaczone centrum gildii
# Wpisz 0 jesli ma byc ustalone przez pozycje gracza
create-center-y: 60
# Czy ma sie tworzyc kula z obsydianu dookola centrum gildii
create-center-sphere: true
# Czy przy tworzeniu gildii powinien byc wklejany schemat
# Wklejenie schematu wymaga pluginu WorldEdit
paste-schematic-on-creation: false
# Nazwa pliku z schematem poczatkowym gildii
# Wklejenie schematu wymaga pluginu WorldEdit
guild-schematic-file-name: funnyguilds.schematic
# Czy schemat przy tworzeniu gildii powinien byc wklejany razem z powietrzem?
# Przy duzych schematach ma to wplyw na wydajnosc
# Wklejenie schematu wymaga pluginu WorldEdit
paste-schematic-with-air: true
# Czy funkcja efektu 'zbugowanych' klockow ma byc wlaczona (dziala tylko na terenie wrogiej gildii)
bugged-blocks: false
# Czas po ktorym 'zbugowane' klocki maja zostac usuniete (warunek wymagany: bugged-blocks = true)
# Czas podawany w tickach (1 sekunda = 20 tickow)
bugged-blocks-timer: 20
# Maksymalna liczba czlonkow w gildii
max-members: 15
# Lista nazw swiatow, na ktorych mozliwosc utworzenia gildii powinna byc zablokowana
blocked-worlds: 
- some_world
# Mozliwosc ucieczki z terenu innej gildii
# Funkcja niedostepna jesli mozliwosc teleportacji do gildii jest wylaczona
escape-enable: true
# Czas, w sekundach, jaki musi uplynac od wlaczenia ucieczki do teleportacji
escape-delay: 120
# Mozliwosc teleportacji do gildii
base-enable: true
# Czas oczekiwania na teleportacje (w sekundach)
base-delay: 5
# Koszt teleportacji do gildii (jezeli brak, wystarczy zrobic: base-items: [])
base-items: 
- 1 iron_ingot
# Koszt dolaczenia do gildii (jezeli brak, wystarczy zrobic: join-items: [])
join-items: 
- 1 gold_ingot
# Mozliwosc powiekszania gildii
enlarge-enable: true
# O ile powieksza teren gildii 1 poziom
enlarge-size: 5
# Koszt powiekszania gildii
# - kazdy myslnik, to 1 poziom gildii
enlarge-items: 
- 5 diamond
- 13 diamond
- 16 diamond
- 20 diamond
- 25 diamond
- 30 diamond
- 35 diamond
- 40 diamond
- 45 diamond
- 50 diamond
# Wielkosc regionu gildii
region-size: 50
# Minimalna odleglosc miedzy terenami gildii
region-min-distance: 10
# Czas wyswietlania powiadomienia na pasku powiadomien (w sekundach)
region-notification-time: 15
# Co ile moze byc wywolywany pasek powiadomien przez jednego gracza (w sekundach)
region-notification-cooldown: 60
# Blokowane komendy dla graczy spoza gildii na jej terenie
region-commands: 
- sethome
# Czy mozna usunac gildie jezeli ktos spoza gildii jest na jej terenie
region-delete-if-near: false
# Czy wlaczyc ochrone przed TNT w gildiach w podanych godzinach
guild-tnt-protection-enabled: false
# O której godzinie ma sie zaczac ochrona przed TNT w gildii
# Godzina w formacie HH:mm
guild-tnt-protection-start-time: "22:00"
# Do której godziny ma dzialac ochrona przed TNT w gildii
# Godzina w formacie HH:mm
guild-tnt-protection-end-time: "06:00"
# Przez ile sekund nie mozna budowac na terenie gildii po wybuchu
region-explode: 120
# Jaki ma byc zasieg pobieranych przedmiotow po wybuchu (jezeli chcesz wylaczyc, wpisz 0)
explode-radius: 3
# Jakie materialy i z jaka szansa maja byc niszczone po wybuchu
# <material>: <szansa (w %)
explode-materials: 
  obsidian: 20.0
  water: 33.0
  lava: 33.0
# Ile zyc ma gildia
war-lives: 3
# Po jakim czasie od zalozenia mozna zaatakowac gildie
war-protection: 24h
# Ile czasu trzeba czekac do nastepnego ataku na gildie
war-wait: 24h
# Jaka waznosc ma gildia po jej zalozeniu
validity-start: 14d
# Ile czasu dodaje przedluzenie gildii
validity-time: 14d
# Ile dni przed koncem wygasania mozna przedluzyc gildie (wpisz 0, jezeli funkcja ma byc wylaczona)
validity-when: 14d
# Koszt przedluzenia gildii
validity-items: 
- 5 diamond
# Ranking od ktorego rozpoczyna gracz
rank-start: 1000
# Czy blokada nabijania rankingu na tych samych osobach powinna byc wlaczona
rank-farming-protect: true
# Czas (w sekundach) blokady nabijania rankingu po walce dwoch osob
rank-farming-cooldown: 7200
# Czy ma byc zablokowana zmiana rankingu, jesli obie osoby z walki maja taki sam adres IP
rank-ip-protect: false
# Czy system asyst ma byc wlaczony
rank-assist-enable: true
# Jaka czesc rankingu za zabicie idzie na konto zabojcy
# 1 to caly ranking, 0 to nic
# Reszta rankingu rozdzielana jest miedzy osoby asystujace w zaleznosci od zadanych obrazen
rank-assist-killer-share: 0.5
# System rankingowy uzywany przez plugin, do wyboru:
# ELO - system bazujacy na rankingu szachowym ELO, najlepiej zbalansowany ze wszystkich trzech
# PERCENT - system, ktory obu graczom zabiera procent rankingu osoby zabitej
# STATIC - system, ktory zawsze zabiera iles rankingu zabijajacemu i iles zabitemu
rank-system: ELO
# Sekcja uzywana TYLKO jesli wybranym rank-system jest ELO!
# Lista stalych obliczen rankingowych ELO, uzywanych przy zmianach rankingu - im mniejsza stala, tym mniejsze zmiany rankingu
# Stale okreslaja tez o ile maksymalnie moze zmienic sie ranking pochodzacy z danego przedzialu
# Lista powinna byc podana od najmniejszych do najwiekszych rankingow i zawierac tylko liczby naturalne, z zerem wlacznie
# Elementy listy powinny byc postaci: "minRank-maxRank stala", np.: "0-1999 32"
# * uzyta w zapisie elementu listy oznacza wszystkie wartosci od danego minRank w gore, np.: "2401-* 16"
elo-constants: 
- 0-1999 32
- 2000-2400 24
- 2401-* 16
# Sekcja uzywana TYLKO jesli wybranym rank-system jest ELO!
# Dzielnik obliczen rankingowych ELO - im mniejszy, tym wieksze zmiany rankingu
# Dzielnik powinien byc liczba dodatnia, niezerowa
elo-divider: 400.0
# Sekcja uzywana TYLKO jesli wybranym rank-system jest ELO!
# Wykladnik potegi obliczen rankingowych ELO - im mniejszy, tym wieksze zmiany rankingu
# Wykladnik powinien byc liczba dodatnia, niezerowa
elo-exponent: 10.0
# Sekcja uzywana TYLKO jesli wybranym rank-system jest PERCENT!
# Procent rankingu osoby zabitej o jaki zmienia sie rankingi po walce
percent-rank-change: 1.0
# Sekcja uzywana TYLKO jesli wybranym rank-system jest STATIC!
# Punkty dawane osobie, ktora wygrywa walke
static-attacker-change: 15
# Sekcja uzywana TYLKO jesli wybranym rank-system jest STATIC!
# Punkty zabierane osobie, ktora przegrywa walke
static-victim-change: 10
# Czy pokazywac informacje przy kliknieciu PPM na gracza
info-player-enabled: true
# Cooldown pomiedzy pokazywaniem informacji przez PPM (w sekundach)
info-player-cooldown: 0
# Czy trzeba kucac, zeby przy klikniecu PPM na gracza wyswietlilo informacje o nim
info-player-sneaking: true
# Czy czlonkowie gildii moga sobie zadawac obrazenia (domyslnie)
damage-guild: false
# Czy sojuszniczy moga sobie zadawac obrazenia
damage-ally: false
# Wyglad znaczika {POS} wstawionego w format chatu
# Znacznik ten pokazuje czy ktos jest liderem, zastepca czy zwyklym czlonkiem gildii
chat-position: "&b{POS} "
# Znacznik dla lidera gildii
chat-position-leader: "**"
# Znacznik dla zastepcy gildii
chat-position-deputy: "*"
# Znacznik dla czlonka gildii
chat-position-member: ''
# Wyglad znaczika {TAG} wstawionego w format chatu
chat-guild: "&b{TAG} "
# Wyglad znaczika {RANK} wstawionego w format chatu
chat-rank: "&b{RANK} "
# Wyglad znaczika {POINTS} wstawionego w format chatu
# Mozesz tu takze uzyc znacznika {POINTS-FORMAT}
chat-points: "&b{POINTS} "
# Wyglad znacznika {POINTS-FORMAT} i {G-POINTS-FORMAT} w zaleznosci od wartosci punktow
# {G-POINTS-FORMAT} (tak samo jak {G-POINTS}) jest uzywane jedynie na liscie graczy
# Lista powinna byc podana od najmniejszych do najwiekszych rankingow i zawierac tylko liczby naturalne, z zerem wlacznie
# Elementy listy powinny byc postaci: "minRank-maxRank wyglad", np.: "0-750 &4{POINTS}"
# * uzyta w zapisie elementu listy oznacza wszystkie wartosci od danego minRank w gore, np.: "1500-* &6&l{POINTS}"
points-format: 
- 0-749 &4{POINTS}
- 750-999 &c{POINTS}
- 1000-1499 &a{POINTS}
- 1500-* &6&l{POINTS}
# Znacznik z punktami dodawany do zmiennej {PTOP-x} i {ONLINE-PTOP-x}
# Uzywaj zmiennych {POINTS} i {POINTS-FORMAT}
# Jesli nie chcesz wyswietlac punktow, tylko sam nick - nie podawaj tu nic
ptop-points: " &7[{POINTS}&7]"
# Znacznik z punktami dodawany do zmiennej {GTOP-x}
# Uzywaj zmiennych {POINTS} i {POINTS-FORMAT}
# Jesli nie chcesz wyswietlac punktow, tylko sam tag - nie podawaj tu nic
gtop-points: " &7[&b{POINTS-FORMAT}&7]"
# Wyglad znacznika {PING-FORMAT} w zaleznosci od wartosci pingu
# Lista powinna byc podana od najmniejszych do najwiekszych wartosci i zawierac tylko liczby naturalne, z zerem wlacznie
# Elementy listy powinny byc postaci: "minPing-maxPing wyglad", np.: "0-75 &a{PING}"
# * uzyta w zapisie elementu listy oznacza wszystkie wartosci od danego minPing w gore, np.: "301-* &c{PING}"
ping-format: 
- 0-75 &a{PING}
- 76-150 &e{PING}
- 151-300 &c{PING}
- 301-* &c{PING}
# Symbol od ktorego zaczyna sie wiadomosc do gildii gildii
chat-priv: "!"
# Symbol od ktorego zaczyna sie wiadomosc do sojusznikow gildii
chat-ally: "!!"
# Symbol od ktorego zaczyna sie wiadomosc do wszystkich gildii
chat-global: "!!!"
# Wyglad wiadomosci wysylanej na czacie gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}, {POS}
chat-priv-design: "&8[&aChat gildii&8] &7{POS}{PLAYER}&8:&f {MESSAGE}"
# Wyglad wiadomosci wysylanej na czacie sojusznikow dla sojusznikow
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}, {POS}
chat-ally-design: "&8[&6Chat sojuszniczy&8] &8{TAG} &7{POS}{PLAYER}&8:&f {MESSAGE}"
# Wyglad wiadomosci wysylanej na czacie globalnym gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}, {POS}
chat-global-design: "&8[&cChat globalny gildii&8] &8{TAG} &7{POS}{PLAYER}&8:&f {MESSAGE}"
# Wyglad tagu osob w gildii
prefix-our: "&a{TAG}&f "
# Wyglad tagu gildii sojuszniczej
prefix-allies: "&6{TAG}&f "
# Wyglad tagu gildii neutralnej (widziany rowniez przez graczy bez gildii)
prefix-other: "&7{TAG}&f "
# Kolory dodawane przed nickiem gracza online przy zamianie zmiennej {PTOP-x}
# Jesli nie chcesz kolorowania zaleznego od statusu online - pozostaw te sekcje (i ptop-offline) pusta
ptop-online: "&a"
# Kolory dodawane przed nickiem gracza offline przy zamianie zmiennej {PTOP-x}
# Jesli nie chcesz kolorowania zaleznego od statusu online - pozostaw te sekcje (i ptop-online) pusta
ptop-offline: "&c"
# Czy wlaczyc dummy z punktami
# UWAGA - zalecane jest wylaczenie tej opcji w przypadku konfliktow z BungeeCord'em, wiecej szczegolow tutaj: https://github.com/FunnyGuilds/FunnyGuilds/issues/769
dummy-enable: true
# Wyglad nazwy wyswietlanej (suffix, za punktami)
dummy-suffix: pkt
# Wyglad listy graczy, przedzial slotow - od 1 do 80
# Schemat wygladu listy: https://github.com/FunnyGuilds/FunnyGuilds/blob/master/tab-scheme.png
# > Spis zmiennych gracza:
# {PLAYER} - nazwa gracza
# {PING} - ping gracza
# {PING-FORMAT} - ping gracza z formatowaniem
# {POINTS} - punkty gracza
# {POINTS-FORMAT} - punkty gracza z formatowaniem
# {POSITION} - pozycja gracza w rankingu
# {KILLS} - liczba zabojstw gracza
# {DEATHS} - liczba smierci gracza
# {KDR} - stosunek zabojstw do smierci gracza
# > Spis zmiennych gildyjnych:
# {G-NAME} - nazwa gildii do ktorej nalezy gracz
# {G-TAG} - tag gildii gracza
# {G-OWNER} - wlasciciel gildii
# {G-DEPUTIES} - zastepcy gildii
# {G-DEPUTY} - losowy z zastepcow gildii
# {G-LIVES} - liczba zyc gildii
# {G-ALLIES} - liczba sojusznikow gildii
# {G-POINTS} - punkty gildii
# {G-POINTS-FORMAT} - punkty gildii z formatowaniem
# {G-POSITION} - pozycja gildii gracza w rankingu
# {G-KILLS} - suma zabojstw czlonkow gildii
# {G-DEATHS} - suma smierci czlonkow gildii
# {G-KDR} - stosunek zabojstw do smierci czlonkow gildii
# {G-MEMBERS-ONLINE} - liczba czlonkow gildii online
# {G-MEMBERS-ALL} - liczba wszystkich czlonkow gildii
# {G-VALIDITY} - data wygasniecia gildii
# {G-REGION-SIZE} - rozmiar gildii
# > Spis pozostalych zmiennych:
# {ONLINE} - liczba graczy online
# {TPS} - TPS serwera (wspierane tylko od wersji 1.8.8+ spigot/paperspigot)
# {SECOND} - Sekunda
# {MINUTE} - Minuta
# {HOUR} - Godzina
# {PTOP-<pozycja>} - Gracz na podanym miejscu w rankingu (np. {PTOP-1}, {PTOP-60})
# {GTOP-<pozycja>} - Gildia na podanej pozycji w rankingu (np. {GTOP-1}, {PTOP-50})
player-list: 
  1: "&7Nick: &b{PLAYER}"
  2: "&7Ping: &b{PING}"
  3: "&7Punkty: &b{POINTS}"
  4: "&7Zabojstwa: &b{KILLS}"
  5: "&7Smierci: &b{DEATHS}"
  6: "&7KDR: &b{KDR}"
  7: "&7Gildia: &b{G-NAME}"
  9: "&7TAG: &b{G-TAG}"
  10: "&7Punkty gildii: &b{G-POINTS-FORMAT}"
  11: "&7Pozycja gildii: &b{G-POSITION}"
  12: "&7Liczba graczy online: &b{G-MEMBERS-ONLINE}"
  21: "&7Online: &b{ONLINE}"
  22: "&7TPS: &b{TPS}"
  41: "&bTop 3 Gildii"
  42: "&71. &b{GTOP-1}"
  43: "&72. &b{GTOP-2}"
  44: "&73. &b{GTOP-3}"
  61: "&bTop 3 Graczy"
  62: "&71. &b{PTOP-1}"
  63: "&72. &b{PTOP-2}"
  64: "&73. &b{PTOP-3}"
# Wyglad naglowka w liscie graczy.
player-list-header: "&7FunnyGuilds &b4.2.0 Tribute"
# Wyglad stopki w liscie graczy.
player-list-footer: "&7O, dziala! &8{HOUR}:{MINUTE}:{SECOND}"
# Liczba pingu pokazana przy kazdej komorce.
player-list-ping: 0
# Czy tablista ma byc wlaczona
player-list-enable: true
# Czy tag gildii podany przy tworzeniu gildii powinien zachowac forme taka, w jakiej zostal wpisany
# UWAGA: Gdy ta opcja jest wlaczona, opcja "guild-tag-uppercase" nie bedzie miala wplywu na tag gildii
guild-tag-keep-case: true
# Czy tagi gildii powinny byc pokazywane wielka litera
# Dziala dopiero po zrestartowaniu serwera
guild-tag-uppercase: false
# Czy wlaczyc tlumaczenie nazw przedmiotow przy zabojstwie
translated-materials-enable: true
# Tlumaczenia nazw przedmiotow przy zabojstwie
# Wypisywac w formacie nazwa_przedmiotu: "tlumaczona nazwa przedmiotu"
translated-materials-name: 
  diamond_sword: "&3diamentowy miecz"
  iron_sword: "&7zelazny miecz"
# Czy filtry nazw i tagow gildii powinny byc wlaczone
check-for-restricted-guild-names: false
# Niedozwolone nazwy przy zakladaniu gildii
restricted-guild-names: 
- Administracja
# Niedozwolone tagi przy zakladaniu gildii
restricted-guild-tags: 
- TEST
# Czy powiadomienia o wejsciu na teren gildii czlonka gildii powinny byc wyswietlane
notification-guild-member-display: false
# Gdzie maja pojawiac sie wiadomosci zwiazane z poruszaniem sie po terenach gildii
# Mozliwe miejsca wyswietlania: ACTIONBAR, BOSSBAR, CHAT, TITLE
region-move-notification-style: 
- ACTIONBAR
- BOSSBAR
# Jak dlugo title/subtitle powinien sie pojawiac
# Czas podawany w tickach (1 sekunda = 20 tickow)
# Opcja dziala tylko gdy aktywne jest powiadamianie w trybie TITLE
notification-title-fade-in: 10
# Jak dlugo title/subtitle powinien pozostac na ekranie gracza
# Czas podawany w tickach (1 sekunda = 20 tickow)
# Opcja dziala tylko gdy aktywne jest powiadamianie w trybie TITLE
notification-title-stay: 10
# Jak dlugo title/subtitle powinien znikac
# Czas podawany w tickach (1 sekunda = 20 tickow)
# Opcja dziala tylko gdy aktywne jest powiadamianie w trybie TITLE
notification-title-fade-out: 10
# Zbior przedmiotow potrzebnych do resetu rankingu
rank-reset-needed-items: 
- 1 diamond
# Czy przy szukaniu danych o graczu ma byc pomijana wielkosc znakow
player-lookup-ignorecase: false
# Nazwy komend
commands: 
  funnyguilds: 
    name: 'funnyguilds'
    aliases: 
    - fg
    enabled: true

  guild: 
    name: 'gildia'
    aliases: 
    - gildie
    - g
    enabled: true

  create: 
    name: 'zaloz'
    aliases: []
    enabled: true

  delete: 
    name: 'usun'
    aliases: []
    enabled: true

  confirm: 
    name: 'potwierdz'
    aliases: []
    enabled: true

  invite: 
    name: 'zapros'
    aliases: []
    enabled: true

  join: 
    name: 'dolacz'
    aliases: []
    enabled: true

  leave: 
    name: 'opusc'
    aliases: []
    enabled: true

  kick: 
    name: 'wyrzuc'
    aliases: []
    enabled: true

  base: 
    name: 'baza'
    aliases: []
    enabled: true

  enlarge: 
    name: 'powieksz'
    aliases: []
    enabled: true

  ally: 
    name: 'sojusz'
    aliases: []
    enabled: true

  items: 
    name: 'przedmioty'
    aliases: []
    enabled: true

  escape: 
    name: 'ucieczka'
    aliases: 
    - escape
    enabled: true

  rankReset: 
    name: 'rankreset'
    aliases: 
    - resetrank
    enabled: true

  break: 
    name: 'rozwiaz'
    aliases: []
    enabled: true

  info: 
    name: 'info'
    aliases: []
    enabled: true

  player: 
    name: 'gracz'
    aliases: []
    enabled: true

  top: 
    name: 'top'
    aliases: 
    - top10
    enabled: true

  validity: 
    name: 'przedluz'
    aliases: []
    enabled: true

  leader: 
    name: 'lider'
    aliases: 
    - zalozyciel
    enabled: true

  deputy: 
    name: 'zastepca'
    aliases: []
    enabled: true

  ranking: 
    name: 'ranking'
    aliases: []
    enabled: true

  setbase: 
    name: 'ustawbaze'
    aliases: 
    - ustawdom
    enabled: true

  pvp: 
    name: 'pvp'
    aliases: 
    - ustawpvp
    enabled: true

  # Komendy administratora
  admin: 
    main: ga
    add: ga dodaj
    delete: ga usun
    kick: ga wyrzuc
    teleport: ga tp
    points: ga points
    kills: ga kills
    deaths: ga deaths
    ban: ga ban
    lives: ga zycia
    move: ga przenies
    unban: ga unban
    validity: ga przedluz
    name: ga nazwa
    spy: ga spy
    enabled: ga enabled
    leader: ga lider
    deputy: ga zastepca


# Czy event PlayMoveEvent ma byc aktywny (odpowiada za wyswietlanie powiadomien o wejsciu na teren gildii)
event-move: true
# Co ile minut ma automatycznie zapisywac dane
data-interval: 1
# Typ zapisu danych
# Flat - Lokalne pliki
# MySQL - baza danych
data-type: 
  flat: true
  mysql: false

# Dane wymagane do polaczenia z baza
# UWAGA: connectionTimeout jest w milisekundach!
# Sekcje usersTableName, guildsTableName i regionsTableName to nazwy tabel z danymi FG w bazie danych
# Najlepiej zmieniac te nazwy tylko wtedy, gdy jest naprawde taka potrzeba (np. wystepuje konflikt z innym pluginem)
# Aby zmienic nazwy tabel, gdy masz juz w bazie jakies dane z FG:
# 1. Wylacz serwer
# 2. Zmien dane w configu FG
# 3. Zmien nazwy tabel w bazie uzywajac np. phpMyAdmin
mysql: 
  hostname: localhost
  port: 3306
  database: db
  user: root
  password: passwd
  poolSize: 16
  connectionTimeout: 30000
  usersTableName: users
  guildsTableName: guilds
  regionsTableName: regions


Edytowałem tylko potrzebne itemy (nawet przed tym, gdy config był domyślny nie chciało tworzyć)

**Comment by Kamilkime** [comment]
@WolfGamesPL https://pastebin.com/

**Comment by WolfGamesPL** [comment]
https://pastebin.com/vkgLJdFT sorry

**Comment by Kamilkime** [comment]
Czy w czasie tworzenia przedmioty w inventory masz nazwane, z jakimś opisem przedmiotu, itp.? Czy są to po prostu czyste itemy?

**Comment by WolfGamesPL** [comment]
Czyste przedmioty

**Comment by Kamilkime** [comment]
Podeślij też może log z konsoli

**Comment by WolfGamesPL** [comment]
Aha, po reloadzie zaczął działać XD

**Comment by Kamilkime** [comment]
Aha 🤔
