### ISSUE TITLE
Zbugowane SOJUSZE!

### ISSUE THREAD

**Issue by Retrumek** [FunnyGuilds/FunnyGuilds#908]
1. Sojusze tak jakby się usuwały lub PIERWSZA gildia zerwie sojusz z DRUGĄ, ale ta PIERWSZA dalej ma sojusz z DRUGĄ a ta DRUGA już nie, i potem Ci się klepać mogą a tamci tych nie.

2. To taki, że czasem graczom zostaje zielony nick na TAB czy /info - a tak naprawdę są offline 👍

**Comment by Kamilkime** [comment]
1. #749 
2. Się zobaczy
