### ISSUE TITLE
Tworzenie plików przy włączeniu serwera

### ISSUE THREAD

**Issue by hamsterofficial** [FunnyGuilds/FunnyGuilds#910]
Cześć! Jest problem, taki że jak pobieram najnowszą stabilną wersje i wrzucam ją na serwer, wywala błąd że nie może mi stworzyć configów.

error: https://hastebin.com/emaheyubut.md
Wersja 1.8.8 (spigot)

**Comment by kacperduras** [comment]
Binarka pobrana z CI?

**Comment by hamsterofficial** [comment]
Build #59 z wersji Nightly działa poprawnie :D
