### ISSUE TITLE
Trzeba coś dodać

### ISSUE THREAD

**Issue by PrzemoVi** [FunnyGuilds/FunnyGuilds#911]
Siemka.
W tabliście są taki paski sygnału, które źle wyglądają. Znacznie lepiej to wygląda, jak świeci się tylko jedna kreska. najlepiej do daj do configa możliwość wybierania, ile ma się świecić :)

Swoją drogą, to jak FG jest odpalone to nie działa żaden plugin na zmianę nicku nad głową gracza, dodanie drugiej lini itd. Jak ci się chce, to mógłbyś zrobić tak,a by inne pluginy działały, albo dodać jakieś proste API do zmiany nicku nad głową. Inne pluginy nie działają, nawet jak w configu wyłącze te punkty przy nicku.

Pozdro

**Comment by insertt** [comment]
Paski sygnału są konfigurowywalne: https://github.com/FunnyGuilds/FunnyGuilds/blob/1955ca56cc92bd98c4d39dd4d1d955491b65b1ce/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java#L880-L882
