### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#926]
- [ ] English
- [x] Polish

**Comment by kacperduras** [comment]
Mogę się podjąć po norwesku jeśli trzeba ✌️

**Comment by IceMeltt** [comment]
Ja mogę po polsku

**Comment by P3ridot** [comment]
Tylko jak z komentarzami? Bo albo by trzeba wymienic wszystkie na angielske albo przez p*laczki dawac podwojne komentarze...

**Comment by P3ridot** [comment]
Generalnie w najnowszym nightly dodaliśmy support dla tłumaczeń (język wybierany na podstawie języka clienta). Trzeba stworzyć:
- tłumaczenie na angielski (normalny plik yaml)
- dodać komentarze w configu, tabliscie i samym pliku z wiadomosciamj po angielsku
