### ISSUE TITLE
Bugowanie blokami - kopiowanie.

### ISSUE THREAD

**Issue by NNorbertPL** [FunnyGuilds/FunnyGuilds#929]
Hej, podpierdalając kod z funnyguilds znalazłem jeden błąd, gdy mamy włączone dodawanie postawionego bloku i stawiając szybko zamienimy slot w ekwipunku to dodaje nam trzymany przedmiot a nie ten który postawiliśmy 
https://github.com/FunnyGuilds/FunnyGuilds/compare/master...NNorbertPL:patch-1

**Comment by Kamilkime** [comment]
Co prawda nie popieram podwalania kodu, ale dzięki za poprawkę =)
