### ISSUE TITLE
FunnyGuilds events error

### ISSUE THREAD

**Issue by xannydev** [FunnyGuilds/FunnyGuilds#933]
Cześć, zaimplementowałem w moim pluginie event GuildCreateEvent od zakładania gildii. Podczas pobierania gildii otrzymuję błąd, który wynika z braku metody. Poniżej błąd:

https://pastebin.com/raw/DBwFHqfs

**Comment by Kamilkime** [comment]
Jak nie ma metody getGuild()? Ona jest dziedziczona z GuildEvent ;/

**Comment by xannydev** [comment]
Wg. kodu tak powinno być, ale jakimś cudem tak nie jest.
¯\_(ツ)_/¯

**Comment by insertt** [comment]
Czy mógłbyś dostarczyć więcej szczegółów dot. środowiska testowego? (log startowy, wersja silnika, plugin.yml Twojego pluginu)

**Comment by Kamilkime** [comment]
Eventy zostały ostatnio poprawione, dodatkowo u mnie w testach nie wyszły żadne błędy - zamykam issue, eventy w FG działają prawidłowo
