### ISSUE TITLE
Wyrzuca graczy z gildii po restarcie.

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#938]
Najnowszy build #102

Po restarcie serwera każdy gracz jest wyrzucany z każdej gildii poza liderem.
Naprawcie to pls.

**Comment by dzikoysk** [comment]
Którego zapisu używasz? (flat/mysql)

**Comment by powerax** [comment]
flat

**Comment by dzikoysk** [comment]
#943
