### ISSUE TITLE
Błąd przy /fg reload

### ISSUE THREAD

**Issue by Revelacyjny** [FunnyGuilds/FunnyGuilds#940]
build 103
https://pastebin.com/raw/YnBxJ5ST

**Comment by insertt** [comment]
Prawdopodobnie błąd związany z aktualizacją pliku przy aktualizacji pluginu do nowszej wersji  - rozwiązaniem jest usunięcie starej konfiguracji wiadomości, wygenerowanie jej na nowo i nadpisanie domyślnych wartości przez te poprzednie.
