### ISSUE TITLE
Replace

### ISSUE THREAD

**Issue by mati12844** [FunnyGuilds/FunnyGuilds#945]
Witam, jaka jest zmienna na {POINTS} i {GUILD} żebym mógł zrobić chat w skrypcie. Chodzi mi o np. takie coś:         replace all "{RANK}" with "%colored player's prefix%" in {_chat}. I odrazu mowie nie chce essentialsa.

**Comment by Kamilkime** [comment]
No, to musisz ustawiać format chatu i FG powinno w nim zamienić np. `{RANK}`

**Comment by Kamilkime** [comment]
Zakładam, że skoro nie ma już dalszych pytań - wszystko jest zrozumiałe i działa jak należy
