### ISSUE TITLE
Ustawianie graczowi własnego, dodatkowego suffixu?

### ISSUE THREAD

**Issue by MrAndeos** [FunnyGuilds/FunnyGuilds#946]
Witam.
Potrzebuję dodać graczowi dodatkowy suffix przy nicku, czy w FunnyGuilds istnieje taka opcja? Na ten moment próbowałem to zrobić, dodając nową drużynę do scoreboardu gracza i ustawiając jej ten suffix, bez sukcesów:
```java
Scoreboard board = funnyGuildsUser.getScoreboard();
Team team = board.registerNewTeam("ochrona");
team.setSuffix(ChatColor.GOLD + "[OCHRONA]");
team.setNameTagVisibility(NameTagVisibility.ALWAYS);
team.addPlayer(player);
funnyGuildsUser.setScoreboard(board);
```

**Comment by Kamilkime** [comment]
Nie, obecnie można dodać tylko prefix, który jest nazwą gildii, ale suffix nie

**Comment by insertt** [comment]
Z powodu braku aktywności zamykam issue. Gdybyś potrzebował dodatkowej pomocy - stwórz nowy issue.
