### ISSUE TITLE
Jak włączyć skiny graczy premium na serwerze non-premium (bukkit)

### ISSUE THREAD

**Issue by Aphrody** [FunnyGuilds/FunnyGuilds#955]
Witam, założyłem serwer Minecraft non-premium na wersji 1.12.1
Problemem jest to, że nie widać skinów graczy premium.
Czy zna ktoś jakiś dobry plugin, który naprawiłby to, lub ewentualnie mógłby takowy dla mnie napisać?
Przeglądałem wiele pluginów polecanych na internecie, ale żaden nie zadziałał.

Przy okazji szukam techników na serwer Minecraft więc proszę chętnych o kontakt.

Z góry dziękuję za odpowiedź.

**Comment by Kamilkime** [comment]
Chociaż nie powinienem, a dlaczego to powiem zaraz - polecam [SkinFetcher](https://github.com/kacperduras/SkinFetcher/) lub [SkinsRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/). Ale ogólnie - issues w FG to nie miejsce na pytania o inne pluginy czy poszukiwania techników. Ale zapraszamy na nasz [serwer Discord](https://discord.gg/CYvyq3u), tutaj na pewno ci ktoś pomoże =)

**Comment by Aphrody** [comment]
No tak przepraszam
