### ISSUE TITLE
Nie da się usunąć gildii

### ISSUE THREAD

**Issue by xDGWG** [FunnyGuilds/FunnyGuilds#957]
Korzystam z wersji Build #118. Jak wyłączy się tereny gildii, założy się gildie, przeładuje się serwer po czym usunie się ją i znowu przeładuje serwer to gildia powróci. Używam zapisu FLAT.

**Comment by insertt** [comment]
Przeładowywanie serwera nie jest zdrowe dla działania pluginów, czy da się ten błąd zreprodukować bez reloadowania?

**Comment by xDGWG** [comment]
Tak samo jak wyłączysz serwer i włączysz.
