### ISSUE TITLE
Problem Pytanie

### ISSUE THREAD

**Issue by pvpunikalnypvp** [FunnyGuilds/FunnyGuilds#960]
Witam mam pytanie bo kiedyś w funnyguildsach było tak że nie pisało Brak (PTOP-x) czy można to jakoś zmienić dodaje ssa 
![githubfunny](https://user-images.githubusercontent.com/18289293/47260526-921bc100-d4bd-11e8-90b6-0be49c2347e3.png)

**Comment by Kamilkime** [comment]
W messages.yml
