### ISSUE TITLE
Wygasanie Gildi

### ISSUE THREAD

**Issue by NuppDEV** [FunnyGuilds/FunnyGuilds#962]
Witam. Gdy wygasa gildia to powoduje  error który ciągle sie powtarza w konsoli:
https://pastebin.com/jtr7Krku
I spami na czacie że ta gildia wygasła ciągle.
https://cdn.discordapp.com/attachments/387222965131149315/505076663147692055/unknown.png
Wersja: https://imgur.com/a/N1FY980

**Comment by Kamilkime** [comment]
Daj może jeszcze cały log z serwera i pokaż jaka wiadomość się wyświetla

**Comment by NuppDEV** [comment]
[20:05:38] [Craft Scheduler Thread - 23/INFO]: ? Gildia [CSRV] wygasla! Jej baza znajdowala sie na x: x: -441, y: 30, z: -198!
Co równe 10 sekund
I dodatkowy ERROR przy włączaniu, i gildie dalej są na tabie.
https://pastebin.com/tg4N6RJ1

**Comment by NuppDEV** [comment]
https://pastebin.com/LVFVY98Y

**Comment by insertt** [comment]
Błąd naprawiony w najnowszym nightly.
