### ISSUE TITLE
Komenda /ga baza {gracz} - Teleportuje gracza do bazy jego gildii

### ISSUE THREAD

**Issue by olfu79** [FunnyGuilds/FunnyGuilds#973]
Propozycja dodania komendy dla administratorów. 
/ga baza {gracz} 
Natychmiastowo teleportuje danegi gracza do bazy jego gildii.

**Comment by Kamilkime** [comment]
https://drive.google.com/open?id=1AldDqdQ-jPaiLeI9uudFjIaU_hPfOUPe
