### ISSUE TITLE
Blokada niszczenia terenu przez TNT poza terenem gildii

### ISSUE THREAD

**Issue by Drizz1** [FunnyGuilds/FunnyGuilds#975]
Mam propozycję odnośnie dodania wybychu tnt jak na "dragonie".

Tnt niszczyłoby bloki tylko i wyłącznie na terenach gildii, a poza nie. Nawet jeśli w FG jest ustawiony procent na zniszczenie danego bloku po wybuchu, to poza terenem gildii nie będzie on niszczony. Jest to po to, żeby armatki tnt nie były niszczone i żeby przebijanie gildii było prostsze i przyjemniejsze. Bo gdy armatka niszczy się po wybuchu tnt to nie leci w stronę, która zakładaliśmy, bo jest ona niszczona przez tnt. Prosili mnie o to gracze, więc zgłaszam propozycję i proszę o dodanie. :D

Poniżej zamieszczam wideo, które to obrazuje:
od 7:09 do 9:29
https://www.youtube.com/watch?v=xvqPeDvfcYc

**Comment by jasuogra** [comment]
Jak ja moje to powinien to być add-on.

**Comment by Drizz1** [comment]
Według mnie to może być zwykła opcja w tym pluginie.
