### ISSUE TITLE
Tab odkrywa zmienne

### ISSUE THREAD

**Issue by MrKatrioPL** [FunnyGuilds/FunnyGuilds#977]
Cześć.

Mam problem. Mianowicie: Tab nie działa w pełni poprawnie. Po wpisaniu zmiennych i załadowaniu na serwer pokazuje mi się to: https://imgur.com/a/Ha4sOeK  (Patrz: Nazwa gildii, Tag gildii, Wlasciciel Gildii, Rozmiar gildii).

Wersja pluginu: 4.3.0 Tribute
Wersja Serwera: 1.8.8

//Edit dodaje config player-list:
player-list:
    1: ""
    2: "&b&l-------------------------"
    3: "&7&lTwoje &2&lStatystyki"
    4: "&b&l-------------------------"
    5: ""
    6: "&7&lNick: &2&l{PLAYER}"
    7: "&7&lPing: &2&l{PING}"
    8: "&7&lPunkty: &2&l{POINTS}"
    9: "&7&lPozycja: &2&l{POSITION}"
    10: "&7&lZabojstwa: &2&l{KILLS}"
    11: "&7&lSmierci: &2&l{DEATHS}"
    12: "&7&lKDR: &2&l{KDR}"
    13: "&7&lIlosc graczy obecnych: &2&l{ONLINE}"
    14: "&7&lGodzina: &2&l{HOUR}&7&l:&2&l{MINUTE}&7&l:&2&l{SECOND}"
    15: ""
    16: ""
    17: ""
    18: ""
    19: ""
    20: ""
    21: ""
    22: "&b&l-------------------------"
    23: "&7&lTwoja &2&lGildia"
    24: "&b&l-------------------------"
    25: ""
    26: "&7&lNazwa Gildii: &2&l{G-NAME}"
    27: "&7&lTag Gildii: &2&l{G-TAG}"
    28: "&7&lWlasciciel Gildii: &2&l{G-OWNER}"
    29: "&7&lPunkty Gildii: &2&l{G-POINTS}"
    30: "&7&lZabojstwa Gildii: &2&l{G-KILLS}"
    31: "&7&lSmierci Gildii: &2&l{G-DEATHS}"
    32: "&7&lKDR Gildii: &2&l{G-KDR}"
    33: "&7&lWszystkich czlonkow: &2&l{G-MEMBERS-ALL}"
    32: "&7&lDostepni czlonkowie: &2&l{G-MEMBERS-ONLINE}"
    33: "&7&lRozmiar Gildii: &2&l{G-REGION-SIZE}"

**Comment by MrKatrioPL** [comment]
+ i nie tylko to. Również TOP graczy oraz TOP Gildii to samo

**Comment by kacperduras** [comment]
#960
