### ISSUE TITLE
NameTagEdit

### ISSUE THREAD

**Issue by dzokuxd** [FunnyGuilds/FunnyGuilds#980]
Moja propozycja jest taka aby dodać współprace [NameTagEdit](https://www.spigotmc.org/resources/nametagedit.3836/) do funnyguilds wtedy każdy by mógł sobie wybrać w configu fg czy chce miec tagi vipa/admina albo innej rangi za nickiem wyglądało by to np. [HASA] dzokv | VIP

**Comment by jasuogra** [comment]
Wykonalne bez dodania wsparcia

**Comment by Kamilkime** [comment]
Albo zaproponować twórcom NameTagEdit dodanie wsparcia dla PlaceholderAPI =)

**Comment by dzokuxd** [comment]
Nie ważne jak ale żeby działało czyli do zrobienia :+1:

**Comment by jasuogra** [comment]
To pisz do twórcy nametagapi, może on ogarnie wcześniej niż fg team.

**Comment by dzokuxd** [comment]
Wątpię w to xD

**Comment by Kamilkime** [comment]
Szczerze? Zgodziłbym się tu z @jasuogra...

**Comment by jasuogra** [comment]
https://github.com/sgtcaze/NametagEdit/issues/198

**Comment by Kamilkime** [comment]
Czyli powinno bez problemu wspierać placeholdery dodawane przez FunnyGuilds do pluginu PlaceholderAPI: https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-2/#funnyguilds

**Comment by jasuogra** [comment]
Nie rozumiem czemu jeszcze issue nie zamknięty? Jest wsparcie, czego chcieć więcej?

**Comment by bmstefanski** [comment]
Zamykam. ~ `Komentarz został automatycznie wygenerowany`

**Comment by Kamilkime** [comment]
Bo chcę żeby sprawdził czy ono działa - niby jest, ale np. nie ma o nim chyba nic na stronie pluginu :/

**Comment by insertt** [comment]
Problem został rozwiązany - gdybyś miał dodatkowe pytania lub problem, stwórz nowy issue.
