### ISSUE TITLE
Tab sie nie pokazuje przy wiekszej ilosci graczy

### ISSUE THREAD

**Issue by yooniks** [FunnyGuilds/FunnyGuilds#982]
tak jak na filmiku:
https://www.youtube.com/watch?v=IQ1T-DrQ7LY
tab nie pokazuje sie przy 300+ graczach
przy 150+- trzeba walnac funnyguilds reload po kilku sekundach od wbicia zeby sie pokazal
silnik 1.8.8 paperspigot
wersja fg: 4.3.0 tribute-ff278f0

**Comment by kacperduras** [comment]
Logi i config poproszę.

**Comment by jasuogra** [comment]
Nikt normalny nie trzyma FunnyGuilds na serwerze powyżej 100 graczy, chyba.

**Comment by yooniks** [comment]
W logach nic nie ma, czysto.
Config defaultowy, tylko tab pozmieniany @kacperduras 


> Nikt normalny nie trzyma FunnyGuilds na serwerze powyżej 100 graczy, chyba.

no niestety, na 1 edycje tylko te mi pozostają

**Comment by jasuogra** [comment]
A spróbuj  na default tabie :thinking:  

Czemu tylko ci to zostaję, na podstawowe funkcję zrobić gildie to nie jest długo.

**Comment by kacperduras** [comment]
Podrzuć jeszcze build.

**Comment by yooniks** [comment]
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (https://yivesmirror.com/grab/paper/PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest)

a wersje funnyguilds podesłał mi Kamilkime, bo na oficjalnej nie dzialaly mi tab z moimi zmiennymi (placeholderapi) 

> Kamilkime27.10.2018
https://drive.google.com/open?id=1O7KW6o6VHscwY_OlkRqCoCYlC_qmiI7w
to powinno dzialac dobrze z tym papi




> A spróbuj na default tabie 🤔
> 
> Czemu tylko ci to zostaję, na podstawowe funkcję zrobić gildie to nie jest długo.

asysty, pelno funkcji itd - tego nie zrobie w kilka dni, same gildie juz cos tam zaczalem robic, no ale robie je w wolnym czasie, wiec troche wolno to idzie

**Comment by kacperduras** [comment]
Pobierz najnowszego nightly i przetestuj, ja postaram się zreprodukować błąd na Twoim silniku przy wersji z Twojego commita i z stable 4.3.0.

**Comment by yooniks** [comment]
> Pobierz najnowszego nightly i przetestuj, ja postaram się zreprodukować błąd na Twoim silniku przy wersji z Twojego commita i z stable 4.3.0.

dalej to samo (najnowsza wersja z nightly, [15:57:08 INFO]: FunnyGuilds 4.3.0 Tribute-27a4cac by FunnyGuilds Team)
180 botów, po relogu gdy juz zaden bot nie wbija pokazuje sie tylko header i footer i po dlugim czasie (2-3 min) w koncu tab, ale aktualizuje sie co kilkanascie sekund (hour:minute:second stoją prawie w miejscu), a normalnie leci co sekunde, zrobie timingsy i zobacze czy coś pokażą, ale pierw musze czekać na restart vpsa

**Comment by Drizz1** [comment]
Nawet przy 40 graczach ten problem występuje

**Comment by Drizz1** [comment]
![desktop screenshot 2018 12 11 - 20 28 26 25](https://user-images.githubusercontent.com/42066318/49825096-e0de2c80-fd83-11e8-85d3-3c23160635b5.png)

**Comment by yooniks** [comment]
Może by tak po prostu dodać jeszcze implementacje z protocollibem i wysyłać nim te pakiety?

**Comment by Gaway69** [comment]
Używaj btlp, nie będziesz miał problemu

**Comment by insertt** [comment]
W ostatnich kilku commitach (ca52907, 24f0d83) dodaliśmy kilka usprawnień dot. tablisty, także prosiłbym o aktualizacje stanu w sprawie tego, czy zgłoszony błąd dalej występuje.

**Comment by insertt** [comment]
Z powodu braku aktywności zamykam issue.
