### ISSUE TITLE
Wygaśniecie gildii Spam na chacie

### ISSUE THREAD

**Issue by pvpunikalnypvp** [FunnyGuilds/FunnyGuilds#983]
Dzień Dobry spotkałem się dzisiaj z problemem ponieważ gdy na moim serwerze wygasa gildia
to spamuje cały czas że wygasła
tak to wygląda
![shu_zbbggo2](https://user-images.githubusercontent.com/18289293/49699130-ad59a180-fbcd-11e8-9da5-5316bf2296af.png)
![shu_pggnnog](https://user-images.githubusercontent.com/18289293/49699131-ad59a180-fbcd-11e8-9afa-79220ea4e8d9.png)

**Comment by Kamilkime** [comment]
https://ci.insertt.pl/job/FunnyGuilds/4/
Najnowsza wersja nightly powinna mieć to załatane

**Comment by insertt** [comment]
Z powodu braku odzewu zamykam issue - gdybyś miał dodatkowe pytania lub problem, stwórz nowy issue.
