### ISSUE TITLE
Problemy z zapisem/wczytaniem danych o gildiach

### ISSUE THREAD

**Issue by Kamilkime** [FunnyGuilds/FunnyGuilds#984]
Coraz więcej osób narzeka na problem:
**1.** Zakładana jest gildia
**2.** Wykonywany jest restart serwera (w niektórych przypadkach nawet i bez niego)
**3.** Region gildii dalej istnieje, gildia nie

**Comment by Drizz1** [comment]
TIP: tylko w przypdaku MYSQL. :)

**Comment by kuba2003tv** [comment]
Mam ten sam problem, i na flacie i na mysql nie działa..

**Comment by PLOliwier** [comment]
Kiedy naprawa tego? Gracze się denerwują :/

**Comment by Kamilkime** [comment]
Gdy osoby, które mają to naprawiać znajdą na to czas. Niestety mamy dużo innych rzeczy do roboty i na FG wolnego czasu (oraz trochę też chęci) nie starcza
