### ISSUE TITLE
znacznik nad głową

### ISSUE THREAD

**Issue by Drizz1** [FunnyGuilds/FunnyGuilds#986]
Przychodzę z propozycją dodania możliwości wyboru w configu kolorów:
- znacznika gildii w której się jest (kolor &a)
- znacznika gildii sojuszniczej (kolor &d)
- znacznika gildii wrogiej (kolor &c)
Proszę o dodanie, gdyż podczas masowej walki ciężko się połapać kto jest z kim ;).
//Powerax

**Comment by Kamilkime** [comment]
Ale gdzie miałyby się pojawiać te kolory?

**Comment by Drizz1** [comment]
No tak zapomniałem napisać, TAG nad glową.

**Comment by Kamilkime** [comment]
![image](https://user-images.githubusercontent.com/10383567/50054584-bb666f80-0143-11e9-9435-00c53c74330a.png)
No to przecież są te ustawienia

**Comment by Drizz1** [comment]
Xd, do zamknięcia.
