### ISSUE TITLE
TabList nie działa gdy na serwerze jest jakiś gm3

### ISSUE THREAD

**Issue by Drizz1** [FunnyGuilds/FunnyGuilds#987]
Jeżeli na serwerze jest gm3 to tablista nie działa dla osoby która wbije na serwer. Relog osoby, która wbiła na serwer nadal nic nie daje. Dopiero gdy gm3 wyjdzie, a tamta osoba relognie to pojawi się tablista. Proszę o naprawienie.
![xd](https://user-images.githubusercontent.com/42066318/50056425-684ce680-015c-11e9-86aa-6685f15f35fa.png)
![desktop screenshot 2018 12 16 - 17 18 42 34](https://user-images.githubusercontent.com/42066318/50056427-6f73f480-015c-11e9-8a3b-71e6ce25baa2.png)
![desktop screenshot 2018 12 11 - 20 28 26 25](https://user-images.githubusercontent.com/42066318/50056430-7438a880-015c-11e9-935d-ced2d130a88c.png)

**Comment by insertt** [comment]
Niereprodukowalny błąd na podstawie podanych informacji (i prawdopodobnie duplikat #982).
