### ISSUE TITLE
System podbijania gildii oparty o Guardiana

### ISSUE THREAD

**Issue by ProDash1998** [FunnyGuilds/FunnyGuilds#991]
Nowy system podboju.
Zamiast EnderCristala uzyc moba ElderGuardiana.

Jak ma działać nowy system?
Baza będzie miała 3 życia jak wcześniej, lecz na nowszych zasadach.

Statystyki Guardiana:

Gdy ma 3 zycia:
  - 1000 HP
   - Odporność II
  -Odporność od ognia I
Przy ataku będzie nadawał graczom 
  - spowolnienie I na 5 sek,  raz na 30 sekund.
  - oślepienie I na 3 sek, raz na 1 minute
  - wyczerpanie na 4 sek , jedno razowo

Sojusznicy dostaja:
Regenracje zdrowia na 3 sek raz na 1 minute
Sila I na 4 sek raz na 90 sek

Gdy ma 2 zycia:
    - 1750HP
    - Odpornosc I
    -Odporność od ognia I

Przy ataku będzie nadawał graczom 
   - trucizna I na 5 sek, raz na 40 sekund.
   - spowolnienie II na 4 sek,  raz na 20 sekund.
   - oślepienie I na 5 sek, raz na 45 minute
   - wyczerpanie na 8 sek , raz na 1 minute ( 2 razowo)

Sojusznicy dostaja:
Regenracje zdrowia na 3 sek raz na 2minuty
Sila I na 5 sek raz na 150 sek

Gdy ma 1 zycie:
  - 2500HP

Przy ataku będzie nadawał graczom 
  - trucizna II na 5 sek, raz na 30 sekund.
  - spowolnienie II na 4 sek,  raz na 20 sekund.
  - oślepienie I na 5 sek, raz na 45 minute
  - wyczerpanie na 10 sek , raz na 1 minute ( 2 razowo)

Sojusznicy dostaja:
Regenracje zdrowia na 5 sek raz na 3 minuty
Sila I na 6 sek raz na 3 minuty

Gdy Guardianowi zostanie zabrane cześć życia np z 1500HP na 550HP. Jego regeneracja będzie trwała  12-48h. 
Gdy Guardian ma jedno życie jego regeneracja jest WYLACZONA!!! Odnowienie regeracji  zalezny od osoby konfigurującej (max 3 rozne typy itemkow)
Odnowienie pełnego życia Guardiana trwa 7 dni. 

Guardian będzie krzyczał gdy wróg wejdzie na gildiie.  Również gracz dostanie informacje na Titles i subtitles.

Gdy gracz będzie chciał anulować mlekiem efekty one nie będą usunięte.

**Comment by kuba2003tv** [comment]
Jestem za!

**Comment by P3ridot** [comment]
#2221
