### ISSUE TITLE
Błąd bazy danych

### ISSUE THREAD

**Issue by PLOliwier** [FunnyGuilds/FunnyGuilds#993]
[10:17:47 ERROR]: Nag author: 'FunnyGuilds Team' of 'FunnyGuilds' about the following: This plugin is not properly shutting down its async tasks when it is being reloaded.  This may cause conflicts with the newly loaded version of the plugin

Najnowsza wersja z https://ci.insertt.pl/job/FunnyGuilds/

Po restarcie serwera wszystkie topki i gildie się restartują używam bazy mysql wszystko jest poprawnie podłączone spigot 1.8

**Comment by insertt** [comment]
Error, który dołączyłeś do zgłoszenia dotyczy sytuacji, gdy przeładowywujesz serwer, podczas gdy FunnyGuilds nie wspiera opcji przeładowywania serwera.

**Comment by PLOliwier** [comment]
daje tylko ten bo taki tylko jest może jest ważny albo nie kij wie

**Comment by bmstefanski** [comment]
Błąd najprawdopodobniej związany z #984

**Comment by PLOliwier** [comment]
Do tego jeszcze na flacie nawet nie chce zapisywać.
