### ISSUE TITLE
Błąd z zapisem gildii

### ISSUE THREAD

**Issue by Carvane** [FunnyGuilds/FunnyGuilds#995]
Cześć, mam taki problem, że nie można dołączyć do gildii oraz gdy wpisuje np. /info (tag gildii) pisze, ze "Gildia o takim tagu nie istnieje" mimo iz ja zalozylem ;-;
Wersja fg.: FunnyGuilds 4.3.0 (MC 1.8-1.13).jar #13 
Wersja sil.: Paperspigot 1.12.2 #1596
Wycinek logow: https://pastebin.com/UzAtU1AA

**Comment by Kamilkime** [comment]
Błąd prawdopodobnie ten sam co w #984
