### ISSUE TITLE
Bug z Tablistą. 1.8.8

### ISSUE THREAD

**Issue by kamyk25902** [FunnyGuilds/FunnyGuilds#998]
Witam. Mam problem niestety z tab listą.
Załączam zdjęcie. 
Wersja: 1.8.8
![image](https://user-images.githubusercontent.com/30175150/51804888-7109ff80-2266-11e9-95ee-4b3860be91f9.png)

**Comment by Kamilkime** [comment]
A... Jaki jest tu problem?

**Comment by kamyk25902** [comment]
spójrz na napis {GTOP-x} a tego nie powinno być. Z {G-LIVES} jest to samo itp.

**Comment by PLOliwier** [comment]
...

**Comment by kamyk25902** [comment]
Dziekuje problem naprawiony:)
