### ISSUE TITLE
Propozycja kilku linijkowego Headera/Footera

### ISSUE THREAD

**Issue by McKoxu** [FunnyGuilds/FunnyGuilds#999]
Miałbym propozycje dodania kilko linijkowego header footera tak jak jest to np. w pluginie TabList
http://prntscr.com/medg3o, tam to jest animowane ale nie chodzi mi o animacje a o to że footer i header mogą być po kilka linijek, mam nadzieje że na tym screenie to dobrze pokazałem

**Comment by insertt** [comment]
Jest to już zaimplementowane, wystarczy użyć znaku nowej linii (`\n`)
![image](https://user-images.githubusercontent.com/25823411/52001788-909c6480-24c0-11e9-9095-d316aad79516.png)
